gemini-hlsw/ocs

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Bryan requested that the minimum number of fractional digits for the PA text field be set to two.
> REL-2922B: Set the minimum number of fractional digits to 2.

- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
This adds a handler for a previously-unknown HORIZONS header line that gives the record number but no common name, followed by the primary designation in prens. The examples given (`2009 MS9`, `2013 LU28`, and `2015 DB216`) now resolve properly.
/cc @andrewwstephens
> REL-2945 add new result handler

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
I missed one aspect when reverting to the old target model, which was, bizarrely, compiling, but causing an issue with regards to running the formatter.
This fixes that and again, will only be in the patch release branch.
> REL-2922B: Fix change to revert to old target model angle

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/resources/simbad-npe.xml
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
This PR fixes a border case when the simbad catalog returns a NullPointerException on its response. This PR was already opened but it was accidentally closed, see #1052
> REL-2890: Catch SIMBAD error response

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/OTOptions.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/general/GeneralPreferences.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/general/GeneralPreferencesPanel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/model/PreferencesChangeEvent.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/model/PreferencesChangeListener.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/observer/ObserverPreferences.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/observer/ObserverPreferencesPanel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/observer/ObservingSitePrompt.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/ui/PreferenceButtonPanelBuilder.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/userprefs/ui/PreferencePanel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewerMenuBar.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/userprefs/observer/ObservingPeer.scala
While updating the OT preferences it was noted that one user preference "Show alternative guide star options" was not used in the OT, this is a legacy option that is unused since we have BAGS
This PR removes this option and cleans some of the old preferences-related classes
Here's the option removed:
> REL-2948: Unused OT preferences

- bundle/jsky.app.ot/build.sbt
This is an addendum to the [REL-403 PR](https://github.com/gemini-hlsw/ocs/pull/1096).  Testing the UI only with `TestLauncher` I failed to notice that I needed to add the new OT package `jsky.app.ot.plot` to the private package list.  This results in an OSGi wiring exception on startup from the command line (or in a packaged app of course).
> REL-403: add missing package

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/rich/pot/sp/package.scala
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/ObsResurrectionCorrection.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedbackEditor.scala
This PR addresses a bug with BAGS and sync.  There are two related changes:
1. The major issue is in the `BagsManager.watch` method.  `watch` is called whenever a new program is opened, or when a sync that has to incorporate remote changes is executed.  When there are incoming changes the current program is replaced wholesale by an updated copy. The `watch` method wasn't taking this into account and would skip these updates.  Future change events would be ignored since `BagsManager` would continue watching the previous/unchanged version of the program.
2. The `BagState`s all kept a reference to the corresponding `ISPObservation`.  This is problematic for sync because the entire program is copied and the copy is updated.  Much of the refactoring work went into avoiding the need to hold on …
> REL-2955: BAGS/Sync bug

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/InstrumentSequenceSync.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/seqcomp/InstrumentSequenceSyncTest.scala
The static instrument component and the first instrument iterator in the sequence (if any) are kept in sync by an `ISPEventMonitor` called `InstrumentSequenceSync`.  When it is informed of a structure change or a property change it performs a synchronization, updating either the static instrument component or the sequence component (or both even) as necessary.  For example, setting the filter  in a GMOS instrument component will automatically update the first row in the GMOS iterator to match if it includes a filter item.
The problem being addressed by this pull request is that rearranging iterators was incorrectly causing the new first instrument iterator to be updated from the static instrument component instead of the other way around.  This results in edits to the iterators just from …
> REL-1939: Instrument/Sequence Sync Update

- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryFunctor.scala
So as it turns out, I was forgetting to filter / unpack a scala `Option` when working with targets in the ODB Browser. This was adding `Option[SPTarget]` to the `TargetsNode`, which blindly accepts anything `Serializable`. This caused the marshaling to fail when converting to XML.
This collects the unpacked `Some[SPTarget]` entries from the list and adds them to the `TargetsNode` instead.
I have tested with three fairly detailed programs and the query runs properly and the targets now appear in the XML output as they did previously.
(Also did some very minor cleanup.)
> REL-2655: Fixed issue with ODB Browser target requests by filtering / unpacking Option.

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
This is just a tiny change but had an impact on our last AGS failure. The line is missleading as this is not only called by BAGS but can be called by AGS, the Catalog Query Tool, etc
It was probably added to track the thread usage in BAGS but I think it can be removed
> Remove incorrect logging statement

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeMouseEvent.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
An NPE has been observed when adding manually a target. It is traced to a `null` target name wrongly set on the TPE
This PR fixes this and adds an extra verification on the Phase2 check that creates the NPE
> REL-2966: NPE when manually adding a guidestar on the TPE

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/image/ImageCatalogClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/image/StoredImagesCache.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/image/BackgroundImageLoader.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/image/ObservationCatalogOverrides.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/ImageCatalogPanel.scala
This PR contains some small bug fixes and improvements requested by users:
* It will create the cache dir if not present (Useful if the user deletes the cache file while the OT is open)
* At program load it will not load images for inactive or observed observations (They will load if the observation is loaded on the TPE)
* Catalog overrides were stored even if it matched the calculated one, polluting the overrides file
> REL-2859: Automatically download and cache images

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/CatalogSearchCriterion.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsUtils4Java.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeMouseEvent.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeTargetPosFeature.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateAsterismsTreeTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTable.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchController.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchModel.java
- bundle/jsky.app.ot/src/main/java/jsky/catalog/gui/TableDisplay.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/ConnectionUtil.java
This PR adds support for adding CWFS guide stars on the TPE once the GEMS Manual Guide Star box has been opened. To make it work you need to get the GEMS Dialog box and using the TPE click on the `+CMFS1/2/3` button and hit on of the hilighted targets
There were at least 2 other alternatives to this problem:
* Integrate GEMS to the Catalog Query Tool
* Add explicit add buttons to GEMS Guide Star Dialog
These were discarded due to the amount of time available
> REL-2638: Add individual CWFS stars using the TPE

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/Parameters.scala
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GmosPrinter.java
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/IFUComponent.java
This is an upgrade to the GMOS ITC to support a new IFU analysis method to sum all apertures with a specified radius of the center, e.g.:
Sum all IFU elements within ____ arcsec of the center
Please note that there is a problem with one line in ITCRequest.scala.  Carlos asked me to submit the pull request anyway.
> Sabrina's REL-2659: ITC support for summing GMOS IFU elements

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsImaging.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSConstants.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSParams.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRSNI.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/InstConstants.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/gnirs/ObsWavelengthTest.scala
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/PioSyntax.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2017A/To2017A.scala
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2017A/gnirs.xml
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2017A/GnirsObsWavelengthTest.scala
I must apologize in advance for this PR.  It's a fairly ugly hack.  I didn't see another way of doing this because it deals with a value that is computed during sequence construction.  The computation must work one way for old executed observations and a different way for new observations.  In the new tabular sequence model, this will no longer be an issue.  At least I feel like I've documented it adequately in the code itself.
The observing wavelength for GNIRS acquisition observations should be computed based on the imaging filter.  Unfortunately in the past this was not done and instead the observing wavelength was always taken from the grating central wavelength during sequence construction.  Old observations therefore used the wrong observing wavelength and we must continue to …
> REL-2646: GNIRS observing wavelength in acquisitions

- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/PioSyntax.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2017A/To2017A.scala
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2017A/vesta.xml
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2017A/EphemerisConversionTest.scala
- project/OcsBundle.scala
This PR adds a migration from pre-2017A ephemeris data to the compressed format used in 2017A.
> REL-2971: 2017A ephemeris PIO migration

- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/TextExport/TextJorgeObslogExporter.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/TextExport/support/InstrumentTextSegmentExporter.java
This PR fixes an embarrassing stringly-typed programming issue.  Namely, when exporting an observing log split by program id, we were picking up program multiple program ids based on a `String` prefix comparison.   For example, observation `GS-2016B-Q-20-1` would be considered to be a part of program `GS-2016B-Q-2` because the program id as a `String` is a prefix of the observation id as a `String`.
> REL-2033: fix split export

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedbackEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TargetDetailPanel.scala
In the previous implementation, if a target in the target environment was selected, pending BAGS feedback would clobber the feedback and only the BAGS feedback was shown.
This small modification ensures that both the feedback for the selected target and any BAGS feedback are both shown in the target editor.
I'd like to get this merged in the next 40 mins if possible to have it included in today's test release.
> REL-2855: Do not allow the BAGS feedback to override the feedback for the currently selected target.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
This PR encompasses a bunch of fixes and requested enhancements for parallactic angle mode, namely:
1. If the PA constraint is set to "parallactic mode" and the user changes the position angle in the TPE, the mode is now automatically switched to "parallactic override."
2. This fixes an issue where the position angle, when being entered by the user, was being written to the instrument in the wrong order, i.e. after the parallactic controls were updated instead of before. This was causing issues with things being overridden.
3. Now the parallactic calculation, as per Andy's request, displays, e.g. if the parallactic angle is 10, "10 / 190" so as to minimize user confusion with 180 flips.
4. A warning tool tip has been added to the parallactic angle calculation to accompany the warning …
> REL-2924: Multiple fixes for parallactic angle mode.

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gems/GemsGuideStarRule.java
This PR updates GeMS AGS so that it ignores the flexure star assignment, preventing ODGW stars from being added to the auto guide group.  Correspondingly, it removes any analysis or phase 2 checks related to ODGW stars for GeMS.
This is the bare minimum required for December but there is a tremendous opportunity for simplification here that we cannot pass up.  The entirety of GeMS AGS can be stripped of flexure star selection code and no longer needs to support ODGW for tip tilt correction - tip tilt will always be Canopus.  The NIR band option can be removed as well.  Since the changes are rather large, we'll leave further work for post-December.
__Note__: there are a few comments tagged with TODO: REL-2941.  Ordinarily we should not leave commented out code but here I wanted to do so …
> REL-2941: make GeMS AGS ignore flexure correction assignment

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/GlassLabel.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EphemerisUpdater.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/SiderealNameEditor.scala
This is a somewhat sketchy update to a very sketchy `GlassLabel` utility class.  The underlying issue is that the glass label is intended to be shown on top of all other widgets, yet allows input to pass through regardless.  The user can kick off a sidereal target name search for instance and then quickly click away to another component.  By the time the result comes back, the call to lookup the root pane associated with the target name widget returns `null` because the target name is not visible.  An easy fix is to save the root component and use it for the subsequent hide but this PR goes a step or two further:
1. You now call the static `GlassLabel.show` method to display the label and get a reference to a `GlassLabel` instance.  Using the instance you call `glass.hide()` to dismiss …
> REL-2988: GlassLabel NPE issues

- build.sbt
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/telescope/PosAngleConstraint.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
The QPT displays a warning when a parallactic angle mode observation is scheduled.
This was not properly accounted for when the `PARALLACTIC_OVERRIDE` mode was added.
This code cleans up the `PosAngleConstraint`s corresponding to parallactic modes by making a common method that ascertains whether a position angle constraint is parallactic, as this check must be done in multiple places, thus eliminating the need to ensure both modes are checked for.
The QPT now properly displays a warning whether an observation's position angle constraint is `PARALLACTIC_ANGLE` or `PARALLACTIC_OVERRIDE`.
> REL-2990: QPT and parallactic override mode

- build.sbt
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
As per REL-2989, BAGS and the PA text field were still having issues. This only seems to manifest when:
1. The TPE is open; and
2. The user modifies the PA contents quickly, e.g. 123.
It appears that due to the use of the Swing EDT, BAGS launches on an old value such as 1 or 12, and then subtasks of tasks launched on the Swing EDT finish in an unpredictable order, and the 123 is overwritten by BAGS and the 123 is never properly registered by BAGS as requiring a new lookup.
This is a very head-desk bashing attempt to fix this by fiddling with the way things are run on the Swing EDT, which seems to fix it in all cases except very rare circumstances which still require the above two mentioned conditions. Instead of Swing EDT tasks launching new Swing EDT tasks, for example, I have …
> REL-2989: Attempting to fix the PA text field

- bundle/jsky.app.ot/src/main/java/jsky/image/gui/DivaMainImageDisplay.java
Background image updating refreshes the TPE image on display with each edit, including trivial updates that don't impact the coordinates or wavelength.  In the majority of cases the actual image file is already being displayed.  This PR introduces a small hack to skip the image update when the TPE is already displaying the desired image.
This works well with the automatic background image updater, but an obvious flaw is that manually selecting a different image with the same file path would fail.  Given where we are in the desktop OT product lifecycle, I think we can safely ignore this issue.
> REL-2999: Only update TPE image if new

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
A tiny update to make sure that the context observation is still available when BAGS feedback arrives.
> REL-2998: check for context observation before updating

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
When a parallactic angle mode is selected and the PA text field has a value that does not equal the calculated parallactic angle or its 180 flip, a warning icon is displayed in the parallactic angle information label, and a tooltip set.
Andy found an issue where switching between observations caused this to break sometimes, where the warning would be improperly set. The need for displaying the warning needs to be re-evaluated whenever the parallactic angle information label changes or the PA text field contents change.
When the PA contents change, an event is fired that is handled, so this case is fine. However, there were instances where the parallactic angle info label contents would change and the warning display code would not be called, thus resulting possibly in a lack of warning or …
> REL-2996: Parallactic angle + position angle warning fix

- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryFunctor.scala
The LCH query functor would skip programs without observations, which is problematic at the beginning of the semester when new proposals have just been added.
> REL-2929: don't skip empty programs

- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryParam.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsTimesService.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/TextBoxWidgetWatcher.java
During testing, Andy noticed that the remaining time was not as he expected, and I discovered that I was not calculating it correctly.
This PR fixes the issue by rectifying the calculation.
Since this calculation is also used in `EdProgram`, I moved the calculation into `ObsTimesService` as per Shane's recommendation.
Since the `EdProgram` code was rather muddled and messy, I cleaned up this class considerably as well. I did, however, leave the `try - catch` blocks in place, even though I don't think some of them are ever invoked (unless possibly with a `NullPointerException`) because I didn't want to risk fundamentally altering the behaviour of this class, especially so close to the December release.
> REL-2655: Fixing ODB Browser remaining time

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala
- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/Parameters.scala
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GmosPrinter.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/PrinterBase.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/Detector.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/SampledSpectrumVisitor.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosNorth.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/SpecS2NSlitVisitor.java
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/seqcomp/InstrumentSequenceSyncTest.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
The OT ITC spectroscopy table was ignoring the fact that some instruments have multiple CCDs. This PR fixes that taking the maximum of the CCD values as requested  and improves the safety of the calculations
> REL-2992: GMOS Hamamatsu CCD ITC overestimates the peak signal + background 

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
Tiny PR hiding an option on the ITC page for GMOS that is not ready to be made public in the next release
> REL-2659: ITC support for summing GMOS IFU elements

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedback.scala
There was a PA issue with BAGS for OI guide probes where if:
1. the PA was set to `x` and a 180 flip mode was available;
2. BAGS found the best guide star at the flip; and
3. The user then reset, either via dragging in the TPE or pasting in the instrument editor, the PA to `x`;
then BAGS would not rerun for the PA of `x`, and thus the guide star at the 180 flip of `x` was maintained but registered as inaccessible to the patrol field.
This is because BAGS maintained, for the observation, the old `AgsHash` value that it previously used to do the lookup, and noted that it had already last performed the lookup for this PA and determined that it did not need to run.
This modification passes around the `ObsContext` to check if the position angle has changed, and if it has, then the hash is …
> REL-2997: Fix PA issue with BAGS

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedback.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedbackEditor.scala
The remaining issue in REL-2956 was a UI issue where the BAGS feedback message would appear and disappear, thus making the other components in the target editor "bounce" up and down to accommodate its UI space requirements.
This simple PR reserves the appropriate amount of room for BAGS feedback so that this is no longer an issue. Nothing is displayed if BAGS is not running.
Right now, the BAGS feedback appears at the bottom of the window, and the guide star feedback above as per the attached picture. (Note the small empty space under the Guide Speed: FAST message.) I think this looks nicer than the alternative and makes sure that it is clear than having empty space between the target editor and the feedback, but that is a matter of personal tastes. If anyone has an argument to reverse …
> REL-2956: Reserve space for BAGS feedback message.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Flamingos2.scala
Previously, the F2 MOS option was always filtered out since it was unavailable.
It is hoping to be made available in 2017B, so this simply undoes the code that filtered out this option from appearing in the resource configuration for F2.
> REL-3039: Unhide the F2 MOS option.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/rich/pot/sp/RichProgram.scala
- bundle/edu.gemini.spModel.io/build.sbt
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/ocs3/Ocs3ExportFunctor.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/ocs3/Ocs3ExportServlet.scala
- bundle/edu.gemini.spdb.shell/src/main/java/edu/gemini/spdb/shell/osgi/Activator.java
- bundle/edu.gemini.spdb.shell/src/main/java/edu/gemini/spdb/shell/osgi/Commands.java
- bundle/edu.gemini.spdb.shell/src/main/scala/edu/gemini/spdb/shell/misc/ExportOcs3Command.scala
This PR builds upon #1148:
* Adds an `exportOcs3` OSGi shell command that works just like `exportXML` except that it uses the OCS3 XML format.  This will make it possible to import from files instead of always having to have an ODB running.
* Adds a program listing option to the export servlet.  Since the servlet exports one program at a time, this allows a client to discover the available programs and request them one by one.
* Fixes a few issues with the OCS3 XML generation.
> OCS3 Export Updates

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/spdb/osgi/Activator.java
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/osgi/Activator.scala
- bundle/edu.gemini.too.event/src/main/scala/edu/gemini/too/event/osgi/Activator.scala
- bundle/edu.gemini.util.osgi/build.sbt
- bundle/edu.gemini.util.osgi/src/main/scala/edu/gemini/util/osgi/SecureServiceFactory.scala
- bundle/edu.gemini.util.osgi/src/test/scala/edu/gemini/util/osgi/SecureServiceFactorySpec.scala
- bundle/edu.gemini.util.trpc/src/main/scala/edu/gemini/util/trpc/osgi/Activator.scala
- bundle/edu.gemini.util.trpc/src/main/scala/edu/gemini/util/trpc/osgi/package.scala
- bundle/jsky.app.ot.testlauncher/src/main/scala/jsky/app/ot/testlauncher/ServiceChecker.scala
WIP fixing the sync/permissions issue. There's a race condition that will cause the same service instance to be re-used for simultaneous requests which has the effect of running all of them with the same set of permissions.
```
[info] Secure Service Factory getSecureService (singular) should
[info]   + work fine with normal service registrations
[info]   + pass principals correctly via getSecureServices
[info]   + ignore principals when called normally
[error]   x return a new service instance each time requested
[error]    '(foo,Set(PImpl(Bob), PImpl(Steve)))' is not equal to '(foo,Set(PImpl(Sam), PImpl(Harry)))' (SecureServiceFactorySpec.scala:100)
[error] Actual:   ...Impl([Bob]),...l([Steve])))
[error] Expected: ...Impl([Sam]),...l([Harry])))
```
Not clear how to fix it yet but at …
> REL-2881 WIP

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
It was requested that, to improve readability in the PDFs generated from the PIT for non-NOAO formats, in the list of co-investigators, the investigator names be made bolded, and hanging indents used in the co-investigator information.
Please see the attached images for what the list used to look like, and what it looks like with regards to these changes.
> REL-3026: PIT PDF cosmestic changes for CoInvestigator information

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
The goal of this change is to remove all investigator information from the first page of the NOAO PDF format generated by the PIT and put it in a separate page between TAC information and Observation Details, as it was thought that having this information on the first page might introduce bias.
This PR creates a new page and places the information there, as can be seen in the attached PDFs. (Note the old one was created with PIT 2017A and the other with the upcoming PIT 2017B.)
[US_2017A_001_summary_old.pdf](https://github.com/gemini-hlsw/ocs/files/747783/US_2017A_001_summary_old.pdf)
[US_2017A_001_summary_new.pdf](https://github.com/gemini-hlsw/ocs/files/747784/US_2017A_001_summary_new.pdf)
> REL-3068: For NOAO PDF generation, move investigator information

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/core/Filter.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/util/SemesterData.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/util/SolutionProvider.scala
- bundle/edu.gemini.qv.plugin/src/test/scala/edu/gemini/qv/plugin/chart/CategorizedDataTest.scala
- bundle/edu.gemini.qv.plugin/src/test/scala/edu/gemini/qv/plugin/filter/core/FilterSpec.scala
- bundle/edu.gemini.qv.plugin/src/test/scala/edu/gemini/qv/plugin/util/SemesterDataSpec.scala
- bundle/edu.gemini.util.skycalc/src/main/scala/edu/gemini/util/skycalc/Night.scala
This is a very subtle bug where QV will break on the last day of the semester **after sunrise**
The PR brings a test case that reproduced the issue and a tentative fix. An issue with the fix is my lack of knowledge about QV, hence I cannot predict if there are any other side effects of the change.
Also extracting a value from an `Option` was the original symptom. That has been changed to instead return a default but I'm not sure if it is the correct one
I hope some of our users could build this and test QV to check for any problems due to this update
> REL-3069: Queue Visualization error on last day of semester

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/Mascot.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/MascotCat.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
These are the modifications requested for the GSAOI guiding estimates for the 2017B PIT.
First off, I clarified the meaning of the progress method, which was extremely unclear, through some renaming. Indeed, there seemed to be some contradictions in the comments / naming.
Second, I now filter out non-Canopus stars. Previously, we returned 0 or 100% depending on whether or not an asterism could be found. As per Bryan's comments on REL-2941, we now return the number of CWFS probes with guide stars divided by three to give the estimate of success.
I also, as per Bryan's recommendation, added a warning if the number of CWFS guide stars is less than three.
> REL-2941: Changes to GSAOI guiding estimates for PIT 2017B

- bundle/edu.gemini.ags.client.impl/src/main/scala/edu/gemini/ags/client/impl/AgsHttpClient.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsPresentation.scala
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/LruCache.java
- project/OcsBundle.scala
In the 2017A PIT call for proposals the ODB server was hammered with AGS http queries for guiding estimations.
Investigation into this shows that repeated, identical queries are made.
Thus, to reduce server load, we implement an LRU cache on query string for successful results.
Note that this also seems to occur with the GSA, as per my notes on REL-2973:
http://jira.gemini.edu:8080/browse/REL-2973
Perhaps it would similarly be worthwhile to add a cache for this as well, especially since these queries seem to be fairly time-intensive? I'd like to do so but am wondering if anyone has any reason to object to this.
> REL-2973: Added LRU cache for AGS estimation queries to eliminate ODB server load.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
This tiny PR removed Texes from the available resources for 2017B.
I inquired with Bryan to see what should be done when upconverting proposals from previous semesters that use Texes, and he said they should simply be displayed as-is, i.e. with Texes still listed as the resource: thus, there is nothing else to do on this front other than remove it from the list.
> REL-3077: Remove Texes from available resource list for 2017B.

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
The page numbering has always been a bit hokey in the PIT NOAO format PDF generation due to forcing odd page numbers.
This simply removes the forcing and allows the page numbers to proceed as normal.
> REL-3068: Fixed weird page numbering in NOAO PDF format.

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Observation.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ObservationTimes.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Submissions.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/TimeAmount.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Observation.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_itac_no_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_itac_with_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_ver_1.0.0.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_ver_1.0.0_with_uk.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_invalid_character.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_latin1_encoding.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_observation_time.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/overheads/OverheadsSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2232_Test.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/overheads/Overheads.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/ObservationEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SubmissionRequestEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/Rows.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListModel.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/template/Phase1Folder.java
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/textComponent/NumberField.scala
This is a substantial change, as described in parent task REL-2925:
http://jira.gemini.edu:8080/browse/REL-2925
Previously, the user would calculate the program time and enter it into the PIT, and this was included for each observation:
`<observation...><time unit="hrs">1.0</time>...</observation>`
for example.
REL-2985 requires the following:
1. Instead of accepting calculated program time, the PIT must now accept integration time, look up overheads from a table (see the `Overheads` class) based on the instrument configuration, and manually perform the calculations to obtain program time, partner time, and total time.
2. When importing old proposals, the existing time must be assumed to be program time, and the calculations reversed as per the instructions on REL-2985 to calculate …
> REL-2985: PIT calculation of observing and calibration overheads

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/AltairNode.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
The laser at GN is not currently functional and thus proposals for 2017B must not allow Altair LGS options to be chosen.
This PR does three things:
1. Remove all Altair LGS options from the resource configuration.
2. When upconverting from a former semester, issue a message if an instrument is configured to use Altair LGS.
3. If a resource is found to use Altair LGS, report an error.
> REL-3079: Altair LGS not available in 2017B.

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Observation.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Observation.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/overheads/OverheadsSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/ObservationEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListModel.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
It appears this morning that due to some unforeseen issues during the science planning phase of REL-2985, science has requested that we roll back some of the changes and that these calculations eventually be moved back to the ITC.
Thus, instead of users entering integration time in the PIT and program time, calibration (partner) time, and total time being a function of this (with old programs needing to upconvert the old time field to program time and reverse-calculate integration time), we will eliminate integration time from the PIT and simply use - as before - program time as the input, but calculate calibration time from this and sum to get total time.
This implements the rollbacks necessary to do this, fixes the UI, and comments out much unnecessary code. Since much of this code …
> REL-2926: Rolling back some of the changes in REL-2985.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
I had accidentally omitted NIFS + Altair from calculations of overheads.
As these are the same as standard NIFS, this simply switched to doing the overheads lookup using the blueprint superclass, `NifsBlueprintBase`.
> REL-2926: Fixed NIFS to work with Altair in calculating overheads.

- app/pit/build.sbt
- app/spdb/build.sbt
- build.sbt
This adds the configuration for the dedicated AGS ODB server and configures the PIT to use it.
> REL-2941: Addition of dedicated AGS ODB server for PIT estimates

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2017B.xml
In the backend servers / proposals, it is very confusing because the terms cfh / cfht / CFH / CFHT are used interchangeably.
I believe this will finally fix the issue.
> REL-3086: Another attempt at a CFHT fix.

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
Since we are no longer using the old GSA, it has been requested that in the problems PDF summary, reference to the GSA be replaced with "Gemini Observatory Archive".
> REL-3090: Minor PDF naming change.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/overheads/OverheadsSpec.scala
Specifications were added to REL-2926 / REL-2985 for empty overheads when using Keck and Subaru instruments. This adds match cases to the `Overheads` class to return `Overheads` for `KeckBlueprint` and `SubaruBlueprint` so that the empty overheads are calculated instead of what happens when no match is performed and `None` is returned, in which case, no overheads are calculated at all.
> REL-3091: Added empty overheads for Keck and Subaru instruments.

- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImEither.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImOption.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Left.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Right.java
- bundle/edu.gemini.shared.util/src/main/scala/edu/gemini/shared/util/immutable/ScalaConverters.scala
- bundle/edu.gemini.spdb.shell/src/main/java/edu/gemini/spdb/shell/osgi/Commands.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
This PR consists of two basic elements:
1. Rewriting the `ImEither` class as per @tpolecat's earlier recommendation to change `ImEither` into an interface with implementations `Left` and `Right` instead of the previous way, which included two `Options` in a concrete `ImEither` class. This would run the risk of having an `ImEither` with both `left` and `right` values set to `None`, which violates how this class is supposed to function.
2. There was an issue in `EdCompTargetList` where it was extremely rare, but it was possible that the `ImEither` in this class representing the selection of a target or group could be `null`. I have changed the variable to an `Option<ImEither>` instead to avoid this and eliminate the problem.
Note that the `ImEither` is still right-biased, as is the case …
> REL-3061: Rewrote ImEither and fixed null pointer exceptions.

- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiHorizonsConstants.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosSouth.java
Previously, E2V was the default CCD manufacturer for GMOS-N.
This was set in `InstGmosCommon` and then overridden in `InstGmosSouth` to set the CCD manufacturer to HAMAMATSU.
Since now both sites will have HAMAMATSU as the default CCD manufacturer, the default in `InstGmosCommon` was changed from E2V to HAMAMATSU and the (no longer necessary) override removed from `InstGmosSouth`.
> REL-3055: Set HAMAMATSU to default for GMOS-N static component.

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/image/ObsWavelengthExtractor.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/image/ObservationCatalogOverrides.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/ImageCatalogPanel.scala
Fixes some eccentricities of the science model that affect the selection of image catalogs based on the central wavelength
> REL-3015: Allow selecting a different image server for Visitor & TEXES observations

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java
They don't get much simpler than this...  Change an ITC error message to clarify that the ITC is what is limited, not the instrument itself.
> REL-3108: Improve GMOS-N ITC error message for IFU-2 + Hamamatsu CCDs

- bundle/edu.gemini.pit/build.sbt
Turns out that apache-xmlrpc is dependent on apache-commons-httpclient, and when we remove the latter from the horizons package, it breaks the OSGi wiring, resulting in an exception.
> REL-3100: Had to add commons to pit build file to fix dependencies.

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/OpenAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/PdfAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/SaveAsAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetExporter.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetImporter.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPSiteQuality.java
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/Chooser.scala
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/HourMinuteFormat.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/sitequality/EdCompSiteQuality.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/sitequality/SiteQualityPanel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/sitequality/TimingWindowDialog.java
- bundle/jsky.app.ot/src/main/resources/resources/conf/UIInfo.xml
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/sitequality/TimingWindowImporter.scala
- bundle/jsky.app.ot/src/test/scala/jsky/app/ot/gemini/editor/sitequality/TimingWindowImporterSpec.scala
In the OT, previously, timing windows needed to be added in the Observation Conditions (Site Quality) node one at a time using the following dialog:
In the case where there were many timing windows, this could become very tedious, so REL-1787 requested the ability to import timing windows from a text file and add them to the existing timing windows.
I added an "Import" button to the UI, as you can see under the cursor in the following screen shot:
This pops up a modal file chooser dialog that allows the user to select a timing window file (.tw):
The file is then parsed using Scala parser combinators in the `TimingWindowImporter.TimingWindowParser` object, and the parsed timing windows added to the list. If any lines fail to parse, a dialog containing a table with line numbers and line …
> REL-1787: Add ability to import timing windows

- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/instruments/GNIRSLogSegment.java
This is the minimum possible fix for `GNIRSLogSegment`.
As per my previous PR, at one point, the cross dispersed property was either `No` or `Yes`.
Now it is `No`, `SXD`, or `LXD`.
Thus, I replaced the `Yes` checks, since this value never shows up, with ones that will work. 
Instead of `if YES then A else B`, we now do `if NO then B else A`.
> REL-1101: Fix for GNIRS e-obslog data

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
This simple PR just presents the proposed `Asterism` interface.  Having an `Asterism` trait will unlock progress on the `SingleTargetAsterism` implementation, `TargetEnvironment` update, and GHOST-specific asterism development.
One potentially controversial question is whether the targets should be `SPTarget` (which is mutable) or `Target` (which is immutable).  If this were new code here would be no question.  In `TargetEnvironment` though, the base position is an `SPTarget` so it seemed like the path of least resistance to make the asterism targets `SPTarget`s.  We drag targets around, for example, in the TPE so making these immutable implies replacing a lot of existing code. It seems like it would be prohibitively difficult.  I'm certainly happy to entertain the idea though if someone …
> REL-3117: Initial Asterism trait

- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/BaselineReorderTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/CalImpl.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/GcalExecTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/SmartGcalExecutedStepTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/TestCalibrationProvider.scala
- bundle/edu.gemini.spModel.smartgcal/src/main/java/edu/gemini/spModel/smartgcal/provider/CalibrationProviderImpl.java
- bundle/edu.gemini.spModel.smartgcal/src/test/java/edu/gemini/spModel/smartgcal/provider/ProviderTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/OT.java
This update would rearrange any flats in a baseline calibration to happen before any arcs (instead of the other way around as it is currently done).
Since we're modifying the sequence calculation, the question "what about existing executed sequences" naturally comes to mind.  Smart GCal was written to handle this type of change and simple monkey tests and a couple of unit tests confirm that it works, at least to some degree.  At any rate any problems with this feature are already present in the codebase.
> REL-246: reorder baseline cals to place flats before arcs

- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/BaselineReorderTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/GcalExecTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/SmartGcalExecutedStepTest.scala
While working on an unrelated feature, I noticed a sporadic failure with the Smart GCal test cases.  I believe the issue lies in an implementation class called `CalibrationProviderHolder`.  This class maintains a shared mutable reference to another class, the `CalibrationProvider`.  I'm not too interested in refactoring Smart GCal to fix this kind of thing because we have reimplemented it in a much less convoluted way already for ocs3.  Design questions aside, this creates a problem for the test cases which need to swap out the `CalibrationProvider` for testing and can't work in an environment in which the provider is changing out from under them.
There is some way to get limited serialization of sbt tests, but this needs to work across all test cases that are doing Smart Gcal.  I don't …
> REL-246: work around an issue with Smart GCal testing

- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryFunctor.scala
The LTTS uses the ODB browser to look up target information from the ODB, and has had, for nonsidereal targets, a `horizonsObjectId` field meant to contain the unique Horizons numerical identifier for a nonsidereal target; however, this field has never been set (I suspect it wasn't available in the old target model, but is easily obtained in the new target model).
LTTS - by design - assumed that this field was never set (as indicated in the comments for Horizons lookups) and searched for targets through Horizons by name. This yielded the issue that many target searches by name produce multiple results, and LTTS could not disambiguate between them to select the correct one, and thus - when this happened - set an RA and Dec of 0 to the nonsidereal target.
Now that we are fixing LTTS to work …
> REL-3128: Populate previously unused horizonsObjectId field in ODB Browser output for use in LCH to uniquely identify nonsidereal targets.

- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryFunctor.scala
As per @tpolecat's comments on previous PR.
> REL-3128: Patch OCS-2017A ODB to use Horizons queryString instead of des

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java
…I added a block to gmos.java to send an error if the central wavelength isn't between specified limits for GS and GN.
> REL-1808: GMOS ITC central wavelength check

- app/ot/build.sbt
- app/qpt/build.sbt
- app/spdb/build.sbt
We previously used gsodbtest2 and gnodbtest2 (CentOS 6) as our test ODB machines.
ITS deleted the unused gsodbtest and gnodbtest machines and redeployed them as CentOS 7 servers.
These are the changes to the build files required to use these new CentOS 7 servers instead.
> REL-3140: Update test ODB servers to CentOS 7 machines

- bundle/edu.gemini.auxfile.workflow/src/main/java/edu/gemini/auxfile/api/AuxFileTransferListener.java
- bundle/edu.gemini.auxfile.workflow/src/main/java/edu/gemini/auxfile/workflow/AddressFetcher.java
- bundle/edu.gemini.auxfile.workflow/src/main/java/edu/gemini/auxfile/workflow/MailTransport.java
- bundle/edu.gemini.auxfile.workflow/src/main/java/edu/gemini/auxfile/workflow/Mailer.java
- bundle/edu.gemini.auxfile.workflow/src/test/java/edu/gemini/auxfile/workflow/ProgramBuilder.java
- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryFunctor.scala
- bundle/edu.gemini.oodb.too.window/src/main/java/edu/gemini/too/email/TooEmail.java
- bundle/edu.gemini.oodb.too.window/src/test/java/edu/gemini/too/email/TooEmailTest.java
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/mail/OdbMail.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/odbState/ProgramContact.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/tigratable/TigraTableRow.java
- bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/mail/test/TestProgramBase.java
- bundle/edu.gemini.util.security/src/main/scala/edu/gemini/util/security/policy/ImplicitPolicy.scala
- bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/gemini/obscat/ObsQueryFunctor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ProgramForm.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/auxfile/AttachmentTableModel.java
The REL task for this PR is confusing, as the requirements have changed several times.
In the end, the description should be ignored, and only the later comments read.
Essentially, this primarily affects the program details (`ProgramForm`), and generalizes the concept of the former `NGO Contact Email` label to `Principal Contact Email`, and changes the `NGO Check?` label in the table to `Check?` to follow suit.
I tried to make this change as transparent as possible by relabeling variables and methods to reflect the change. This will, however, introduce discrepancies into the OCS code base in a few places, such as the ODB Browser, where the principal contact email will still be exported as the NGO contact email due to the XML format, which we do not wish to change as the scope would be too …
> REL-2942: Change program support labels

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosNorth.java
With the change to Hamamatsu CCDs for GMOS-N, the default amp count must now be changed from 6 to 12.
> REL-3055: Changing default amp count to 12 for GMOS-N for Hamamatsu.

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
With the change in GMOS-N to use Hamamatsu CCDs, we must update the exposure limits in Phase 2 checks.
This simply updates the phase 2 checks with the new values as specified in:
http://jira.gemini.edu:8080/browse/REL-3057
> REL-3057: Update GMOS-N Hamamatsu Phase 2 exposure limits

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/sitequality/SiteQualityPanel.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/sitequality/TimingWindowImporter.scala
- bundle/jsky.app.ot/src/test/scala/jsky/app/ot/gemini/editor/sitequality/TimingWindowImporterSpec.scala
In `TimingWindowImporter`, in converting from an `hh` and `mm` (and optional `ss`) specified as `Int` to a `Long` in ms, I did not convert the `hh`, `mm`, and `ss` to `Long`s first, which resulted in 32-bit integer arithmetic overflow for large values of `hh` (e.g. 720 as stated in @andrewwstephens's comment in the REL task). 
Now I convert the time elements first to `Long`s so that the arithmetic is performed in 64 bits, and the computation acts as expected instead of resulting in a negative time value.
I also added a test case for this.
In addition, as per Andy's recommendation, I changed the icon for timing window imports for clarity.
> REL-1787: Fixed arithmetic overflow in converting from hh:mm:ss to Long in ms.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GMOS_N_BP.xml
GMOS-N is switching from E2V to Hamamatsu detectors.
Thus, the template XML must be changed.
> REL-3056: Updated GMOS-N template XML for Hamamatsu detectors.

- bundle/edu.gemini.lchquery.servlet/src/main/scala/edu/gemini/lchquery/servlet/LchQueryParam.scala
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/timeacct/TimeAcctAllocation.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/timeacct/TimeAcctAward.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/timeacct/TimeAcctPio.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/TimeValue.java
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2017B/To2017B.scala
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2017B/timeAcct.xml
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2017B/TimeAcctMigrationTest.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/ExecHoursTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusInternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TimeAccountingSummaryTable.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ProgramForm.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/progadmin/TimeAcctEditor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/progadmin/TimeAcctUI.java
This PR changes the time accounting model to split the time award across program and partner.  Before the model was essentially a map from partner to double (hours) and now it is a map from partner to `TimeAcctAward` which in turn contains a `Duration` for the program award and a `Duration` for the partner award.
The data migration simply converts the old hours amount to an explicit program award in milliseconds and a 0 ms partner award.  The program admin editor is updated to allow editing both values.  (Bryan was opposed to making this split too visible, but this is only available to staff members and there's no good way to allow editing total hours without offering an editor for both parts.)
> REL-2928: (Part A)

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
The F2 Open filter is obsolete, and this PR marks it as such.
As it was set as the default filter for new F2 observations, after consulting with science, H has been set as the new default.
> REL-1280: Obsolete the F2 Open filter.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/IterFlatObsForm.java
When I was cleaning up the class `IterFlatObsForm`, I forgot to add `Constraints` to the cleaned up code for adding arc `JCheckBox`es to the UI, which caused an NPE.
This cleans this up so the `Constraints` are in place and the alignment is still set properly, but in a simpler way.
> REL-3146: Fixed NullPointerException In IterFlatObsForm

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
Science added new values for GMOS-N Hamamatsu detectors for g-band.
This simply changes these for P2 checks.
> REL-3057: Modified g-band values for GMOS-N Hamamatsu detectors.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ProgramForm.java
Same as PR for 2017B release branch, but merging into develop as well.
Science has requested (take three or four) that we change the labels in the ProgramForm for contact emails to reflect the way that the process now works as opposed to how it used to work with rigidly defined contacts.
I have updated the labels and the names of the widgets accordingly.
Unless someone comments on this PR insisting that I do so, at this point, I am not going to update the SPProgram accessors and member variables because this far into the process, it seems risky.
I made notes at the top of ProgramForm and EdProgram to indicate that there will be an inconsistency in labels / SPProgram data member names. This also translates to the ODB Browser, but that was - a week or two ago - agreed to be acceptable.
> REL-2942: Program form contact email label changes.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/TargetEnvironment.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/OT.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpePositionMap.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeAsterismFeature.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeBasePosFeature.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/image/BackgroundImageLoader.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/ImageCatalogPanel.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/TpeContext.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
This subsumes #1235 and is a follow-on to #1222 that updates the TPE to handle asterisms. It does the following:
- The TPE base position is now defined as the base position of the Asterism. It is updated when any target in the asterism moves.
- The base position feature now draws all targets, and has been renamed the asterism feature.
- The base position itself is not drawn. A new feature is needed for this.
Further work here probably needs to wait until it's possible to construct and manipulate multi-target asterisms in the target list editor. There will certainly be usability issues to deal with. But this PR gets us to a sensible starting point.
> Asterism Updates part B (again)

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/package.scala
Beforehand, in order to calculate the ratio of program time to total time (for scaling minimum time and awarded time during the skeleton import), we simply summed over all the observations in a proposal.
@cquiroz and @swalker2m pointed out that we should only be doing so for enabled observations in the appropriate band. I have extracted the common shared code out of `Phase1FolderFactory` into the package module that will be used by both, and since this is no longer really a property of a `Proposal` that we should be considering in the P1 model, I moved code from the `Proposal` class that I added here as well.
> REL-2928: Use only enabled observations of the appropriate band in time scaling

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
Based on a careful reading of the GHOST ConOps document, this PR represents an initial attempt at defining the GHOST asterism data model.  GHOST offers a fairly sophisticated set of modes and configuration options.  Not all options are applicable to all modes.  Rather than creating a generic `Asterism` implementation that contains mutually exclusive options, I'm attempting to constrain the choices to match those available in the various operating modes.  This helps guide user interface development and limits the possibility of ending up in an inconsistent state.
I expect there will be a number of iterations required to get the model in good shape.  When the changes die down I anticipate adding `Lens`es to make it easier to manipulate.
A few outstanding questions for science-staff include: …
> REL-3119: Initial GHOST asterism model

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xjb/GmosN.xjb
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java
Makes R150_G5306 obsolete to make way for R150_G5308, which should be selected when the PI chooses an R150 filter in the phase 1 proposal.
> REL-3153: Obsolete GMOS North R150_G5306

- bundle/edu.gemini.too.event/src/main/scala/edu/gemini/too/event/osgi/Activator.scala
- bundle/edu.gemini.too.event/src/main/scala/edu/gemini/too/event/service/TooCondition.scala
- bundle/edu.gemini.too.event/src/main/scala/edu/gemini/too/event/service/TooService.scala
This reverts commit 343c04ef94c9d8bef7d9eec7eefb25beaf85eff0.
Tracking change to release/ocs-2017B.
> Revert "REL-566: ignore acquisition and cal for ToO triggers"

- app/spdb/build.sbt
@swalker2m was attempting to connect to the ODB with VisualVM but found the startup scripts were missing several defines and parameters: this fixes the SPDB `build.sbt` to now add these to the startup scripts.
> REL-3162: SPDB build file changes.

- build.sbt
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/image/ImageSearchQuerySpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListModel.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
- bundle/edu.gemini.spModel.core/build.sbt
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeSystem.scala
- project/OcsBuild.scala
- project/build.sbt
This updates the `spModel.core` dependencies to versions that have 2.12 artifacts available, which we need in order to move compile it to 2.12 for Gem. There were a handful of compile errors that are fixed here. After this change you can say
sbt ++2.12.2 bundle_edu_gemini_spModel_core/packageBin
to create a jarfile for core compiled with 2.12
> update spModel core libs

- .travis.yml
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemGroup.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemObservation.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemSeqComponent.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/guide/VignettingCalculator.scala
- bundle/edu.gemini.util.security/src/main/scala/edu/gemini/util/security/auth/keychain/KeyChain.scala
- logging.properties
- project/OcsBuild.scala
This sets up the Travis build to run `sbt -q` with a custom logging config that only reports errors. (I verified that you do in fact see compile/test failures). I turned most of the `println`s that were in test output (I couldn't find all of them) into logger messages, so you still see them in a normal build and when running, but not in the CI log.
The CI log for this build should demonstrate silence. We'll see.
I also turned on caching which should speed things up a tiny bit. We'll see.
> quiet down the build

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ProgramForm.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/progadmin/TimeAcctEditor.java
- bundle/jsky.coords/src/main/java/jsky/coords/HMS.java
Bryan wanted some precision in times displayed to be changed.
This makes the program form display only second precision, and the admin panel display 2 decimals of hour precision for awarded times and min time.
Also, I fixed a UI issue where a column in the time UI was specified incorrectly.
> REL-2928: Fixed displayed time precisions as per JIRA notes.

- project/src/main/scala/edu/gemini/osgi/tools/app/RPMDistHandler.scala
This file specifies a "top level" directory to build RPMs in (in /tmp/.rpmtmpblahblah) and causes rpmbuild to fail.
> REL-3170: Remove rpmmacros on rpm building machine.

- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/obslog/DBNightlyPlanInfo.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/util/SummaryUtils.java
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Block.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/ObsAdapter.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/odbState/ObservationState.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/odbState/ProgramHistoryItem.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/dbup/AllEventsLoggingService.java
- bundle/jsky.app.ot/src/main/java/jsky/image/gui/ImagePrintDialog.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EdProgramHelper.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/auxfile/AuxFileEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
- bundle/jsky.util/src/main/java/jsky/util/DateUtil.java
This commit focuses on dates which don't follow the year, month and day order.
Where changed the format followed is yyyy-MMM-dd. Dates with different
format (like slashes as separator instead of dashes) but with the right order
get a pass for now.
Please watch out for any date format change that would break something that's not validated with a test. I tried not touch anything that looked like it was part of a path or filename though.
Not all dates are consistent for now because I couldn't find a large enough set of changes that could pass the tests. It was unfeasible to run the whole test suite for every date format change but from this commit I think I can check the tests for every date format change. I hope to at least fix the ones with different separators.
> REL-2784 Make date formatting order consistent

- project/src/main/scala/edu/gemini/osgi/tools/app/RPMDistHandler.scala
> REL-3170: Remove .rpmmacros to stop rpmbuild from failing.

- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/tigratable/TigraTableCreator.java
- bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/tigratable/TigraTableData.scala
This PR updates the way that `TigraTableCreator` obtains a `VcsService`, taking advantage of the new `SecureServiceFactory` utility.  The previous version was failing to find a `VcsService` and therefore failing to update the TigraTable data.
> REL-3171: fix TigraTable creation

- app/itc/build.sbt
We need to move ITC to run on CentOS 7 and thus 64 bit support is needed. This PR updates the configuration to support that case
> REL-3177: Support running ITC on Centos 7

- bundle/edu.gemini.qpt.client/src/main/scala/edu/gemini/qpt/TestLauncher.scala
This adds a standalone launcher for QPT. When it comes up the keychain (which contains the peer mapping) will treat localhost as if it were Gemini South.
> qpt test launcher

- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPanel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ObservationPanel.java
This is an early PR to check I'm going in the right direction. I have to still figure out how to add a legend and some thin lines.
Now the background colors of the elevation plots of the OT go like this:
Light grey: Sunset -> Start Nautical twilight (12°)
Dark grey: Start Nautical twilight (12°) -> End Nautical twilight (12°)
Light grey: End Nautical twilight (12°) -> Sunrise
> REL-1485: OT elevation plot background

- build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.pit.launcher/build.sbt
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/PiEditor.scala
This PR relaxes the restriction that emails TLDs must be between 2 and 4 characters. The exported PDF now also will behave better for very long email addresses
I added a couple of changes to the build to simplify launching the PIT from sbt rather than IntelliJ
> REL-3114: Remove constraint on email address suffixes in PIT

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Flamingos2.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/f2_removedfilters.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/Flamingos2Spec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
The PIT 2018A won't support these two filters
> REL-3190: Remove Y and J-lo filters for Flamingos 2

- bundle/edu.gemini.seqexec.odb/src/main/scala/edu/gemini/seqexec/odb/SeqExecService.scala
- bundle/edu.gemini.seqexec.odb/src/main/scala/edu/gemini/seqexec/odb/SmartGcal.scala
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/Flamingos2_ARC.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/Flamingos2_FLAT.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GMOS-N_ARC.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GMOS-N_FLAT.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GMOS-S_ARC.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GMOS-S_FLAT.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GNIRS_ARC.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GNIRS_FLAT.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GPI_ARC.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/GPI_FLAT.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/NIFS_ARC.csv
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/NIRI_FLAT.csv
- bundle/edu.gemini.spModel.smartgcal/src/test/java/edu/gemini/spModel/smartgcal/provider/ProviderTest.java
- project/OcsBundle.scala
In the previous REL-3189 (#1283), I updated the seqexec client to retrieve observation XML in order to relieve the dependency on binary serialization and make it possible to compile the seqexec with Scala 2.12. The seqexec client now expands the sequence in its own process instead of directly receiving it from the database.
What I failed to take into account though is that sequence expansion requires smart gcal lookup tables. This PR addresses that oversight.  I wasn't sure how this will be incorporated into the seqexec though, so feel free to update this as necessary.  As it stands there is a `SmartGcal.initialize()` function that has to be called to get a `CalibrationProvider`, which is needed by the `SeqExecService` client.  You pass the Gemini South ODB peer (always GS) and a …
> Add Smart Gcal Updating to Seqexec Client

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Itac.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/servlet/SkeletonServlet.scala
This is a subtle bug on the way the phase1 ITAC entry was modeled. This change includes the possibility that the value hasn't been set rather than defaulting to reject solving the bug indicated on REL-3155
> REL-3155: CHFT time modifications remove TAC acceptance in PIT

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Site.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/visibility/TargetVisibilityCalc.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Submission.xsd
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2018A.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.pit/src/main/java/edu/gemini/pit/ui/util/SharedIcons.java
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/BlueprintEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/Partners.scala
For historical reasons the PIT has mixed the usage of CFHT and CFH to refer to the Canada-France-Hawaii Telescope
This PR fixes this unifying it to use always CFH and it also enables the p1-monitor to handle CFH properly
> REL-3086: Configure the P1 monitor to handle CFHT proposals

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
This are more updates to get an unbiased view of the investigators list. It creates a new table that doesn't show the investigator's name or whether they are principal or co-investigators
This also includes a fix on an upconversion of certain graces proposals bug
> REL-3151: Format changes to PIT PDF investigator list to reduce unconscious bias

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/AllocAdapter.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Obs.java
This was causing the issue reported by @andrewwstephens. Now the OT and QPT elevation plot are identical:
(The screenshot from Andy was with Gemini North, but I don't know how to make the QPT switch to the North. In any case that target at that date was also wrong in the QPT for the South before)
> Make getCoords always recalculate the coordinates

- app/pit/build.sbt
- build.sbt
This will be used for the first PIT release targeting the real backends and will be the basis of a new branch for the pit 2018 release
> Updated settings for release candidate

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/pwfs/PwfsRule.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/PwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/PwfsProbeRangeArea.java
It turns out the PWFS2 p2checker was ruling out the guide stars that where between the inner limit and the inner boundary which should have been picked, as the AGS is already doing.
We also introduced an enumeration class for the results of the PWFS2 p2checker so that it's easier to understand.
> REL-2838 Make PWFS2 p2checker agree with the PWFS2 AGS

- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/DirScanner.scala
Last minute fix. There can be a race condition that makes the dir be created after update is called
> REL-3220: NPE on p1-monitor

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/GcalStepCalculator.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/PlannedTime.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/DefaultImList.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImCollections.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImList.java
- bundle/edu.gemini.shared.util/src/test/java/edu/gemini/shared/util/immutable/ImListTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/ObserveTimeLineNode.java
Adding the GMOS overheads was the primary goal but most of the changes in this PR are about the tooltip message over the timeline which now shows the configurations that didn't contribute to the maximum timings.
The code for the tooltip is quite dirty but not I'm not sure how to do it more cleanly in Java.
> REL-1121: Add GMOS timing overheads

- build.sbt
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/michelle/MichelleParams.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/type/SpTypeUtil.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/EnumTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/flamingos2/F2EnumsTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/michelle/MichelleEnumsTest.scala
This PR corrects an issue with parsing of F2 and Michelle engineering enums that resulted in data loss.  In particular, when reading an optional enum tag from XML, we make the call:
```java
v = Pio.getValue(paramSet, WINDOW_COVER_PROP.getName());
if (v != null) setWindowCover(WindowCover.valueOf(v, getWindowCover()));
```
where the value of `getWindowCover()`, intended to be used as the default value in case `v` is not readable, is usually `None` when initializing a program.  Then in the `WindowCover` parser we would inexplicably map the default value to the actual lookup of `v` resulting in `None`.
> REL-3251: Fix parsing of F2 and Michelle engineering enums

- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
This PR updates a test case that is currently failing due to a problem in JPL's horizons service.  Namely a search for "halley" gives an unexpected error message at the top, which breaks the regular expression that is trying to parse the results. Since the problem appears to be in the server, i don't think we should try to work around it in the parser itself.
> REL-3264: workaround horizons service bug

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/timeacct/TimeAcctCategory.java
Adds Limited-term Participant as requested.  Reports, PIO, OT admin etc. all work off the `TimeAcctCategory` enum so nothing else needs to be changed.  As noted in the Jira Task, this category isn't available in Phase I so the PIT and ITAC and skeleton creation code are all unchanged as well.
> REL-3254: add a new time accounting category

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GRACES_BP.xml
Just a straight update of the template program for Hamamatsu CCDs.  No logic updates.
> REL-3277: update graces templates

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/sitequality/SiteQualityPanel.java
The timing window table can now be sorted by columns.
Edits to the table are properly sorted, with the selection maintained, but with the following changes:
1. If new data is successfully imported to the table, the selection is cleared.
2. If existing rows are deleted, the selection is cleared (as those rows are gone). Previously, we would have selected the row that moved into the position of the first deleted row, which is nonsensical to do.
3. If a new row is added, it is selected.
With the exception of (3), which seems logical to me, this is in line with general `JTable` guidelines that recommend when the structure of the table changes, the selection should be programatically cleared.
> REL-1791: Timing window table now sortable by columns.

- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/html/HtmlUtil.scala
Modified HtmlUtil.scala to include the SED brightness when a user-defined spectrum is input.
> REL-3126 Show user-defined SED brightness normalization in ITC output

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateDsl2.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
A new pseudocode instruction made it seem like several new observations should be included to a template, but I believe this was a misinterpretation on my part
```
SET Well depth == Deep for {5}-{14},{22}
```
I've reimplemented the instruction here to set the well depth only for those listed observations that are otherwise already included.
> REL-3187: reinterpret well depth pcode

- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TargetConfig.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java
This is a small update to populate the `tag` parameter of TCC target elements.  I'm not sure why we were passing an empty String here, but we have the available information.  @jluhrs can you confirm that this will be okay?
Ideally there should be an associated test case but the TCC XML and dom4j APIs are difficult to use.  After a few hours trying to get a reasonable test, I decided that a visual inspection of the output was probably sufficient.
> REL-1438: add tag to TCC config

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/dataflow/GsaSequenceEditor.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/SeqRepeatFlatObsCB.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/dataflow/ProprietaryTest.scala
This PR fulfills a new feature request and fixes a bug.  The new feature is that programs marked as having private metadata now will get the specified proprietary months for even non-charged datasets like daycals.  The bug is that manual flat/arcs were missing the proprietary header fields in the sequence.
> REL-3129: Proprietary Months Issue

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
Two more bug fixes for GNIRS template creation.
1) Existing bug on H-mag partitioning that lumped the <7 and <11.5 buckets together
2) Stop always including library observation 23 (reacquisition) even when not needed
> REL-3187, take 3

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPElevationPlotPlugin.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPanel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotPanel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/LegendTitleUser.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ObservationPanel.java
This PR does two things:
1. Removes the times from the titles of the elevation plot and the observation chart as per my conversation with @andrewwstephens. (This information is now displayed directly in the plot, and thus is no longer useful in the title.)
2. Fixes the previously used hideous legends by adding spacing between legend items in the legend.
@cquiroz, I tried to switch from `java.util` to `java.time` classes, but there was just way too much conversion that needed to be done back and forth, and `JFreeChart` uses the `java.util` classes, so it just became way too cumbersome.
Here is a before and after demonstrating the title and legend difference:
> REL-1485: Removed times from elevation titles and fixed legend appearance.

- bundle/edu.gemini.util.skycalc/src/main/java/edu/gemini/skycalc/TwilightBoundedNight.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPanel.java
- bundle/jsky.util/src/main/java/jsky/util/DateUtil.java
As per Andy's comments on REL-1485, on the new labels on the elevation plot for sunrise, twilights, and sunsets, we were truncating times to minute precision, when we should have been rounding to the nearest minute.
This change handles that, with some code I largely yoinked off stackoverflow.
> REL-1485: Added rounding for sunset / twilights / sunrise times.

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/ImageCatalogPanel.scala
This PR addresses a comment in JIRA:
> It's a minor issue, but in the Position Editor "Image Catalog" section at the bottom of the left-hand panel, the busy spinner icon that appears when images are being downloaded overlaps the radio button.
The spinner icon brushes the side of the radio button to the right, so this update adds a bit of space to separate them.
> REL-1438: add a bit of space after the image download spinner

- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ObservationPanel.java
As per Andy's comment on REL-1485, the elevation panel and observation chart would formerly use titles of the form:
"Night of 2017 Nov 16 ---> 2017 Nov 17"
This makeshift arrow looked ugly, especially in certain cases, so I have changed it to a proper unicode long arrow:
"Night of 2017 Nov 16 ⟶ 2017 Nov 17"
> REL-1485: Change to unicode arrow in date range titles.

- app/spdb/build.sbt
- app/spdb/scripts/spdb
This PR does two things:
1. Removes the MaxPermSize parameter from the `build.sbt` file for the `spdb`, since this parameter is obsolete in Java 8.0, which is the requirement for OCS.
2. Introduces the `init.d` script, `spdb`, which can `start`, `stop`, `restart`, and `status` query the ODB, as per Chris Stark's request for server shutdowns.
I would appreciate any suggestions for the `spdb` script if anyone has any ideas for improvements, or sees any possible issues with it.
> REL-3310: Addition of spdb init.d script, and removal of obsolete JVM parameters.

- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/obslog/DBNightlyPlanInfo.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/obslog/functor/OlListPlanFunctor.java
- bundle/edu.gemini.obslog/src/main/resources/openLog.jsp
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Block.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/odbState/ObservationState.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/sitequality/SiteQualityPanel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/too/TooAlertPanel.java
- bundle/jsky.app.ot/src/main/java/jsky/image/gui/ImagePrintDialog.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/util/TimeZonePreference.scala
- bundle/jsky.util/src/main/java/jsky/util/DateUtil.java
The obslog was generating exceptions from the update from `SimpleDateFormat` to `DateTimeFormatter`, because `DateTimeFormatter` needs a specified `ZoneId` to be able to extract certain fields from an `Instant` or other `TemporalAccessor`.
I also modernized `ObservationState` to use new `java.time` constructs instead of the old `java.util.Calendar`. See below in comments for more notes on this.
> REL-2784: Fixing exceptions arising from not setting ZoneIds.

- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
Since we removed twilight times from the elevation plot and observation chart titles, the dates are now sometimes wrong, so we are reverting back to start and end date to have the appropriate dates appear.
> REL-1485: Restored title dates to start and end dates instead of twilights.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/too/Too.java
This PR addresses a bug in which all standard ToO observations are reset to rapid ToO in a rapid ToO program if the program admin dialog is opened and the "OK" button is clicked.
Determining the ToO status of an observation involves consulting the ToO designation of the program as a whole and the value of a "override rapid too" flag in the observation itself.  The combination of these values determines the ToO status of the observation.  It is probably most concisely described in code:
```java
public static TooType get(ISPObservation obs) {
final TooType progType = get(obs.getProgram());
if (progType == TooType.rapid) {
final boolean override = ((SPObservation) obs.getDataObject()).isOverrideRapidToo();
return override ? TooType.standard : TooType.rapid;
} else {
return progType;
}
}
``` …
> REL-3317: don't clobber ToO 'override rapid'

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/DBProgramChooserFilter.java
This is to avoid confusion on the part of DD PIs that no longer see their programs listed by default in the ODB due to the `other` filter being set to `false` by default.
We now set it to `true` by default as per Andy's comment on REL-2185.
> REL-2185: Other type programs are now selected by default

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/CandidateObsComparator.java
In recent changes, when a variant in the QPT is deleted, the `CandidateObsComparator` causes a `NullPointerException` due to the fact that the selected `Variant` is then `null` and it tries to retrieve a comparator from it.
This change just instead uses a dummy comparison, since there are no `Obs` to be compared when there is no selected `Variant`.
> REL-3323: Fix QPT NPE after deleting a variant

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/CandidateObsComparator.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Obs.java
In recent changes, when a variant in the QPT is deleted, the `CandidateObsComparator` causes a `NullPointerException` due to the fact that the selected `Variant` is then `null` and it tries to retrieve a comparator from it.
This change just instead uses a dummy comparison, since there are no `Obs` to be compared when there is no selected `Variant`.
> REL-3323: Fix QPT NPE after deleting a variant (for 2018A)

- app/spdb/scripts/spdb
The original `spdb` `init.d` script accidentally started the `spdb` as `root` when it should have been started as `software`. This should fix that according to my research.
(Note: I cannot test this directly because `/sbin/runuser` is only executable as `root`.)
> REL-3310: Fixing script to run spdb as software instead of root.

- app/spdb/scripts/spdb
Added a line to help the ITS staff by enabling them to do a `chkconfig --add spdb`.
> REL-3310: Added line to allow sysadm to do a chkconfig add.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/GpiCB.java
This restores the accidentally removed setting of magnitudes for H and I band in `GpiCB.java`, and has been rewritten to make it clear that these properties are being set instead of relying on unusual uses of `ApplyOp`.
> REL-3342: Restored magnitude property settings to GpiCB.

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsMagnitudeTable.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gems/GemsGuideStarRule.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/CanopusWfs.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gems/GemsGuideProbeGroup.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gems/CanopusFeature.java
This code is an extension of my earlier PR that I released for NGS2 regarding OT_REQ_002, which requests squares of 4 arcsecs drawn around targets. Discussions from Thursday revealed that science staff is stating that these squares are not just for display in the TPE and have physical significance, i.e. they must fall completely in the Canopus patrol field and cannot overlap.
This PR extends on my earlier work to implement the code for target validation, asterism filtering, and Phase-2 checks to take these physical constraints into account.
Unfortunately, to determine if two squares overlap, we need the position angle, as two squares next to each other may intersect when rotated at certain angles, and not intersect otherwise, so I had to change how the position angle was handled a bit in …
> REL-3341: Implement 4 arcsec squares around active guide probe targets for CWFS

- build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2018A.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
This PR changes the template used for DD and PW to include the full info unlike the current status where the pdf was formatted with the unbiased version
> REL-3557: Change p1monitor to use the old style for DD proposals

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsMagnitudeTable.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsGuideSearchOptionsSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsVoTableCatalogSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
Reverts gemini-hlsw/ocs#1393, as we are moving NGS2 into its own feature branch.
> Revert "REL-3339: Update CWFS limiting magnitudes for NGS2"

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xjb/GmosN.xjb
- bundle/edu.gemini.model.p1/src/main/xjb/GmosS.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/GmosN.xsd
- bundle/edu.gemini.model.p1/src/main/xsd/GmosS.xsd
This mirrors task REL-3272, i.e. adding the OVI and OVIC filters for GMOS-N and GMOS-S to the OT, which has already been done.
The PIT must support these new filters for 2018B. This adds the filters and their internal names to the XJB and XSD files, as well as to the immutable classes.
I think we will also need to modify the template creation process, e.g. `GmosNImaging.defaultExposures`:
https://github.com/gemini-hlsw/ocs/blob/f6e26b07e05f7ba3c69b4850534f3303cfe56153/bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gmos/GmosNImaging.scala#L40
> REL-3273: Add OVI and OVIC filters for GMOS-N and GMOS-S to PIT.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/AltairNode.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Due to the fact that LGS was not available at GN due to laser issues, the code for allowing LGS options was removed for 2017B, and any upconverted proposals asking for LGS were issued an error.
Now that toptica is available, we need to restore LGS options for GN. This essentially undoes REL-3363 to re-offer LGS and to eliminate any error messages issued if a proposal requests LGS.
> REL-3363: Revert REL-3079 to allow LGS options for GN instruments in the PIT

- bundle/edu.gemini.ags.client.impl/src/main/scala/edu/gemini/ags/client/impl/QueryArgs.scala
GRACES uses GMOS-N OIWFS for guiding. Right now, AGS queries pass "inst=GRACES", which causes failure. Instead, GRACES should translate to GMOS-N for AGS lookups.
I also sorted the cases alphabetically for ease.
Here is a screenshot showing GRACES working as GMOS-N.
> REL-3288: Change AGS client to use GMOS-N OI for GRACES.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Dssi.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_dssi_gn.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
The following have been listed as requirements for the 2018B PIT:
1. Remove TEXES from the list of instruments.
2. Add Phoenix to the list of instruments (GS only).
3. Make DSSI GS only, as Alopeke will be used for GN instead.
In this PR, I adjust the instrument list accordingly, i.e. removing TEXES and adding Phoenix back, and change DSSI to be GS only. Here is the instrument list now:
Here is what you now see when you select DSSI. (This is how Phoenix works, despite the strangeness of a one option selection box, so I followed suit to indicate that it is only at GS, especially important now since this has not always been the case.)
The UpConverter now takes DSSI observations at GN and issues a warning, and changes them to GS with the information that Alopeke should be used for GN …
> REL-3349: PIT visitor instrument changes.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/AlopekeBlueprint.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/BlueprintBase.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_alopeke.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/AlopekeBlueprintSpec.scala
I noticed during testing that both DSSI and TEXES proposals had a tag in the instrument node with `<visitor>true</visitor>` and that Alopeke had `<visitor>false</visitor>`, which is wrong and something I missed in the initial implementation.
This fixes that.
> REL-3351: Made Alopeke a visitor instrument.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
I had forgotten to:
1. Remove the code from an earlier upconversion that removed Phoenix. Since it is offered this semester, that was problematic.
2. Texes was not being removed.
Phoenix now remains and Texes is now removed.
Furthermore, the code to assign Phoenix to GS is now only run if the site is missing or set to GN.
> REL-3349: Fixed visitor instruments in PIT

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/GmosNorth.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GmosNBlueprintIfu.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GmosNBlueprintImaging.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GmosNBlueprintLongslit.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GmosNBlueprintLongslitNs.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GmosNBlueprintMos.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_gmosn_altair_lgs.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Andy pointed out that GMOS-N does not support Altair for 2018B. Thus, I:
1. Removed the Altair node from the GMOS-N instrument tree, instead forcing `AltairNone` to be used.
2. Removed any Altair mode other than `AltairNone` during upconversion, issuing a warning.
3. Removed references to Altair modes in GMOS-N names (as they will always be `None`, which would be confusing).
4. Added a case to the `ProblemRobot` (which should never happen) that reports an error if one tries to use GMOS-N with an Altair mode.
5. Added a test case to `UpConverterSpec` to make sure the Altair mode was set to `AltairNone`.
> REL-3363: GMOS-N does not support Altair in 2018B

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_alopeke.xml
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/AlopekeBlueprint.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Alopeke.xsd
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_alopeke.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/AlopekeSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/AlopekeBlueprintSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
Reports with the Hawaiian okina "apostrophe-like" character were making this display as `#Alopeke`. I changed to the apostrophe to fix this.
> REL-3351: Changed okinas to apostrophes to avoid unicode issues, take 2.

- app/pit/build.sbt
The PIT `build.sbt` file has a property to indicate whether it is a test build or not.
After some investigation, I found that even if the property is changed from `true` to `false` or vice versa, there are many instances in which the compiled code retains the former value, and this has been quite problematic in the past with regards to making release builds.
The most reliable way to make a release build is to simply comment the line out as it defaults to `false`: hence the addition of the warning comment here.
It is used in `AppMode.scala`:
https://github.com/gemini-hlsw/ocs/blob/develop/bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/model/AppMode.scala
> REL-3384: Added warning to PIT build.sbt file.

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/MagnitudeConstraints.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/package.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPSiteQuality.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProperMotion.scala
This PR does three things:
1. Makes (hopefully all of) the model updates for GHOST targets / asterisms for now as per discussions with Steve.
2. Turns (I don't know if this is a bad idea due to possibly differing epochs) `ProperMotion` into a `Monoid`. Either way, I suspect we're going to have to assume same epochs at some point, as we were before in `DualTarget`, or throw an exception. This greatly simplifies adding `Option[ProperMotion]`s.
3. Refactors the code for making magnitude adjustments based on conditions out of both `edu.gemini.spModel.gemini.ghost` and the `edu.gemini.catalog` API and puts it into `SPSiteQuality`, where it probably belongs.
> REL-3390: GHOST Asterism model updates.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/obscomp/package.scala
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/ObsEditValidator.scala
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/ObsPermissionCorrection.scala
- bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/ObsEditValidatorTest.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdObservation2.java
ToO trigger attempts in inactive programs are not actually carried out, but nothing stops a PI from trying.  That is, the OT allows the PI to toggle a ToO observation from "on hold" to "prepared" and submit the update.  Nothing indicates that the trigger attempt will ultimately fail.  This PR addresses the problem in both the UI and during the sync.  In particular:
* The OT observation editor will no longer allow a  PI to change the observation status of an "on hold" or "prepared" ToO observation in an inactive program.
* Nevertheless, before a sync the OT might be working with a copy of the program that is still marked active though it is in fact now been made inactive in the database.  Therefore we raise a sync permission error when we detect a trigger attempt in a now inactive program.
> REL-3293: Stop PI ToO trigger attempt in inactive program

- bundle/edu.gemini.pot/build.sbt
I forgot to add GHOST to the `build.sbt` `OSGi.exportPackages`.
After this, the SPDB and OT run fine, and GHOST does not yet (which is what we want) appear in the instrument list in the OT.
> REL-3391: Added missing OSGi export package for GHOST.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/VISITOR_BP.txt
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/AlmostEqual.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/AlmostEqualSpec.scala
In the previous implementation:
`!(Angle.fromDegrees(359.999999) ~= Angle.zero)`.
This fixes that.
> REL-3406: Fix AlmostEqual for Angles.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016A/PlutoDemotionTest.scala
This PR synchronizes access to a `DateFormat` object to prevent a potential test case failure.  I had originally intended to switch to `java.time.format.DateTimeFormatter` so that synchronization wouldn't be necessary but the existing `SPTargetPio.parseDate` method seemed complicated and would have to be modified.
> REL-3411: synchronize access to formatter

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/VariantAdapter.java
- bundle/edu.gemini.util.skycalc/src/main/java/edu/gemini/skycalc/TwilightBoundedNight.java
- bundle/jsky.util/src/main/java/jsky/util/DateUtil.java
This changes QPT to round almanac times using the same logic as in the OT, which makes the times vague enough to agree with the ObsLog at GS, which uses Tololo values.
> REL-3313 round almanac times in qpt

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/AsterismType.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismConverters.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostParamSetCodecs.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/AsterismConvertersSpec.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Almosts.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Arbitraries.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/AsterismParamSetCodecSpec.scala
- bundle/jsky.app.ot/src/main/resources/resources/conf/UIInfo.xml
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
This is a major refactoring of `GhostAsterism` to divvy up `StandardAsterism` into four subclasses, one for each type of standard asterism as per discussion with @swalker2m earlier today.
(It also includes REL-3395, as I branched from that PR to create this one.)
Everything else in here is a consequence of that refactor.
I think this is an improvement, especially to `AsterismType`, and simplifies a number of things.
This PR is largely to ensure that all test cases still pass and to get feedback from @swalker2m.
> REL-3390B: GHOST major refactor

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/PowerLawSpectrum.java
The power-law generator was occasionally going 1 step beyond the predefined dimension of the array due to imprecision in representing the looped variable.  In the case I investigated (B600 @ 500nm) the loop was set to stop at 1181.97, but on what should have been the last step the wavelength was only at 1181.969999999 so it tried to loop through one more time and crashed.  To avoid this I changed the for loop to increment the index rather than the wavelength.
> REL-3412: GMOS-S ITC fails with power-law input SED

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
This PR adds the label "UNAVAILABLE" to the ITC components which are no longer available, and makes several other purely cosmetic improvements to the web forms, including re-organizing the GMOS filter lists, and making various labels more consistent.  I also re-instated the PWFS to the Michelle and TRECS ITCs, as they were throwing errors.  Finally, I updated the Acq-Cam ITC to use the new style "Calculate" button for consistency with the other ITC forms.
> REL-3388: Relabel obsolete components in the ITC web forms

- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
This adds support for headers of the form `1I/'Oumuamua (A/2017 U1)` and `A/2017 U7`. The Jira issue also mentions `A/2018 C2` which should be handled by the latter pattern but the object seems to have disappeared. 
Once verified this change needs to be cross-ported to gem.
**Update:**  `A/2018 C2` was renamed to `A/2018 F4`, and it does works as expected.
> REL-3400 add support for new horizons formats

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
This PR fixes, or works around, an initialization issue.  When opening a QPT plan from the web, parts of the `Schedule` being created are accessed during initialization.  In particular, the `Variants` take the `Schedule` with which they are associated and use it as part of their own initialization. Unfortunately one of things that a `Variant` queries is the ICTD data, which wasn't yet available when needed.
> REL-902: move initialization of ICTD

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/action/OpenAction.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/ViewerManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/OpenDialog.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/ProgTableModel.scala
Updates the OT Open dialog to allow multi-interval selection, changing the list selection model from `SINGLE_SELECTION` to `MULTIPLE_INTERVAL_SELECTION`.
It also enforces a total storage size limit and prevents checking out programs that would take the total storage over the size limit.  This wasn't explicitly requested but I worried about the consequences of attempting to check out the entire ODB.
The previous single select model would generate distinct warnings when deleting programs depending upon whether the program is not present in the remote database, has changes that haven't been committed, or is in sync.  Updating this for multi-select required a bit of simplification but nevertheless is the grimmest part of the PR.
> REL-1502: multi-select in open dialog

- bundle/edu.gemini.ictd/src/main/scala/edu/gemini/ictd/dao/CustomMaskDao.scala
This is a followup for #1473.  It fixes the case of the `MOS` table.  It turns out that mysql tables are case insensitive on OS X where I did the development, but case sensitive on Linux where the official test server runs.
> REL-902: fix case of MOS table

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/DefaultSampledSpectrum.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/SEDFactory.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/Validation.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/RedshiftVisitor.java
If a user supplies a SED which covers too broad a range in wavelength the ITC will resample it from start to finish and end up with an array which is too large for memory and it will silently crash, providing no feedback to the user about what is wrong.  The SED that was submitted by a user extends from 944 - 2,000,000 nm and the resampled SED has 99,952,807 points.
The solution implemented here is to extract only the wavelength range required by the instrument configuration, ignoring the unnecessary ends.  This required adding yet another implementation of DefaultSampledSpectrum which takes the desired wavelength range and the target redshift.
During testing, I noticed that some redshifts (e.g. 0.3) would truncate the input SED by one element when the redshift was applied.  Thus there is …
> REL-3421: Prevent ITC OutOfMemoryError with oversized user-supplied SEDs

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/gmos/FullExposureTime.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/gmos/NodAndShuffleExposureTimeTest.scala
This PR follows up on #1475, adding a test case that was missing.
> REL-3279: test case for full n&s exposure time

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
This PR includes a minor update to the GSAOI ITC web form, removing some obsolete text after the implementation of the automatic Strehl lookup, and fixing the "(more info)" links which were pointing to more info about NIRI.  I also fixed a few background links which were still using http instead of https (per REL-3332).
> Feature/REL-3222 - Update GSAOI ITC web form

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/IFUComponent.java
This is the continuation of the upgrade to the GMOS ITC to support a new IFU analysis method to sum all apertures with a specified radius of the center, e.g.:
Sum all IFU elements within ____ arcsec of the center
This resolves the issues of:
Center and pack fibers using correct geometry
Display the number of summed elements in the generated plot title
Display the analysis method in the GMOS ITC page
> REL-2659: Complete ITC support for summing GMOS IFU elements

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/DefaultSampledSpectrum.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/SEDFactory.java
This PR expands the range of the extracted user-supplied SED to cover the specified normalization band.
> REL-3421: Fix ITC failure when user-supplied SED range is too large

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ObsWeighter.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/CandidateDecorator.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/ClientExclusion.java
A small update to the ICTD/QPT integration.  It was requested to distinguish observations with an unavailable custom mask from those with an unavailable filter/grating, etc.
If there isn't a problem with this change, I'll make another PR for the release branch.
> REL-902: distinguish config unavailable vs mask unavailable

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/ShellAdvisor.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskAttribute.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskController.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskDecorator.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskViewAdvisor.java
A request was made to display the ICTD mask availability data, which I placed in a table beside "Instruments".
If this seems acceptable, I'll also make a PR for the release branch as well.
> REL-902: add a Masks table

- bundle/edu.gemini.oodb.too.url/README.md
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/TooUpdate.java
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/impl/TooUpdateServiceImpl.java
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTarget.java
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTooGuideTarget.java
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTooUpdate.java
- bundle/edu.gemini.oodb.too.url/src/test/scala/edu/gemini/spdb/rapidtoo/www/HttpTargetSpec.scala
Skips setting the guide star if not specified in the ToO trigger request.
> REL-3028: make ToO guide star optional

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This PR is still not complete but it's intended as a request for feedback. These are the main points of contention.
- Multiple constraint intervals. Right now it only uses the first interval of the night, but how do we really want to represent these cases? I'd try to show the interval that affects more allocations but I'm not sure how to do it and that might require much more time than are willing to spend on.
- Open ended constraints. I'd use the start/end of the night, but would that be correct?
- Conditions to show messages. Right now they are always shown when there are constraints present, but I guess maybe we don't want to show them when the condition is not met, is that the case?
- Background constraint. It's still pending but since it seems the trickiest I'm leaving it until the …
> REL-1714 Extra notice messages for constraints

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
This is a trivial update to REL-1714. It occurred to me that we didn't change the cache creation bit to use the constants @jdnavarro defined in `Variant`.  While I was fixing that, it seemed like we might as well provide constants for all the cache names.
> REL-1714: addendum 

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/TimePreference.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/problem/ProblemController.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/MarkerAdapter.java
This is yet another iteration on the new constraint messages for the QPT.
This is still WIP, but I'm sending it anyway to make sure I'm on the right path. This is what I was planning to do next.
Notice that now we are reporting the message even when there is an error. We think this is alright since 1. there are not as many messages as when we were reporting messages for each constraint, and 2. whenever there is an error we expect the user to correct it right away.
> REL-1714-C Report intersection of constraints

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This changes the QPT scoring algorithm to respect PI priorities. There was something nutty happening before that caused priorities to be considered only for TOO observations.
Also updates the score marker to disregard non-science observations.
> REL-397 (2) update scoring and marker

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
Because there are still glitches we are deactivating this feature for an
imminent production release.
> REL-1714 Comment out intersection message

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
This tweaks the scoring algorithm to make the penalty for a partially-blocked observation (i.e., one that cannot be scheduled in its entirety) slightly less than the penalty for a one-step decrease in user priority. This means that (all other things being equal) a higher-priority observation will always be recommended, even if it's partially blocked.
> REL-397 (3) tweak QPT scoring algorithm

- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
This comments out the two test cases in `HS2Spec` that are failing, thus causing all Travis builds to fail and preventing PR merging.
@tpolecat explains why these cases are failing and why it is not a matter of concern:
"We handle that asteroid format but no longer have any way to get horizons to generate it because all the applicable targets have been reclassified as comets, as far as I can tell."
> REL-3431: Commented out the culprits in HS2Spec.

- build.sbt
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/TargetEnvironment.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetObsComp.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetObsCompCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPCoordinates.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPSkyObject.scala
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GMOSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GNIRSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GhostSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/NICISupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/NIFSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/NIRISupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/ObservationEnvironment.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/PhoenixSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TargetConfig.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TargetGroupConfig.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccHandler.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TexesSupport.java
This implements the code to let the TCC load GHOST observations from the session queue, as well as fix some minor comment issues and cleanup along the way.
Here are two screenshots of GHOST observations in the TCC.
The first is a single target standard resolution GHOST observation of M62:
The second is a dual target observation, in which case, the base position is not a named target, and thus we call it `Sky Position`:
> REL-3435: GHOST now can be loaded by the TCC

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/TimePreference.java
- bundle/edu.gemini.qpt.client/src/main/resources/edu/gemini/qpt/ui/html/template.vm
This PR addresses an issue with formatting marker message time intervals in the QPT's published plan.  Danny and I worked on this together.  We realized that we could get the time preference from the `ScheduleDocument` and use that to format the messages with a few tweaks here and there.
> REL-1714: publish plan with selected timezone

- app/itc/build.sbt
- app/ot/build.sbt
- app/qpt/build.sbt
Increasing the max memory allocation for the QPT and OT as the garbage collector generated an `OutOfMemoryError` for the program GS-2018A-Q-419.
> REL-3447: Upping max memory allocation.

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This is a follow up to the new intersection messages in the QPT. There was a glitch when dragging an allocation around close to the night border that this commit should fix.
This was reported initially as an error when *opening a queue from the web* but it might be this issue in disguise instead.
> REL-1714: Use Nautical twilight for QPT intersection messages

- bundle/edu.gemini.ictd/src/main/scala/edu/gemini/ictd/CustomMaskKey.scala
- bundle/edu.gemini.ictd/src/main/scala/edu/gemini/ictd/dao/CustomMaskDao.scala
- bundle/edu.gemini.ictd/src/test/scala/edu/gemini/ictd/CustomMaskKeySpec.scala
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskController.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Ictd.java
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProgramId.scala
- project/OcsBundle.scala
In the initial QPT+ICTD release I misinterpreted the columns of the ICTD `MOS` table.  I had thought that an observation's custom mask name should be matched to the `MOS` table's `ODF` field to find the mask's availability.  In reality the `ODF` field turns out to be informational and the `MOS` table should instead by keyed by its corresponding program id + `RunningNo` columns.
This PR updates the code to ignore the `MOS` table `ODF` column altogether.  Instead it parses a GMOS observation's custom mask field to obtain a `CustomMaskKey`, identifying the program id and running number for the mask entry in the `MOS` table.
> REL-3452: parse mask name and use it as lookup key

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/AirmassLimit.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ElevationConstraintSolver.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/RiseTransitSet.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visualizer/Visualizer.java
This PR updates the default error and warning airmass limits used throughout the QPT as requested.  Previously the limits were defined in a couple of places.  They have now have been collected in an `AirmassLimit` enum.
I believe this is correct, but perhaps @tpolecat could take a look as well.  I definitely could have missed some of them.
> REL-1714: change airmass limits

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/Twilight.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/MergeAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/OpenFromWebAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/VariantAdapter.java
This PR changes the QPT twilight boundaries to the civil, 6 degree definition.  This allows `SBAny` observations to be scheduled earlier in the night without impacting other sky background constraints. 
To ensure consistency, I centralized the twilight bound computation in a single place.  I'm not particularly pleased with how it came out though.
> REL-1714: Change night boundaries to civil twilight

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/Twilight.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/VariantAdapter.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visualizer/Visualizer.java
Airmass limits and twilight bounds were adjusted as requested in #1534 and #1535 respectively.  I had incorrectly assumed that the QPT should display the new reality accordingly.  Instead the old limits and boundaries should in fact still be displayed and yet the calculations need to be based on the new limits.  This PR updates the visualizer, property sheets and schedule document accordingly.
> REL-1714: show nautical twilight and airmass 2 limits

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This replaces the contributing constraints in the QPT intersection messages with a letter indicating which constraint was responsible for a given constraint limit. For example: "Notice: Must be observed between: 19:55(A) - 22:18(T)."
> REL-1714: Report constraint contributing to intersection boundary

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/AirmassLimit.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ElevationConstraintSolver.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/Twilight.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/MergeAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/OpenFromWebAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/RiseTransitSet.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/VariantAdapter.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visualizer/Visualizer.java
This PR brings the latest spate of QPT changes to address the final REL-1714 request over to the release branch.
> The QCs decided to change the default airmass constraints to give a warning if airmass > 2.0 and give an error if airmass > 2.3.  It was also agreed that BG-Any observations may be scheduled between civil (6-deg) twilights.  It was requested to add a letters to the time ranges to indicate the origin of the constraints: (T)iming window, (A)irmass, (B)ackground, and (H)our angle.  For example: "Notice: Must be observed between: 19:55(A) - 22:18(T)."
> REL-1714: patch release update

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This was a bug we missed in #1536.
> REL-1714: Fix bogus timestamp equality check

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Observation.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_disabled_observations.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ObservationSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListModel.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
This redoes some work that was originally intended to be in the 2018B PIT, but that we felt hadn't had adequate testing to ensure it was working exactly as expected.
The idea here is that normally, when the PIT is launched, the Observations section contains no entries.
Science requested in REL-3290 that this be changed, and the Observations section begin with an "empty observation" to serve as a guide for users so that they better understood how to create the necessary data.
Here is a before picture:
Here is an after picture. As you can see, there is now an empty observation:
> REL-3290: Implemented empty observation in PIT.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/AltairNode.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
The laser at GN is not working and thus will not be available for 2019A proposals.
This PR:
1. Removes the LGS options from Altair;
2. Issues a warning if upconverting with an observation requiring Altair LGS; and
3. Produces an error (that disallows submission) if the proposal contains an observation with Altair LGS.
Here is a screenshot that shows the Altair node in the resource selection:
> REL-3453: Made Altair LGS unavailable for 2019A

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
Updated GMOS north and south web forms to include radial IFU summing analysis method with a default value of 1 arcsec.
Expecting Travis to fail the checks in bundle_edu_gemini_horizons_api, which Olesja has also encountered and was not modified in this case either.
> REL-2659: Clean up ITC support for summing GMOS IFU elements web forms

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/ScheduleIO.java
- bundle/edu.gemini.qpt.client/src/test/resources/edu/gemini/qpt/core/v1031-unexpected.qpt
- bundle/edu.gemini.qpt.client/src/test/resources/edu/gemini/qpt/core/v1031.qpt
- bundle/edu.gemini.qpt.client/src/test/scala/edu/gemini/qpt/core/MigrationSpec.scala
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/MiniModel.java
When opening an old schedule document, the block interval is set to nautical twilight.  Because the block interval trims all the cache results (such as the `VISIBLE_UNION_CACHE`) we mistakenly report availability ranges limited by nautical twilight.
This PR adjusts block boundaries to civil twilight upon import if they were set to nautical twilight.
> REL-1714: Support for migrating pre-civil twilight schedules

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
The faintness level acceptable by GPI in the PIT is now affected by the conditions (image quality and cloud cover). This incorporates the faintness level adjustments as per the JIRA task, and prioritizes problem messages as per discussions with Frederik and Bryan.
(Note: it is possible, with the new updates, for a target to be simultaneously "too bright" and "too dark" if certain conditions are chosen: hence why the error messages are prioritized. This was discussed with science and despite the oddity of it, is the desired requirement.)
> REL-3413: Update GPI magnitude checks in PIT

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/resources/edu/gemini/qpt/ui/html/template.vm
I inadvertently deleted a QPT `ScheduleDocument` method because it appeared to have no usages only to find out that yes, in fact it is used from a velocity template.  This marks the 1001st time I've relearned that lesson.
> REL-1714: replace access to twilight for velocity template

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
This is a straight-forward change of the exposure time at which the OT will automatically select "Very Bright" (high-noise) read mode.
The ITC tests all (surprisingly) pass.
> REL-3465: Modify GNIRS exposure time at which read mode is set to "Very Bright"

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
I had misconfigured the parameters to `LastStepConverter` for the last few semesters, so that when upconverting, say, a proposal from **2018A,** the user was told to see the original, unmodified proposal, to use the **2018B** PIT.
This fixes that.
> REL-3466: Fixed improper use of LastStepConverter

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/HorizonsLookup.scala
This is in response to Bryan's note on REL-3111 saying there were too many ephemeris data entries during PIT lookups (where we had approximately four): Rob and Bryan decided to cut the number back to 200 entries.
> REL-3111: Cutting back the number of ephemerides entries to 200.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
Carlos discovered that GHOST high resolution observations were not serializing properly.
This is because the standard resolution observations use a sealed trait, whereas the high resolution observations use a sealed abstract class, which I suppose needs to be marked as serializable.
> REL-3460: Fixed serialization problems with GHOST HR programs.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Observation.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
In the original change I made for REL-3290, I implemented a "template" observation, i.e. an empty observation so that the fields needed to be filled by people filing proposals was more user-friendly:
However, it was brought to my attention during testing that the template did not show up for band 3 observations. This PR rectifies that. Note that a bit of ugly hackery is involved, as we need `Observation` to always have a band 1/2 observation and a band 3 observation (although, if empty, these are eliminated before submission).
Here is the final result:
> PIT REL-3290: Extend template observations to band 3

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Flamingos2.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
F2 MOS mode is not being offered in 2019A.
This PR:
1. Hides MOS mode from the mode configuration dialog;
2. Reports an error in the upconverter for 2019A if an observation is in F2 MOS mode;
3. Includes this check in a test case; and
4. Reports an error in the "problems" section as long as an F2 MOS observation exists, preventing proposal submission.
> REL-3485: Hid F2 MOS for 2019A and set up errors.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
Classical observing with CFH is no longer available: it will  now be done in queue mode.
This PR, as a result:
1. Upconverts  an older classical proposal with CFH to a queue proposal with CFH.
2. Issues an error in the Problems section if  Classical + CFH somehow simultaneously become both selected in the model. (This should never happen.)
3. Changes  the contents of the Request Type combo box to disinclude "Exchange Request (CFH PIs)" when the proposal class is classical.
4. If the Request Type combo box is set to "Exchange Request (CFH PIs)" and the user changes the Proposal Class to Classical, the Request Type is set to "Gemini Partner Request" (the first thing in the Request Type list).
> REL-3493: Hide CFH option from classical observing.

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2019A.xml
This makes the changes to prepare for the 2019A actual PIT release, instead of the test releases.
Based off previous PR to do the same for 2018B:
https://github.com/gemini-hlsw/ocs/commit/2de0681b744a036dba5c944d68cee37fb6ed2fe1
> REL-3495: Preparing PIT for 2019A release.

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/InstallationState.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTable.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTableModel.scala
This PR implements an additional feature request for REL-1958: ICTD / QV integration.  Namely, it shows *which* instrument components in an observation configuration are not installed in a tooltip popup.
> REL-1958: show which configuration items are missing

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/image/ImageCatalogClient.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageDisplayFrame.java
- bundle/jsky.app.ot/src/main/java/jsky/image/fits/codec/FITSDataDouble.java
- bundle/jsky.app.ot/src/main/java/jsky/image/gui/ImageDisplayControl.java
- bundle/jsky.app.ot/src/main/java/jsky/image/gui/ImageDisplayControlFrame.java
- bundle/jsky.app.ot/src/main/java/jsky/image/operator/CutLevelOpImage.java
These are some fixes to bugs I found when prototyping a mosaic service for 2MASS images.
I tried to open a Montage-generated FITS image and immediately ran into destruction.
- `ImageDisplayControlFrame` and `ImageDisplayControl` need to be abstract … the constructor does some downcasting that only works if you're using the one and only subclass `TpeImageDisplayFrame`. So I made them abstract and moved the non-functioning `main` method.
- `FITSDataDouble` was downcasting to a JAI class that has since appeared in `java.awt`, I guess. Changing it to use the AWT class instead made it work. No idea.
- We couldn't deal with FITS images with double-precision data so I copy/pasted the handler for `Float` to deal with it. Seems to work.
**Late addition:** I also noticed that every image request …
> Fixes for TPE image handling.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/timingwindowcheck/TimingWindowFunctor.scala
- bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/timingwindowcheck/Arbitraries.scala
- bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/timingwindowcheck/Setup.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ProgramForm.java
This PR finishes REL-361 by adding a support for a requirement found in the comment section that I had overlooked in #1576.  Namely, it provides a timing window notification override flag that can be set by anybody with access to the program in the top-level node editor. 
> Recently there have been some programs that create many (~100) observations with one timing window per observation, for example, GN-2018A-Q-124 NIRI observations of Io. Programs like this may prefer to not get an email every time a window expires. One possible solution would be to add a checkbox at the top of the program "Notify of expired timing windows" where PIs can opt-out of these emails. In this case, we may want to relabel the "Notify PI" checkbox and possibly put the two notification checkboxes on a new line, …
> REL-361-B: timing window notification override flag

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/image/ImageCatalog.scala
This updates the 2MASS image server URL used by the TPE … they switched to SSL for some reason. Tested on a handful of targets. Works, also pretty fast.
> REL-3530 Update 2MASS image server URL in the OT

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Ephemeris.scala
This PR makes a small but important change to the way that the twilight bounds are calculated for the purpose of adding markers explaining observability limits.  Instead of repeatedly calculating the twilight bounds based on the time of individual allocations, we make it consistent with the schedule caches themselves using the schedule start time as a whole.
This fixes an issue in which an allocation well off of the night into the morning (when adjusted from a previous schedule and used as a template) was triggering an exception.
> REL-3519: make twilight calculation consistent

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
The only P2 rule using a call to `getObsAsterism` was not checking `null`, which the method can return, thus causing a NPE in the OT when trying to open programs.
> REL-3533: null check now performed after call to getObsAsterism.

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
An addendum to #1581, empty schedules like the ones you (temporarily) get when creating a new plan, have no start and therefore no allocs nor markers.  Since we're now relying on `Schedule.getStart()` to figure out the twilight bounds the schedule needs a start or else the call to `getStart()` generates an `IllegalStateException("Schedule is empty.")`.
> REL-3519: empty schedules have no start

- bundle/edu.gemini.itc.shared/src/main/java/edu/gemini/itc/shared/ITCChart.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
GMOS I changed the GMOSrecipe directly, as it was explicity defined what colors are assigned to what data series. F2, NIFS, NIRI, and GNIRS only need the "Signal" and "SQRT" data series reversed (the S2N charts for these instruments already fit the requested color scheme). For this, I reversed the color indices in ITCchart.java -with suggestions from Sebastian - to reverse the data colors. Tested web bundle before creating pull request.
> REL-2630: Changes to chart colors

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java
We have a new filter for GMOS-N: this just adds it.
It's taking the place of `DS920_G0312`, but I have been told not to obsolete it.
> REL-3536: Added ri filter for GMOS-N.

- .gitignore
- app/spdb/build.sbt
`OcsCredentials.scala` (from the `ocs-credentials` svn project) needed an update to make the test and production ICTD configuration work for the ODB.  Along the way, I removed the `dnavarro` config and updated the `.gitignore` to ignore Idea's `.iws` files.
In other words, this PR doesn't fix the problem with the ICTD configuration but was necessitated by updates to OCS credentials that do fix the problem.
<b>Update your `ocs-credentials` project when this is merged.</b>
> REL-3545: ancillary changes around OcsCredentials update

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/CandidateObsController.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/CandidateObsViewAdvisor.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/problem/ProblemController.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/variant/VariantViewAdvisor.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visit/edit/CutAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visit/edit/DeleteAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visit/edit/PasteAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visit/edit/SelectAllAction.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visualizer/PlotViewer.java
`edu.gemini.ui.gface.GViewer` maintains a nullable `model` field.  It was implemented years before the `Option` concept was fully understood in the Java world and has caused problems, particularly for drag and drop, in the QPT.  Ideally we would refactor `model` to wrap it in an `Option` and in fact I started down that path.  Because the change was beginning to grow beyond what I'm confortable updating during the testing period I punted though and just started doing `null` checks. 
This PR looks more daunting than it actually is because the editor has trimmed trailing whitespace.  If we could ignore whitespace the changes view would be much smaller.
> REL-3519: check usages of viewer.getModel()

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/Visitor.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/VisitorBase.scala
When creating a blueprint for visitor instruments, the changes in this PR will set the wavelength according to the instrument name.  Since we don't have a type for the various visitor instruments and yet we need to distinguish between Alopeke and DSSI to set the default wavelength, we just check the name set from the PIT.
> REL-3526: set default wavelength for visitor instruments

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
Fixes a bug in the editor for proper motion fields in template parameters.  In particular, instead of updating a new target we were updating a clone of a new target and then promptly forgetting it.
> REL-3352: make proper motion field editing great again

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
REL-1608 brought an update to time accounting rules, but only for observations started in 2019A and beyond.  In order to make testing in November 2018 possible, we need to act as though the update works starting in 2018B until it can be verified.  Once verified, I'll need to undo this update.
> REL-1608: temporary change to start time accounting update in 2018B for testing

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTable.scala
This PR fixes a couple of bugs with ICTD integration.  Namely:
* adds a renderer for integer columns so that they appear with the proper highlight colors
* handles rendering correctly when the table is reordered via sorting
> REL-1958: QV observation table bug fixes

- bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/maskcheck/MaskCheckCron.scala
Sadly the only way we have to determine if a file is a mask definition file is by name.  Instead of ending with `.odf` though as previously assumed, they are in fact terminated with `_odf.fits`.
> REL-1985: fix ODF file name suffix

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/ScheduleIO.java
TIL that QCs will deliberately "schedule" observations in the day time as alternatives. When we open a queue plan with allocations during the day surrounding the schedule night, they shouldn't be flagged as incorrect. This PR widens the valid range to include the surrounding day time.
> REL-3519: widen the valid allocation time range in QPT schedule files

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
This PR fixes a few issues with the TPE / CQT integration.  Most importantly, it handles guide star candidate selection in the TPE such that the corresponding target row in the CQT is also selected.  This was broken due to an initialization order issue so I reworked it to explicitly link and unlink with the necessary image widget observers instead of doing it on construction.
In addition, when using the visitor instrument, updates to the CQT form would cause the selected site to go missing from the observation context which made it impossible to calculate guide star quality.
These updates are admittedly ad hoc. A complete rewrite of the TPE and catalog search code is probably in oder.  I think given the EOL status of this code and the fact that we're nearing the end of the testing cycle, …
> REL-2719: TPE / Catalog Query Tool Integration Bug Fixes

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java
This is a tiny tweak to make the colors of the GNIRS ITC XD "Final" S/N graph darker.
> REL-2630: make colors of GNIRS ITC XD Final S/N graph darker

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsGuideStars.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsMagnitudeTable.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/Mascot.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsGuideSearchOptionsSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsTestVoTableMod.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsVoTableCatalogSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala
This PR introduces a change to the CWFS magnitude limits and a change to the way that the magnitude limits are adjusted to conditions.  In particular, the nominal R-band magnitude limit itself is lowered from 16.3 to 15.0 to require brighter stars and the sky background is no longer considered relevant.
The main challenge of this task was keeping the test suite working.  To make that possible, I apply magnitude corrections to the canned catalog results such that they correspond to the new limit calculations.  For the most part this worked but the magnitude limit change does produce slightly different strehl calculations which change the result of one test case (see the `gems_m6.xml` cases).
> REL-3550: update GeMS CWFS limits

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/AltairNode.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Altair will now be offered for all forthcoming 2019A proposals. This undoes the previous changes that made Altair not offered for 2019A.
> REL-3552: Re-enable Altair for rest of 2019A semester.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/GmosNorth.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
As LGS isn't possible with GMOS-N for 2019A, we add code to remove Altair nodes from GMOS-N observations, as we did in REL-3363.
> REL-3552: Restore code from earlier semester that removes Altair from GMOS-N

- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/AOConfig.java
Due to the new laser, the magnitude as per the WDBA must be changed.
I have confirmed that this does not affect GeMS.
> REL-3563: Update Altair default LGS guide star magnitude

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
The TPE plot for AGS guide star candidates needs a guide probe to evaluate guide stars.  Using the probe's magnitude limits it can determine whether the guide star is too faint or requires slower guiding, etc. and hence color the candidate accordingly.
At least in theory, for GeMS multiple guide probes can be involved and unfortunately only one can be used for the plot colors.  In reality we only use Canopus now for GeMS so this PR tweaks the catalog UI to ensure that we evaluate GeMS candidates wrt to Canopus.  Before it would select the first one [which happens to be F2 OIWFS](https://github.com/gemini-hlsw/ocs/blob/develop/bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala#L191)!
> REL-3550: use CWFS3 to evaluate guide star suitability for GeMS TPE plot

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
This took an embarrassingly long time to figure out, given what a simple fix it was.
The issue was that when switching target types, if the user tried to switch a target to the base, the base would not change, and the target would morph to the base and would be unselectable.
This was due to creating the asterism incorrectly, using the old base position for the new base position and the user position. This resulted in the base position never changing, and having the same reference as the user position (that was morphed from the base position), thus making the user position unselectable.
I have fixed this by setting the new base position to the user target to morph, as it should have been, and now the base position converts properly, and everything is selectable.
> REL-3569: Fixed issue with base morphing.

- bundle/edu.gemini.ags.client.impl/src/main/scala/edu/gemini/ags/client/impl/QueryArgs.scala
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_zorro.xml
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Zorro.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/BlueprintBase.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ZorroBlueprint.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Proposal.xsd
- bundle/edu.gemini.model.p1/src/main/xsd/Zorro.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_zorro.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_dssi_gs.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/ZorroSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ZorroBlueprintSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpBlueprintFactory.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Zorro is a copy of 'Alopeke that is replacing DSSI at GS just as 'Alopeke replaced DSSI at GN.
Thus, the implementation was straightforward, following the implementation that was done for 2018B when 'Alopeke replaced DSSI. Note that this also covers REL-3607, i.e. adding initial implementation for Zorro to the OT, since it was easier to just do them both at once.
Here are two screenshots of a 2017B DSSI GS program being opened in the 2019B PIT.
> REL-3454: Add support for Zorro at GS to replace DSSI.

- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTooUpdate.java
- bundle/edu.gemini.oodb.too.url/src/test/scala/edu/gemini/spdb/rapidtoo/www/HttpUpdateSpec.scala
Changes an error message when the exposure time cannot be parsed as an integer and raises the maximum exposure time to 1200 seconds.
> REL-3609: addendum

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
Readding Texes as per REL-3606. The other parts of 3606 (i.e. show Zorro and hide DSSI) were taken care of by the PR for REL-3454.
> REL-3606: Readded Texes to the PIT.

- bundle/edu.gemini.auxfile.workflow/build.sbt
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObsRecordDatasetFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitTimeFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitsFactory.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/InstrumentService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/NightObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObsCache.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/ObsExecRecord.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisit.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/ObsVisitService.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/TimeAccounting.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obs/InstrumentServiceSpec.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TimeAccountingSummaryTable.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/EdCompObslog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogGUI.java
Changes the time accounting rules to always charge for visitor instrument observations regardless of whether there are any chargeable datasets in a visit.  This change is to be retroactively applied to the start of 2019A (which is why the existing 2019A rule could be simply updated).
Time accounting has heretofore been instrument agnostic, so the bulk of this update is passing the instrument down through multiple layers of API to the `VisitCalculator` where it is needed.  Otherwise there is a new `InstrumentService` that calculates the `Instrument` associated with an `ISPObservation` (if any) and an update to the `SPObsCache` to cache the calculation.
> REL-3625: time accounting rule update

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisit.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
Adds `serialVersionUID` to a couple of classes to avoid spurious serialization incompatibilities. The `PrivateVisitList` and `PrivateVisit` API changes slightly but not the data itself.
I've confirmed that with these changes the current production version of programs containing observations with an observation log will open fine in either version of the ODB or OT.
> REL-3625: add serialVersionUID

- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/SpImportService.scala
Fixes an issue with the "Create duplicate" option when trying to import from XML a program without a program id that already exists in the database.  We cannot assume that an `ISPProgram` has a program id.
> REL-3627: fix duplicate on import

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
Send the correct number of exposures (without coadds since they are now separate).
> REL-3632: Fix OT ITC interface which is double-counting coadds

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/syntax/package.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/syntax/sp/Instrument.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
Adds Acquisition Camera, Phoenix and Texes to the list of instruments which should be an exception to the new Time Accounting rule of REL-1608.
> REL-3636: AcqCam, Phoenix and Texes exceptions

- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObsRecordDatasetFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitTimeFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitsFactory.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/NightObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/ObsExecRecord.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisit.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/ObsVisitService.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/TimeAccounting.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TimeAccountingSummaryTable.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/EdCompObslog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogGUI.java
Updates the 2019A time accounting rule to always charge for GPI acquisitions, since they often do not produce datasets.  The bulk of the work was adding the observation `ObsClass` as a parameter since it is needed to make the determination.
> REL-3628: time accounting update for GPI acquisitions

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/config/AbstractSeqComponentCB.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/SeqConfigGNIRSCB.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/gnirs/ObsWavelengthTest.scala
Fixes a bug in SmartGcal lookup for GNIRS.  In particular, a change to the way that the observing wavelength is set in the sequence is required in order to have the correct observing wavelength value at the time it is used by the SmartGcal lookup.  Instead of post-processing the sequence to add observing wavelength, it needs to be written into each step where it changes.
__CAUTION:__ This PR plumbs the depths of the current sequence model and may burn your eyes.
> REL-3520: GNIRS Observing Wavelength in SmartGcal

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSConstants.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSParams.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
This adds an engineering item to the GNIRS iterator to select one of the Hartmann masks, and another engineering item to manually set the focus.  This seems to work as expected from the UI, but please check that it makes sense.  One complication is that the Hartmann masks are *not* in a separate mechanism, but rather installed in filter wheel #1.
> REL-3620: Add GNIRS Hartmann masks and focus

- build.sbt
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/template/TemplateParameters.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
The ToO target type was missing in the OT templates menu. As is visible in this screen cap, this resulted in ToO targets being labeled as non-sidereal in the template editor:
When the templates were instantiated, they were still created as having target type ToO; however, it was not possible to create new targets with target type ToO in the template editor.
Now, in the case that a program is a ToO program, we add the target type ToO to the combo box, and ToO targets display the proper type in the template editor:
> REL-3603: Missing ToO Target Type in OT Templates menu

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/util/ConstraintsCache.scala
Timing windows may be defined with a number of "Repeats". The OT elevation plot and the QPT interpret this to mean there are Nrepeat + 1 windows, i.e. if a window repeats once there are two total.  This change updates QVis to have the same interpretation.
> REL-3667: Change the number of QVis repeated windows to N+1

- app/itc/build.sbt
The production ITC is experiencing `OutOfMemoryException`s, and thus I am increasing the max heap size. I have submitted a help desk ticket to increase the amount of RAM to the VM to 4 GB as well, as it is currently set at 2 GB.
> REL-3654: Increasing max heap size for ITC.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Longslit.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Mos.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/F2BlueprintTest.scala
There were some discrepancies between observation library IDs in the former` F2_BP.xml` file and the `F2_BP.txt` algorithm implementation, which was causing errors to be reported about nonexistence observation library IDs.
This uses the new files, which now ingest F2 blueprints correctly, and also fixes a problem where two notes were missing.
> REL-3661: F2 blueprint update fix

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Base.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Imaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Longslit.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Mos.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/F2BlueprintTest.scala
This PR fixes a few issues with skeleton creation and template instantiation for F2.
* All notes should now be included
* The order of observations should be what is expected
* Conditions should be copied in when instantiating
Inexplicably, we sort the observations by library id so I had to renumber the ids in the XML and p-code.
I removed the explicit conditions from the XML because they were preventing the template conditions from being used.
It doesn't include the logic for setting the custom mask name since it relies on having the program id, which isn't available.  I left a bit of code commented out that may do the trick if add a parameter to initialize to pass in the program id.
> REL-3661: F2 template updates

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
Minor tweaks to REL-3661:
* Changes the "mask daytime image" observation to provide explicit Any/Any/Any/Any conditions.  
* Updates the version date in the p-code file.
> REL-3661: template updates

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/VisitorBase.scala
When Zorro was added, it should have had the same wavelength as Alopeke, but due to not including it in `VisitorBase`, it defaulted to the visitor wavelength.
This fixes that problem so that now Alopeke and Zorro have the same wavelength.
> REL-3607: Set Zorro wavelength to be the same as Alopeke

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GMOS_N_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GMOS_S_BP.xml
Updates GMOS spectroscopy observation templates with a new note.  These are apparently copied in by virtue of being part of the science observation rather than being explicitly listed as in the F2 case.
The template programs also contain ancillary updates in the latest model such as the addition of asterisms.
> REL-3684: updated notes

- .gitignore
- app/spdb/build.sbt
- project/src/main/scala/edu/gemini/osgi/tools/app/Configuration.scala
The reports service does not run reliably in `g[ns]odbtest`.  This is apparently related to the polling of EPICS weather channels in the test environment and results in pegging the CPU and the inability to turn off either the reports bundle itself or the `spdb` process as a whole.  It would be nice to find out why the EPICS channels cannot be monitored in the test environment, but in lieu of that we can also just skip it for the test servers.  That's what this PR accomplishes.  Specifically it
* runs the reports bundle at level 60
* sets the default startlevel to 50 in the `g[ns]odbtest` configurations
Yes, this is a hack.
> Turn off reports by default in g[ns]odbtest

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/instrument/InstViewAdvisor.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/instrument/OutlineNode.java
The QPT "Update from ICTD" command was only working when there were in fact updates to the information in the ICTD.  The user quite naturally expected to use this feature to restore the values from the ICTD after they had been manipulated in the QPT "Instrument" feature tree.  That wasn't working because:
* Since the ICTD information didn't update no event was triggered and no updates to the selected features were done.
* The `OutlineNode` has some odd selection behavior in its `setSelected` implementation.  Out of extreme hubris and tempting fate, I created a new version called `setSelectedCorrectly` that is only used by the "Update from ICTD" feature. With this in place, the parent nodes are updated to reflect the state of their child nodes as expected.
> REL-3696: fix Update from ICTD issues

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/AbortObserveEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/EndDatasetEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/EndIdleEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/ExecEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/ObsExecEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/PauseObserveEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/StartDatasetEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/event/StartIdleEvent.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsExecEventHandler.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsExecLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/ObsExecRecord.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/AbstractSessionEventConsumer.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/DatasetCompleteEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/DatasetStartEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/ObservationAbortEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/ObservationPauseEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/ObservationStopEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/SequenceStartEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/SessionEvent.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/SessionXmlRpcHandler.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/dbup/AllEventsLoggingService.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/dbup/DBUpdateService.java
REL-3698 concerns an end dataset event that was apparently received but not processed.  It isn't clear from the logs what happened.  This PR simply tightens a few loose screws, removes some unused code, and adds more logging that might help diagnose the issue or at least narrow the search space if it comes up again.
> REL-3698: more logging

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameResolver.scala
PIs are not allowed to specify better conditions at phase 2 than were declared during phase 1. To enforce this constraint we provide a "phase 2 check" that compares phase 2 observations with template parameters extracted from the phase 1 document.  In order to do the comparison, it finds matching parameters based upon the science target.
This check is only enabled for sidereal targets today, but this PR would add non-sidereal targets as well.  In order to compare non-sidereal targets we use the horizons id rather than the coordinates check used for sidereal targets.  This allows the ephemeris to differ or be missing for one or the other target and still be considered the same.
Unfortunately the template parameters are not being initialized with the horizons id from the phase 1 document. …
> REL-3695: NonSidereal Phase 2 Checks

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
Small update to #1682. When the template parameter target type is changed, keep the target name. In other words, switching from Non-Sidereal to Sidereal or vice versa shouldn't cause the target name to be reset to "Untitled".
> REL-3695: keep the name when the target type changes

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Proposal.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_extragalactic.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_galactic.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_solarsystem.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
This accomplishes what is laid out in REL-3640, namely:
1. Rename "TAC Category" to "Category"
2. Change the previous categories - Solar System, Galactic, Extragalactic to a list of seven categories.
3. Modify the UpConverter to convert the previous categories to the new ones that are applicable to them.
NOTES:
1. I wanted to change `TacCategory` to `Category` to reflect this, but `scalaz` contains a `Category` so this resulted in clashes.
2. The REL task specifically asks to keep the `proposal` tag attribute as `tacCategory` in order to simplify this change; hence, I did not change it.
Here is an example of up-conversion of a Zorro Galactic program and the resultant UI where you can see that the Category is now "Stars and stellar evolution."
> REL-3640: Updates to PIT categories

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
Images demonstrating the positioning of the observing mode after the keywords section as requested in the PR.
Queue + No TOO:
Queue + Rapid TOO:
Queue + Standard TOO:
> REL-3671: Moved observing mode and TOO information as per request.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
This PR makes some GPI private enums public so they can be used on the seqexec
See:
https://github.com/gemini-hlsw/ocs3/pull/1033
> Make gpi enums public

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
The next in a series of updates to add GAIA.  This one allows redshift to be specified in terms of radial velocity instead of the existing redshift option.  If both redshift and radial velocity are specified, the redshift value is preferred.
This is needed because GAIA results only have radial velocity and we only store redshift in the `ocs` target model.
> REL-3676-B: Radial velocity to redshift

- bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/gems/GemsGuideStarSearchOptions.java
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/mascot/MascotGuideStarSpec.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQueryResultSpec.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQuerySpec.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
Installment three on the road to including GAIA.  This one is mostly a mechanical refactoring but there is one substantive change.  The entry point is:
```scala
VoTable.parse(catalog: CatalogName, is: InputStream): CatalogResult
```
which in turn called a `parse` method that tries to figure out which adapter to use, for each table row, based on the XML it encounters. Unfortunately GAIA cannot be easily identified this way and it seemed to me that we should base the adapter on the given `CatalogName` upfront.
Most of the changes, though, are just related to moving the `CatalogName` instances inside the `CatalogName` object and the `CatalogAdapter` instances inside the `CatalogAdapter` object.
> REL-3676: small refactoring

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/mascot/MascotGuideStarSpec.scala
- bundle/edu.gemini.catalog/src/main/resources/votable-1.3.xsd
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/VersionToken.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/VersionTokenSpec.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/SiderealNameEditor.scala
The next REL-3676 installment adds Gaia to `VoTableClient` and updates the manual catalog UI to include Gaia in the list of options.
The bulk of this PR is the VO Table schema 1.3 version (which is needed for the Gaia results) but doesn't need to be reviewed.  It also adds a `VersionToken` class to work with the schema versions.
> REL-3676: add Gaia to VoTableClient

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
A small update to `VoTableParser` to include a target's epoch.  Gaia results have reference epoch 2015.5.
> REL-3676: get the epoch from the results

- .gitignore
The files linked by credentials for TOO exploder information should have been added to `.gitignore`. This fixes that.
> REL-3729: Adding files to .gitignore.

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
When using the `PARALLACTIC_OVERRIDE` mode, it was possible for the parallactic angle to be flipped by 180 degrees, which is not the desired behaviour as the PI knows what angle is desired. Thus, the `PARALLACTIC_OVERRIDE` option should behave like the `FIXED` option instead of the `FIXED_180` option.
This fixes that so that the angle does not end up flipped.
> REL-3448: Fixed PARALLACTIC_OVERRIDE to not flip by 180.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/util/DefaultSchedulingBlock.scala
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2020A/To2020A.scala
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2020A/GS-2020A-Q-501.xml
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2020A/SchedulingBlockTest.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
This PR contains a couple of updates to the way that scheduling blocks are handled:
1. When importing old programs it adds a default scheduling block to observations that do not have one.
2. It makes the scheduling block editor always available in the target environment form.
The context for these changes is that GeMS AGS is failing for older observations that have no scheduling block.  This happens because in theory you cannot know the base position coordinates without first knowing *when* you're asking for them. "In theory" because in reality we don't apply proper motion updates to sidereal targets anyway. Nevertheless, without base position coordinates there's no way to know whether potential guide stars are in range.
We create a default scheduling block for new observations anyway, so …
> Scheduling Blocks

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/image/ImageCatalog.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/image/ImageCatalogClient.scala
This adds the Montage version of the 2MASS image server, which create custom tiled images that fill the TPE field better than the existing servers. Here is an example looking at M3. It's a little movie actually, if you click on it.
Note that the image in the example has been cached locally. The first time it was accessed it took about 30 seconds, because the mosaic process has to do a lot of work aligning/scaling/rotating and matching contrast levels. The server caches tiles (so nearby positions will resolve more quickly) as well as the final mosaic image (so other people looking at the observation should receive the image quickly).
This is work-in-progress (need to move the montage server over to Gemini, it's running on my private Heroku account right now).
> add montage image servers

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/util/DefaultSchedulingBlock.scala
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2020A/SchedulingBlockTest.scala
This PR updates #1716 to future-proof a test case.  The way that `DefaultSchedulingBlock` works is that it
1. Extracts the semester from a program id
2. Computes the midpoint of said semester
3. Compares it to the midpoint of the current semester
4. Chooses the bigger of the two for the scheduling block start
```scala
def forPid(pid: SPProgramID): SchedulingBlock =
SchedulingBlock(
getPidSemesterCenter(pid).foldLeft(getCurrentSemesterCenter(Site.GS))(_ max _)
)
```
The test case ignored that fact and would begin failing post-2020A without this update.
> REL-3743-B: fix test case which would have failed in the future

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Ngs2Strategy.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/TpePlotter.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeCatalogFeature.scala
This PR adds visualization of PWFS1 options to the guide star candidate plot for GSOI/GeMS.  The challenging bit was a change to the plotter to accept an explicitly provided guide probe for the magnitude evaluation instead of always using the default guide probe for the strategy (CWFS1 in the case of the `Ngs2Strategy`).
> REL-3747: visualization of PWFS1 options

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/ResolutionMode.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismTypeConverters.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
- bundle/jsky.app.ot/src/main/resources/resources/conf/UIInfo.xml
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
In the GHOST instrument configuration node, the user chooses the asterism type to be observed: this determines the behaviour of the target node component in terms of what is allowed and what is expected.
Originally, we had a single drop-down list of all the available asterism modes. It was decided that this should be refined into three resolution modes - standard resolution, high resolution, and precision radial velocity - and then have sub-modes that determine the asterism type.
In addition, when the user changes resolution modes, we attempt to pick the asterism type closest in the new resolution mode to the old resolution mode and perform a conversion on the target environment so that no information is lost.
Here is what the original looked like:
Here are some screen shots of the new …
> GHOSTSW-9: Divide asterism types into resolution modes

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiDetectorArray.java
Update the GSAOI hotspot as requested, such that the (-5, 8) offset is relative to the lower left corner of detector array 3 instead of the base position.  In the image below the view is centered at (0,0) so an offset of (5, -8) should fall in the corner of array 3.
> REL-3744: adjust GSAOI hotspot

- bundle/jsky.app.ot/src/main/resources/resources/conf/UIInfo.xml
We don't want GHOST to appear amongst the list of instruments available for 2020A.
This removes it from the list.
> REL-3758: Removed GHOST from UIInfo.xml

- app/spdb/build.sbt
Due to the change from gsodbtest to sbfodbdev-lv1, the IP address of the VM has changed, which necessitates the change of the IP in the spdb build.sbt file in order to allow incoming telnet connections to the machine.
This updates the IP address.
> REL-3764: Updating IP for gsodbtest / sbfodbdev-lv1.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
GHOST requires target coordinates sent with proper motion taken into effect.
Previously, we sent regular coordinates. Now we use the proper motion calculator that was implemented from OCS3 to send the proper motion coordinates for targets.
Here, in the target editor, you can see the coordinates from the catalog for M32 along with the proper motion information.
Here, in the static configuration, you can see the proper-motion adjusted coordinates for M32 being sent:
> GHOSTSW-18: Proper motion coordinates now sent in sequence for targets.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/exchange/Subaru.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/subaru_multiple.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
As per REL-3769, the following are not available in 2020B:
1. GPI
2. Subaru COMICS
3. Subaru FMOS
Here are some screenshots showing their removal upon opening a program with Subaru COMICS, Subaru FMOS, and Subaru Prime (which should change, from last semester, to Subaru Hyper Prime):
> REL-3769: Resource changes for PIT 2020B.

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Of course, due to erasure, every blueprint was triggering the message that GPI is not offered in 2020B. I think this is the proper way to fix it: it appears to be working now.
> REL-3769: Stupid erasure.

- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
As per the requirements, investigator information is no longer displayed in the generated PDFs for fast turnaround programs.
NOAO with investigators:
[ft-investigators.pdf](https://github.com/gemini-hlsw/ocs/files/4104498/ft-investigators.pdf)
NOAO without investigators:
[ft-no-investigators.pdf](https://github.com/gemini-hlsw/ocs/files/4104500/ft-no-investigators.pdf)
> REL-3772: Do not include investigator information in FT proposals.

- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
The investigator information for FT should only be removed from the p1-monitor. This restores the default behaviour for the PIT and p1pdfmaker and removes it p1-monitor.
> REL-3772: Remove investigator information from FT backend PDFS2, take 2.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
I had forgotten to add guiding for SRIFU1, SRIFU2, and HRIFU1 targets to the configuration.
This rectifies that. You can see srifu1Guiding set to Disabled in the configuration in the screenshot.
> GHOSTSW-21: Added guiding apply keywords to SRIFU1, SRIFU2, and HRIFU1 when applicable

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
This PR unifies the name of the constants in GHOST and adds a few more
> Make constant naming uniform and add a few more

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
I had neglected to add guiding to high resolution mode. This adds the value, as you can see here:
> GHOSTSW-21: Added high resolution mode guiding and minor cleanup.

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
GAIA queries are failing in the production OT, which impacts (mostly) NGS2/GSAOI.  This is due to a server-side change to require https.  Log output from the current OT:
```
Feb 10, 2020 11:57:14 AM org.apache.commons.httpclient.HttpMethodBase processRedirectResponse
WARNING: Redirect from protocol http to https is not supported
```
Simply switching to https seems to fix the problem.
> Switch to https for GAIA

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Catalog.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Result.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Simbad.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/VOTableCatalog.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SimbadLookup.scala
This PR replaces the use of `actor` with `Future` in `edu.gemini.pit.catalog`. This change is required to enable executing PIT on Java 13, which in turn is required for OS X notarization. I've done this in the most straightforward way that I could think of because the PIT catalog code has been superseded even in the `ocs` codebase, which itself is nearing its end of life.
I've also removed the `&&` combinator since it is unused.
> Switch actor to future in edu.gemini.pit.catalog

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.pit.launcher/build.sbt
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
- bundle/edu.gemini.pit/build.sbt
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/model/AppMode.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/osgi/Activator.scala
- bundle/edu.gemini.spModel.core/build.sbt
- project/OcsKey.scala
This eliminates the unpredictable `edu.gemini.pit.test` property to determine whether the PIT being built is a test release or a production release, and instead uses the `pitVersion` in the main `build.sbt` as is done with the OT.
> Make PIT use pitVersion in build.sbt to set version including test / production

- build.sbt
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
Sets the AGS host correctly in the `PITLauncher` which is used now in the OSX version.
> Update AGS host

- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/TooUpdate.java
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/impl/TooUpdateServiceImpl.java
- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTooUpdate.java
- bundle/edu.gemini.oodb.too.url/src/test/scala/edu/gemini/spdb/rapidtoo/www/HttpUpdateSpec.scala
A small update to ToO triggering to allow the note title to be set in the request instead of being fixed to "Finding Chart".  The requirement is that either note text or note title result in a note being added and that given note text without a title, it should default to "Finding Chart".
> REL-3789: add noteTitle parameter to ToO trigger

- project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
Disk images created by default on Mojave use APFS, which doesn't work with ancient MacOS versions (10.9 or earlier).  This PR adds an option to `hdiutil` to explicitly choose HFS+.
> Use HFS+ for MacOS disk images

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetSelection.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
GHOST was resulting in a `None.get()` when switching from Sidereal to Nonsidereal target due to the fact that we explicitly list the base position as well as the IFU targets.
Additionally, GHOST does not support imaging, so this was changed.
> Minor GHOST fixes

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
As per the new requirements, I've added a second fiber agitator to GHOST. The parameters sent to seqexec are now `enableFiberAgitator1` and `enableFiberAgitator2`. (I will update the document.)
Here is a screenshot of the new static GHOST component with the second fiber agitator checkbox in the bottom right area.
> GHOSTSW-26: Added second fiber agitator.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdObservation2.java
This PR would permit PIs to edit observation priority (high/medium/low) for "on hold" observations.  There is a disconcerting warning against doing this very thing in the code that currently disables this feature:
> Don't allow changing priorities when status is not phase1 (not even when on-hold).		            
> This is to avoid getting to an un-editable state.
The warning has been there since the code was first ingested in GitHub 6 years ago. I can think of and find no reason why this should be the case and indeed testing doesn't reveal this problem. I hope it was a misunderstanding, but if anybody has more information please speak up!
> REL-3791: allow PIs to adjust observation priority when on hold

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdProgram.java
This PR would make it possible for anybody who otherwise has access to a program to change the PI email field *in the OT editor* at least.  The reason it wasn't this way before is that "user" keys are tied to this email address.  If your access to the program is via a user key then you end up not being able to sync the program and losing even the ability to edit it unless you can switch to some other key that does work.  So that seems poor.  I expect support ticket requests.
I have a question in the JIRA task but thought I'd get this PR out for discussion in the meantime.
> REL-3458: allow anybody to edit the PI email

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsMagnitudeTable.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
This PR addresses parts 1 and 3 of REL-3771.  Namely:
1. New CWFS NGS2 limiting magnitudes
3. Remove the Color restrictions in the transformation equations 
Part of 3 was to use fixed g GAIA magnitude limits in the search, which simplifies the code a bit.
> REL-3771: NGS2 updates after commissioning

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
As per Steve's specification, as a temporary measure, we will use an inner radius of 5.5 arcsecs.
> GHOSTSW-27: Set PWFS2 inner radius for GHOST.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
The inner radius for PWFS2 for GHOST was set for 5.5 arcsec, which needed to be adjusted.
> GHOSTSW-27: Adjusted inner PWFS2 radius.

- build.sbt
When we updated the certificates, I re-versioned the PIT as 2020B.2.2.1, which broke the PIT. It should have been re-versioned as 2020B.2.1.2, which results in a match with the current version. (Note that re-versioning as 2020B.2.2.2 would have broken things as well since the previous version was broken.)
I spoke with Bryan and this is not a problem since 2020B.2.2.1 was never released, so the versioning remains consistent.
> REL-3813: Version change to get PIT to work.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
The GNIRS acquisition mirror slips at some instrument angles, and the most slippage is seen at Cassegrain Rotator angles of 45 - 150 degrees. When the OT selects the PA for average parallactic angle observations it has two choices separated by 180 degrees. We would like the default to be the one that avoids 45 < CRPA < 150.
Because of this, we want to avoid the average parallactic angle in [45, 150] and take the 180 degree flip instead. We do this by overriding `InstGNIRS`'`setPosAngleDegrees` method inherited from `SPInstObsComp`, to which all methods that set the pos angle are delegated.
> REL-3808: Avoid [45,150] for GNIRS average parallactic angle.

- bundle/edu.gemini.seqexec.odb/src/main/scala/edu/gemini/seqexec/odb/SeqExecService.scala
GHOST needs target information sent with the seqexec.
This PR includes the targets and their type on the info the seqexec can get from queued sequences
> Include the targets when reading the sequence for the seqexec

- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
We need to pass GHOST user targets to the seqexec and while a previous PR was included letting the seqexec query them but it maybe better to include them in the sequence:
Note, the targets are corrected by proper motion like for the science targets
> Include user targets in the sequence config

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/ghost/SeqConfigGhost.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/ghost/SeqConfigGhostCB.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExp.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
Ghost exposure time properties were being placed in the "observe" system config in some places and the "instrument" system config in others.  The OCS in general has special handling of exposure time that is hard to replicate for Ghost. This PR makes the special Ghost-specific exposure time parameters always appear in the "observe" system config.
> Ghost Exposure Time / Count Sequence Update

- build.sbt
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Submission.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_au_submission.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/PartnersSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/Institutions.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/Partners.scala
This removes AU from the Phase 1 model (it's still in the Phase 2 model because old programs yadda yadda).
This required an up-converter so I went ahead and did the rest of the 21A prep.
> REL-3829 - Remove AU partner from PIT, Prep for 21A

- bundle/edu.gemini.gsa.query/src/main/scala/edu/gemini/gsa/query/GsaQuery.scala
GOA switched to use an TLS certificate signed by Let's Encrypt. This PR makes the calls use a custom keystore that includes Let's Encrypt root cert
> REL-3826: Use a custom keystore for calls to GOA

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosSouthType.java
Added a method to tell if an FPU is custom. It would make it easy to handle custom masks in the seqexec
> Add isCustom method to GMOS FPU enums

- .gitignore
- app/ags/build.sbt
- app/ags/conf/logging.properties
- project/OcsCredentials.scala.template
This allows the `ags` app to work with both http and https at the port used by the PIT.  It required corresponding updates to the svn `ocs-credentials` project.  Once merged, the production `gn` and `gs` configuration distributions need to be tested on the build machine.
> REL-3854: Update to run standalone AGS service app

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosSouthType.java
A "very blue blaze" has changed the name of "G480" to "B480".  From Bryan:
> We've decide to rename the grating B480 because of the very blue blaze. Therefore, I've changes 'G480' to 'B480' in the description.
> REL-3849: G480 => B480

- bundle/edu.gemini.gsa.query/src/main/scala/edu/gemini/gsa/query/GsaQuery.scala
The fix for REL-3826 also fixed REL-3841, see:
https://github.com/gemini-hlsw/ocs/commit/47d7a38a5f820249657ac20866e6e4411a2d7762
However there are still some plain `http` queries done in the context of `dataman` that got broken in the process.
This PR fixes that setting the custom `keystore` only for `https` calls
> REL-3841 Fix http/https calls to the archive

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
This PR makes `DisperserOrder` an iterable property and adds it to the configuration regardless of the observing mode.  In particular it doesn't make sense for imaging steps but will be present in the configuration regardless.  This was done to accommodate observations with mixed imaging and spectroscopy steps that heretofore do not allow setting the disperser order (and don't add it to the sequence) when the first step is imaging.
If there is anything outside of `ocs` proper that infers spectroscopy from the presence of a disperser order property in the sequence, it will break with this change.  In theory, scripts should already be checking the disperser itself to make this determination.  The seqexec itself ignores disperser order and wavelength for imaging steps so it should be okay …
> REL-3860: Iterable, omnipresent DisperserOrder

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/instrument/InstViewAdvisor.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Obs.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java
- bundle/edu.gemini.qpt.shared/src/test/scala/edu/gemini/qpt/shared/util/ObsBuilder.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/data/ObservationProvider.scala
Shows the visitor instrument name instead of "Visitor Instrument" in the QPT and published plan.  Sadly all visitor instruments are otherwise treated the same so ICTD availability and filtering in the "Instruments" tab may be confusing.
> REL-3869: show visitor instrument name

- app/spdb/build.sbt
Updates the `osgi.shell.telnet.ip` property for the base-facility ODB.  This had been done in the production configuration for 2020B release, but not updated in GitHub.
> **Be aware** The remote shell does not listen on all interfaces by default; it only listens on the localhost. That is, by default the remote shell is only accessible from the host on which the remote shell is running. To access the system from another host, you have to configure the IP address of the interface to which the remote shell should be attached.
> update telnet ip

- bundle/edu.gemini.model.p1.targetio/src/main/scala/edu/gemini/model/p1/targetio/impl/HorizonsEphemerisParser.scala
- bundle/edu.gemini.model.p1.targetio/src/main/scala/edu/gemini/model/p1/targetio/impl/NonSiderealReader.scala
- bundle/edu.gemini.model.p1.targetio/src/test/scala/edu/gemini/model/p1/targetio/impl/TargetUtil.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Target.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Target.xsd
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/HorizonsLookup.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/P1TargetConverter.scala
This change:
- Adds `horizonsDesignation` as an optional attribute for `NonSiderealTarget` in the Phase 1 schema. 
- Captures this value after a successful Horizons lookup in the PIT target editor.
- Preserves the value through skeleton generation.
Note that this change does _not_ attempt to parse the designation from imported ephemeris files. I think this is probably impossible in general because you need to know what kind of search you were doing in order to interpret the header.
> Capture HorizonsDesignation in PIT

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1.targetio/src/main/scala/edu/gemini/model/p1/targetio/impl/HorizonsEphemerisParser.scala
- bundle/edu.gemini.model.p1.targetio/src/main/scala/edu/gemini/model/p1/targetio/impl/NonSiderealReader.scala
- bundle/edu.gemini.model.p1.targetio/src/test/scala/edu/gemini/model/p1/targetio/impl/TargetUtil.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Target.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Target.xsd
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/HorizonsLookup.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/target/TargetView.scala
In response to Bryan's concern about target names being ambiguous, this PR
- adds the query string to the editor popup, which brings the behavior mostly into parity with what the OT does.
- adds a Query column to the target view.
- It also adds the query string to the PDF, when present. Implemented for Gemini ...
- and NOAO
> [REL-3792] (3) add query string to target editor

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/tac/TacView.scala
Fixes a bug when saving a GT proposal without submission responses. It also improves the wording of the ProblemRobot in TAC mode
> REL-3861 Fixes a bug when saving a GT proposal

- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
This seems to break horizons now, and in any case is no longer needed.
> Don't install a custom SSL factory for horizons

- build.sbt
- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
Fixes the horizons lookup without changing the model version number
The title on the UI was hardcoded to include the minor version number 🙈
> Horizon fix without updating the model version

- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Inst.java
Removes obsolete instrument items from the QPT filters.  The specific request was to remove the GNIRS 3.0 slit (which is obsolete).  It seemed like all obsolete items should be removed though.  Presumably this means that any observations configured to use an obsolete item will not appear in the candidate set.
> REL-934: Remove obsolete instrument options

- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GMOSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GmosNorthSupportTest.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GmosSouthSupportTest.java
Updates the GMOS TCC configuration names to be uniform (also appending OI and P1 as appropriate).
> REL-3899: update GMOS TCC config

- bundle/edu.gemini.util.skycalc/src/main/scala/edu/gemini/util/skycalc/calc/TargetCalculator.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Going well beyond just touching the third rail, this PR would update `BagsManager` to:
* make its update to the target environment and position angle consistent by holding a write lock
* only performing the update if the observation is in the expected state as it was when the AGS calculation was kicked off
This is to address the complaint about the position angle in the OT reverting to previous values when typing quickly.  I could not reproduce this issue but these changes _may_ help and _seem_ like the right thing to do regardless. 
There are also a handful of inconsequential updates made while browsing the code as well.  I'll mark the important bits.
> REL-3863: controlled pos angle update

- build.sbt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/VISITOR_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateFactoryImpl.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/Visitor.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/VisitorBase.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/VisitorInst.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/VisitorBlueprintSpec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/rich/pot/sp/RichNode.scala
Makes a couple of changes to the visitor blueprint / template code:
1. Adds the ability to assign a position angle based on visitor instrument name
2. Adds the ability to include notes based on visitor instrument name
Updates the visitor template with a couple of IGRINS notes.
Because there are now a handful of visitor-instrument specific specializations, I collected them all in a new `VisitorInst` type.
> REL-3900: IGRINS template updates

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/dataflow/GsaSequenceEditor.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsclass/ObsClass.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/dataflow/ProprietaryTest.scala
Program calibrations should henceforth have no proprietary period.  To make this more clear, I replaced `shouldChargeProgram` (which included program calibrations naturally) with `respectsProprietaryPeriod`.
> REL-3926: change prog cal proprietary period

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosSouthType.java
Adds new GMOS-S filters, making them available in the OT and QPT.
> REL-3927: new GMOS-S filters

- bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/gems/GemsCatalogChoice.java
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Strategy.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/package.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
Adds an additional catalog option for GAIA at Gemini.  I don't yet have the correct query URL for external users, but it can be tested by internal users.  A followup-up PR will be needed to correct the address.  It does show up in all the right places in the OT though.
> REL-3924: Add GAIA @ Gemini

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
Updates the non-GAIA Gemini catalog URL to a test server version.  It turns out that the addition of GAIA brings with it an updated catalog server in general which impacts all catalogs.  In this version, catalogs (and AGS) will require the VPN or be inside the firewall.  Before the release, another PR will need to be made going back to the public server address.
> Catalog URL update for testing

- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
Rollover is now called "persistent" in official documentation so 'r' doesn't correspond.  The request then was to remove 'r' from the rollover semester in reports and leave it at, for example, `[21B]` so that it survives the next name change.
> REL-3913: remove the 'r' from rollover semester

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSParams.java
Adds a couple of new decker options for GNIRS.  By default, decker isn't added to the sequence but is available if the user wants to override the default value.
> REL-3809: add IFU deckers

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/VersionToken.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
We're leaving GAIA @ Gemini and the new catalog server for December.  To facilitate the upgrade at a later date this PR:
* Accepts either VO table version 1.2 or 1.3
* Removes GAIA @ Gemini from the manual catalog search list only
> REL-3924: Prepare for 2021B

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nifs/InstNIFS.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/SPInstObsComp.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/flamingos2/PlannedTimeTest.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gpi/PlannedTimeTest.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/nifs/PlannedTimeTest.java
Changes a constant to a method call to solve an initialization issue.  In particular, a `static` block was not being initialized before referenced in `SPInstObsComp`.
> REL-3955: initialization issue in DHS_WRITE_TIME

- PUBLISH.txt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Observation.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Target.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
ITAC users need a way to override the ephemeris for nonsidereal targets, because sometimes the reference point at mid-semester is in an RA bucket that's too full. This adds a `referenceCoordinates` method to the Phase 1 immutable `NonSiderealTarget`, which for various reasons is where it needs to go. I'm not proud of any of this.
> reference coordinates

- build.sbt
I'm going to publish the 2.13 versions of the p1 model and related modules for ITAC, so I need to bump the versions. @cquiroz is this sensible?
> bump versions

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phase1/GsaPhase1Data.java
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TimeAccountingSummaryTable.java
It's unclear why, but the 2021B programs began to include time accounting summary report rows for all partners instead of only those which allocated time.  This update:
1. Limits the report to only partners which allocated time
2. Replaces keywords in `GsaPhase1Data`.  We don't use this information any longer, but including it (for now) allows a patch release to be created from `develop` without serialization issues.
> REL-3985: fix time accounting summary report

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsExecEventHandler.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsExecLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/Session.java
REL-3986 involves dropped start/end visit events.  The code for handling events was refactored for sending FIRE messages and so no longer corresponds to what is currently in production.  Accordingly, it's difficult to tell what might be wrong with the production version.  This PR simply adds a bit of logging so that we might gather additional information in the interim between the patch release and the December update.
> REL-3986: adding logging

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visit/VisitViewAdvisor.java
Observation IDs have gotten longer since the QPT was first released.  In particular all program ids have indices of at least 3 digits now.  This made it so the typical observation id is truncated in the Scheduled Visits table.
This PR makes the minimum size observation id slightly bigger to accommodate the new program id standard and makes the column resizable as requested.
> REL-3940: make QPT scheduled visit Observation column bigger

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/api/ConfigMatcher.java
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/util/SequenceRule.java
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/Flamingos2RuleSpec.scala
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSpec.scala
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/RuleSpec.scala
Updates a GMOS N&S P2 Checker rule to work with all obs classes, not just `SCIENCE`.
> REL-3976: N&S warnings for all obs classes

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpBlueprintFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/Visitor.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/VisitorBase.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/VisitorBlueprintSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/visitor/VisitorInstrument.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/visitor/blueprint/SpVisitorBlueprint.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/visitor/VisitorConfig.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/visitor/PlannedTimeTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/visitor/blueprint/SpVisitorBlueprintTest.scala
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/ComboPropertyCtrl.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/visitor/VisitorEditor.java
The PR fixes an issue with visitor instrument configurations.  Heretofore we relied upon the `name` parameter of the visitor instrument in order to lookup the corresponding configuration.  Because that's silly and error-prone, and because we do _have_ the proper visitor instrument identification from the outset at Phase 1, this PR changes `VisitorInstrument` to track the corresponding configuration directly.
There is a matching change to the visitor instrument editor in the OT.  Staff users can select the visitor instrument configuration to apply (for setup and readout time).  PIs can see which one was selected.
In the screen shot above the "Name" is "Zorro Wide Field" etc. etc.  We could pick out "Zorro" and cross our fingers or we could actually store the `VisitorConfig.Zorro` instead, …
> REL-3945: Stop relying on visitor instrument name

- bundle/edu.gemini.itc.web/src/main/resources/index.html
Not sure how we lost it, but I found an old copy of the file from 2014.
> REL-4018: Reinstate missing ITC sky background data file

- bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/session/FireEnvironment.scala
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/session/FireTest.scala
FIRE messages are posted asynchronously after the event that triggered them has been processed. The test case waits up to one second for the event to show up before triggering more events, but when other test cases are running in parallel and the machine is busy that is sometimes not enough.  This PR increases the wait time for an expected FIRE message to 10 seconds.
The PR only changes test code.
> Make the fire test more reliable

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/template/RegenerationClient.java
This fixes an issue where the `pid` parameter to the `TemplateServlet` was not being seen when passed in the multipart body, which caused the reset request to fail. There's probably a way to do it this way but I couldn't figure it out, so I moved the parameter into the URL.
Monkey-tested locally with PIT/OT/SPDB.
> REL-3987 GMOS skeleton updates (2)

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gmos/GmosNImaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gmos/GmosSImaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GmosNorthBlueprintSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GmosSouthBlueprintSpec.scala
The blueprint text updates didn't mention changing the folder type for imaging, so I left it as `TYPE_SHEDULING` and in fact wrote some code to abstract over this difference. But I had interpreted the requiremeents incorrectly and all GMOS templates should in fact expand to `TYPE_FOLDER` instead. So this changes the folder type for imaging templates but leaves the abstraction there, in case they change their mind or we need to use the pattern for other instruments in the future.
> REL-3987 GMOS skeleton updates (3)

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/AsterismType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/ResolutionMode.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetSelection.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismConverters.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismTypeConverters.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostParamSetCodecs.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/AsterismConvertersSpec.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Almosts.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Arbitraries.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/AsterismParamSetCodecSpec.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/telescopePosTableModel/TelescopePosTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/telescopePosTableModel/Utils.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
We incorrectly had labeled HRIFU as HRIFU1 and invented an HRIFU2 that doesn't exist.  The only high resolution option, as I understand it, is HRIFU + Sky.  This PR removes the HRIFU1 Target mode and changes HRIFU1 Target + HRIFU2 Sky to just "HRIFU Target, SRIFU2 Sky".  That is, the sky position is at SRIFU2 though it is unused.  Instead the dedicated HR sky fibers just above it are used as shown in the TPE.
In the screenshot below, I added a "User" target where the sky coordinates are.  Ordinarily nothing would show here, but slightly north of it are the HR sky fibers.
The requirements are still not clear though so I expect at least one more round of this.
> REL-3997: No such thing as GHOST HRIFU2 or HR w/o sky

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/OverheadTablePrinter.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/InstNICI.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/PlannedTime.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/ObserveTimeLineNode.java
There should be a readout cost per exposure, not one for the entire step.  So 4x100 Red + 1x400 Blue actually has a readout cost of 4x60 (not just 60) and exposure + readout is 400 + 240 = 640.
Updates the planned time category so that `detail` is no longer nullable but rather an `Option`.  Adds the exposure count and label ("blue" or "red") that dominates the readout overhead in the `detail` message.
> REL-4005-B: Correct GHOST Readout Cost

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/VISITOR_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/visitor/Visitor.scala
Two separate fixes in one PR.
1. The blueprint XML had improperly identified the science observation as a partner cal, which meant that upon instantiation it didn't pick up the phase 1 target.
2. I didn't know whether the calibration observation should take the PI-supplied name and made the wrong assumption.
> REL-3965: visitor name + science target fix

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExpCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCamera.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCameras.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/syntax/JavaDuration.scala
Fixes a bug with GHOST planned time calculation.  I was treating the exposure and readout times independently so a case such as 
```
Red.: 1 x 500s
Blue: 3 x 100s
```
would pick up 500s exposure from the red camera and 180s readout (3 x 60s) from the blue for a total of 680s (500 + 180).  Instead the red camera should "dominate" the calculation because 1 x (500 + 60) > 3 x (100 + 60) and we should have a total time of 560s instead of 680s.
> REL-4005: exposure time again

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/GhostSeqRepeatFlatObsCB.java
GHOST has its own manual GCAL sequence node to accommodate the two independent cameras.  Unfortunately the GHOST copy was adding `String` sequence values to the sequence instead of actual objects.  To make this part of the sequence match non-GHOST sequences, this PR switches to objects.
> REL-3882: match GHOST and non-GHOST calibration sequences

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
#1940, but for the `develop` branch.
> REL-3924: switch to production URLs

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
Hartmann settings remain for any existing observations, but the option disappears in the OT.
> REL-4050: mark hartmann lyot wheel options obsolete

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/visitor/VisitorEditor.java
Currently only staff members can change the selected visitor instrument configuration.  This PR removes that restriction so that PIs can do so as well.
> REL-4080: allow PIs to change visitor instrument

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala
> REL-3919: Use GAIA as the AGS catalog

- bundle/edu.gemini.phase2.skeleton.servlet/skeleton.sh
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/auxfile/SkeletonAuxfileWriter.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/servlet/SkeletonServlet.scala
Updates the skeleton creation servlet (and the `skeleton` bash script that calls it) to allow multiple attachment arguments.  The existing single `attachment` parameter is still supported, but alternatively any number of `attachment`# parameters (`attachment1`, `attachment2`, ...) can be sent instead.  If old-style `attachment` is used, any indexed attachment parameters are ignored.
> REL-4059: Support multiple attachment parameters

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/util/DBCopyService.java
When copying an On Hold ToO observation to a different program we're supposed to reset the status to Phase 2.  This was working for individual observations but not for observations within a group.  The issue was the calculation of whether the group is being copied into the same or a different program.  We were making a group copy for the target program and then comparing that new group's program key to the target program key.  Instead we needed to compare the existing group's program key to the target program's key.
> REL-1632: copy on-hold obs bug

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ImprovedSkyCalc.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ImprovedSkyCalcMethods.java
This makes several improvements to the sky brightness calculation used by the QPT:
http://jira.gemini.edu:8080/browse/REL-3978
> REL-3978: Improve QPT sky brightness calculation

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
This modifies the GNIRS acquisition templates to use different exposure times for different wavelength regimes.
> REL-4076: Update GNIRS acquisition template exposure time

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/ISPNode.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemAbstractBase.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemObsExecLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsExecLog.java
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/MergePlan.scala
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsServer.scala
- bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/progstate/LeafNodeFetchFunctor.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/ProgramUpdater.scala
More logging to illuminate, hopefully, what is happening in REL-4013.  The issue appears to be that execution events like start and end visit, which are kept in the `ObsExecLog`, are getting overwritten somehow in the sync/merge process.
> REL-4013: Missing Start/EndVisit logging

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTable.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
The 2.14 release of GAIA brought some surprises which broke ags in production for GEMS.
The main change is that when requesting the field "designation" it brings additionally an item `ID="DESIGNATION`
The usage of the ID field varies across votable implementation thus it is not just as simple as to lower case it.
Instead I added a `postProcessField` item to `CatalogAdapter` such that it is fixed only for GAIA
> FIX Gaia id field parsing

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/telescopePosTableModel/BaseCoordinatesRow.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/telescopePosTableModel/TelescopePosTableModel.java
This changes the base name from `Sky` to `Base` for Ghost target environments in dual-target mode.
> [REL-3999] change base name for dual target

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/SPAbstractFactory.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/nsp/SPTreeEditUtil.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewerActions.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/action/AddObsCompAction.java
Fixes a bug in which a new target added to an existing GHOST observation is created without a GHOST asterism, leaving the observation broken.
There is still a problem in that pasting a non-GHOST target component onto a GHOST observation (with or without an existing target component) creates this situation.  This was going to be difficult to fix and at least now you can correct this situation by deleting the pasted target component and adding a new one.
> REL-4003: Add target to GHOST observation

- bundle/jsky.app.ot.testlauncher/build.sbt
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/tpe/CatalogImageDisplay.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
This is a bit tricky as if we have started the OT before with GHOST this will be disabled and the override won't work
It is probably not worth trying to reset the value on `jsky.properties` or what do you think @swalker2m ?
> REL-3995 Enable GMOS Fov by default

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsHash.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/api/AgsHashSpec.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeAsterismFeature.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeCatalogFeature.scala
The `AgsHash` did not take into consideration explicit GHOST base positions that are unlinked from targets.  This prevented AGS from knowing that an update was needed when the base position changes.
Unrelatedly, I tweaking the drawing of the bullseye marking the base position in these cases so that appears centered.
> REL-4113: AGS / GHOST / Explicit base bug

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/ZeroMagnitudeStar.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeBand.scala
This adds the three Gaia bands (G_BP, G, G_RP) to the OT and ITC.
Note that the tests are currently failing, so this will need a bit of help.
> REL-3977 - Add Gaia bands to the ITC & OT

- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/rules/ghost/GhostRule.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostIfuPatrolField.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/telescopePosTableModel/TelescopePosTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeAsterismFeature.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
Places the HR Sky fibers on the exact coordinates entered by the user, adjusting the position of the SRIFU2 accordingly 3.28 arcseconds south.
> REL-4024: adjust HR Sky location

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
From Andy:
This is working well, however, we are missing some stars that could be useful.  Could the query be relaxed to:
1. Remove the parallax constraint
2. Remove the bright magnitude limit (change phot_g_mean_mag+BETWEEN+9+AND+19 to phot_g_mean_mag<19)
3. Increase the proper motion constraint from <100 to <1000 mas/yr
> REL-3919: relax GAIA constraints

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/auxfile/SkeletonAuxfileWriter.scala
It appears we select the wrong PDF format when the skeleton is created.
> REL-4122: switch the PDF format

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/ZeroMagnitudeStar.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeBand.scala
This UNDOES the changes in REL-3977:
https://github.com/gemini-hlsw/ocs/pull/2002
I'm not very happy with the ITC results when the input SED is normalized by one of the Gaia filters.  I suspect that this is due to the asymmetry of these filters, and to resolve the issue we may need to convolve the input SED with the normalizing filter profile.
> feature/REL-3977: REMOVE Gaia bands from the ITC & OT

- bundle/edu.gemini.wdba.xmlrpc.server/README.md
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/RotatorConfigTest.java
Because `fixed` is not the same as `Fixed`, we were adding
```
<param name="posAngle" value="fixed"/>
```
instead of 
```
<param name="rotator" value="fixed"/>
```
Hilarity ensued.
> REL-4020: set a 'rotator' param instead of 'posAngle' for MaroonX

- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsFailure.scala
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsServer.scala
- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/package.scala
This is a slightly modified version of (#2025) for the release branch.  It was changed to remove insignificant but possibly serialization-incompatible changes.
> REL-4013: hold the lock during sync updates

- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/servlets/JsonServlet.scala
To enable better caching of itc results we need to know if the data or algorithms from the ocs have changed.
This is added only at the edge on the Json servlets for itc rather than in the ITC itself to avoid breaking the TRPC protocol used by the OT
> Add optional version token for the itc json servlets

- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ImprovedSkyCalcMethods.java
- bundle/edu.gemini.util.skycalc/src/main/java/edu/gemini/skycalc/ImprovedSkyCalcMethods.java
This has been commented out forever but it's actually a case that happens and it was messing up the RA bucket calculation in ITAC. We'll see if it breaks any testcases.
Ok well a HORIZONS testcase is failing because a sample query we're using just started returning more answers. Not important, just added those to the testcase.
> uncomment negative lst handler

- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GhostSupport.java
My understanding is that we return this in microns, It was specified as 655 nanometers
> Return ghost observing wavelength

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPSkyObject.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Allows both targets and coordinates in the OT target environment table to be copied and pasted interchangeably.
> REL-4205: copy/paste targets and coordinates

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/nsp/SPTreeEditUtil.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/action/AddObsCompAction.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/nsp/AsterismEditUtil.scala
We developed a type tree / cardinality validity checker for science programs when we were working on program synchronization.  It works reasonably well but now we're confronted with an issue it cannot handle.  In particular, asterisms are stored in the target component but nevertheless tied to particular instruments.  The GHOST asterisms only apply to GHOST observations, and the non-GHOST single target asterism cannot be used with GHOST.  The validity checker doesn't prevent incpompatibilies because it doesn't drill into the component content but rather bases its decisions on component type alone.
This PR introduces an OT hack to prevent the worst issues that can arise.  After an observation component is pasted or added, an asterism/instrument compatibility check is performed and the …
> REL-4002: copy/paste incompatible asterism + instrument

- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiHorizonsConstants.java
- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiQueryExecutor.java
- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
Uses core `Site` to extract site coordinates instead of a separate constant.
> REL-4210: use Site coords in horizons queries

- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiHorizonsConstants.java
- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiReplyBuilder.java
- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
At some point Horizons started sending many more columns than we expected, which resulted in incorrect values for RA/Dec tracking and apparent magnitude. This PR adds an explicit column selection to the HTTP request, makes a change to the parser since we can't get back exactly what we were getting before, and adds a sanity test.
> REL-4211: fix ephemeris parsing

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
- bundle/edu.gemini.p2checker/src/test/java/edu/gemini/p2checker/rules/AbstractRuleTest.java
- bundle/edu.gemini.p2checker/src/test/java/edu/gemini/p2checker/rules/GmosRuleTest.java
Adds a new P2 Checker rule for GMOS calibrations with non-Any/Any/Any/Any conditions.
> REL-4028: calibration + conditions rule

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/progadmin/TimeAcctEditor.java
Shows time accounting information with 2 decimal places of precision.  (The data itself is stored in a `Duration`.)
> REL-4161: format 2 decimal places in time accounting editor

- build.sbt
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GhostStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Strategy.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/ags/AgsStrategyKey.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/tpe/TpePWFSFeature.java
When using GHOST in single-target mode with an unlinked base position, we want to make the IFU position work as though it were the base position for the purpose of AGS -- that is, as if the target and base were in fact linked.  (All other GHOST asterisms continue to work with the base position in a normal way.)
To accomplish this, I added a new GHOST strategy that delegates to the normal single probe strategy with an accordingly modified observation context.  It also hacks the PWFS TPE feature to display the probe ranges as if the target were an offset position.
> REL-4193: A Very Special GHOST PWFS AGS Strategy

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsHash.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/api/AgsHashSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/acqcam/InstAcqCam.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/michelle/InstMichelle.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/InstNICI.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nifs/InstNIFS.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/InstNIRI.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phoenix/InstPhoenix.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/texes/InstTexes.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/trecs/InstTReCS.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/visitor/VisitorInstrument.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/SPInstObsComp.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/PwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/phoenix/PhoenixSpec.scala
GHOST PWFS1 inner search range limit for AGS is now asterism-dependent.  Single target mode uses a 4.7' limit while all others use 5.75'.  This required adding a parameter to the PWFS range limit method in order to obtain the chosen asterism.
> REL-4217: asterism-dependent PWFS1 limit

- app/spdb/build.sbt
- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/rules/ghost/GhostRule.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostIfuPatrolField.scala
According ot the latest requirements we need to apply different offsets to GHOST targets only for purposes of p2 checks:
SRIFU1: p = -1mm = -1.64 arcsec, q = +1mm = 1.64 arcsec
SRIFU2: p = 0 arcsec, q = +1mm = 1.64 arcsec
HRIFU: p = 0 arcsec, q = -1mm = -1.64 arcsec
HRSKY: p = 0 arcsec, q = -1mm = -1.64 arcsec
> Change the offsets applied to GHOST targets for p2 calculations

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSpec.scala
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/RuleSpec.scala
Switches the GMOS calibration / conditions rule to work at the observation level instead of step-by-step.
> REL-4228: fix p2 check

- .gitignore
- bundle/edu.gemini.oodb.too.window/src/main/java/edu/gemini/too/email/TooEmail.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/mail/PrepareMessageAction.java
Adding recipients in separate calls produces a `Cc` header per call apparently, which Google is now rejecting:
```
Bounced
550-5.7.1 [209.85.220.97] This message is not RFC 5322 compliant, the issue is: 550-5.7.1 duplicate CC headers. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. Please review 550 5.7.1 RFC 5322 specifications for more information. s144-20020a1f2c96000000b003be18067bcasor4079229vks.5 - gsmtp
```
This is an attempt to fix the problem but adding all recipients in a single call.
> Fix "duplicate Cc" bounce

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/ghost/GhostReadNoiseGain.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/type/SpTypeUtil.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/RadioPropertyCtrl.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
Removes the fast/high option in the OT.  The task did not state what to do with existing programs which have Fast/High already selected, but it seemed reasonable not to change them.
The option is now hidden in the OT unless it is already selected in which case it is visible but clearly marked as undesirable:
Once a non-obsolete choice is made (and the user revisits the editor), the option to select the obsolete choice is gone.
> REL-4252: remove fast high

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
Hides the "Enable guide fibers" options in the OT and removes them from the sequence configuration.  I'm not committing to removing them altogether yet since it changes the asterism definition drastically (`GhostTarget` would go away altogether) and it seems like it could easily come back.
> REL-4203: Hide guide fiber options

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/SPInstObsComp.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCamera.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/PlannedTimeTest.scala
Ditches the formula for calculating readout time in favor of a simple lookup.  Changes the write time.
> REL-4295: Ghost readout + write times

- build.sbt
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Coordinates.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Offset.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/CoordinatesSpec.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/OffsetSpec.scala
When we instantiate GHOST templates we add a fake target (for Dual Target mode) or fake sky positions (for the + sky modes).  These are created such that they are separated by 2 arcmins from the known target position.  Unfortunately this was being done as a simple offset in RA when in reality it should be angular separation.
> Fix offset calculation

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemObsExecLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
This PR would change the log level to `FINE` for some rather verbose log messages that were added specifically to track down a problem with synchronization.  That problem has been solved and the log messages are distracting from actual issues that might appear so it seems appropriate to tone them down a bit before the 2023B release.
> Logging Cleanup

- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/Dataman.scala
- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsRefreshRunnable.scala
- bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/ObsRefreshRunnableSpec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/dataset/SummitState.scala
This is a hack around for a problem in the FITS storage service wherein the dataset status as reported on the summit vs. the archive diverges.  This is a situation we currently expect to be remedied quickly as it should synchronize the two.  Accordingly we frequently (every 2 minutes) poll asking for updates on these datasets so that the status can be shown to the user in a timely manner.  Unfortunately though the synchronization doesn't always happen, or in some cases we don't _observe_ that it has happened because the modification timestamp has gone backward in time and we've ignored the updated status.  Over time the set of datasets in this category has grown to be considerably large (over 3,000 at GN).
The hack is to simply stop expecting a quick update (and stop asking the server for …
> Stop frequent checks for old diverged datasets

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/Igrins2Printer.java
- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2Arm.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2Recipe.java
- bundle/edu.gemini.itc/src/main/resources/igrins2/igrins2.dat
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/igrins2/Igrins2.scala
This pr makes a few minor updates to the IGRINS-2 ITC: detector dark current, read noise, well-depth, and exposure time limits.
This includes a modified relationship between the number of Fowler samples and read noise in Igrins2.scala, where there are 2 separate calculations of the readnoise which could probably be merged.
> REL 4277: IGRINS-2 ITC (v2)

- app/pit/dist/MacOS/entitlements.plist
- project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
This PR contains updates to the build such that the signed mac installer can also be notarized:.
This requires three chaanges:
* Sign each binary in the jdk separately
* Mark the binaries as "hardened"
* Add a set of entitlements to let the JDK run properly
The notarization process is not automated just yet, it has to be done manually
More details at
https://github.com/gemini-hlsw/ocs/wiki/Signing-Applications-for-OSX#osx-notarization
> Update signing process for mac

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/PublishAction.java
Since publishing to GN is currently unavailable, this update changes the publishing order at GS to `PACHON` and then `INTERNAL` (GN).  It will still time out when attempting to publish at GN, but the site-local publish will in theory have happened by that point.
One caveat: this is untested since it involves network connections that aren't available to me.
> REL-4366: publish to pachon first for GS

- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Inst.java
This adds IGRINS-2 to the `Inst` enumeration in QPT as an available instrument at GN. It shows up in the tree ok, and IGRINS observations appear correctly in the candidate view.
> [REL-4364] Add IGRINS-2 to inst enum

- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/rules/ghost/GhostRule.scala
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GhostSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPCoordinates.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
Adds `pmCorrectedCoordinates` to `GhostTarget` and `pmCorrectedBasePosition` to `Asterism`.  These are unused except in the `GhostRule` as requested.  This is unfortunately confusing for multiple reasons:
* Asking for a target's coordinates takes a time parameter (`when`) which implies that it will be PM corrected.  It is not.  Only sidereal targets use the `when` parameter.
* Fixing the problem above might open Pandora's box, so now there are `pmCorrected` options that also take a time `when` but do in fact use it for sidereal targets.
* Applying proper motion to `GhostRule` coordinate checks will mean that it no longer matches what we plot in the position editor, generating angst.
> REL-4345: Apply Proper Motion Corrections in `GhostRule` Coordinate Checks

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EphemerisUpdater.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameResolver.scala
Andy reports problems with non-sidereal name resolution hanging occasionally.  He's even had to kill the OT to resolve it.  It works for me, but makes me suspicious that we're mixing in UI updates from non-event loop threads.  We seem to be pretty meticulous about keeping UI updates in the event loop, but I did find one spot where we weren't doing it.  Perhaps this will fix the issue?  Is there a better way?
> REL-3922: non-sidereal target lookup UI event loop issues

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/SeqRepeatFlatObs.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/SeqRepeatSmartGcalObsCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/seqcomp/DefaultArcObsClass.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/rich/pot/sp/RichNode.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/BaselineReorderTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/CalImpl.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/GcalExecTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/Post2024BArcTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/Pre2024BArcTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/SmartGcalArcObsClassBase.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/seqcomp/SmartGcalExecutedStepTest.scala
An embarrassing hack to change the default `OcsClass` for arcs in 2024B and beyond.  It's important to maintain the old default for old programs since the value impacts time accounting, which isn't recorded anywhere but instead recalculated on demand.  So, this is a _wee bit_ sketchy.  To avoid checking when you're asking, we instead check the program id and strip the semester from it.  If the semester is defined and pre-2024B we keep the old default.  Otherwise we use the new default.
> REL-4411: 24B default ObsClass for arcs

- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/Dataman.scala
- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/PollService.scala
- bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/PollServiceSpec.scala
Reduces the insistency of the daily full database / archive sync, reducing the thread count from 10 to 2 and backing the thread priority down by one.  This was in response to a request from Paul to avoid hitting the FITS servers with too many simultaneous requests.
Because all of the polling was done by shared worker pools, I had to segregate the jobs and put the daily full sync in its own pool.  Because the work is done by a priority queue, with the program sync being the lowest, I then needed to lower the thread priority of the separate daily program sync.
> REL-4390: back off daily sync

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
Adds a "MOS PreImaging" flag to the OT "browser" Flamingos 2 options.
> REL-4297: add F2 preimaging flag

- app/spdb/build.sbt
Changing the IP of the Scheduler ODB to what it should be.
> Fixing the IP address of gnodbscheduler.

- build.sbt
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/SeqexecConfigTest.scala
A side effect of the changes for GHOST non-sidereals was to remove the coordinates for the sidereal targets if they have a null proper motion.
This breaks all GHOST modes in the seqexec unless pm is set
This was tested against a local instance of the seqeexc
> Include target coordinates for sidereals

- app/spdb/build.sbt
`cpofits-lv1.cl.gemini.edu` is apparently the old summit storage host.  This PR switches `gsodbtest` to use the same alias used on `gsodb`.
> REL-4390: update summit FITS storage service host

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/image/BackgroundImageLoader.scala
There was a FR (https://noirlab.atlassian.net/browse/GSFR-43564) which complains of not being able to see the FITS background image in an observation.  The problem turned out to be that the observation was missing observing conditions, which is really irrelevant for the purpose of showing a FITS image.
> REL-4481: allow viewing targets in observations without obs conditions

- app/spdb/build.sbt
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Inst.java
This change exposes obsolete configuration options (this can be undone later if desired) so that both of the R400 gratings at GN will be visible in QPT. This will allow for mid-semester switchover without requiring a new QPT release.
> REL-4580 (expose obsolete configuration options)

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GmosPrinter.java
- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
This adds separate options in the GMOS ITC web form for either Long Slit or MOS so that the correct acquisition overhead is given.  The S/N calculations should be unchanged.
> REL-4448 - Include correct acquisition overheads (Slit or MOS) in GMOS ITC

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/OverheadTablePrinter.java
- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/igrins2/Igrins2.scala
This is a trivial change to avoid adding re-centering overheads in the IGRINS-2 ITC.  Note that even though it is no longer used, I reset the IGRINS-2 re-acquisition time back to 5 minutes since that had been accidentally set to the acquisition time of 7 minutes.
> REL-4602: Do not add recentering overheads in the IGRINS-2 ITC

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/Igrins2Printer.java
- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2Recipe.java
This PR fixes a bug  where the number of Fowler samples and read noise was derived from the exposure time set in the web form even though the user had asked for the integration time to achieve a S/N.  This also optimizes the calculations so that only 2 iterations (per arm) are required.
> REL-4637 Fix IGRINS-2 ITC reporting of Fowler Samples when requesting time to achive a S/N

- build.sbt
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2Recipe.java
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/Igrins2Spec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/igrins2/Igrins2.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/igrins2/FowlerCalcTest.scala
A few minor IGRINS-2 updates:
1. Update the minimum exposure time from 1.63 to 3.08.
2. Update the Fowler sampling equation to: N_Fowler = int((T_exp +1.45479 - 0.168)/1.45479)
3. Update overheads for Fowler Sampling [1, 2, 4, 8, 16] to {8.5, 11.3, 16.0, 24.0, 39.5}
> REL-4667: IGRINS-2 updates

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSpec.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/EdCompInstGMOS.java
you can still copy paste an old program using gmos e2v
A phase 2 check will indicate that this is not allowed, and you should change it to Hammamatsu. 
The UI now only lets you ever change from E2V to Hammamatsu
> REL-4509 Add P2 check for GMOS-N observations with E2V

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
When calculating the number of exposures required to reach a desired S/N, limit the number of exposures to 1000 to prevent bad things from happening.
> REL-4706: limit the calculated number of exposures to 1000

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
Making the F2 Y filter obsolete. REL-2501 requested this `Y` filter and `F1056`  and `F1063` to be hidden - but the last two were taken care in REL-3561
> REL-2501 "obsoleting" Y filter that was never purchased.

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java
This includes some minor updates:
- update the maximum allowed counts from 50% to 60% of the linearity limit
- increase the maximum exposure time from 300s to 600s
- limit the maximum number of exposures to 1000
> REL-4638 v2: F2 ITC calculation of exposure time & number of exposures to achieve S/N
