- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/package.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/AgsTest.scala
I should have rebased prior to merging the equinox fix, sorry.
> OCSADV-154 fix compile errors

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTarget.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/HmsDegTarget.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/INonSiderealTarget.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ITarget.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/NonSiderealTarget.java
This is a small refactor that moves the `ImList<Magnitude>` member from `spTarget` to `ITarget` (which has been made into a subclass of `CoordinateSystem` for this purpose).
The diff for `ITarget` is a little confusing because it's trying to interleave deletions with unrelated pasted code from `SPTarget`. Sorry.
> OCSADV-154 push mags into itarget

- bundle/edu.gemini.catalog/src/main/java/jsky/catalog/skycat/SkycatCatalog.java
- bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Small changes to remove non working name server catalogues
> REL-2918: Change default target name resolver to SIMBAD@ESO

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2015A.xml
Small update to p1-monitor configuration, should be integrated to develop too
> Updated configuration for CfP PW and DT for 2015A

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTarget.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/CoordinateTypes.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/HmsDegTarget.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TrackingEditor.java
This PR removes the tracking effective wavelength parameter of proper motion. It is never used. (I discussed this with Andy a while back.)
> OCSADV-154  remove tracking effective wavelength

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/core/FilterXMLFormatter.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/core/FilterXMLParser.scala
The code here needs an overhaul, it is easy to forget to keep the xml translations in sync when code is added. A type class based approach and some additional testing is on the todo list for later releases. For now, this solves the issue.
> REL-2179: Added missing to/from xml conversion for GSAO filters.

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/core/FilterXMLFormatter.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/core/FilterXMLParser.scala
Ooops, I did it again. Messed up the branch before merging it. These changes are identical to the previous ones. Sorry.
> REL-2177: Custom QV charts are lost when application is quit.

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTable.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTableModel.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/util/Exporter.scala
Some improvements in how values are formatted when tables are exported from QV.
> REL-2214: Fixes in how values in tables are exported (formatting).

- build.sbt
I find myself looking stuff up a lot in Dash and it's kind of clicky. So this lets you do it from the sbt prompt.
> Add command to open dash from sbt prompt

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
Graces is an option on 2015B, this PR makes it available to end users
> REL-2200: Expose Graces

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/URLConstants.scala
> REL-2029: Change PIT template button URL

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Updated a problem robot to forbid submissions when any partner's request is zero
Th relevant commit is cc574d4, the rest is code improvements and formatting
> REL-2032: Do not submit to partners with zero requested time

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Simple PR containing a new `ProblemRobot` for the PIT
> REL-1391: Increase proposal size limit and give helpful error when too large

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_au_no_submission.xml
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
Fix for AU templates not being displayed correctly if not yet submitted
> REL-813: Update AU proposal number with each semester

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/model/Model.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitStatus.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala
Improve parsing of the backend response to give a better error message to the user
> REL-2231: Display full PIT version in compatibility error message

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalIo.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_invalid_character.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
Quick PR, sometimes people edit their proposals by hand and break the XML, this PR takes care of filtering out non valid xml files
> REL-2030: Invalid character causes proposal to be rejected

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Site.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
> REL-2226: Changes to CFHT related labels

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xjb/Graces.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Graces.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_graces.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/GracesBlueprintSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
This PR contains renaming of Graces fiber modes and updates to test accordingly
> REL-1841: Changes to Graces fiber modes' names

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
This PR fulfills a request to mark certain partners as un-elegible for joint proposals.
No changes to the model are required, just a new Problem Robot
> REL-2248: Limited partners and joint proposals

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
This PR lets both classical and queue proposal to get requests from CFHT
> REL-2226: Add CFHT as a new exchange request type

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/SaveAction.scala
Quick PR to fix a small bug closing the PIT, It will ask to confirm twice if you say no the first time
> REL-2252: Double prompt when attempting to close the PIT

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/package.scala
Version changes for the PIT release
> REL-2030: Prepare PIT 2015B release

- bundle/edu.gemini.model.p1.submit/src/test/scala/edu/gemini/model/p1/submit/ResponseParserTest.scala
A broken test related to phase-1 went undetected, this PR fixes that
> Fixed broken tests when changing ServiceError signature

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SubmissionRequestEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
This PR contains two small requested updates for the PIT pertaining REL-2248 and REL-2032
> Minor pit release fixes

- app/p1-monitor/build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2015B.xml
> REL-2257: Release of p1-monitor for 2015B

- bundle/edu.gemini.ags/src/test/resources/ocsadv-245-lgs.xml
- bundle/edu.gemini.ags/src/test/resources/ocsadv245.xml
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsCatalogResultsSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsUtils4JavaSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsVoTableCatalogSpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/AgsTest.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTable.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/resources/fmag.xml
- bundle/edu.gemini.catalog/src/test/resources/sloan.xml
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPSiteQuality.java
Out of a reported error on handling NIRI + NGS and NIRI + LGS it was detected that the processing of catalog bands was incomplete
This PR improves handling but as a side effect, AGS internal processing requires modifications. Those will be carried on OCSADV-255
A test `SingleProbeStrategySpec` reproduces the original reported error but it hasn't been fixed yet
Gems is also broken and will be fixed on OCSADV-272
> OCSADV-245: Support Sloan's bands (Was AGS not working with NIRI+NGS nor NIRI+LGS)

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/altair/AltairRule.java
From JIRA: Requirement: Change the current Phase 2 check 
WARNING if Altair Guide Star Type == Natural Guide Star, "The Altair field lens is recommended for most observations." 
to 
WARNING if Altair Guide Star Type == Natural Guide Star AND Base coordinate != Altair AOWFS coordinate , "The Altair field lens is recommended for off-axis targets."
> REL-781: Update Altair w/ field lens warning.

- bundle/edu.gemini.pot/build.sbt
This missing packages break SPDB at runtime
> OCSADV-255: Missing package export to be used by AGS

- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/VignettingTest.scala
(Will be fixed soon but breaks tests now.)
> OCSADV-256: Ignoring incomplete test

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2OiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/flamingos2/F2OiwfsProbeArm.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/gmos/GmosOiwfsProbeArm.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/inst/OIWFSVignettingFeature.scala
We will now display the vignetting / quality calculation temporarily to facilitate debugging.
> OCSADV-256: Fixing bugs and adding temporary debug code as per Andy's request.

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
> OCSADV-296: Bug fix: only look at last part in data label for index

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GPI_BP.xml
Small PR updating the blueprint template for GPI
It was tested using the `skeleton` utility and an appropriate gpi proposal
> REL-2205: Error in some GPI templates - OT 2015A.1.1.1

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gpi/PlannedTimeTest.java
Small PR that updates the overheads calculation for GPI when there is iteration on the the Halfwave plate component
Added two unit test to check a few scenarios and their calculations
> REL-2208: GPI Halfwave plate configuration is 30s but should be 5s

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gpi/GpiRule.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gpi/GpiTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gpi/GpiEditor.java
Small PR containing a bug fix for GPI cal entrance shutter, the PR is mostly cleaning up a bit the code, removing warnings, etc, the actual fix is just one line
> REL-2229: GPI ENG OT tab entrance shutter flag also closes cal entrance

- bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/gems/GemsGuideStarSearchOptions.java
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchController.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchModel.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/gems/CatalogUtils4Java.scala
On this PR the option to do manual search using the PPMXL backend of the Gemini's catalog is enabled, additionally the table is updated to show only the relevant bands in each case
An extra is the switch to search on Gemini's new urls that will be open to the internet soon
> OCSADV-294: Support search on Gemini's ppmxl catalog

- bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/catalog/gui/TableDisplay.java
- bundle/jsky.coords/src/main/java/jsky/coords/gui/SexagesimalTableCellRenderer.java
This is a small PR fixing the naming of the GEMS Manual Search columns, also formatting of magnitudes is improved a bit
> OCSADV-294: Gems manual search box fixes

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
Quick PR to fix a bug on VoTableBackend
> Remove sealed keyword that shouldn't be there and breaks test cases

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala
X/Y Binning directions were mixed up.
> Bugfix: X is spectral and Y is spatial binning.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala
This PR fixes weird behavior in the magnitude editor caused by enabled status updating described by @swalker2m in [OCSADV-320](http://swgserv01.cl.gemini.edu:8080/browse/OCSADV-320).
> OCSADV-320 enablement issues w/ magnitude editor

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ConicNameEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealNameEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/package.scala
Mimics the behavior and look of the 2015A target editor as requested in OCSADV-327.
> OCSADV-327: add a magnifying glass button that kicks off a name search

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/Horizons.scala
Fix comparison between String and Long, shouldn't affect behavior just the use of caching
> Horizons caching

- bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/ConnectionUtil.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/PrintUtil.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/PrintableJTable.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/ProgressPanel.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/StatusLogger.java
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/StatusPanel.java
- project/OcsBundle.scala
UCAC4 use the `VoTable2Skycat` servlet proxy running on SPDB, Access is via https and this requires supporting the self-signed certificate and skip hostname validation like TRPC does
> OCSADV-311: Manual Search with UCAC4 not working on https

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/servlets/ImageServlet.java
Following Shane's suggestion I am replacing the home made LRU cache based on a ```ConcurrentHashMap``` with one based on ```LinkedHashMap```. Note that ```LinkedHashMap``` is not concurrent and has to be synchronized, the resulting speed penalty however seems to be small, at least for only a handful of parallel requests. And since the expected load on the web app is more on the order of requests per hour than requests per second I guess it doesn't really matter anyway.
> Simplification of caching in ImageServlet.

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/servlets/ImageServlet.java
> Bugix: Throw appropriate exception in case of a cache miss.

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
Update the VoTable parser to be smarter on ppmxl.
ppmxl may contain more than one measurement for R and B bands, the rule is to pick the first value over the second if possible
> OCSADV-317: PPMXL Catalog contains more than one Magnitude measurement

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Strategy.scala
Exactly what it says on the tin.
> OCSADV-333: include OIWFS in non-sidereal AGS strategy options

- bundle/jsky.app.ot/src/main/java/jsky/navigator/NavigatorCatalogMenu.java
Restore the removed catalog menu on the position editor
> OCSADV-340: Missing Catalog menu item

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
No functionality change, just small changes to the layout to incorporate some user feedback (Analysis Method).
> OCSADV-342: Layout changes on ITC panel.

- bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
Tiny PR to remove the non-working CADC catalog
> REL-2328: Remove OT catalog "Digitized Sky at CADC (2nd generation)"

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetObsComp.java
Target node title changes per request in OCSADV-349.
> OCSADV-349: change target node labels in the tree view

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/graces/Graces.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_1842_Test.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2232_Test.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala
Graces targets were not being partitioned, as reported by @andrewwstephens in #356.
> REL-1842 graces partitioner

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/NIFS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/NifsAo.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2232_Test.scala
The obs re-ordering was incomplete, leaving an incorrect reference in the LGS expansion. This PR fixes that bug and adds Andy's failing program as a testcase.
> REL-2232 fix obs renumbering issue

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/SiteQualityPanel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/TimingWindowDialog.java
Depending on their values some of the text input fields in the "Edit Timing Window" shrunk to a very small size which made it impossible to see the value that was entered. Also, the event handling was somehow weird and often the OK button had to be clicked twice.
Changing the event handling and adapting the layout seems to solve these issues, I also increased the size of the table so that there is more room for wide entries.
NEW:
PREVIOUS:
Use ?w=1 , I converted the tabs to spaces.
> REL-815: Fixes in layout and event handling.

- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala
This PR updates the wording of the new target precession note as requested by Andy.
> OCSADV-350: update wording of precession note

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/VcsPeerSelectionDialog.scala
The sync command will pop up a dialog for selecting the ODB to associate with a new program.  It tries to place this dialog near the UI element that triggered the sync.  When this is the command shortcut, an `IllegalComponentStateException` is thrown because it cannot get the screen location for a component that isn't visible.  This PR just updates the code to also try the `SPViewer` instance and, failing that, use the center of the screen.
> REL-2330: Fix IllegalComponentStateException

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Imaging.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/Flamingos2SupportTest.java
New filter `K-long` added for Flamingos2.
> REL-2307: Added new F2 filter.

- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Inst.java
This PR adds F2 filter options to the QPT (and groups FP Units and Filters for convenience).
> REL-2307: add F2 filters to QPT options

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
Taking advantage of @swalker2m latest changes in https://github.com/gemini-hlsw/ocs/pull/418 which added the magnitude system to the magnitudes made fixing this straight forward.
> OCSADV-358: Pass magnitude system down to ITC (Vega vs AB vs Jy).

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
IFU-2 is not yet supported, instead show options for IFU left/right blue/red.
> OCSADV-361: IFU left/right options instead of IFU-2 in web app

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
A small fix for the site comparison issue that @cquiroz founds.   Apologies, I'd meant to commit this before the merge of the last REL-2122 PR.
> REL-2122: fix site comparison

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
Some users don't have an observing peer defined, for those we fall back to GN or GS (in this order) as the peer to be used for ITC service calls.
This is a bit lame, but turns out it is reasonably difficult to check for a "fastest to reach" peer in a more or less reliable way. I think this deserves a better and more general solution but for the June release I am afraid this is as good as it gets.
(I just had a discussion with Andy and we decided to run some load tests against gnodbtest2 on Tuesday to get  a better feel for the CPU load that we're creating with the ITC service calls. Depending on how that works out we might also distribute the calls randomly between GN and GS.)
> OCSADV-348: Use observing peer or GN or GS for ITC calls

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
The rule did not take into account the detector manufacturer when looking up the limits and always returned the limits for EE2.
> REL-2239: Bug fix for GMOS rules

- project/src/main/scala/edu/gemini/osgi/tools/app/RPMDistHandler.scala
Fixed an issue where the ssh session execution of `rpmbuild` was not properly being waited for, which caused the sftp copy to fail or copy an older RPM.
Fixed sftp copy to only copy the precise version built.
Added a lot more cleanup code (using an ssh channel) to remove entire `rpmbuild` directory from remote machine.
> REL-2310: OT & QPT RPM building

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/AgsClient.scala
Bryan requested some changes to the auto-GS fail dialog.
> REL-2366: Changed message as per Bryan's request.

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/util/PITLauncher.scala
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/IShellAdvisor.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/impl/Workspace.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/osgi/Activator.java
This PR contains version and semester changes for PIT 2016A. 
There are a few tab and raw types fixes to old code as well,
Also I created a PITLauncher app similar to OCS's TestLauncher to start the PIT from inside IDEA
> REL-2372: Prepare PIT 2016A

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/URLConstants.scala
> REL-2271: Reword PIT Download templates menu item

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Flamingos2.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xjb/Flamingos2.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Flamingos2.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/Flamingos2Spec.scala
This PR includes the new flamingos2 filter in the phase1 model and decision tree
> REL-2308: Add Flamingos-2 K-long filter to the 16A PIT

- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/package.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/util/PITLauncher.scala
Small PR to update the urls for the Phase I backends that will be now hosted at Gemini
> REL-2272: Gemini must host all Phase I backend servers

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Investigator.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Small PR to forbid a common case where proposals are submitted with the default PI name 'Principal Investigator'
> REL-2287: Do not allow proposal submission without the full PI name

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitStatus.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala
Small changes to messages when submitting a new proposal
> REL-2290: Update PIT submission success status information

- bundle/edu.gemini.pit/src/main/java/edu/gemini/pit/ui/util/SharedIcons.java
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/target/TargetView.scala
The combobox used to select the target type has been replaced by Radio Buttons, icons remain as before.
See a screenshot:
> REL-2292: PIT target type radio buttons

- bundle/edu.gemini.pit/src/main/java/edu/gemini/pit/ui/util/GlassLabel.java
After the switch to Java 1.7 the transparency method used for the submit window stopped working. This PR fixes that as shown below
Before
After
> REL-2255: Submit view goes black

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/VisibilityRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/target/TargetView.scala
This PR forbids adding ToO targets unless the ToO Option has been selected. In case the user has a ToO target and changes the ToOption to None, submissions won't be allowed via the ProblemRobot
> REL-529: ToO targets must not be allowed in non-ToO proposals (PIT)

- bundle/jsky.app.ot.testlauncher/src/main/scala/jsky/app/ot/testlauncher/TestLauncher.scala
This is a very simple utility to autolaunch a program when starting the OT via `TestLauncher` with lots of help from @swalker2m . It saves a few clicks when doing UI work
I configure it on IDEA with:
> Launch a program from IDEA/TestLauncher

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
Tiny PR adding Australia as not allowed in joint proposals
> REL-2396: Australia a limited partner starting in 16A

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Phoenix.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/PhoenixBlueprint.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Phoenix.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_phoenix.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/PhoenixSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/PhoenixBlueprintSpec.scala
Science change this task, and now we don't want to support multiple filters for Phoenix
I don't have experience reverting a pull request, let's hope Github knows how to do it properly :smile:
> Revert "REL-2356: Add Phoenix to the 2016A PIT resource list"

- bundle/edu.gemini.model.p1/src/main/xjb/Phoenix.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/Phoenix.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/PhoenixSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phoenix/InstPhoenix.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phoenix/InstPhoenixCB.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phoenix/PhoenixParams.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/phoenix/EdCompInstPhoenix.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/phoenix/PhoenixForm.java
More updates to Phoenix filters. This change also required adding a filter to Phoenix's model on the pot bundle
Also cleaned up warnings and some generated code on the Phoenix model and UI on the OT
> REL-2356: Add Phoenix to the 2016A PIT resource list

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xjb/Niri.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/Niri.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_niri_removed_filters.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
It turns out I commented out the wrong NIRI filters, this PR fixes that
> REL-2390: Remove NIRI filters from 2016A PIT

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java
Small tweak to fix a build break.
> OCSADV-399: oops, build break

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Small leftover from the transition to the new target model in OCSADV-155
> REL-2431: GPI target errors when all requested magnitudes entered

- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/util/ReportUtils.java
- bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/gemini/obscat/ObsQueryFunctor.java
Updates for time-varying/missing coordinates (1of 6).
- `ReportUtils` hour angle distribution 
- `ObsQueryFunctor` region matching
> OCSADV-399-D

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gems/StrehlFeature.java
Prepare StrehlFeature for possibly-missing coordinates. (4/6)
This code is used by the TPE drawing code, which catches exceptions and shows them to the user. So I'm hoping the exception added to `targetListToStarList` is good enough.
> OCSADV-399-G

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
Extraction of GNIRS parameters for ITC calculations and some other changes to allow ITC calculations for GNIRS in the OT.
> OCSADV-371: Support for GNRS ITC

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
A trivial change to the display name of DSSI in the PIT instrument list.
> REL-2464: change DSSI label

- bundle/edu.gemini.itc.shared/src/main/java/edu/gemini/itc/shared/SourceDefinition.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/HtmlPrinter.java
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/EmissionLineSpectrum.java
- bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/util/Fixture.scala
- bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/util/Hash.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SourcePio.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SpectralDistribution.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/SpTargetPioSpec.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Wavelength.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SourceDetailsEditor.scala
> OCSADV-355B: Replace EmissionLine.Flux with Irradiance from squants.

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsGuideStars.scala
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ITarget.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/system/test/HmsDegTargetCase.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/system/test/NamedTargetCase.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TemplateSummaryTable.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TargetConfig.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateAsterismsTreeTableModel.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/CoordinateEditor.scala
Next up, this adds a time parameter to `getRa/DecString`.
> OCSADV-399-N

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
Small PR to show the distance of each target to the base coordinates. See the screenshot:
> OCSADV-408: Add a distance column to the Catalog Navigator

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
A filtering of invalid magnitudes was removed by mistake and that let some extra targets through breaking a few Gems AGS test
This PR fixes  this, tests in catalog and ags pass
> Broken Gems AGS test

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/UCAC3Regression.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ITarget.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/SpTargetPioSpec.scala
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2015B/TargetConversionTest.scala
- bundle/edu.gemini.spdb.rollover.servlet/src/main/scala/edu/gemini/rollover/servlet/RolloverObservation.scala
- bundle/edu.gemini.spdb.rollover.servlet/src/main/scala/edu/gemini/rollover/servlet/RolloverServlet.scala
This PR removes `getRaDegrees` and fixes a few remaining uses (mostly tests).
> OCSADV-399-O

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phoenix/PhoenixParams.java
Obsoleted a Phoenix filter and cleaned up code.
> REL-2408: Obsolete Phoenix filter

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/InstNIRI.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
Thanks to @fnussber for noticing a compilation error and a test missed
> Fix for merge compilation error

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
This is an update the the F2 template XML as per Ruben and Andy.
The tests listed in the JIRA issue seem to pass correctly with the new template in place.
> REL-2408: Updated F2 template XML

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/api/IConfigMatcher.java
- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gnirs/GnirsRule.java
New GNIRS P2 warning for when AcqCam is OUT and Decker is set to AcqCam.
Also some general small cleanup of existing code.
> REL-2167: Added P2 check for GNIRS as requested.

- bundle/edu.gemini.spModel.pio/build.sbt
Export for codec package seems to be missing from the spModel pio bundle.
> Bugfix: Added missing export.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GPI_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GPI_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gpi/Gpi.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2465_Test.scala
This updates the GPI blueprint (which is simpler now) and adds a test.
> REL-2465 update GPI blueprint

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Altair.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GnirsBlueprintImaging.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GnirsBlueprintSpectroscopy.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GnirsBlueprintSpec.scala
This adds the new XML file which has minor changes and did not require any logic changes. I added a sanity test just to ensure that template expansion works but didn't try to test the existing expansion logic (which is quite complex).
> REL-2498 Update GNIRS blueprint

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GMOS_S_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GmosSouthBlueprintSpec.scala
This updates the GMOS template, which did not require any logic changes. Added a sanity check just to ensure that template expansion works in all configurations.
> REL-2385 update GMOS template

- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/Flamingos2Support.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/Flamingos2SupportTest.java
Implementation of REL-1962, with updated unit tests.
> REL-1962: Modified instrument configuration names sent to TCC for FLAMINGOS-2 when using PWFS2.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/GuideProbeTargets.java
Fixed an issue with the way new primary targets were chosen when a BAGS target exists and a manual primary target was deleted.
> OCSADV-461: BAGS exception

- bundle/edu.gemini.pot/build.sbt
> REL-2415 fix manifest

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/ModelConverters.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealNameEditor.scala
Small PR that sets the Epoch when a Simbad query includes Proper Motion
> REL-2513: Update proper motion epoch with Simbad query

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealNameEditor.scala
Simple PR to reset PM, RV and Z if they don't come on a simbad query
> REL-2512: Overwrite old motion values on Simbad query

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/NumericPropertySheet.scala
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/NumberBoxWidget.java
The `NumberBoxWidget` is the base for many of the UI elements that allow to enter numbers in the OT, in particular also the `NumericPropertySheet`. So far this widget didn't allow to enter numbers in scientific notation, e.g. `1e-15`.
This PR extends the `NumberBoxWidget` to allow entry of "incomplete" exponential numbers, this is needed because the numbers are validated after every single key stroke. In addition to this, the `NumberFormatter`s and `DecimalFormatter`s used for the `NumericPropertySheet` are modified so that they automatically default to exponential notation for very small and very big numbers. Using those formatters has also the advantage that they deal with corner cases like empty strings and - how convenient - incomplete exponential numbers (e.g. `1e` or `1e-`) by just …
> OCSADV-355B: Allow input of numbers in exponential notation.

- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/service/ItcServiceImpl.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/SpectralDistribution.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SourceDetailsEditor.scala
Changes to a string, addition of a tooltip and a small refactoring.
> OCSADV-354B: Change string and add tooltip for undefined user SEDs.

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
Tiny PR which deals with settings some default values for the ITC analysis method depending on instrument and instrument configuration. Unfortunately we just found out that the values we set here seem not to be taken into account in the calculations as expected, but this is a bug that has been with us for a long time and needs to be addressed separately.
On the upside I also implemented a simple cache that allows to keep analysis methods for an observation until the OT is restarted which should be replaced by properly making those settings part of the model and persist them with the rest of the observation data.
> OCSADV-345: Provide default analysis methods. 

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
> REL-2498 update gnirs bp

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
> REL-2540: Disallow to iterate over custom list width in F2 sequences.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetObsComp.java
The target node title in the node tree was not being set correctly.
This was due to the fact that format of the title of the target node had changed from `Targets (...)` to one of `Comet:`, `Minor Planet:`, `Solar System:`, or `Target:`, and the check to determine if the title needed to be rebuilt was still based on the old title format and had not been updated.
This updates as required and solves the problem.
I also `final`ed what I could in this class.
> REL-2525: Target node title in node tree not set correctly.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/dataflow/GsaAspect.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/dataflow/ProprietaryTest.scala
A simple PR to set the default proprietary period for demo science programs.
> REL-2547: set demo science proprietary period

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/PHOENIX_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/PHOENIX_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/SpPhoenixTemplateSpec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/phoenix/blueprint/SpPhoenixBlueprint.scala
This updates the templates and corrects the naming of template groups.
> REL-2415-B Add Phoenix OT templates 

- bundle/edu.gemini.dataman.app/doc/Dataman.md
A minor documentation update, describing changes to how polling is conducted.
> REL-2407: documentation update

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/HtmlPrinter.java
> OCSADV-492: Bug fix: Added missing break statement.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
This just adds some last-minute changes from Andy. No logic changes. Tests pass.
> REL-2498-C Update GNIRS Blueprint

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
Tiny PR, resets the unplot/plot button to the "Unplot" state when a new target is reloaded
> REL-2556: Reset unplot state

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/PHOENIX_BP.xml
Another blueprint update. No logic changes. Tests pass.
> REL-2415-C Add Phoenix OT templates

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/itc/AnalysisMethodPanel.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/itc/ConditionsPanel.scala
Visual changes only. The layout and some text values have been changed. Current look:
> OCSADV-494: Overhaul of ITC panel layout.

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/itc/AnalysisMethodPanel.scala
Bug fix that adds case statements for some missing cases.
> OCSADV-493: Bug fix: Deal properly with GS IFU-N&S cases.

- bundle/edu.gemini.model.p1/src/main/xjb/Flamingos2.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/Flamingos2.xsd
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
Small PR that updates the wavelength for F2 K Long Filter from 2.0 to 2.2 um.
> REL-2500: Update wavelength for F2 K_LONG filter

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/ProgTableModel.scala
In the open program dialog, we filter out local programs for which the current key doesn't provide access. For example, if you now have a lowly "user" key you might not see all programs you checked out when you had a staff key.
However, we do not check whether the peer associated with a local program matches the currently selected peer.  So if you have a "staff" key from one peer, it will show you the local programs from all peers *even though you can only work with those that match the selected key's peer*.  In these cross-site cases we show the program in the open dialog table and report an "Error" in the "Changes" column because we don't have permission to lookup the status of the program.
This PR updates the local program filtering to also remove local programs associated with a peer …
> REL-2551: open dialog issue

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
This PR removes the site for visitors instruments used in the Catalog Query Tool. A side effect is that the AGS limits are selected with the site from the chosen guiders rather than the one on the context.
This fixes a bug where visitor instruments may not always select the correct strategy since a visitor can be either on the north or south
> REL-2476: AGS for visitor instruments not working

- bundle/edu.gemini.smartgcal.servlet/src/main/java/edu/gemini/smartgcal/servlet/repository/CalibrationSubversionRepository.java
The smartgcal servlet shows some erratic behavior on startup. It sometimes fails and sometimes starts without problems. Currently I don't have a good idea of what's going on.
This PR contains a minimally invasive change to the smartgcal startup that I hope will leave us with some additional information about what's going wrong when trying to startup the svn command line environment, which is the root cause of why the smartgcal servlet is (sometimes) not available.
Once we have a better idea of what's going on we can move the diagnostic command execution into the `catch` statement, for now I would like to see its output even if things go ok.
Add-On: From looking at the code I am now thinking that there might be some synchronization issues/race conditions in the code, this would explain the …
> REL-2508: Smartgcal service startup issues.

- bundle/edu.gemini.smartgcal.servlet/src/main/java/edu/gemini/smartgcal/servlet/repository/CalibrationSubversionRepository.java
Minor change to append the version information to the logging output.
> REL-2508: Version information logging added.

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
The title says it all. Low impact last minute change.
> REL-2500: Update F2 K-long filter label

- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/Flamingos2SupportTest.java
Fixes a test case that was broken by the PR for REL-2500.
> REL-2500: fix broken test case

- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/TemplateNumberingCorrection.scala
- bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/TemplateNumberCorrectionSpec.scala
This PR fixes a bug in which the template group version information is incremented whenever anything in the template group changes.  The bug arrises from a merge correction to prevent two distinct template groups created in distinct OTs from having the same `VersionToken` number.  However, the template group node version should be updated only if the `VersionToken` is in fact changed.
> OCSADV-511: template group sync bug

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/DeclinationSpec.scala
This PR sets the build for the 2016B PIT and adds the initial upconversion code for older proposals
> REL-2581: Configure PIT to 2016B Semester

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xjb/Flamingos2.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/Flamingos2.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_f2_old_longslit.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
This PR fixes the K-long typo and adds upconversion logic for legacy proposals using the bogus value
> REL-2565: Update F2 K-long filter label in PIT

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/target/TargetView.scala
This PR remove some changes for REL-259, allowing Targets Of Opportunity to be selected for any PIT proposal type
> REL-2528: Undo Changes from REL-529

- bundle/edu.gemini.catalog/build.sbt
Small PR to fix missed OSGi package export
> Add skipped osgi export of package edu.gemini.catalog.image

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/EphemerisElementEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/CatalogRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/GsaRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/MultiFormatTextField.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/RaDecFields.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/target/TargetView.scala
This PR fixes a couple of bugs outputting `Declination` values, given that the underlying `Angle` doesn't support negatives. This requires new formatters on the output
> REL-2582B: Replace PIT target model

- bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TCS.scala
It's fairly common to have a "pipeline" of functions of type `A => A` and the identity value `a => a` for a "no-op", and this is what we see in this code that manipulates a `TcsConfig`. 
It turns out that we can do this more easily by using `Endo[A]` which simply wraps `A => A` and provides a monoid where `|+|` is `andThen` and `zero` is the identity function.
> Replace A => A with Endo[A]

- app/p1-monitor/build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/DirScanner.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorMailer.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/fetch/FetchRequest.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/fetch/FetchServlet.scala
This PR changes the p1-monitor configuration to run on the new phase1 host and adds support for FT and partner proposals
Note that the configuration will change once we move out of the testing phase
> REL-2522: Implement backend monitors for hbfphase1-lv1

- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/SpPhoenixTemplateSpec.scala
Sorry for breaking the build, this PR fixes the compilation error
> REL-2463C:  Add site options to all visitor instruments

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/BlueprintBase.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/SubaruBlueprint.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
This PR adds several checks for PIT proposals mostly around conditions, LGS and band 3
> REL-1806: Implement PIT validation checks of conditions and configurations

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/IShellContext.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/impl/Shell.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/impl/View.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/util/SimpleInternalFrame.java
- bundle/edu.gemini.ui.workspace/src/main/scala/edu/gemini/ui/workspace/util/InternalFrameHelp.scala
Small PR that adds a tooltip to the help button on the PIT sub windows
> REL- 2571: Add help page links to PIT tabs

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
The PDF output needs some tweaks given that certain instrument can specify either side
Some lovely xsl programming included
> REL-2463: Add site options to all visitor instruments

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorMailer.scala
This PR adds support for Subaru proposals on p1 monitor
> REL-2296: Enable 'extras' on Subaru back-end

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Small problem checker for band 3 proposals without observations
> REL-1232: Add ToDo for Band 3 observations

- bundle/edu.gemini.model.p1.visibility/src/main/scala/edu/gemini/model/p1/visibility/TargetVisibilityCalc.scala
- bundle/edu.gemini.model.p1.visibility/src/test/scala/edu/gemini/model/p1/visibility/TestTargetVisibilityTest.scala
> REL-1692: B semester 11hr incorrect error

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/util/SequenceRule.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/DateRange.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/FileUtil.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/RWLock.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/StringUtil.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/TimeValue.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/DefaultImList.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImCollections.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/None.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Pair.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Trio.java
- bundle/edu.gemini.shared.util/src/main/scala/edu/gemini/shared/util/package.scala
Another PR removing warnings, nothing too special
Some methods were removed, given that they are marked unused by IDEA
> Removed warnings on shared.util p2checker

- bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Executor.scala
- bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ExecutorImpl.scala
This is the first step in implementing the resource management: finding out what systems will be used to run a specific sequence.
> OCSADV-518: Compute set of systems used by a sequence.

- bundle/edu.gemini.model.p1.visibility/src/main/scala/edu/gemini/model/p1/visibility/TargetVisibilityCalc.scala
- bundle/edu.gemini.model.p1.visibility/src/test/scala/edu/gemini/model/p1/visibility/TestTargetVisibilityTest.scala
Small change to DEC limits for GS on Gems and B semester
> REL-1692: Update PIT RA & Dec limits for 2016B

- bundle/edu.gemini.wdba.session.client/src/main/java/edu/gemini/wdba/session/client/WDBA_XmlRpc_SessionClient.java
- bundle/edu.gemini.wdba.shared/src/main/java/edu/gemini/wdba/shared/QueuedObservation.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/server/osgi/WDBAServerActivator.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/session/SessionEventSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GMOSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/ITccInstrumentSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/ParamSet.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccBoilerPlate.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/Flamingos2SupportTest.java
- bundle/jsky.app.ot/src/test/scala/jsky/app/ot/vcs/VcsStatusTest.scala
Another warnings removal PR in this case touching the WDBA bundles
> Removed warnings from wdba bundles

- bundle/edu.gemini.gsa.client/src/main/scala/edu/gemini/gsa/client/impl/GsaUrl.scala
- bundle/edu.gemini.gsa.query/src/main/scala/edu/gemini/gsa/query/GsaFileListQuery.scala
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_f2_old_longslit.xml
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B.xml
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
This PR contains several small updates to PIT related bugs or improvements. These will be included in the next RC4 release
> PIT bug fixes and changes

- bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_texes_gn_and_gs.xml
> REL-2463 Forgotten test file

- bundle/edu.gemini.model.p1/src/main/xjb/Gpi.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Gpi.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/GpiSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/GpiBlueprintSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/GsaoiBlueprintSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/SpBlueprintFactoryTest.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/SpPhoenixTemplateSpec.scala
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gpi/GpiTest.java
This PR exposes the unblocked modes on the PIT, A few tests were added and some small cleanups. All test pass
> REL-2620: GPI: Add the UNBLOCKED modes to PIT 

- README.md
Let the welcome page show if the build is successful
> Show travis badge on the main README file

- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsLogActions.scala
- bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/ObsLogActionsSpec.scala
This PR simply tracks changes made to the release branch in PR #805.
> REL-2622: tracking changes to the release branch

- bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/ObsLogActionsSpec.scala
A minor fix for a test case that otherwise would sometimes fail.  Sorry about that.
> REL-2622: fix test case bug

- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/PollService.scala
- bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/PollServiceSpec.scala
Skips `PollServiceSpec` tests since they cannot run reliably in travis.
> Turn off PollServiceSpec tests.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/TextUI.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/UIState.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalIo.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/XMLConverterSpec.scala
Small PR that hides Texes on the PIT and remove some deprecation warnings
> REL-2649: Hide TEXES in the 2016B PIT

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/resources/simbad_hip43018.xml
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
Small PR that makes negative parallax values equal to 0, to avoid confusing the TCC. Some warnings were removed too.
> REL-2661: Ignore negative parallaxes from Simbad

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
Minor PR that removes a restriction where to set the PI Partner Affiliation you need to set the institution. With this change the affiliation can be set independently
> REL-2670: Allow selecting FT PI Affiliation without PI address

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/ProposalClass.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/FtProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gsaoi/GsaoiBase.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/niri/NiriBase.scala
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/OpenAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/Institutions.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/ConversionResultDialog.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
- bundle/edu.gemini.sp.vcs.log/src/test/scala/edu/gemini/sp/vcs/log/impl/PersistentVcsLog2Spec.scala
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/migration/toPalote/Grillo2Palote.java
This PR sets the stage for a new release of the PIT. Subaru users can now apply to FT proposal and thus the model and UI need to support "Japan" as a PI Affiliation country.
This PR contains model updates, UI changes, upconversion logic and fixes for some warnings
> REL-2667: Add Japan to the PIT FT PI Affiliation menu

- app/p1-monitor/build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B-2.xml
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B.xml
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.test.xml
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
This PR creates an extra version of p1-monitor to support Subaru as an FT partner
> REL-2667-B: Add Japan to the PIT FT PI Affiliation menu

- app/pit/build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B-2.xml
Tiny PR with updates required to do the final PIT-2016B.2.2 release
> Changed settings to release PIT-2016B.2.2

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/GuidingFeedbackEditor.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/SourceDetailsEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TargetDetailPanel.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TargetTypeEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TestFrame.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TooDetailEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TooNameEditor.scala
This adds a target editor for TOO targets (visible only for TOO programs).
> REL-2704 add too editor

- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeBand.scala
After spending an hour trying to change the list cell renderer I gave up and just changed the `toString`. Sorry.
> REL-2710: magnitude band rendering

- app/spdb/build.sbt
- bundle/edu.gemini.horizons.api/build.sbt
Small PR with fixes to osgi references making spdb buildable
> OSGi fixes

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java
Just spotted this. Search/replace error at some point.
> fix infinite loop

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealDetailEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/package.scala
This adds a button to refresh the ephemeris; it's enabled when the Horizons designation and site are known.
> REL-2754 Add ephemeris refresh button

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
This fixes a problem where the target would get renamed to `unused` on ephemeris refresh. Also replaces an instance variable with a method.
> REL-2754 fix "unused" bug

- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala
This is a trivial change that was really hard to figure out because it intersected with the Canada issue and a UI bug (REL-2762) that causes all the ephemeris data to disappear if the window is too small.
The underlying problem is that if you have an observation with an existing scheduling block (which will be the case for executed observations that use average parallactic angle) then the scheduling block's start and the target's valid-at date will probably not coincide. This means the imported target's 1-point ephemeris won't be sufficient and you end up with no "default" coordinates. So the solution is to discard any existing scheduling block and always make it align with the old valid-at date. Andy agrees this is ok.
> REL-2749 change 2016B import to discard existing scheduling blocks

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
Currently the Horizons lookup code updates the target name with the common name of the target, which isn't always desirable. This changes the logic as follows:
- If the search term is a substring of the common name, it is expanded to the full common name. So `hal` would be expanded `Hale-Bopp`.
- If the search term is a substring of the primary designation (normally this will be an exact match) the primary designation is retained; `67p` would become `67P`.
- If neither case holds (should be impossible but with HORIZONS you never know) the user-provided name is unchanged.
- The name is not updated when refreshing the ephemeris.
> REL-2700 improve renaming logic in horizons lookup

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
If you're guiding on a non-sidereal target it is now displayed on the TPE in gray (here guiding on Titan while observing Dione).
@swalker2m the guide environment remains a mystery to me (even after the big refactor) so there may be a better way to implement `getGuideEphemerides`.
> REL-2769 add guide ephemerides to tpe

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/tpe/ImageCatalogLoader.scala
At certain targets on the sky, Gemini's image catalogue fails, It was decided that this won't be fixed at the catalogue level, but instead we produce a better error message
The HTTP query to load the image has an OK result so we need to inspect the body to tell that it fails
Here's the error message
> REL-2776: TPE image lookup fails mysteriously

- bundle/jsky.app.ot/src/main/java/jsky/image/ImageColorITTs.java
- bundle/jsky.app.ot/src/main/java/jsky/image/ImageColormap.java
- bundle/jsky.app.ot/src/main/java/jsky/image/ImageProcessor.java
- bundle/jsky.app.ot/src/main/java/jsky/image/gui/ImageColors.java
The previous PR fixed the color maps, this one fixes the intensity maps
> REL-2334-B: Fix OT Position Editor color map and intensity options

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/progadmin/AdminUI.java
Small PR changing a label on the program admin UI
> REL-2585: Rename "GSA Attributes" on the Program Admin dialog

- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/impl/TooUpdateServiceImpl.java
This PR addresses an issue with handling URL ToO requests.  In particular, we were trying to update ToO targets with information in the request.  Since they are ToO targets, you cannot set the RA/Dec and magnitude information. Rather than updating the target and guide environment, the change is to create simple new `SiderealTarget`s from the information in the request and make a new guide environment set up for manual guiding.
> REL-2760: Fix target and guide star creation from request

- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/impl/TooUpdateServiceImpl.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideGroup.scala
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/GuideGroupTest.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetGroupTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
Rename manual guide group naming and set it into a shared constant
> REL-2763: Rename the manual guide group

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/scilib/ScienceLibraryFetcher.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/scilib/ScienceLibraryInfo.java
Small update to find the GPI library on the ODB
> REL-2520: Add GPI example library to the OT

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
> REL-2628: Update Flamingos-2 Templates for 2016B

- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/NonSiderealTargetRulesSpec.scala
Removed P2 check for scheduling block outside the program semester, as requested.
> REL-2726 remove ERR_SCHEDULING_BLOCK_SEM

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/gsaoi/PlannedTimeTest.scala
Small PR updating an offset time. Also changed some numbers in the code for constants
> REL-2645: Update GSAOI guided offset overhead

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
The change allowing Altair + GMOS to use multiple probes broke the P2 check and required some changes to the way the P2 check for LGS was handled.
This was made, along with some basic custodial cleanup.
> REL-2790B: Fixed P2 check and general cleanup.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/AgsStrategyPanel.java
This PR makes the AGS strategy labels consistent between the target list form editor and the TPE.
> REL-2788: label change

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
As per the JIRA task:
1. Added new and changed existing tooltips.
2. Made tooltips appear for table header.
The second task is actually nontrivial, and was done based on a Java example as provided here:
http://docs.oracle.com/javase/tutorial/uiswing/examples/components/TableToolTipsDemoProject/src/components/TableToolTipsDemo.java
> REL-2804: ITC table tooltips

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
In the fix for REL-2785 I introduced a bug in which the scheduling block would only be updated if the observing night changed. This fixes that.
> REL-2815 fix sched block update

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/comment/CommentViewer.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/histo/HistoViewer.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visualizer/PlotViewer.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GListViewer.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GSelection.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GSelectionBroker.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GTableViewer.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GTreeViewer.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GViewer.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/util/SelectionHub.java
Sometimes wildcards `?` are your friend
> REL-2820: QPT  java.lang.ClassCastException

- bundle/edu.gemini.sp.vcs.log/src/main/scala/edu/gemini/sp/vcs/log/VcsLog.scala
- bundle/edu.gemini.sp.vcs.log/src/main/scala/edu/gemini/sp/vcs/log/impl/PersistentVcsLog2.scala
- bundle/edu.gemini.sp.vcs.log/src/test/scala/edu/gemini/sp/vcs/log/impl/PersistentVcsLog2Spec.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/archive/Archiver.scala
This implements VCS log archiving per #1004.
> implement vcs log archiving

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/resources/votable-ppmxl-proper-motion.xml
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/AngularVelocity.scala
This PR properly converts proper motion read from the PPMXL catalog
> REL-2841: Fix PPMXL proper motion units

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSDtaXRuleTest.scala
Please make sure the dirtiness of the tests I wrote are tolerable. I felt quite nasty writing them ;)
> REL-2456 Report a warning when DTA X offset is not a multiple of y-pixel binning

- app/spdb/build.sbt
- project/OcsCredentials.scala.template
This is the same as #1015, but using a different branch in my fork instead of `develop`. This way it's easier to keep rebasing the code in this PR if more commits are added to the main `develop` branch.
> Add my credentials

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewer.java
This "for the record" PR just tracks updates to the release branch for REL-2857.
> REL-2857: tracking changes in release branch

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/Helpers.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/PosAngleUpdateTest.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/VignettingTest.scala
This PR simply tracks changes made to release/ocs-2016B in the `develop` branch.
> REL-2874: tracking changes to release branch

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/resources/simbad-ngc-2438.xml
- bundle/edu.gemini.catalog/src/test/resources/votable-ppmxl-proper-motion.xml
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/AngularVelocity.scala
This PR brings three pull requests into ocs-2016B, these already exist on develop
> Retrofit REL-2841/REL-2853

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/osgi/Activator.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/PublishAction.java
- bundle/edu.gemini.qpt.client/src/main/scala/edu/gemini/qpt/ui/action/PublishDialog.scala
Tracking changes to the release branch.
> REL-2878: QPT password prompt

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/PlannedTime.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/BeanPropertyTestBase.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiPropertyTest.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/CheckboxPropertyCtrl.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/PropertyCtrl.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/RadioPropertyCtrl.java
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/bean/CheckboxEnumPropertyCtrl.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gsaoi/GsaoiEditor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchModel.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
This PR includes:
* Changes GSAOI model to include a flag for position angle constraints
* Update Gsaoi Editor to with the new flag
* Changes GEMS-AGS algorithm to select position angles depending on the flag
* Updates Gems Manual Search Dialog box to sync the old pos angle constraint flag with the model. The sync is two way between both editors
> REL-2858: Add PA mode option to GSAOI component

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/PlannedTime.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/BeanPropertyTestBase.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiPropertyTest.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/CheckboxPropertyCtrl.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/PropertyCtrl.java
- bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/RadioPropertyCtrl.java
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/bean/CheckboxEnumPropertyCtrl.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gsaoi/GsaoiEditor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchModel.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Tracking release changes into develop
> Rebase of REL-2858

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsParamSetCodecs.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsTargetCalculatorService.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/SchedulingBlock.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obs/Arbitraries.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obs/ObsParamSetCodecSpec.scala
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/PioSyntax.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B2.scala
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/SchedulingBlockMigrationTest.scala
- bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/ParamSetCodec.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleDialog.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
Rebased onto `develop`; see #1028.
> Integrate REL-2852 into develop branch

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/flamingos2/Flamingos2Editor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/EdCompInstGMOS.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gnirs/EdCompInstGNIRS.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Track changes to release branch.
> REL-2852-B: add PositionAnglePanel.updateEnabledState

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
An issue was arising when the PA field was being edited during an AGS lookup, which can easily be done by performing a longer AGS lookup such as in the example in the REL task via GSAOI.
Previously, PA constraints (e.g. fixed, fixed+180, unbounded) were handled by the AGS lookup itself and ignored by BAGS, which indiscriminately took the results of the lookup and applied them to the observation.
If the PA constraint was set to fixed and the PA was being edited, say to contain 45, then an AGS lookup would be triggered for the entry of the 4. If the user typed the 5 before the results for 4 came back, the PA would be set to 45 by the user, and another BAGS lookup would be queued by moving the BAGS state for the observation to `RunningEdited`. Once the results returned for the PA = 4 lookup, …
> REL-2858: Stop PA from being modified by BAGS when it should not be

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedback.scala
Tracking changes from patch release to develop and making change needed in AGS feedback to accommodate change to `BagsManager.RunningEditedState`.
> REL-2858: Tracking changes to develop

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
Changes needed to prepare for PIT 2017A.1.1.
> REL-2888: Made changes to bump PIT version to 2017A.1.1

- bundle/edu.gemini.pit/build.sbt
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/BrowseAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/BlueprintEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/VisitorSelector.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/ShellAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
- bundle/edu.gemini.shared.gui/build.sbt
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/Platform.scala
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/Browser.scala
- bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/ErrorBoxWithHyperlink.scala
- bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/VersionException.java
- bundle/edu.gemini.util.security/src/main/scala/edu/gemini/util/security/auth/ui/AddKeyDialog.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/ProgTableModel.scala
Bring fix fer REL-2886 to the develop branch
> REL-2886: Include OT installation link in incompatibility warning

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/visibility/TargetVisibilityCalc.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/visibility/TestTargetVisibilityTest.scala
The Dec limits for GN LGS have been requested to be changed in the PIT as per the JIRA task.
This sets the new limits and updates the test cases.
> REL-2807: Changed GN LGS Dec limits in PIT.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
- bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/Institutions.scala
Pretty straightforward from the subject.
Note that since Korea is an inaccurate country name, as per the data provided in the JIRA task, I changed the code internally to use "Republic of Korea" as well.
> REL-2691: Added Korean institutions and required NGO / partner information

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
A new task came in requesting that the PIT issue a warning for PI phone numbers with less than 10 digits.
> REL-2879: Added warning for invalid phone numbers

- app/p1-monitor/build.sbt
> REL-2888: Updated p1-monitor build file to include 2017A.

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2017A.xml
The 2017A release of the PIT needs a configuration file in order to build and function properly.
This is that configuration file.
> REL-2888: Add config file for p1-monitor or 2017A.

- app/p1pdfmaker/dist/Linux/p1pdfmaker
> REL-2937: Updated p1pdfmaker startup script.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/parallacticangle/ParallacticAngleSupportInst.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/inst/ParallacticAngleSupport.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsTargetCalculatorService.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Tracking changes from `develop` to `release/ocs-2016B`.
> REL-2922: Parallactic angle setting PA at too high a precision

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Tracking multiple parallactic angle changes to release branch.
> REL-2921: Tracking changes to release branch.

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
> REL-2922B: Tracking PA precision 2 changes to release branch

- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
Pull commits from #1083 into release branch.
> REL-2945 add new result handler (release branch)

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Base.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Imaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Longslit.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/F2BlueprintTest.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/blueprint/SpFlamingos2BlueprintBase.java
Small changes to the phase2 template for F2
> REL-2906: Updated F2 templates for 2017A

- bundle/edu.gemini.ags.servlet/src/main/scala/edu/gemini/ags/servlet/AgsServlet.scala
This PR adds a thread pool for the `AgsServlet` used by the PIT for running AGS estimations. For context, we discovered during the day or two before the last proposal deadline that OCS cron jobs stopped working. This was traced to a flood of `AgsServlet` requests from PIT. Since the servlet was doing AGS estimation in the default execution context, it was competing with other non-AGS work like the daily backup. Many estimation requests were resulting in timeout failures so PIT also wasn't showing the guide star search result probability.
This update doesn't fix the load problem per se, but it does improve the situation. Namely the default execution context thread count is limited to the number of processors available. Since AGS estimations are mostly blocked on the catalog search, …
> REL-2957: thread pool for AgsServlet

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/variant/VariantDecorator.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Inst.java
This PR enables phoenix to be usable on the QPT, see below:
While testing an NPE was detected when closing. The second commit adds a fix for that event
> REL-2833: Add Phoenix support to QPT

- bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsServer.scala
Andy reports a sporadic issue with permissions when doing a sync.  I cannot reproduce the problem or imagine why it fails on occasion.  This PR introduces a bit of logging that will divide the problem in half and tell us whether the issue is that the necessary key occasionally goes missing or that the permission check fails when it shouldn't.
> REL-2881: sync permission issue

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GMOS_S_BP.xml
GMOS-S blueprint XML update to remove custom ROIs.  There is no corresponding code update.
> REL-3003: GMOS-S Template Update

- bundle/jsky.app.ot/src/main/resources/resources/conf/welcome.html
Tiny PR, update the text describing the OT's splash window image
> REL-2938: Update OT application icon for 2017A

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/niri/EdCompInstNIRI.java
> REL-3014: Fixed name of NiriFilterComboBoxRenderer to no longer use Greek NU

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
Basic changes needed to bump PIT version.
Transformers will be modified later to accommodate REL-2985.
> REL-3059: Made changes to bump PIT version to 2017B.2.1

- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
Didn't catch this during the first PR on this REL task.
> REL-3059: Updating PITLauncher to use the appropriate version number.

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2017B.xml
We need to add another configuration file for 2017B semester for the p1 monitor for proper PIT testing of submissions. This simple PR does that.
> REL-3059: Adding 2017B conf file for p1 monitor.

- app/p1-monitor/build.sbt
Sorry... second time doing this, and keep discovering missed details.
> REL-3059: A couple more required changes for 2017B test for p1-monitor.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/overheads/OverheadsSpec.scala
Self-explanatory. Bryan updated the values for several instruments.
> REL-2985: Updated Overheads values and fixed OverheadsSpec accordingly.

- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
> REL-3059: Updated model CHANGELOG.

- app/spdb/build.sbt
My new laptop has my user account as sraaphorst instead of sraaphor as it was on my old laptop.
I am changing the spdb.sbt file to update this and update my IP for telnet access.
> REL-3106: Updated spdb build.sbt file.

- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiHorizonsConstants.java
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Horizons.scala
See description. HORIZONS access via http no longer seems to work.
> REL-3100: Updating HORIZONS protocol to https.

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Horizons.scala
Migrating changes to develop.
(Note the http to https change was already incorporated in an earlier PR.)
> REL-3100: Changes for HORIZONS for comet and asteroid lookups.

- bundle/edu.gemini.horizons.api/build.sbt
- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/api/HorizonsQuery.java
- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/api/HorizonsReply.java
- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiQueryExecutor.java
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Horizons.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/HorizonsDesignation.scala
Finally, the last PR for this never-ending REL task.
> REL-3100: Migrating PIT Horizons changes to develop.

- .travis.yml
Travis changed their VMs and our builds broke. This PR fixes it
> Fixes changes to travis that break sbt builds

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/flamingos2/Flamingos2Editor.java
As per @andrewwstephens' comment, the F2 Dark filter is now obsolete.
> REL-3031: Obsolete F2 Dark filter.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
This PR simply modifies the `SpProgramFactory` class used in importing P1 XMLs accepted by ITAC to properly populate the program and partner time fields in the new `TimeAcctAward` class.
We will not be using the new P1 calculated partner time in the OT as of yet, but we will store this information for a future release as per @swalker2m's previous PR for this REL task.
> REL-2928: Populate TimeAcctAward properly from times in proposal observations.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Proposal.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
As per our discussion on Tuesday, minimum time is now scaled to only contain program time.
> REL-2928: Minimum time now adjusted to only be partner time.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
We now use awarded time instead of summing across observations.
> REL-2928: Changes as per PR comments from previous PR to use awarded time.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xjb/GmosN.xjb
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java
This PR just tracks an update to the 2017B release branch.
> REL-3153: obsolete GMOS North R150_G5306

- app/spdb/build.sbt
Also tracking these changes to the develop branch, which add necessary defines and parameters to spdb startup scripts so that they can be debugged using VisualVM.
> REL-3162: SPDB build file changes

- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/tigratable/TigraTableCreator.java
- bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/tigratable/TigraTableData.scala
Tracking changes in the release branch.
> REL-3171: fix TigraTable creation

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
This PR updates the version numbers and upconverts to start building the PIT 2018A
> REL-3819: Prepare the PIT for 2018A

- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/OpenAction.scala
Fix for a small bug on the PIT launcher that makes it forget what the current opened file is
> REL-3206: PIT launcher file opening

- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/SubContainer.scala
- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/SubmitClient.scala
- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/SubmitDestination.scala
- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/package.scala
- bundle/edu.gemini.model.p1.submit/src/test/scala/edu/gemini/model/p1/submit/Submit.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Submissions.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/ProposalClass.xsd
- bundle/edu.gemini.model.p1/src/main/xsd/Submission.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SIPProposalSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/BlueprintEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitStatus.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala
This PR adds a new proposal class to the PIT: `Subaru Intensive Proposal` class. The PR updates the model, adds UI controls to select the proposal properties and includes a new backend for submissions.
Here's a screenshot
> REL-3193: Support Subaru Intensive Programs in PIT

- bundle/edu.gemini.itc.web/src/main/resources/index.html
Micro update for the upcoming ITC release
> Update release day for itc

- app/itc/build.sbt
Replay of PR #1274 onto the release branch
> REL-3177 Added configuration to build ITC for Linux 64

- app/p1pdfmaker/dist/Linux/p1pdfmaker
- bundle/edu.gemini.model.p1.pdf/build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/layout.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/auxfile/SkeletonAuxfileWriter.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/PdfAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/AppPreferencesEditor.scala
- bundle/edu.gemini.tools.p1pdfmaker/build.sbt
- bundle/edu.gemini.tools.p1pdfmaker/src/main/java/edu/gemini/tools/p1pdfmaker/P1PdfMaker.java
This PR changes quite a bit the templates used to produce PDFs from the phase 1 proposals. It makes it flexible where to put the list of investigators
Most of the work goes into changing the xsl definitions and testing
> REL-3151: Format changes to PIT PDF investigator list to reduce unconscious bias

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
Small detail forgotten when adding SIP proposals was to include them on the templates. This PR fixes that
> REL-3193: Support SIP programs on the PDF templates

- app/p1-monitor/build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2018A.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorMailer.scala
Adds the 2018A configuration and support for SIP programs
> REL-3207: P1 monitor for Subaru Intensive Program

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala
> REL-3193c: Support Subaru Intensive Programs in PIT

- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/DirScanner.scala
In certain cases p1-monitor cannot read the list of files being monitored (most likely due to a permissions failure) and it produces an NPE inside the timer. This make is look like the monitor is running but it doesn't process files
This is a simple fix wrapping the `listFiles` call and if it fails it fatally exits
> REL-3220: NPE on p1-monitor

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2018A.xml
Forgot to update the p1-monitor configuration for the PIT 2018A release
> Updated p1-monitor configuration

- bundle/edu.gemini.seqexec.odb/src/main/scala/edu/gemini/seqexec/odb/SeqExecService.scala
On the new seqexec we'd like to display the file id of already executed steps. This information is on the program and can be transferred to the seqexec when reading the configuration sequencep
> SEQNG-312: Display file id of already executed steps

- bundle/edu.gemini.seqexec.odb/src/main/scala/edu/gemini/seqexec/odb/SeqExecService.scala
Replay of #1327 on the release branch
> SEQNG-312B: Display file id of already executed steps

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/michelle/MichelleParams.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/type/SpTypeUtil.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/EnumTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/flamingos2/F2EnumsTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/michelle/MichelleEnumsTest.scala
#1328 again, but for `develop` branch
> REL-3251: fix enum lookup

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/OffStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/ScienceTargetStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Strategy.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/ags/AgsAnalysisRule.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/altair/AltairAowfsGuider.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2OiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/Canopus.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GnirsOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/GpiOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgw.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/NiciOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nifs/NifsOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/NiriOiwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideProbe.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/PwfsGuideProbe.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/ags/AgsStrategyKey.scala
- bundle/edu.gemini.qpt.client/src/main/scala/edu/gemini/qpt/core/listeners/AgsAnalysisListener.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/BandsList.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/AgsStrategyCombo.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/TargetFeedback.scala
There are still some potentially confusing UI behavior that still needs to be addressed, but with this PR is now possible to deactivate the guide star.
> REL-2834: Allow deactivation of AGS

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateDsl2.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
Combination REL-3253 and REL-3187 template updates.
> REL-3253, REL-3187: GNIRS template updates

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GPI_BP.xml
Small changes to the observation type of calibrations for GPI
> REL-3276: Updated GPI template

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosSouthType.java
As per the JIRA task, we have two new filters for the upcoming semester for GMOS-N and GMOS-S.
This adds them, with Julia's specifications and on where she would like to see them added in the list for GMOS-N.
> REL-3272: Added two new filters each to GMOS-N and GMOS-S.

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
When AGS is Off there is now p2checker warning.
This was necessary to close REL-2834. The tests are still missing but I have some work in progress stashed away in case we want to include tests in this PR.
> REL-2834 Add AGS Off p2checker rule

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/Validation.java
Slight change to redshift is included in calculation of single emission line.
> REL-1622: Updated validation.java so final wavelength includes redshift

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/visualizer/VisualizerConstants.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPanel.java
Here is the extraction from the previous PR that simply makes the minimum changes to sync up the colour schemes for plots in the QPT and OT.
> REL-1485 simplifed: Minimum color changes to sync OT and QPT.

- bundle/jsky.app.ot/src/main/resources/resources/conf/welcome.html
Galaxy names in provided splash screen data were incorrect and needed fixing.
> REL-3256: Changed galaxy names as requested by science.

- bundle/edu.gemini.spdb.reports.collection/src/main/resources/resources/odbMailTemplates/Down_ForReview.txt
- bundle/edu.gemini.spdb.reports.collection/src/main/resources/resources/odbMailTemplates/Down_Phase2.txt
- bundle/edu.gemini.spdb.reports.collection/src/main/resources/resources/odbMailTemplates/OnHold.txt
- bundle/edu.gemini.spdb.reports.collection/src/main/resources/resources/odbMailTemplates/Up_ForActivation.txt
- bundle/edu.gemini.spdb.reports.collection/src/main/resources/resources/odbMailTemplates/Up_ForReview.txt
- bundle/edu.gemini.spdb.reports.collection/src/main/resources/resources/odbMailTemplates/Up_Ready.txt
A small adjustment to the wording of the ODB observation status change email notifications.
> Feature/REL-3169: Update ODB status change email notification text

- build.sbt
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPElevationPlotPlugin.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPanel.java
- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
Added time labels to the OT elevation plot in accordance with the discussion on REL-1485.
Also removed warnings from the code and deleted commented out code.
Added `@Overrides` as well.
You can see the times indicated in the attached PNG for sunrise, sunset, and 12-deg twilight.
> REL-1485: Added time labels.

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/Validation.java
Tiny fix to ITC emission line minimum width redshift correction calculation.
> Feature/REL-1622: ITC single emission line minimum broadening should take into account redshift

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GRACES_BP.xml
No logic changes, XML updated to latest version.
> REL-3277: update GRACES template XML

- bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
Thanks to @sraaphorst for the tip.
> REL-2835 Get rid of Null Exception in ElevationPlot

- bundle/edu.gemini.util.skycalc/src/main/java/edu/gemini/skycalc/TwilightBoundedNight.java
I forgot to include this in #1361
> REL-1485 Use switch case for TwilightBoundType choice

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/DBProgramChooserFilter.java
> Revert "REL-2185: Other type programs are now selected by default"

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpProgramFactory.scala
This is PR #1386 for the `develop` branch.
> REL-2928: respect ITAC allocated time

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
Update URLs for images displayed in the ITC web form to avoid browser security warnings.
> REL-3332: Change ITC image URLs from HTTP to HTTPS

- bundle/edu.gemini.lchquery.servlet/src/test/scala/edu/gemini/lchquery/servlet/LchQueryRegexSpec.scala
One of the test cases for the ODB browser improvements (i.e. moving away from `StringUtil` to proper regular expressions) was improperly formed, sometimes failing when Travis was run.
> REL-3336: Fixing broken test case that was causing issues sometimes when Travis was run.

- bundle/edu.gemini.lchquery.servlet/src/test/scala/edu/gemini/lchquery/servlet/LchQueryRegexSpec.scala
One of the test cases for the ODB browser improvements (i.e. moving away from `StringUtil` to proper regular expressions) was improperly formed, sometimes failing when Travis was run.
> Fixing broken test case that was causing issues sometimes when Travis was run.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/GpiCB.java
RFC, and then we'll do a test release to make sure this works as expected when we are ready.
> REL-3342: Reverting to fix the break in serialization from deleting inner classes.

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gems/GemsGuideStarRule.java
As per discussion on https://github.com/gemini-hlsw/ocs/pull/1407
> REL-3341: Simplify if clause in P2 check for CWFS magnitudes.

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
This simply performs the necessary maintenance to upgrade the PIT to 2018B.
> REL-3362: Upgrade PIT to 2018B.

- bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml
Added three institutions, and updated one.
> REL-3270: Update PIT institution addresses for 2018B

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2018B.xml
These are the changes necessary to move the PIT from test build to official release.
> REL-3362: Configure PIT for 2018B release.

- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpBlueprintFactory.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/visitor/VisitorEditor.java
This adds the basics of the `Alopeke` code to the template generator so that P1 proposals from ITAC can be imported into the ODB.
> REL-3360: Added Alopeke code to template generator.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GnirsBlueprintSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_3376_Test.scala
This updates the GNIRS template expansion as requested. I factored the arbitraries out of `GnirsBlueprintSpec` so they could be reused.
> REL-3376 update GNIRS template

- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
This PR is 100% changes from @leashma where I resolved some conflicts that were preventing merging.
> REl-3275 ITC web form cleanup

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/AsterismType.java
I accidentally left in a comment that no longer applies. 😊
> REL-3390B: Removed no longer applicable comment.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/config2/config.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/gmos/FullExposureTime.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
This PR is another attempt at REL-3279.  Unfortunately it doesn't improve much upon [the previous version](https://github.com/gemini-hlsw/ocs/pull/1460/files), but does at least complain if it finds unexpected values in the sequence or if required values are missing instead of using defaults.
After discussion with Bryan and Arturo, we decided that I would work on building out sequence test cases in May as time permits in order to focus on getting more amnesty tasks into the test release now.
> REL-3279: ITC full exposure time for GMOS N&S

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/OpenDialog.scala
Adds a "Revert" button to the "Open" dialog.  The button is active if you select at least one program that exists in a remote database and that has pending local changes.  If pressed it will discard the local changes and fetch the remote version of the program.
As usual, I feel a bit sheepish about this PR.  The "Open" dialog has been abused a bit already and this doesn't improve the situation.  Ideally the "Open" dialog would be refactored into a generic program chooser with the ability to checkout remote programs.  It would be configured for distinct purposes: opening programs, deleting programs, or reverting changes.  That would hide features that don't apply to the other modes and simplify the UI.  This would be a lot more work though and isn't what we agreed to do in REL-1577.
> REL-1577: Add Revert button to OpenDialog

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_3376_Test.scala
This refines the logic for offset iterators as requested.
> REL-3376 updated skeleton expansion

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/util/ObsWeighter.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/CandidateDecorator.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/ClientExclusion.java
This is a copy of #1493, but for the release branch.
> REL-902: distinguish config unavailable vs mask unavailable

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/DefaultSampledSpectrum.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/SEDFactory.java
> REL-3421: expand range of user-supplied SED to cover normalization band

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/ShellAdvisor.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskAttribute.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskController.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskDecorator.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskViewAdvisor.java
A copy of #1494 for the release branch.
> REL-902: add a Masks table

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This is #1474 backported for 2018B branch release.
> REL-1714 Extra notice messages for constraints

- bundle/jsky.app.ot/src/main/resources/resources/conf/welcome.html
This is a trivial PR to tweak my own text in the OT welcome screen and update the last-modified date.
> REL-3426: Tweak welcome text and date

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/TimePreference.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/problem/ProblemController.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/property/adapter/MarkerAdapter.java
This also includes support for times formatted by timezone.
Sorry for how dirty this commit is. I had to do it.
Backported from #1501.
> REL-1714 Report intersection of constraints

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/SEDFactory.java
This fixes the import of user-supplied SEDs for GNIRS XD.
> REL-3421: fix GNIRS XD wavelength range

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
> REL-397 update scoring and marker

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/resources/edu/gemini/qpt/ui/html/template.vm
> REL-1714 Fix timezone formatting for web report

- bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Marker.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/TimePreference.java
- bundle/edu.gemini.qpt.client/src/main/resources/edu/gemini/qpt/ui/html/template.vm
Cherry picked from #1522 and #1523.
> Backport REL-397 REL-1714 REL-3431 from `develop`

- bundle/edu.gemini.ictd/src/main/scala/edu/gemini/ictd/CustomMaskKey.scala
- bundle/edu.gemini.ictd/src/main/scala/edu/gemini/ictd/dao/CustomMaskDao.scala
- bundle/edu.gemini.ictd/src/test/scala/edu/gemini/ictd/CustomMaskKeySpec.scala
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Variant.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/mask/MaskController.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Ictd.java
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProgramId.scala
- project/OcsBundle.scala
This brings #1532 to the release branch for the patch release.  It is slightly edited to avoid making any changes to `edu.gemini.spModel.core` that might break serialization compatibility.
> REL-3452: cross program mask bug fix for QPT/ICTD integration

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
* Fix bogus timestamp equality check
* Check intersection boundary is sunset/sunrise
It turns the constraint caches are trimmed by the night boundaries, so we need. 
to check for the boundaries before looking for more specific constraints.
> REL-1714: cherry pick bug fix for release branch

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/listeners/LimitsListener.java
This PR implements a small change to the message when an interval in the QPT is limited by twilight bounds.  Instead of calling it "sunrise" or "sunset" we instead write "twilight".  This permitted a modest simplification to the code as well.
> REL-1714: swap sunset/sunrise for twilight

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2018B.xml
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2019A.xml
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
These are the basic steps to prepare the PIT for the 2019A release.
> REL-3466: Initial preparations for 2019A PIT.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala
REL-3444 requires making the changes to allow the Republic of Korea to be a full partner. From the description of the task and from what I can see, this appears to consist of changing it so that they can submit joint proposals.
> REL-3444: Allow KR to submit joint proposals.

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/ScheduleIO.java
- bundle/edu.gemini.qpt.client/src/test/resources/edu/gemini/qpt/core/v1031-unexpected.qpt
- bundle/edu.gemini.qpt.client/src/test/resources/edu/gemini/qpt/core/v1031.qpt
- bundle/edu.gemini.qpt.client/src/test/scala/edu/gemini/qpt/core/MigrationSpec.scala
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/MiniModel.java
Bringing #1551 to the `develop` branch.
> REL-1714: convert nautical twilight bounds on schedule import

- app/p1-monitor/build.sbt
I always forget to do this with the other steps...
> REL-3469: Updating P1-monitor build.sbt file.

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/html/ScheduleDocument.java
- bundle/edu.gemini.qpt.client/src/main/resources/edu/gemini/qpt/ui/html/template.vm
> REL-1714: replace access to twilight for velocity template

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/HorizonsLookup.scala
This is just some cleaning up based on @tpolecat's suggestions on my earlier REL-3111 PR #1559.
> REL-3111: Cleanup of HorizonsLookup changes

- build.sbt
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/OpenDialog.scala
This increases the limit on the local OT storage from 50 MB to 100 MB as requested.
> REL-3438: Increase OT local DB storage limit.

- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/TpePlotter.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingIcon.scala
Updates to the guide quality color and symbols to make them consistent across target component, TPE plot and CQT.
> REL-2719: Guide Quality Color Update

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/DBProgramChooserFilter.java
> REL-2185: Now DD and SV programs are included with queue programs.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
GPI Half wave plate angle not stored
> REL-3612 Properly save/restore HalfWavePlateAngle property for GPI

- app/p1-monitor/build.sbt
- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2019B.xml
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
This prepares the PIT for 2019B.
I will also make the proxy changes on the p1-monitor as required.
> REL-3619: Preparing PIT for 2019B.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
> REL-3612: Properly save/restore HalfWavePlateAngle property for GPI

- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTooUpdate.java
- bundle/edu.gemini.oodb.too.url/src/test/scala/edu/gemini/spdb/rapidtoo/www/HttpUpdateSpec.scala
Tracking changes to release branch.
> REL-3609: addendum (#1626)

- bundle/edu.gemini.auxfile.workflow/build.sbt
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObsRecordDatasetFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitTimeFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitsFactory.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/InstrumentService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/NightObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObsCache.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/ObsExecRecord.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisit.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/ObsVisitService.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/TimeAccounting.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obs/InstrumentServiceSpec.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TimeAccountingSummaryTable.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/EdCompObslog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogGUI.java
Tracking approved changes to the production release in #1631.
> REL-3625: time accounting rule update

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisit.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
Tracking approved release branch updates.
> REL-3625: add serialVersionUID

- bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/www/HttpTooUpdate.java
Makes a requested wording change in the error message for invalid seconds parameter.
> REL-3609: wording change in error message

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
This PR just ports the PR made to develop:
https://github.com/gemini-hlsw/ocs/pull/1638
to the 2019A release branch, as we'd like to include it in the upcoming patch release.
> REL-3632: Backporting Andy's changes to the 2019A release branch.

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Forgot to move this change into the release branch.
> REL-3569: Fixed issue with base morphing.

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/syntax/package.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/syntax/sp/Instrument.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
This simply tracks #1641 into the `develop` branch.
> REL-3636: visitor instrument update from release branch

- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObsRecordDatasetFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitTimeFactory.java
- bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/transfer/ObservationObsVisitsFactory.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/NightObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsTimesService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obslog/ObsLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/ObsExecRecord.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisit.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/PrivateVisitList.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/ObsVisitService.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/TimeAccounting.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obsrecord/VisitCalculator.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/TimeAccountingSummaryTable.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/EdCompObslog.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogGUI.java
> REL-3628: time accounting update for GPI acquisitions (#1643)

- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obsrecord/TimeAccountingSpec.scala
Updates #1643 with a test case fix.
> REL-3628: fix sporadic test case failure

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/selector/OptionsSelector.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/selector/RefreshDialog.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTableModel.scala
Updates to the default options in the OT Queue Visualization plugin.
> REL-2897: Update default QVis options

- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/selector/OptionsSelector.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/selector/RefreshDialog.scala
- bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/table/ObservationTableModel.scala
These are Andy's updates, but for the release branch.
> REL-2897: update default options (#1646)

- .travis.yml
This is a test to fix our Travis configuration.
> REL-3669: Trying Trusty dist, which supports OpenJDK 8.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/NIFS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/Nifs.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/NifsAo.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2232_Test.scala
> Revert "REL-3666: Updating NIFS blueprint template rules."

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/NIFS_BP.xml
> REL-3666: Trying simpler solution by rearranging libraryIDs to original ones.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Imaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Longslit.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Mos.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/F2BlueprintTest.scala
> REL-3661: Updating F2 blueprint rules according to new rules.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
One more update was required for the F2 MOS blueprint. It has been tested with an F2 MOS proposal using the skeleton ODB import and shows a correct result.
> REL-3661: Updated F2 blueprint for MOS.

- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/core/Schedule.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/instrument/InstViewAdvisor.java
- bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/instrument/OutlineNode.java
Copies #1677 into the `release/ocs-2019B` branch.  We have been requested to make a QPT release with this change as soon as possible.
> REL-3696: fix Update from ICTD issues

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameResolver.scala
Tracking #1682 for the `develop` branch.
> REL-3695: NonSidereal Phase 2 Checks (#1682)

- bundle/edu.gemini.model.p1/src/main/xsd/Keyword.xsd
> REL-3639 Add Multi-messenger astrophysics keyword

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
Tracks #1686 in the develop branch.
> REL-3695: keep the name when the target type changes

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
As per the REL task instructions...
> REL-3701: Removed Texes and Phoenix from 2020A.

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Investigator.xsd
> REL-3590: Changed MEN to MAN.

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2020A.xml
This configuration fie was omitted from the PIT 2020A configuration.
> REL-3706: Added p1monitor 2020A configuration.

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
This installment wedges in a Gaia catalog adapter, completing the abuse of the original design.
> REL-3676: add Gaia adapter

- bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/gems/GemsGuideStarSearchOptions.java
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala
- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala
- bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/mascot/MascotGuideStarSpec.scala
- bundle/edu.gemini.catalog/src/main/resources/votable-1.3.xsd
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQueryResultSpec.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQuerySpec.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/VersionToken.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/VersionTokenSpec.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
- bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/SiderealNameEditor.scala
This PR takes the updates to add GAIA from the `develop` branch and makes them available for NGS2.
> REL-3676: Add GAIA

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiDetectorArray.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiDetectorArrayTest.java
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgwGroupTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gsaoi/GsaoiDetectorArrayFeature.java
Based on commissioning data, the GSAOI detector array offset must be moved.
> REL-3744: move GSAOI detector array offset

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
Added the ISS port tab to the GHOST instrument editor.
We include this in a tab because we will have multiple tabs forthcoming for more information / configuration.
> GHOSTSW-8: Added ISS port.

- bundle/edu.gemini.model.p1/src/main/xjb/GmosN.xjb
> REL-3757 - Fix error importing skeleton using GMOS NS 0.25" slit

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java
> Fix GNIRS XD S/N plot label

- build.sbt
- bundle/edu.gemini.itc.shared/src/main/java/edu/gemini/itc/shared/ConfigCreator.java
- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala
- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/InstrumentDetails.scala
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCghost.html
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/html/GhostPrinter.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/InstrumentDetailsCodec.scala
- bundle/edu.gemini.itc/src/main/resources/ghost/todo.dat
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/ghost/Ghost.scala
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/ghost/GhostRecipe.scala
- bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/util/Hash.scala
This is the skeleton for GHOST for the ITC.
> GHOSTSW-7: GHOST ITC structure

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/CalUnitParams.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/GhostSeqRepeatFlatObs.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/GhostSeqRepeatFlatObsCB.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatDarkObs.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExp.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExpCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismTypeConverters.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
Additional PR requests from the GHOST merge to develop.
> GHOST merge: PR requests

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostScienceAreaGeometry.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/inst/SciAreaFeature.java
Added the GHOST science area FOV, which is a 7.5 arcmin circle centred at the base.
> GHOSTSW-22: Added Science area.

- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
Bryan wants the changes from the 2020B PIT regarding hiding FT investigator info deployed next week for the 2020A PIT so this is the backport.
> Tracking changes back from 2020B.

- app/spdb/build.sbt
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ObservationMetaRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/ReorderBar.scala
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/gface/GSelection.java
- bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/impl/Workspace.java
The PIT uses in certain places actors which can't run on JDK 13. This PR removes some of them as well as other minor fixes
Another area where actors are used is on catalog queries but that will be handled on a separate PR
> Remove some actor usage

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
#1756 for production/patch release
> Update GAIA URL to use https

- project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
> Use HFS+ for MacOS disk images

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
> REL-3831 Add Warning if no gender is selected

- bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml
> Add INCT to the list of institutions

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
Small fix for the upconversion
> Fixes typos in the upconversion

- app/p1-monitor/build.sbt
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1Monitor.scala
Small touches to make p1 monitor work
> Adjustments to p1 monitor

- app/p1pdfmaker/build.sbt
- build.sbt
Fixes a bug on creating p1pdf maker and sets the PIT version as non test
> Fixes p1pdfmaker missing bundle

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2021A.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
> p1 monitor updates

- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2021A.xml
Small fix or p1 monitor. After this we should tag the ocs for the pit 2021A
> Fix template used on p1 monitor

- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/OverheadTablePrinter.java
- bundle/edu.gemini.itc.web/src/main/resources/index.html
Another contender for the tiniest pr award.
> REL-3857: fix the calculated number of exposures when supplied a s/n and source fraction <1

- bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Ngs2Strategy.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/CanopusWfs.java
Unsure what to do next. @swalker2m ?
> REL-3745: Change CWFS visualization in the Position Editor

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Imaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Longslit.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Mos.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/F2BlueprintTest.scala
This is a simple update to F2_BP.xml.
> REL-3818: F2_BP.xml update

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GRACES_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateDb.scala
No changes need to be made to the import process, it seems.
> REL-3865: Updated GRACES blueprint.

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
The old XML file had typos and some issues in it. This is the new version from science.
> REL-3818: Replaced XML file.

- bundle/edu.gemini.gsa.query/src/main/scala/edu/gemini/gsa/query/JsonCodecs.scala
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsPresentation.scala
Replace user visible `dataset` for `data file` in the PIT and pdfs
> Use data file for dataset

- bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml
Added some new institutions and removed a duplicated Stanford entry
> More institutions

- app/p1-monitor/build.sbt
- bundle/edu.gemini.model.p1.pdf/build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2021B.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
Sets p1 monitor for 2021B and assigns FT to use the noao template
It also fixes a bug on the template when using FT
> Fix a bug on the NOAO template and setup p1 monitor

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2021B.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
Fix for the previous PR as the template requested should be used by LP not FT
> Set the noao template to LP rather than FT

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/HorizonsLookup.scala
Followup for REL-3792.
The PIT currently uses the catalog's object name when creating a new target following a Horizons lookup. This is a feature in cases where the catalog name is more precise, but an annoyance in cases where the catalog name is ambiguous.
So this PR changes the behavior to use the query string (i.e., whatever the user typed in) as the target name.
> retain original query as object name

- build.sbt
Ready for the "final" release of 2021B
> Version change for the PIT

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOAO.xml
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2021B.xml
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
Signed-off-by: Carlos Quiroz <cquiroz@gemini.edu>
> Make SIP proposals use the Noao List at the end format

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/Gnirs.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSParams.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java
- bundle/edu.gemini.spModel.smartgcal/src/test/java/edu/gemini/spModel/smartgcal/CalibrationMapTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gnirs/EdCompInstGNIRS.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gnirs/GnirsForm.java
Adds GNIRS IFU options according to spec.
> REL-3809: GNIRS IFU options

- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
Same horizons fix, but for the release branch.
> Don't install a custom SSL factory for horizons lookups

- bundle/edu.gemini.ags.servlet/src/main/scala/edu/gemini/ags/servlet/json/SiderealTargetCodec.scala
- bundle/edu.gemini.ags.servlet/src/test/scala/edu/gemini/ags/servlet/arb/ArbSiderealTarget.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamCodecs.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Parallax.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProperMotion.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/TargetMigrationTest.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NumericPropertySheet2.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/SiderealDetailEditor.scala
- bundle/jsky.util.gui/src/main/java/jsky/util/gui/NumberBoxWidget.java
Just put in on my (technical debt) tab.
> REL-3872: Don't allow negative parallax

- app/qpt/doc/manual/index.html
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/MiniModel.java
- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java
- bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/Semester.java
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/RolloverPeriod.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/package.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/RolloverPeriodSpec.scala
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/report/AbstractQueueProgramStatusExternalReport.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/report/AbstractTemplateSummaryReport.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/report/ExecHoursReport.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/report/TemplateSummaryHtmlReport.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/report/TemplateSummaryTextReport.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusExternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/table/QueueProgramStatusInternalTable.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/spdb/reports/collection/util/ReportUtils.java
- bundle/edu.gemini.spdb.reports.collection/src/main/resources/edu/gemini/spdb/reports/collection/report/QueueProgramStatusExternalReport.vm
- bundle/edu.gemini.spdb.rollover.servlet/src/main/scala/edu/gemini/rollover/servlet/IncludeProgram.scala
The period for which a rollover program is considered valid changed in 2018A (though reports and QPT were never updated to reflect it).  The definition of this period is scattered all over the place so I attempted to define it in a single class, `RolloverPeriod`.
> REL-3916: RolloverPeriod

- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/RolloverPeriodSpec.scala
Got the semester wrong in a test case.
> REL-3916-B: test case bugfix

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/SpecS2NSlitVisitor.java
The main change here is to pass the "one-pixel" source fraction to SlitThroughput on L250 of GmosRecipe.java so that the "Signal and SQRT(Background)" plot is for a single pixel.
> Change the GMOS ITC summed IFU signal plot to be for a single element.

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/PlannedTime.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/gmos/PlannedTimeTest.scala
Minor update to GMOS N&S planned time overhead per cycle.
> REL-1935: updated GMOS N&S planned time

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/VISITOR_BP.xml
Updates visitor instrument template note text.
> REL-3900: update note text

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogGUI.java
I'm not sure why this has never been an issue before, or has never been reported before.  Nevertheless, working around it seems straightforward.  See suggested changes.
> REL-3949: NPE in obslog GUI

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOIRLAB.xml
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
> REL-3698 Replace mentions to NOAO with NOIRLab on the pdf templates

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Proposal.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/binding/Bound.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phase1/GsaPhase1Data.java
The set of categories on Phase I have changed and expanded. To make it easier to select they are now grouped in the UI:
> REL-3957 Add new categories and update

- build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOIRLAB.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
> REL-3957 Update the pdf templates according to the request

- build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/MaroonXBlueprint.scala
Missed formatting Maroon-X in the templates
> REL-3959 Mention Maroon-X on the pdf templates

- bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiHorizonsConstants.java
- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
This updates our Horizons client to use the JPL's new API (the old one is going away).
> WIP - Horizons API changes

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/NIFS_BP.xml
Minor change to the wording + editor stripping off trailing whitespace.
> REL-3961: NIFS Note Text Update

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/DataflowStatusService.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/dataset/DataflowStatus.scala
- bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/gemini/obscat/ObsQueryFunctor.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdObservation2.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obscat/ObsCatalog.java
Makes the "Dataflow Status" filter work as expected in the OT browser.
> REL-3964: respect dataflow status selections in OT browser

- app/spdb/build.sbt
Update release branch with correct FIRE URL for production ODBs.
> Correct FIRE URL for production ODB

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/VISITOR_BP.xml
Updates a few of the IGNRIS template observation settings in the XML itself.
> REL-3965: template XML update

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
Corrects the GHOST standard resolution IFU size.  In theory. The requirements are difficult to parse.
> REL-4014: correct GHOST IFU size

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
General GHOST TPE update:
* Displays HR sky fibers
* Shows IFUs used for sky positions in a blue-ish color instead of green
* Shows labels on the IFUs when the size is big enough to permit seeing them
Since I couldn't find requirements that I could understand I made up my own.  Accordingly, expect iteration on this.
> REL-3997: GHOST TPE Fibers

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
> REL-4015: update Gemini test catalog URLs

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemObsExecLog.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsrecord/ObsExecRecord.java
Something sometimes happens to start/end events.  The log says they are recorded and yet they are not there.  I have a couple of theories but I'm hoping to gather more information with logging.
> REL-3986: more logging

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemObsExecLog.java
Cuts down on extraneous logging that the previous REL-3986 introduced, yet adds a stack trace when it does matter.  While testing unrelated changes I noticed that test output was extremely chatty and wanted to focus it more on the cases that matter (when Start/End visits are added or removed).
> REL-3986: update logging

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
I chose the wrong parameters to extract the red/blue counts.
> REL-4005: correct GHOST timeline

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/AsterismType.java
> REL-3997: change HR asterism label

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExpCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCamera.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCameras.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/syntax/JavaDuration.scala
#1936 for the 22A release branch.
> REL-4005: exposure time again

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/GhostSeqRepeatFlatObsCB.java
> REL-3882: GHOST sequence consistency 

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala
These become functional after the release.
> REL-3924: switch to production URLs

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
**TL;DR**: This PR is a minor ~hack~ adjustment to compute the future, post-update observation hash that BAGS will look for with the position angle change _only when it is actually needed_.
--
BAGS computes a hash of relevant observation properties to determine when it is necessary to perform an AGS lookup. If an observation is updated but the hash doesn't change, BAGS can safely ignore the update.  One of the relevant hash input parameters is the instrument position angle.  AGS can be configured to search other position angles for the best guide star and assign the selected guide star **and** position angle required to reach it.  For example, when GMOS is set to "Allow 180º flip" to find a better guide star.
After doing an AGS update to assign a guide star (and potentially a new position …
> REL-4030: BAGS manual guide star + 180º flip bug

- bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml
> REL-3994 Update institutions list

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Investigator.xsd
- bundle/edu.gemini.model.p1/src/main/xsd/ProposalClass.xsd
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorMailer.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
The PIT needs to add support for multi facility proposals. This PR is the first part containing the model changes and the basic UI.
The UI needs refinements but I'm awaiting for clarification on the requirements
> REL-4043: PIT support for AEON part I

- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/Post.scala
- bundle/edu.gemini.model.p1.submit/src/test/scala/edu/gemini/model/p1/submit/ResponseParserTest.scala
- bundle/edu.gemini.model.p1.submit/src/test/scala/edu/gemini/model/p1/submit/Submit.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Meta.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_itac_no_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_itac_with_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_ver_1.0.0.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_latin1_encoding.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_latin1.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/auxfile/SkeletonAuxfileWriter.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
This contains DARP support on the p1 model and the PIT. It still needs some work on p1-monitor, skeletons and the backend servers
> REL-4041: DARP support part I

- bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/Post.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalIo.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/Meta.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_itac_no_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_itac_with_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_ver_1.0.0.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_latin1_encoding.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_ver_1.0.0_itac_no_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_ver_1.0.0_itac_with_ngoauthority.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ItacSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
I wasn't very happy about the DARP attachment model and I think it could be improved a bit with this PR
> Simplify the DARP model

- bundle/edu.gemini.gsa.client/src/main/scala/edu/gemini/gsa/client/api/GsaParams.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
> REL-3979 Support GOA searches for alopeke, zorro and igrins

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/ProposalClass.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_special.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
> REL-2527 Add ToOChoice to special proposal types

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-NOIRLAB.xml
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
> REL-3989 Select the middle semester date for non-sidereal targets

- bundle/edu.gemini.model.p1.pdf/build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/auxfile/SkeletonAuxfileWriter.scala
> REL-4041 Update PDF maker to handle two pdfs

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala
> We should store the attachment full path

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/URLConstants.scala
> REL-4063 Update Help links

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/overheads/OverheadsSpec.scala
> REL-4044 Set F2 Longslit and MOS overheads as for NIRSpectroscopy

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/GeminiTimeRequiredEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
> REL-4043 Handle a couple of border cases with the aeonMode flag

- build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/scala/edu/gemini/model/p1/pdf/P1PDF.scala
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala
- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/auxfile/SkeletonAuxfileWriter.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/PdfAction.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/AppPreferencesEditor.scala
> REL-4041 Don't show investigators on DARP mode

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Flamingos2.scala
> REL-4046 Re enable F2 MOS mode

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/AgsRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ObservationMetaRobot.scala
> REL-3989 Show the coordinates as in the middle of the semester

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Flamingos2.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/URLConstants.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Cherry picked commits to release an interim version of PIT 2022A
> PIT 2022A.1.1.3

- bundle/edu.gemini.gsa.client/src/test/scala/edu/gemini/gsa/client/impl/GsaQueryExample.scala
- bundle/edu.gemini.gsa.query/src/main/scala/edu/gemini/gsa/query/GsaFileListQuery.scala
> REL-4074 Encode name of non sidereal targets in GSA queries

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/Partners.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
> REL-4041 Some touches to the DARP Ui

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala
> REL-4041 Subaru exchange proposals can participate on DARP

- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
> REL-4052 Hide JWST for FT and DD

- build.sbt
- bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2022B.xml
> Next PIT release

- bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala
> Some small conf changes

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/visitor/VisitorInstrument.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/visitor/VisitorConfig.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/visitor/VisitorPosAngleMode.scala
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccNames.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/VisitorInstrumentSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TestBase.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/VisitorSupportTest.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/visitor/VisitorEditor.java
Fixes CR (and position angle) for MaroonX.
> REL-4020: fixed position angle for MaroonX

- app/ot/build.sbt
- app/spdb/build.sbt
Increases stack in OT and SPDB to facilitate merging giant programs.
> REL-4095: Increase stack space

- bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Inst.java
> [REL-4084] add ghost

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/gemini/obscat/ObsCatalogInfo.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/obscat/ObsCatalogHelper.scala
It only supports red/blue binning
> REL-4085 Add GHOST to the OT browser

- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/rules/ghost/GhostRule.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostIfuPatrolField.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostScienceAreaGeometry.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/Asterism.scala
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/None.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Option.java
- bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Some.java
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Angle.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeAsterismFeature.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
Handles GHOST target position range checks correctly by taking into account the particular IFU patrol range.
https://user-images.githubusercontent.com/4906023/163463720-f62a0c85-8820-4262-b0e9-96e2e334d6fd.mov
> REL-4000: GHOST IFU Range Errors

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/InstConfigInfo.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/SPInstObsComp.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/AsterismType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/ResolutionMode.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/gemini/obscat/ObsQueryFunctor.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
Hacks to make it possible to query on GHOST resolution and asterism type parameters.
> REL-4085: add resolution and asterism type to GHOST browser parameters

- bundle/edu.gemini.model.p1/src/main/xsd/Gnirs.xsd
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateFactoryImpl.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GnirsBlueprintSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_3376_Test.scala
This adds a blueprint expansion logic that handles IFU spectroscopy.
> REL-3980 GNIRS Spectroscopy (IFU)

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html
A small bug-fix to the NIRI ITC web form.
> REL-4116:  Add NIRI ITC port selector and default to up-looking port

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
I never got to the bottom of this, but catalog XML processing needs to be single-threaded.  For large result sets (e.g., 30K), the XML parsing from `String` to `Elem` to a list of targets takes a second or two which will now be paid for sequentially.
> REL-4126: synchronize XML processing

- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTable.scala
- bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala
- bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
Replay of a fix applied to the production OT
> Fix parsing error with gaia

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/config/IConfigBuilder.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/ghost/GhostReadNoiseGain.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obscomp/SPInstObsComp.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExpCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCamera.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCameras.scala
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/test/InstrumentSequenceTestBase.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/PlannedTimeTest.scala
Adds GHOST planned time according to spec.
> REL-4129:  GHOST planned time calculation

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
This fixes some issues in the XML and makes one code change, setting the FPU and decker for library obs 35.
> [REL-3980] update XML and p-code

- bundle/edu.gemini.wdba.xmlrpc.server/README.md
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/RotatorConfigTest.java
> REL-4020: set a 'rotator' param instead of 'posAngle' for MaroonX

- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml
- bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_ghost.xml
- bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Ghost.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/BlueprintBase.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GhostBlueprint.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/xjb/Ghost.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Ghost.xsd
- bundle/edu.gemini.model.p1/src/main/xsd/Proposal.xsd
Base GHOST support but only with a single target
> PIT GHOST support

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Submissions.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/ProposalClass.xsd
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SubmissionRequestEditor.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
Only GT can have band3. This is restricted on the UI only
> REL-4146 Support band3 on special proposals

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/main/xjb/Ghost.xjb
- bundle/edu.gemini.model.p1/src/main/xsd/Ghost.xsd
- flake.lock
This made it impossible to set requested times for GHOST
> Set GHOST overheads

- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/GmosNorth.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- flake.lock
> Prepare next pit test release

- build.sbt
- bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
> Another pit test

- bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
For HORIZONS records I had lazily assumed (falsely) that all records begin with three lines of metadata, followed by a delimiter, followed by the record data. In fact the number of metadata lines is arbitrary. So this changes the parser to handle any amount and just key on the delimiter line, as it always should have.
> fix header parsing

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/Flamingos2SupportTest.java
See "fault" report https://osc.cl.gemini.edu/browse/FR-42313
> REL-4191: update F2 filter wavelengths

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
I'm not totally sure if these are correct. Some samples:
* Standard Single
* Standard Dual
* Standard + Sky
* HR Single
> REL-4202 Show Ghost targets on the TPE

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/visitor/VisitorConfig.scala
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/VisitorInstrumentSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/VisitorInstrumentSupportTest.java
Uses the specific visitor instrument name / config for TCC instrument name and TCC pointing origin.
> REL-4178: TCC config updates

- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
- flake.lock
> REL-3966 Draw HRIFU Sky position

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
Requested update to PWFS2 inner limit.
> REL-4193: GHOST AGS PWFS2 inner limit update

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/test/SpModelTestBase.java
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/MagTest.scala
Adds target magnitudes in g and v bands to GHOST sequence.
> REL-4230: add g and v mags to ghost sequence

- bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/rules/ghost/GhostRule.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/AsterismType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/ResolutionMode.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismConverters.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/AsterismTypeConverters.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostParamSetCodecs.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/AsterismConvertersSpec.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Arbitraries.scala
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2023A/To2023A.scala
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2023A/GS-2022B-Q-1.xml
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2023A/GhostPrvTest.scala
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeGhostIFUFeature.scala
> REL-4229: release branch

- bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSpec.scala
- bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/RuleSpec.scala
> REL-4228: release branch

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/ghost/GhostReadNoiseGain.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExpCB.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCamera.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/PlannedTimeTest.scala
#2083 and #2084 for release branch.
> REL-4232: release branch

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/SpecS2NSlitVisitor.java
Support different input and output slit dimensions.
> REL-3981: ITC support for GNIRS IFUs

- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/AngularVelocity.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Epoch.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProperMotion.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
- bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/ProperMotionSpec.scala
- bundle/jsky.app.ot/src/main/java/jsky/science/ProperMotion.java
Carlos' fixes from #2096 for the release branch.  We decided that since
a) we don't use PM other than in GHOST, and
b) it was wrong anyway
we might as well fix this as well if we are making a patch release.
> Make PM calculations match lucuma-core

- bundle/edu.gemini.oodb.too.window/src/main/java/edu/gemini/too/email/TooEmail.java
- bundle/edu.gemini.spdb.reports.collection/src/main/java/edu/gemini/dbTools/mail/PrepareMessageAction.java
> De-duplicate cc

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/seqcomp/GhostSeqRepeatExp.java
> Fix setParamSet

- bundle/edu.gemini.itc/src/main/resources/gnirs/gnirs_LR-IFU.dat
This is a trivial PR to update the GNIRS low-resolution IFU throughput with measured values.
> REL-3981: Update GNIRS LR-IFU throughput

- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GhostSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/tcc/GhostSupportTest.scala
> REL-4313: add asterism to TCC instrument config

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala
- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/Parameters.scala
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/ItcSpectroscopyResultCodec.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/ObservationDetailsCodec.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/servlets/JsonServlet.scala
- bundle/edu.gemini.itc.web/src/test/scala/edu/gemini/itc/web/arb/ArbItcSpectroscopyResult.scala
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/ghost/GHostRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsRecipe.java
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Result.scala
These are some changes to make the latest calculations amenable to be used with explore
This should be merged after #2126
> Improvements to the ITC json api

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosReadoutTime.java
For the GPP project I needed to dump the GMOS readout time keys in a format that would be easy to `COPY FROM STDIN` into the database.  It isn't used by the `ocs` project, but it does no harm and having written it I thought I might as well keep it in case I need it again at some point.
> GMOS readout time key dump

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala
- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/Parameters.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/ItcImagingResultCodec.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/ItcSpectroscopyResultCodec.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/ObservationDetailsCodec.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/package.scala
- bundle/edu.gemini.itc.web/src/test/scala/edu/gemini/itc/web/arb/ArbExposureCalculation.scala
- bundle/edu.gemini.itc.web/src/test/scala/edu/gemini/itc/web/arb/ArbItcImagingResult.scala
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala
- bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Result.scala
These changes are required to export the `ImagingExp` results to the json ITC servlet
> Export ImagingExp to json

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCamera.scala
Fixes a typo in the GHOST blue camera readout time table.
> REL-4295: Fix Ghost readout time entry

- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/Dataman.scala
- bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsRefreshRunnable.scala
- bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/ObsRefreshRunnableSpec.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/dataset/SummitState.scala
> Dataman Poll (Release Branch)

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Gnirs.scala
Replay of https://github.com/gemini-hlsw/ocs/pull/2181 on the release branch
> REL-4354 Fix logic when to allow GNIRS LR_IFU

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
For some reason this didn't get folded into the previous PR
> Use a regex to search for the old target modes

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
The SNR was harcoded to 0 by mistake
> Fix for a missed parameter

- app/pit/dist/MacOS/entitlements.plist
- project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
Replay of PR #2192 on the 2023B PIT branch
> Update signing process for mac

- app/ot/dist/MacOS/entitlements.plist
- app/qpt/dist/MacOS/entitlements.plist
Needed to notarize those applications
> Add entitlements to the OT and QPT

- app/pit/build.sbt
- build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Gnirs.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
- bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Changes the logic of converting certain NIFS proposals and adjusts the location of the AGS server
> Last minute PIT changes

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/ghost/GhostEditor.scala
Adds the prescribed Ghost engineering component with optional exposure time settings.
> REL-4347: Ghost engineering component

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GnirsBlueprintSpec.scala
This is an update to the library program XML and a trivial logic change.
> REL-4363: GNIRS template update

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/IterBiasObsForm.java
Changes the name of the coadds label as requested.
> REL-4343: update coadds label

- bundle/edu.gemini.itc.web/src/main/resources/index.html
- bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html
- bundle/edu.gemini.itc/src/main/resources/gnirs/gnirs_HR-IFU.dat
This includes a few minor updates to the ITC:
1. Update GNIRS HR-IFU throughput
2. Update the GNIRS ITC web form to give more details about the various read modes
3. Clean up the (internal) ITC selection page (index.html)
> GNIRS ITC updates

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/Igrins2Spec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/IGRINS-2_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/IGRINS-2_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpBlueprintFactory.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateDb.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateFactoryImpl.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/igrins2/Igrins2.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/Igrins2BlueprintTest.scala
- bundle/edu.gemini.pot/build.sbt
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/igrins2/NoddingOption.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/igrins2/blueprint/SpIgrins2Blueprint.java
Welcomes IGRINS2 to the world of templates.
> REL-4420: IGRINS2 Template

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/Ghost.scala
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostCB.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/PlannedTimeTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/SeqexecConfigTest.scala
- bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/ghost/SequenceTestBase.scala
- bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Target.scala
.... does not try to limit which targets may be non-sidereal.
> REL-4360: Adds target type to GHOST sequence parameters

- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/smartgcal/SmartGcalService.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/smartgcal/keys/ConfigKeyIgrins2.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/smartgcal/maps/Igrins2CalibrationMap.java
- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/igrins2/Igrins2.scala
- bundle/edu.gemini.spModel.smartgcal/src/main/java/edu/gemini/spModel/smartgcal/CalibrationMapFactory.java
- bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/IGRINS-2_FLAT.csv
Support for SmartGcal with IGRINS.  There is no instrument configuration to match.  It appears to be these constant values.
> REL-4414: IGRINS SmartGcal

- bundle/edu.gemini.programexport.servlet/src/main/scala/edu/gemini/programexport/servlet/ProgramExportServlet.scala
- bundle/edu.gemini.programexport.servlet/src/main/scala/edu/gemini/programexport/servlet/osgi/Activator.scala
Adds requested non-sidereal target information to the program export servlet.  Also restricts access to internal port.
> REL-4442: more nonsidereal target info

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/igrins2/Igrins2ScienceAreaGeometry.scala
Small request from science that looks [trivial](https://noirlab.atlassian.net/browse/REL-4446)
but please review and see if I'm missing something as I haven't touched this in years.
> REL-4446 Update TPE visualization Igrins2ScienceAreaGeometry.scala

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsImaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/GnirsBlueprintSpec.scala
Based on a diff of the pseudocode.
> REL-4392: GNIRS template updates

- bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/visitor/VisitorConfig.scala
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GMOSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GNIRSSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/Igrins2Support.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/ObservationEnvironment.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/VisitorInstrumentSupport.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GnirsSupportTest.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/VisitorSupportTest.java
- bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/tcc/Igrins2SupportTest.scala
Adds P1/P2-specific configs for select instruments.
> REL-4428: WDBA / TCC instrument config updates

- app/spdb/build.sbt
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Igrins2.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_igrins2.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/Igrins2BlueprintSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/ProposalSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/SemesterProperties.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/IGRINS-2_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/igrins2/Igrins2.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/Igrins2BlueprintTest.scala
- bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/igrins2/NoddingOption.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/igrins2/blueprint/SpIgrins2Blueprint.java
> REL-4429 Renaming of IG2 nodding options

- build.sbt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/igrins2/Igrins2.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/Igrins2BlueprintTest.scala
Adds the Phase II Checklist note to IGRINS-2.
> REL-4420: Add Phase II Checklist note

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsBase.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsImaging.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopy.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
Latest clarifications on REL-4392, GNIRS template updates.
> REL-4392: GNIRS template clarifications

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.xml
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
More clarifications and updates.
> REL-4390: more GNIRS template updates

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GNIRS_BP.txt
- bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/gnirs/GnirsSpectroscopyIfu.scala
Make the sacrificial flat note dependent on using HR-IFU.
> REL-4392: more GNIRS template updates

- build.sbt
- bundle/edu.gemini.programexport.servlet/src/main/scala/edu/gemini/programexport/servlet/ProgramExportServlet.scala
Replay of https://github.com/gemini-hlsw/ocs/pull/2313 on the release branch
> Gsfr 44100 b

- bundle/edu.gemini.qpt.client/src/main/resources/edu/gemini/qpt/ui/html/template.vm
This updates the QPT-published queue plan web page to include links from the Resource Summary to each of the queue plan variants as well as links to jump back to the resource summary at the top.
> REL-4627: Update QPT published plan to include links to each variant

- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Igrins2.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Igrins2Blueprint.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
- bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/overheads/Overheads.scala
- bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG
- bundle/edu.gemini.model.p1/src/main/xsd/Igrins2.xsd
- bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_igrins2.xml
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/Igrins2BlueprintSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
- bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/overheads/OverheadsSpec.scala
- bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/Igrins2BlueprintTest.scala
I misunderstood the requirements. This is a rework of REL-4624
> REL-4624 Update model and all dependencies

- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java
F2-ITC was not returning the calculated exposure time and count.
This PR fixed it
> Return the calculated exposure and time

- bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/Parameters.scala
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/Flamingos2Printer.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GmosPrinter.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GnirsPrinter.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/HtmlPrinter.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/Igrins2Printer.java
- bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/OverheadTablePrinter.java
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala
- bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/json/ObservationDetailsCodec.scala
- bundle/edu.gemini.itc.web/src/test/scala/edu/gemini/itc/web/arb/ArbObservingDetails.scala
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/igrins2/Igrins2Recipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleRecipe.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/ImagingMethodExptime.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/ImagingPointS2NMethodBCalculation.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/ImagingS2NCalculationFactory.java
- bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsRecipe.java
- bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/util/Fixture.scala
I know we are not supposed to change the ocs much but the hierarchy of calculation methods in ITC is wrong and it is confusing for the work being done on gpp itc
> Better hierarchy

- bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/F2_BP.xml
Updates the F2 "blueprint" science program from science.
> REL-4657: update F2_BP.xml

- bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/SPComponentType.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
- bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/util/SPTreeUtil.java
- bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java
- bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2025B/To2025B.scala
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2025B/GN-2025A-Q-1.xml
- bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2025B/GN-2025A-Q-2.xml
- bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2025B/Igrins2SequenceFixTest.scala
There is a mismatch between the names of the iterator and the component for IGRINS-2
I'm not totally sure how to do migrations, this will be my first time, please check.
> REL-4647 feat: Rename IGRINS-2 sequence

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/SplashDialog.java
- bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/OpenDialog.scala
- bundle/jsky.util/src/main/java/jsky/util/Preferences.java
This pr attempts to put new OT windows on the same screen as the mouse.  There may be a better way to do this...
> REL-4701: Improve OT window placement on multi-screen computers

- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/EdCompInstGMOS.java
- bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/GmosForm.java
get disabled and stay disabled!!
> REL-4509 Always disable the amp buttons
