gemini-hlsw/ocs

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
The so-called "user" blind offset targets are supposed to be indexed from 1 when formatted for display.
=> REL-2193: format user target numbers correctly

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/ScienceTargetStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/checker/P2Checker.java, bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/rules/visitor/VisitorRule.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingFeedback.scala
Added a `VisitorRule` to force P2 AGS checks for visitor instruments.
Also removed the `UnknownError` I previously added and returned when the `Site` couldn't be determined since we don't want an obscure message of `Unknown error.` being displayed for AGS / P2 / QPT when this happens.
Made `AgsAnalysis` methods into `Option[AgsAnalysis]` methods to compensate for the removal to allow for no analysis when the analysis does not make sense / cannot be done.
=> REL-2197: AGS feedback for VisitorInstrument

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/NonSiderealTargetSupport.java
This PR cleans up some of the terrible mess surrounding nonsidereal target editing in the OT. It is still terrible of course but it's substantially easier to follow now. The main culprit was `NonSiderealTargetSupport`, which had a bunch of enums encoded as arrays indexed by constants, and an amazing `String[][][]` for storing information about which fields to show and how to label them for different types of target. So this is all greatly simplified now.
The diff will be hard to follow, sorry. You might just glance at the before and after versions of `NonSiderealTargetSupport`.
=> OCSADV-154 Target editor cleanup

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTarget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/ProperMotionEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TrackingEditor.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
`SPTarget` has a bunch of methods for proper motion that take and return `String`, and in all cases the caller is using `double` and ends up doing string conversion. Mind-boggling. Anyway, fixed. Tests pass. OT works.
=> OCSADV-154  fix stringly-typed PM methods

bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/package.scala
Before I forget, I noticed the backend urls are incorrect for Poor Weather and Directors Time.
This patch fixes that
=> Hotfix: Revert url for Poor Weather and Directors Time backends to non SV

bundle/jsky.app.ot/src/main/java/jsky/html/HTMLViewer.java
This is a fix for a `NullPointerException` that sometimes occurs in the TPE.  There exists the concept of a history list of image and catalog query results.  In the past this history list would be initialized upon creation of the `HTMLViewer` class in the constructor by loading serialized data from a file.  At some point this was turned off but the history list was unfortunately left altogether uninitialized.
This change simply initializes the history list to an empty list upon creation of the class.  There are many opportunities for improvement in this class, starting with parameterizing the `LinkedList` correctly.  I'm bypassing those opportunities though since I want to touch this code as little as possible for the patch release.
=> REL-2175: NPE bugfix

bundle/edu.gemini.ags.servlet/src/main/java/edu/gemini/ags/servlet/ToContext.java, bundle/edu.gemini.lchquery.servlet/src/test/java/edu/gemini/lchquery/servlet/LchQueryFunctorTest.java, bundle/edu.gemini.oodb.too.url/src/main/java/edu/gemini/spdb/rapidtoo/impl/TooUpdateServiceImpl.java, bundle/edu.gemini.p2checker/src/test/java/edu/gemini/p2checker/rules/AbstractRuleTest.java, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpTargetFactory.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTarget.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/SPTargetSkyObjectTest.java, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/data/ObservationProvider.scala, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GsaoiSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GuideConfigTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GuideGroupTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetGroupTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetMagnitudeTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/MagnitudeEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/PosMap.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeBasePosFeature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
This PR removes the remaining mutators on `SPTarget` with the exception of those associated with proper motion. These will be pushed down into `HmsDegTarget` in a distinct PR. The implementations have been inlined and in some cases include an explicit call to tell the `SPTarget` to notify listeners. This is terrible but it will go away soon enough; all target mods will soon be done via `setTarget`.
=> OCSADV-154  remove SPTarget mutators

project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
Adding NSHighResolutionCapable in Info.plist turns on high resolution support for OSX which results in properly rendered fonts instead of fuzzy fluffiness on retina displays. Icons are still scaled up and would need to be replaced with icons with higher resolution. However having crisp texts already goes a long way. I tested this with a locally edited version, but we should probably do a proper test with a properly built OT version before releasing this.
@swalker2m @cquiroz : Is this going to take care of OT, QPT and PIT?
=> Added NSHighResolutionCapable=true in Info.plist for OSX

bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/QvStore.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/Axis.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/ui/CategoriesEditor.scala
When loading bar charts from disk the lookup for the "dynamic" axes for Observations and Programs failed because they are currently not part of the default set of axes. (This could/should probably be changed, but when I tried to do that I run into some side-effects which I did not want to deal with in a bugfix release.)
In order to fix this for now, the two axes are manually added to the axes lookup table used to resolve axes by names when a bar chart is loaded from disk.
=> REL-2177B: Custom QV charts are lost when application is quit (2)

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Graces.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/GracesBlueprint.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala, bundle/edu.gemini.model.p1/src/main/xjb/Graces.xjb, bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG, bundle/edu.gemini.model.p1/src/main/xsd/Graces.xsd, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_graces.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_graces.xml, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/GracesSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/GracesBlueprintSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
This PR contains two updates to the Graces model:
* Rename of fiber modes
* Addition of read mode
The PR takes care of the xml, model and decision tree changes plus tests
=> REL-1841: Update GRACES PIT options

bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/QvStore.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/Axis.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/Chart.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/editor/Selectors.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/ui/AxisEditor.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/chart/ui/CategoriesEditor.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/core/FilterXMLFormatter.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/panels/HistogramChartPanel.scala
Another bug fix for QV. Hopefully it can still make it into the bug fix release. It has been tested by Kristin with a test version I created locally for her.
This is a set of fixes that deal with problems with dynamic or "on-the-fly" axes in QV. (An axis in QV is a sequence of filters that is used to define a sequence of bins for an axis of a histogram or table. The same concept btw. is used in QV for color coding in graphs, i.e. splitting the data into several bins which each are differentiated by a different color.)
First the changes in this PR address a problem that is caused by the fact that dynamic axes are actually stubs that don't contain any filters because those are created on-the-fly based on the currently available data (e.g. the available observations if separate bins for all …
=> REL-2177C: Additional bug fixes for dealing with dynamic axes.

project/src/main/scala/edu/gemini/osgi/tools/app/RPMDistHandler.scala
QPT RPM failed on execution. It was noted that the jar files are different on the rpm than on the plain distribution.
This effect was traced to the binary stripping step for rpm
http://livecipher.blogspot.com/2012/06/disable-binary-stripping-in-rpmbuild.html
This PR changes .rpmmacros to prevent binary stripping
=> Prevent RPM binary stripping

project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
This is a hack to work around an error encountered while creating a Mac `.dmg` for the QPT.  
release/ocs-2015A.1.1.2 * 19$ hdiutil create -srcfolder /Users/swalker/dev/ocs/app/qpt/target/qpt/2015A-test.1.1.2/MacOS/mac-test/Gemini\ QPT\ 2015A-test.1.1.2.app -volname qpt_2015A-test.1.1.2_macos /Users/swalker/dev/ocs/app/qpt/target/qpt/2015A-test.1.1.2/MacOS/mac-test/qpt_2015A-test.1.1.2_macos.dmg
.....................................................................................................................................................................................
hdiutil: create failed - error -5341
Googling that one lead me to this [sketchy “solution”](http://stackoverflow.com/questions/18621467/error-creating-disk-image-using-hdutil) which is basically to add a .Trash folder …
=> REL-2246: hack to work around bug in hdiutil

bundle/edu.gemini.catalog/build.sbt
SPDB is broken due to a missing package on the catalog bundle, this PR fixes that without bringing other non-completed AGS work
=> Export edu.gemini.catalog.votable package

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SubmissionRequestEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
On this PR the UI has been changed so when a PI selects a 0 time for a partner it is the same as removing the partner
The other change will open the partner time editor if the zero partner time problem is selected
=> REL-2032: Do not submit to partners with zero requested time

bundle/edu.gemini.model.p1/build.sbt
We used to have a command to create the schema tarball distributed to NGOs.
This PR restore this capability on the sbt build
=> Command to create a tar ball of the phase1 model schema

bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergeNode.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ProgramLocation.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/Unmergeable.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/package.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/PreliminaryMergePropertyTest.scala
This is the first of a series of corrections to be applied to the preliminary merge.  A `MergeCorrection` is just a function `MergePlan => MergePlan` that potentially modifies the provided plan in some way to correct for a flaw produced by the preliminary merge.  In this particular instance, the issue is that observations created locally can be given the same observation numbers as those created independently in the remote program.  Any such observations must be renumbered to be greater than the maximum remote observation number.  Note that no `ISPObservation` instances themselves are actually changed in this process.  Updates to the `ISPNodes` will be handled when the `MergePlan` is actually applied in a later step.
=> OCSADV-200-E: observation renumbering

bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/test/java/edu/gemini/catalog/api/QueryConstraintTest.java, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQuerySpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/QueryCacheSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala
This is a full rewrite of the previous attempt to do query caching. A traditional key-based cache (like scalaz's `Memo`) will be suboptimal in this case as we can reuse query results for nearby targets, e.g. if we had searched at the pole for a radius 1 and then we try the pole with radius 0.5, we can reuse the previous query doing client-side filtering.
The selected approach for the cache is a LRU cache based on a linear sequence where elements are moved to the front if they are used. To find items on the cache the client needs to provide a function that traverses the existing cache finding compatible queries. This limits performance to O(n) at best but given the relatively small size of the cache it is much faster than redoing the remote query
After some benchmarking `Vector` was …
=> OCSADV-230: Add catalog query caching

bundle/edu.gemini.sp.vcs.tui/src/main/scala/edu/gemini/sp/vcs/server/VcsServerImpl.scala, bundle/edu.gemini.sp.vcs.tui/src/main/scala/edu/gemini/sp/vcs/tui/osgi/CommandsImpl.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/Commit.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/Merge.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/MergeValidity.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/OldMergePlan.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/OldVcsFailure.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/TrpcVcsServer.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/Update.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/VcsLocking.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/VcsServer.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/VersionControlSystem.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestMerge.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestMergePlan.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestMergeSecurity.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestMergeValidity.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestStaffOnlyFields.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestingEnvironment.scala, bundle/jsky.app.ot.plugin/src/main/scala/jsky/app/ot/plugin/OtViewerService.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EdProgramHelper.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/too/TooHandler.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/SyncAllDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/SyncAllModel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/VcsGuiOp.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/VcsProgressDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/ViewerService.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/OpenDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/ProgTableModel.scala
This is a trivial rename of a few classes in order to simplify continuing development.  The changes apply to classes in the _original merge algorithm_ whose names were the same as similar classes in the new algorithm.  Of course they were already in different packages and compiled and worked fine, but the Idea Scala plugin could not distinguish them properly in a package object.  For example in
````scala
package edu.gemini.sp.vcs
...
package object diff {
type MergeCorrection = MergePlan => Unmergeable \/ MergePlan
type TryVcs[A] = VcsFailure \/ A
type VcsAction[+A] = EitherT[Task, VcsFailure, A]
...
}
````
the plugin would pick up the `MergePlan` and the `VcsFailure` from `edu.gemini.sp.vcs` instead of `edu.gemini.sp.vcs.diff`. The change simply performs the following renaming:
```` …
```
=> OCSADV-200: rename old MergePlan and old VcsFailure

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/sync/GuideSync.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/sp/validator/Validator.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergeCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergeNode.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ValidityCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/Vcs.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/package.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ValidityCorrectionSpec.scala, bundle/edu.gemini.util.security/src/main/scala/edu/gemini/util/security/policy/ImplicitPolicy.scala
This update brings validity corrections to the program merge.  Validity corrections refer to repairing a `MergePlan` so that it can be used to make valid edits to a Science Program.  It uses the existing program `Validator` to detect cardinality violations in the merge tree and then moves them into a `ConflictFolder` in the parent node, just as the existing production merge algorithm does.  The important commit is the first one, which introduces the `ValidityCorrection` class.
__Testing:__ I added a `ValidityCorrectionSpec` unit test that exercises basic functionality.  More importantly the property tests with their generated programs and edits now perform the validity correction, a new property was added that states that the end result must pass the `Validator`, and I removed a …
=> OCSADV-200-H: ValidityCorrection

build.sbt, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/VignettingTest.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/ModelConverters.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/gmos/GmosOiwfsProbeArm.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/guide/ScalaGuideProbeUtil.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/inst/FeatureGeometry.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/inst/ProbeArmGeometry.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/GMOS_OIWFS_Feature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/GMOS_SciAreaFeature.java
TPE would previously draw the science area in the wrong place if the base was not (0,0). This has been fixed.
=> OCSADV-196: TPE science area drawing bugfix

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/data/AbstractDataObject.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/data/ISPDataObject.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/rich/pot/sp/package.scala, bundle/edu.gemini.pot/src/test/java/edu/gemini/pot/spdb/test/TriggerCase.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/config/test/TestDataObject.java, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergeCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/StaffOnlyFieldCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/Vcs.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/VcsServer.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/StaffOnlyFieldCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/TestEnv.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/VcsServerSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/VcsSpec.scala
This installment introduces staff-only field corrections.  Some program nodes contain data that may only be edited by users with a staff key.  In particular, the root node itself, observations, and program notes (i.e., "pink" notes).  Examples of staff-only fields are the rollover status of the program or the QA state of an observation.  The merge correction algorithm has been updated to reset staff-only field edits to the appropriate values if a non-staff user should edit them, say via importing edited XML or an OT-bug.
To make this possible, a `copy` syntax function was added to `ISPDataObject` instances.  This permits duplicating a random data object `x` with `x.copy`.  The copy function is covered in the [first commit](https://github.com/gemini-hlsw/ocs/commit/3ccd7ba93ceb1507aaf27a2a2 …
=> OCSADV-200-J: Staff-only field corrections

bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/EdIteratorFolder.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/Keys.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/UniqueConfig.scala
This PR addresses two steps for the ITC integration. 
It adds functionality in ```UniqueConfig``` that deals with extracting the "unique configurations" that are relevant for the ITC calculations, i.e. it groups all observes in the sequence according to their configurations (e.g. dispersers, filters etc). For each of those groups we will later have to trigger a call to the ITC service. (Note: I just noticed that there is already another ```UniqueConfig``` implementation in the pot bundle which seems to do some similar stuff. However since the UniqueConfig here is short and very specific to ITC I think I will leave it as is and not try to use the ```UniqueConfig``` from the pot bundle.)
It also adds UI elements to the Base Sequence Component node which display those unique configurations …
=> OCSADV-248,OCSADV-250: Adding ITC panels to OT

bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrection.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ValidityCorrectionSpec.scala
This is a small update to observation number corrections.  It simply increments node version information when adjusting the observation number.  This is mostly to be consistent with other corrections.  The idea is that any adjustment to the merge plan should be reflected as a local edit.  We compare the version information of the final merge plan to the original program to know whether any updates need to be made locally before sending changes to the database.
=> OCSADV-200-K: increment version when correcting observation numbers

bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/config/test/CBNestedSeqCompCase.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/config/test/CBObsCompCase.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/config/test/CBSeqCompCase.java
The change to make all data objects cloneable broke some old test cases.  The behavior of these old test cases relied upon having a reference to a test data object returned when requested from the program node instead of being copied.  This update fixes those test cases by making them work like the real data objects.  They are copied when requested and have to be replaced after modifying them.
=> OCSADV-200: bugfix for ancient test cases

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
Smart GCal doesn't work for GPI and in fact throws an exception when you try to add a smart flat or arc to a GPI sequence.  This is problematic for test cases that generate random programs and sequences.  Until Smart GCal for GPI is specified by the science staff, we should just turn it off.
I tried GPI in the OT after these changes and don't see any problem, but I'd like @fnussber to review this in case there is anything I'm overlooking.
There is one substantive commit that takes away the `CalibrationKeyProvider` interface.  The second commit is a bit of cleanup: removes the `static` modifier from enums since they are static anyway, and takes away the `private` modifier from enum constructors since they are already private.
=> OCSADV-291: Turn off Smart GCal for GPI

bundle/edu.gemini.sp.vcs/build.sbt
This is a quick fix for a bug with the old VCS service, which wasn't being started in some cases because the `edu.gemini.sp.vcs.tui` bundle could not find a required service, whose service class, `edu.gemini.vcs.log.VcsLog`, shares the same package root of a package exported by `edu.gemini.vcs`.
Ultimately the `edu.gemini.vcs` bundle, which houses the old VCS code, will be retired and the who-provides-what questions will become clearer.
=> OCSADV-200: fix old vcs service registration

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
Another one of a set of release tasks for the June release. This one is basically about repeating a set of P2 check rules for GMOS-N Hamamatsu CCDs for GMOS-S.
I will verify tomorrow with science if the gain is indeed needed (currently ```AmpGain.LOW``` everywhere) and if not clean that out, too.
While the ```GmosRule``` class would certainly benefit from some additional refactoring (splitting into separate files) since it is rather large, I decided to only do a few quick fixes for now to shorten stuff a bit and get rid of some warnings.
=> REL-2239: Phase2 checks not applied to GMOS-S + Hamamatsu

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/SiteQualityPanel.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/TimingWindowDialog.java
From the JIRA task: Requirements: Periods of timing windows must include seconds, so the format must be hhh:mm:ss. The default period must be 48:00:00. 'Nuff said.
=> REL-815: Show seconds for periods in timing constraints.

build.sbt
This adds a check to the build that ensures the Java runtime agrees with the `javaVersion` setting. If there is a mismatch you see this:
```
ocs (java-version)$ sbt
[info] Loading project definition from /Users/rnorris/Scala/ocs/project
***
***                   INCORRECT JAVA RUNTIME VERSION 
***
***  The build expects version 1.8, but you are running 1.7.0_67.
***  Change the VM you're using to run sbt to avoid confusion and strange behavior.
***
[info] Set current project to ocs (in build file:/Users/rnorris/Scala/ocs/)
> 
```
=> Added Java runtime version check to build

bundle/edu.gemini.pot/src/test/scala/edu/gemini/pot/sp/ProgramGen.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergeCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ObsEdit.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ProgramDiff.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/TemplateNumberingCorrection.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/TestMerge.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ProgramDiffTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/TemplateNumberCorrectionSpec.scala
This merge installment introduces the last expected `MergePlan` correction.  It makes use of the existing `VersionTokenUtil` class to renumber template groups that are split both locally and remotely.  For example, if template group "1" is split remotely and committed to the database, we end up with groups "1" and "1.1".  If the same happens locally we have the same template groups, "1" and "1.1" but the two new "1.1" template groups are different objects with different keys. In this case the local "1.1" is renumbered to "1.2".
This correction builds on `VersionTokenUtil` to manipulate the `MergePlan` in order to guarantee that all template groups are uniquely numbered.  See `TemplateNumberingCorrection`.   It also fixes a bug in which template observations were not being considered in …
=> OCSADV-200-O: template numbering correction

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsRegistrar.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/ScienceTargetStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/WatchablePos.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/TargetEnvironment.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/ModelConverters.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingFeedback.scala
This bug originates from the lack of a capability to to analyze a single guide star on `AgsStrategy` interface. This new method has been added on this PR, plus tests and refactorings in a few places
=> OCSADV-297: All guide star quality icons change when switching stars

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/VignettingTest.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/flamingos2/Flamingos2_OIWFS_Feature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/flamingos2/Flamingos2_SciAreaFeature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/GMOS_OIWFS_Feature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/GMOS_SciAreaFeature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/inst/OIWFS_Feature.java
There is an issue with the new vignetting calculations and the new GMOS and F2 science area and probe arm models.  This PR restores the old OT/TPE definitions of GMOS/F2 features and disables the vignetting calculation while leaving all the code for the new work in place but unused.  This accomplishes a few goals:
* Allows us to put together a test release for the other OT work for 2015B
* Provides a fallback for the 2015B release if we cannot sort the problems out in time
* Gives us a quick reference to the old implementation to help work on the issue with the new model
Note that the GMOS/F2 classes `Flamingos2_OIWFS_Feature`, `Flamingos2_SciAreaFeature`, `GMOS_OIWFS_Feature`, and `GMOS_SciAreaFeature` are all simply restored from the repository and are intended to be temporary.  No …
=> OCSADV-256: restore TPE version of GMOS and F2 OI and science area

bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/Conflict.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/Conflicts.java, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergeNode.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/MergePlan.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ObsPermissionCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/PreliminaryMerge.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/StaffOnlyFieldCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/TemplateNumberingCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/ValidityCorrection.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/Vcs.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/VcsServer.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs/diff/package.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/MergeTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsEditValidatorTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ObsPermissionCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ProgramDiffTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/TemplateNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/TestEnv.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/ValidityCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs/diff/VcsServerSpec.scala
This installment adds merge conflict notes as appropriate.  Conflict notes are issues that must be brought to the attention of the user.  The already exist in the program model and are already handled by the OT.  The user is forced to acknowledge all conflicts before they can send changes to the server.
This code updates the `Modified` `MergeNode` with a field for `Conflicts` from the existing program model and augments the merge algorithm to add the appropriate notes.  It also updates `VcsServer` to reject attempts to store differences that contain conflict notes.
=> OCSADV-200-P: merge conflict notes

app/spdb/build.sbt, bundle/edu.gemini.services.server/src/main/scala/edu/gemini/services/server/osgi/Activator.scala
This is a tiny PR that adds a bundle property to the spdb app.  It's called `edu.gemini.services.server.start` and if not present it defaults to `true`.  You can define it and set it to `false` though and the spdb won't try to do the google services login.  I added that property to my own spdb configuration since I've never worked with anything that needs it.
In theory relinking the credentials files will make the login work, and it does for a time.  Eventually though it stops working and you have to relink.  Perhaps it is because the resources directory is missing, I'm not sure.  The end result though is that usually while trying to use the spdb command line during development it is spinning and writing out google services login exceptions.  Also, I'm often at home with a saturated 3G …
=> Google Services Ignore

bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsCatalogResultsSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQueryResultSpec.scala
The UCAC4 catalog sometimes includes magnitudes that should be ignored, this PR updates those rules to discard magnitudes with value 20 OR with error >= 0.9
Before, magnitudes were discarded if both conditions were true
=> OCSADV-303:Ignore bogus magnitude values on UCAC4

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/service/ItcServiceImpl.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/EdIteratorFolder.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
This PR incorporates a collection of suggestions and improvements from Andy after he played around with the ITC integration for a bit. It's mostly improvements in the ITC tables (tooltips, alignment etc).
Furthermore, the source magnitude and band are now extracted from the science target depending on the instrument configuration, i.e. the magnitude of the band is taken that corresponds most closely to the observing wavelength of the instrument configuration. Unifying the bands from spModel and ITC is planned as a future task, currently there's a mapping between the two. The source mag and band that's been selected for each instrument configuration is now displayed in the results table.
Converting the peak pixel flux to ADU has been left out for now, because currently there is no general …
=> OCSADV-295: UI improvements

bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/gems/GemsGuideStarSearchOptions.java, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsUtils4Java.scala, bundle/edu.gemini.catalog/src/main/java/edu/gemini/catalog/skycat/binding/skyobj/GemsSkyObjectFactory.java, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeGuideStarDialog.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateAsterismsTreeTable.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateAsterismsTreeTableModel.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchController.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchModel.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/gems/CatalogUtils4Java.scala
This PR updates the manual guide star search feature to work with UCAC4.
Note that this is not the final PR as we may need to support non UCAC4 catalogs too, but we can use to test the basic functionality. Currently, queries to any other catalog will go to UCAC4.
The usual code cleanups and conversions of lambdas, raw types, etc.. are included
Here are a couple of screenshots of the Dialog box
=> OCSADV-294: Support Manual GS Search for GEMS and UCAC4

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gpi/GpiTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gpi/GpiEditor.java
As part of REL-2012 it is necessary to add two parameters (aoOptimize, NoFPMPinhole) to let the Seqexec configure the instrument properly
This PR contains code adding the parameters and UI updates to GPI's Engineering Tab
=> REL-2012: Configuration from GPI/Seqexec must set Optimize and No FPM

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
I messed up a logic simplification that caused the modified target environment to not be reassigned when a target was deleted. This PR fixes that. If you view it with `?w=1` on the URL you will see that it's a minor change (most changed lines are due to indentation).
=> OCSADV-316 fixed broken delete button

bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/NIFS_BP.txt, bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/NIFS_BP.xml, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/TemplateDb.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/Nifs.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/NifsAo.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/NifsBase.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/nifs/TargetBrightness.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2232_Test.scala
This updates the selection of acquisitions based on example target brightness in K. It also adds two notes to all NIFS observations.
=> REL-2232 Update NIFS Templates for 2015B

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/InstrumentDetails.scala, bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsParameters.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleParameters.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsParameters.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsParameters.java, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/BaselineGmos.scala, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/BaselineGnirs.scala, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/BaselineMichelle.scala, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/BaselineNifs.scala, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/BaselineTRecs.scala, bundle/edu.gemini.shared.skyobject/src/main/java/edu/gemini/shared/skyobject/Magnitude.java, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Wavelength.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/AlmostEqual.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/WavelengthSpec.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
This is a bug fix that deals with problems that stem from different units being used for wavelengths throughout the code (nanometers vs micrometers). It seemed appropriate to introduce a dedicated type that allows to deal with different units in a graceful way.
=> OCSADV-319: Bug fix: Issues with nano- vs micro-meters in wavelengths.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/package.scala
This resolves (I think) some threading issues ([OCSINF-437](http://swgserv01.cl.gemini.edu:8080/browse/OCSINF-437) and [OCSINF-438](http://swgserv01.cl.gemini.edu:8080/browse/OCSINF-438)) and  that can cause races and deadlocks when doing a SIMBAD lookup. Basically I restored the old `SwingWorker` logic, in a slightly saner Scala wrapper.
Recommend viewing the diff with `?w=1` on the URL; most of the diff lines are due to a loss of a level of indentation.
=> OCSINF-437 OCSINF-438 revert to original SwingWorker logic

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeVignettingTest.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingArbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingCalcSpec.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Coordinates.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Magnitude.scala, project/OcsBundle.scala
This PR fixes an issue in which the default `Magnitude` ordering (which considers magnitude band) does not produce expected results for AGS. 
````scala
// by system name, band name, value and error (in that order)
implicit val MagnitudeOrdering: scala.math.Ordering[Magnitude] =
scala.math.Ordering.by(m => (m.system.name, m.band.name, m.value, m.error))
````
AGS works with "any" R-like band (r, R, and UC) and uses the magnitude value of the first one that it finds.
The bulk of the updates are to the test cases.  The only substantive changes are those in `SingleProbeStrategy` itself. Along the way I also deleted an unused GMOS type called `PosAngleMode` which has been superseded by `PosAngleConstraint`.
=> OCSADV-309: magnitude sorting fixes

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/api/P2Problems.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/api/Problem.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/api/ProblemRollup.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPProblemsViewer.java
Fixes a mysterious disappearing P2 check problem.  The issue is that the `Problem`s were being stored in a `TreeSet` and yet had a `Comparable` implementation wasn't consistent with `equals`.  So when you copy and paste an observation with problems and it recalculates the combined problem set, the problems in the new observation counted as already existing in the `TreeSet`.  The solution is to remove the bogus `Comparable` implementation and store the problems in a `HashSet` instead.
To keep the problem list from being displayed in random order, they are now sorted by severity and description before being listed.
This bug falls firmly into the category, "how did this ever work?".
=> REL-2298: disappearing P2 check bug fix.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPProblemsViewer.java
Naturally the updates for REL-2298 in the last PR generate a NPE when you shutdown the OT.  I offer my apologies for the hassle of another PR.  @tpolecat I agree, this is all terrible.
=> REL-2298: NPE on shutdown

bundle/edu.gemini.itc/build.sbt, project/OcsCredentials.scala.template
Changes in itc build file and credentials template that allow to build and run ITC as a standalone app.
(This is Florian talking on behalf of Sabrina ;): I've fixed a bug in the itc app build file and also added (empty) configurations for everybody to the credentials template file. This makes it easier to do a build without the credentials because the template file can be used as-is as a stand in for the "real" credentials file and allows to compile the code.
=> Changes in itc build file and credentials template

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/horizons/HorizonsService.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ConicNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/Horizons.scala
This PR offers fixes for a null pointer exception reported by Andy in REL-2314 along with a couple of other issues that fell out of testing.  First, when canceling a lookup of a "multiple answer" result we were showing a popup that read "Internal error: MultipleResults".  This was because the canceled result was being taken for a valid answer from Horizons (see `HorizonsService`).  Second, if we change the name of a conic target, the horizons ID was not being reset which resulted in unintended cache hits on the lookup as well as misleading information in the UI (see `ConicNameEditor`).
For the actual null pointer exception, I just assume that a `HorizonsReply` can return `null` for any of its fields, which is a decent assumption given the state of the old Java horizons code.  One thing …
=> REL-2314: horizons bug fixes

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ValidAtEditor.scala
This PR fixes a few issues with the "valid at" handling.
1. Switches to an `ActionListener` instead of an `ItemListener` so that reselecting the already selected element in the time menu registers as an event (and the date time can be subsequently updated to reflect the current time).
2. Removes a seemingly unneeded document listener that causes a concurrent modification exception.
3. (By request) reproduces some questionable behavior in the production OT in which selecting "Now" in the time menu also changes the calendar to today's date.
=> OCSADV-324: 'valid at' bug fixes

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SourceDetailsEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala
The `OtItemEditor` `updateEnabledState` methods are charged with enabling and disabling widgets in the various editors. Unfortunately it's a bit of a flawed mechanism and getting it to work correctly is very tricky. This PR is a bit of a hack that addresses a problem with enabled state in the target editors. Namely, visiting an executed observation's target before looking at an editable target will incorrectly record the "previous" edit state of the widgets. If that makes no sense to you, well, don't worry it shouldn't. Ideally we would rework the enabled state setting altogether but obviously not just before the release.
There are two commits.  The first fixes the enabled state issue for all non-ITC widgets and the second are the changes required for the ITC widgets.
=> OCSADV-330-B: target editor enabled state fixes

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/context/ObsContext.java
`EdCompTargetList`, responding to an event after the target component it is editing has been cut, makes a call to get the `ObsContext` passing in the target component's "context observation". See `OtItemEditor.getContextObservation` (which really should return an `Option` instead of `null`).  Of course having been cut there is no context observation.
In general you cannot construct an `ObsContext` from a `null` `ISPObservation` so this little hack seems somewhat defendable.  All apologies.
=> OCSADV-337: NPE creating observation context

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/inst/OiwfsPlotFeature.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/inst/SciAreaPlotFeature.scala
A bit of an ad-hoc fix to a bug which prevented plotting the science area and probe range if the observation is missing the observing conditions.
=> REL-2322: missing observing conditions prevents plotting GMOS

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Somehow in all the changes the guiding feedback is not updated when the selected strategy changes.  This PR takes care of that little issue.
=> OCSADV-338: added missing guiding feedback update

bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/servlets/ImageServlet.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/DatFile.scala
Not all available components in the OT are supported by the ITC, for some filters and other components we don't have the necessary data files. While the options in the web app are restricted to the available components now with the OT this originally severe problem became a regular occurrence, which is why I turned down the log level in order to keep it from flooding the logs.
=> Log fine tuning.

bundle/edu.gemini.itc.shared/src/main/java/edu/gemini/itc/shared/ITCChart.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/SequenceTabUtil.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcParametersProvider.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
Lots of UI changes.
* Added a feedback panel at the bottom for error messages (similar to guider feedback)
* Adapt table column widths to actual content (use less space horizontally)
* Charts adapt to available vertical space
* Fixed plot limits input fields
* Use ```NumberBoxWidget``` for input (same widget as in ```TargetEditor```)
* Keep current row selected, select row 0 as default
* Condition values deviating from program conditions are shown in red, identical values in black
* Mark rows with problems with x icon in first column
* Fixed rendering for special values, e.g. ```DisplayableSpType```
* and some other tiny bits and pieces
=> OCSADV-323C: Usability and UI improvements on ITC panels

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
Bug fix and test case for a particular target that broke the matching of guide probe targets
Note that the target is on the northern hemisphere and AGS will dutifully find targets even though you can't see the target with GEMS
=> OCSADV-339: MASCOT error when no CWFS guide stars found

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/SpTargetPioSpec.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala
This PR introduces fixes for a couple of bugs in target I/O.
* In this release we precess B1950 targets in a migration step.  The migration code writes the precessed RA and Dec back into the `ParamSet` to be later read by `SPTargetPio`.  It takes the B1950 RA `String` in HH:MM:SS format, does the math to convert it to J2000 and then writes the value in degrees as a `String`.  This `String` value in degrees was being interpreted by `SPTargetIO` as hours.  The fix is to first try parsing the value as a `Double` degrees and, failing that, fallback to HH:MM:SS (or DD:MM:SS for declination).
* `To2015B` was setting the proper motion value and units incorrectly in the updated `ParamSet`.  The result coming back from the precession code is in degrees per year which was being converted to …
=> OCSADV-329: Target I/O Bug

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SourceDetailsEditor.scala
Yes, ok. The "Click to Activate" idea was not going to win any awards. It has been replaced by "«undefined»" options for both pull down menus.
@swalker2m : I simplified the ```updateEnabledState()```. However I am wondering about the ```editable``` method and the additional ```node```. ```editable``` doesn't seem to be called anywhere. Can we delete this or am I missing something?
=> Add "undefined" option to source profile and distribution editors.

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/InstrumentDetails.scala, bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/BaselineGmos.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/Keys.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
This PR addresses the following issues:
* Use the custom slit width for GMOS custom masks.
* Give an error message for F2 for custom  masks (for F2 there is no way to know the slit width for custom masks).
* Ignore changing DTA X-Offset values for GMOS when calculating the "unique" configuration for ITC.
* Small fix in an error message.
=> OCSADV-321: Fixes for GMOS and F2 custom masks

bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015A/To2015A.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2015B/AsAcomet.xml, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2015B/TemplateTargetConversionTest.scala
This PR contains updates to the migration code for semesters 2015A and 2015B.
* __2015A__ - In 2015A the representation of template parameters changed. Part of the conversion process required copying PIO `ParamSet`s that represent targets and conditions.  This was done by reading the `ParamSet` into an `SPTarget` (or `SPSiteQuality`) and then exporting it back to a new `ParamSet`.  This is problematic because the target `ParamSet` format has changed.  Instead of going through the model classes, the update has been changed to simply copy the XML snippets into their proper places for the 2015A template parameter representation.  Note, this was only an issue when importing pre-2015A XML.
* __2015B__ - The 2015B migration was working for targets inside observations but ignoring template …
=> REL-2306: Fix "AsA comet" import issue

bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg, bundle/edu.gemini.catalog/src/main/resources/resources/conf/AstroCat.xml, bundle/jsky.app.ot/src/main/java/jsky/navigator/NavigatorCatalogMenu.java
Small PR that removes the "Archives" menu from the Position Editor
A bunch of code could be removed right away, but it will be easier to do when we do the full replacement of the skycat queries
=> REL-2327: Remove OT "Archives" menu

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/inst/SciAreaPlotFeature.scala
This is a bug fix for a problem in which the position angle triangle plotted in the TPE would disappear unless the observation has site quality / observing conditions.  Ordinarily if an important part of an observation is missing we cannot construct an `ObsContext`.  In this case though the observing conditions are irrelevant so we simply provide them to allow the construction of `ObsContext` even without the site quality node.
=> REL-2322: always show the pos angle triangle

bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/EdIteratorFolder.java
A tiny bug fix that removes the change listener for the duration it takes to shuffle around the tabbed panes. This avoids updates on the panels being called when they shouldn't (e.g. updating ITC panels when there is no ITC data available).
=> Avoid unnecessary updates when panels are shuffled around.

bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2015B/GS-2015B-T-1.xml, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2015B/TargetConversionTest.scala
This PR tweaks the B1950 conversion process in a couple of ways:
1. Sets the epoch to 2000.0.
2. Adds a note with the original B1950 coordinates.
=> OCSADV-350: target conversion updates

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/CoordinateEditor.scala
In response to Andy's comment I added `(J2000)` to the right of the RA/DEC boxes. It would have pushed too many things around to put it on the left.
=> OCSADV-314 add j2000 label

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala
Apparently the `TargetDetailPanel` disappears permanently from the target editor in some cases and requires an OT restart to reenable it.  I've been unable to reproduce the issue and unable to spot any obvious issues with the code.  However past experience has shown that when adding and removing components from a panel in response to events, a `revalidate` is often needed.  I threw in a `repaint` for good measure.  I propose that we continue testing with these changes and reevaluate if necessary.  Sorry, I realize this is wholly unsatisfactory.
=> REL-2331: disappearing target detail panel

bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
The name says it all. Besides removing CADC catalogs, two "catalog directories" were removed as they produce NPEs shown in the OT when clicked
=> REL-2329: Remove obsolete CADC catalogs

bundle/edu.gemini.itc.shared/src/main/java/edu/gemini/itc/shared/ObservationDetails.java, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsRecipe.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/service/ItcServiceImpl.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/Gsaoi.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcParametersProvider.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
In order to calculate the resulting S/N it is important to know the fraction of "on-source" vs "off-source" images. ITC uses a guesstimation algorithm as follows: take the FOV / science area of the instrument and check if  ```p-offset > 0.5*width or q-offset > 0.5*height```, if so, the image is considered to be off-source and on-source otherwise.
The science area returned by the instruments already takes into account that the FOV for spectroscopy is actually reduced to the slit width of the mask, which is precisely what we need here.
Note that I added a 85"x85" science area to the GSAOI instrument, replacing the default of -1"x-1". Tests are all still ok.
I also piggy-backed a small change on top of this one which deals with taking co-adds into account for NIRI and GSAOI (OCSADV-346).
=> OCSADV-328/346: ITC on-source fraction and coadds.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ConicNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ValidAtEditor.scala
This changes the nonsidereal editor to preserve magnitude and spectral info on Horizons lookup.
=> OCSADV-347 preserve mags, spectral info on horizons update

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/MagnitudeEditor.java
This prevents the terrible creepy-crawling enablement status setter from enabling the **Select →** box in the magnitude editor.
=> Prevent enablement of select → box

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
This is a small change to disable the sky aperture value of the analysis method for certain instruments for which this feature is not supported and a default value of 1.0 has to be used instead.
Unrelated to this I am also adding a bugfix to the event handling in case of updates that avoids an update causing more updates and therefore creating more work than needed.
=> OCSADV-345: Don't allow users to edit sky aperture F2, NIRI, GSAOI

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
Coadds can change during a sequence and the correct values need to be read from the configuration sequence. The coadd values are now also displayed on the ITC result tables for instruments that support them (NIRI, GSAOI, GNIRS, NIFS).
=> OCSADV-346: Better handling of coadds

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
For GMOS all calculations are done for each CCD individually in order to take CCD specific properties into account. When reporting max flow and S/N values we have to take all those CCDs into account.
=> OCSADV-353: Calculate peak and S/N values for multiple CCDs correctly

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala
This is take 2 of an attempt to fix the problem with disappearing target detail editors.  The issue is that distinct`TargetDetailPanel` instances cannot share the same instances of the individual `TargetDetailEditor`s.
This is probably not the most elegant solution but it does correctly handle both the enabled state and fix the problem with shared detail panels.
=> REL-2331: create target detail editor instances for each panel

project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
There is a bug on Mavericks which (sometimes) prevents `hdiutil` from making `dmg` files of sizes over 100 MB. This is a workaround for that for now.
See https://discussions.apple.com/thread/5667409
=> REL-2246: Workaround for hdiutil issue on Mavericks.

bundle/edu.gemini.shared.skyobject/src/main/java/edu/gemini/shared/skyobject/Magnitude.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/MagnitudeEditor.java
Update to the target editor, when a magnitude band belonging to the AB system is selected, set the magnitude system to AB. Else, select the Vega system
A few code simplifications and warnings removal are also included
=> OCSADV-355: SDSS filters must default to AB mag system

bundle/edu.gemini.shared.skyobject/src/main/java/edu/gemini/shared/skyobject/Magnitude.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/BrightnessParser.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2015B/BrightnessParserSpec.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/MagnitudeEditor.java
> Make sure that all Sloan filters (u, g, r, i, z) are imported with System = AB.
Also added a `defaultSystem` field to the `Band` itself for convenience and removed the explicit `AB_BANDS` listing.
=> OCSADV-332: default to AB for sloan filters in brightness parser

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ConicTarget.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/CoordinateParam.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/CoordinateTypes.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/HmsDegTarget.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/NamedTarget.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/NonSiderealTarget.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TargetConfig.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/JplMinorBodyDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/MpcMinorPlanetDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealDetailEditor.scala
This PR contains a handful of label changes
> * Change the Sidereal target Epoch units from "JD" to "years" 
> * Change the Sidereal target proper motion label from Delta to mu 
> * Change the parallax units from arcsec to mas 
and one slightly more significant change
> * For comets and asteroids, I don't think we should pre-fill the Epoch or TP with 2000, since those are in Julian days and will have values around 2.45e6 
Here the epoch is being stored in `NonSiderealTarget` and shared by the two subclasses, `ConicTarget` and `NamedTarget`.  Presumably the epoch for `NamedTarget`, if relevant at all, should continue to be 2000.0 years while the two epoch values for `ConicTarget` now default to 0.0 JD.
The old `ITarget` hierarchy is fairly poor and this change continues the tradition.  In …
=> OCSADV-357: minor target changes

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/acqcam/AcqCamRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/Validation.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gsaoi/GsaoiRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsRecipe.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SpatialProfile.scala
This moves some general validation logic down into the server so that it is executed for web requests and OT requests alike. Also, it deals with the problem noted in OCSADV-362 caused by exceptions thrown by ```require``` in the constructor of ```GaussianSource``` when entering values for FWHM in the target editor.
=> OCSADV-351: Validate sky aperture >= 1 and Gaussian FWHM >= 0.1

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala, bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/AcqCamPrinter.java, bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/Flamingos2Printer.java, bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GmosPrinter.java, bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/GsaoiPrinter.java, bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/NiriPrinter.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/acqcam/AcqCamRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gsaoi/Gsaoi.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gsaoi/GsaoiRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsRecipe.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Result.scala, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/service/ItcServiceImpl.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
In order to improve the usefulness of the ITC results in the OT we added some saturation warnings which previously were only shown on the web pages.
Unfortunately this PR shows, that there is still quite some repetition of code between different instruments, that could/should be addressed at some point, like e.g. some of the warnings are the same for the different instruments. So, there's still room for improvement for the ITC code, but I guess it's quite a bit better than 4 months ago..
=> OCSADV-341: Show saturation warnings in OT

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java, bundle/edu.gemini.p2checker/src/test/java/edu/gemini/p2checker/rules/AbstractRuleTest.java, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSDtaXRuleTest.scala
A new Phase 2 check.
> REQUIREMENT: IF Instrument == GMOS-S AND CCD Manufacturer == Hamamatsu AND YBINNING=1 AND DTA X Offset < -4 THEN ERROR: The GMOS-S Hamamatsu allowed DTA X range is -4 to +6 for Ybin=1 
> REQUIREMENT: IF Instrument == GMOS-S AND CCD Manufacturer == Hamamatsu AND YBINNING>1 AND DTA X Offset < -2 THEN ERROR: The GMOS-S Hamamatsu allowed DTA X range is -2 to +6 for Ybin=2 or 4
=> REL-2122: GMOS-S DTA X limit check

bundle/edu.gemini.smartgcal.servlet/build.sbt
The smartgcal servlet was not starting because of a `ClassNotFound` exception.  The class in question was actually part of the smartgcal servlet bundle so I think it is just a matter of getting the bnd parameters set correctly.
=> REL-2338: smartgcal servlet startup issue

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopeForm.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ConicDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ConicNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/CoordinateEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/NamedDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ValidAtEditor.scala
This PR contains updates to the target editor layout based on Andy's idea to move the magnitude table to the right of the coordinate editor.  These are all cosmetic changes whose goal is to make it it possible to see all widgets with a narrower OT window, place all coordinate information in a single column and make it possible to view more magnitude settings without scrolling. Unfortunately to achieve a nice layout I had to extract widgets from sub-editors so that they could be placed in a single grid bag.  My apologies go out especially to Rob for destroying that part of the code.  Perhaps there is a better way of achieving the same goal?
=> REL-2333: target component layout updates

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopeForm.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
This PR gives the OT target component a horizontal scrollbar when necessary (as opposed to shrinking all the columns to fit in the available space).
=> REL-2339: make target table scroll horizontally

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/visitor/VisitorInstrument.java
As requested, estimated visitor instrument setup time drops to 10 minutes (though unfortunately we express setup time in seconds as a double so that's 600.0 seconds).
=> REL-2340: change visitor instrument setup time

app/ot/build.sbt, project/src/main/scala/edu/gemini/osgi/tools/app/AppBuilder.scala, project/src/main/scala/edu/gemini/osgi/tools/app/Configuration.scala, project/src/main/scala/edu/gemini/osgi/tools/app/GenericUnixDistHandler.scala, project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala, project/src/main/scala/edu/gemini/osgi/tools/app/RPMDistHandler.scala, project/src/main/scala/edu/gemini/osgi/tools/app/WinDistHandler.scala
Now builds OCS RPMs remotely.
NOTE: this requires an update to your OcsCredentials file, which must be checked out of the Gemini svn repository.
=> REL-2310: Remote RPM building

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ConicDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/NamedDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealDetailEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala
This PR offers a small adjustment to the target detail panel layout.  In particular, when space is tight and sub-panels begin to shrink we should prefer to first conceal the "Source" panel, then "Magnitudes" and finally "General".  Before the shrinking order was exactly the opposite.
=> REL-2341: change shrinking order in target details panel

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
GNIRS and NIFS ITC support is not fully finished yet and will be added at a later stage. This PR simply hides the ITC panels for those instruments.
ITC support for Michelle and TReCS has also been disabled. Potentially ITC for these legacy instruments will never be supported in the OT; they are (still) supported in the web app.
=> OCSADV-363: Disable ITC panels for GNIRS and NIFS

bundle/edu.gemini.itc.shared/src/main/java/edu/gemini/itc/shared/ObservingConditions.java, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gems/Gems.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/michelle/MichelleRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/trecs/TRecsRecipe.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/service/ItcServiceImpl.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
GSAOI ITC calculations have been fully functional for a while but the Strehl value was missing. I was not able to get the precise average Strehl value from the Mascot / AGS code in a simple way due to my lack of understanding the code and also because I was very hesitant to change that code even in the slightest bit at such a late stage.
Following Bryan's suggestion I implemented an approximation for the GeMS performance based on this table http://www.gemini.edu/sciops/instruments/gems/gems-performance which should be good enough for now. We can follow up with using the more precise Strehl values at a later stage.
I am aware that this change is a bit a late comer, so I am ok in case people think we should not put that into the release. Andy is going to test it and I will certainly play …
=> OCSADV-344: Implement GeMS Strehl approximation for GSAOI

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/NumericPropertySheet.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SourceDetailsEditor.scala
Some mess-up with the event handling / repaint / whatever cycle caused the text edit widgets on the source editor to loose focus. An earlier "fix" to work around this by resetting the focus after every key stroke did not work as expected on Windows and made those edit boxes unusable.
I settled on a more streamlined event handling that in particular only changes the visibility of some of the data entry panels (implemented using ```NumericPropertySheet```) if necessary, this seems to avoid taking away the focus from the text edit box which avoids the need of resetting the focus on the widget and therefore should hopefully also resolve this issue on Windows.
=> OCSADV-362: Improve event handling on source editor.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala
One of my shameful moments when integrating the ITC was that I haven't (yet) unified the wavebands used in ITC and the core. Of course - as always - this has now come back to haunt me.
For reasons unknown ITC does not support Y and u bands. In order to deal with this I have translated those bands to other, nearby bands when passing information down from the OT to the ITC. However the preferable way seems to be to ignore those bands when deciding on the magnitude and use other magnitude information.
This PR reflects this change by ignoring magnitudes defined in Y or u and give an error message if no other magnitudes are defined.
And yes, this needs to be cleaned up and those wavelength band definitions need to be unified. But there are only so many hours in a day.
=> OCSADV-365: Ignore Y and u bands for ITC calculations.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/TargetDetailPanel.scala
This PR fixes a subtle bug in enabled state management for the target detail panel.  Ordinarily enabled state updating is ignored when setting the enabled state to the same value as it was before in order to avoid updating the table of "previous" enabled state values.  You can see this in `OtItemEditor`:
````java
protected void updateEnabledState(boolean enabled) {
if (enabled != isEnabled()) {
setEnabled(enabled);
updateEnabledState(getWindow().getComponents(), enabled);
}
}
````
In the case of `EdCompTargetList` we were ignoring this step in the overridden `updateEnabledState` method.
Unfortunately this fix is not very satisfying.  Enabled state management in the OT needs to be redone from scratch.  The table of all all widget's previous enabled state values is very fragile.
=> REL-2351: target detail enabled state fix

bundle/edu.gemini.catalog/src/main/resources/jsky/catalog/osgi/skycat.cfg
Previously, UCAC4 at Gemini queried gnodbtest2, which was not the desired behaviour.
Separated UCAC4 at Gemini into two catalogs (one for north, which now queries gnodb, and one for south, which now queries gsodb).
=> REL-2362: UCAC4 at Gemini fix

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/Horizons.scala
There were two issues reported in [REL-2364](http://jira.gemini.edu:8080/browse/REL-2364):
- The `A` element was mistakenly used for `QR` for comets. This has been fixed.
- Horizons object ids are not stable; they can change and be reassigned as the database is updated. This led to the very strange behavior seen when old targets were pasted into new programs and their (now incorrect) ids were used for "update" operations. This has been fixed by always doing a name lookup. This means that the disambiguation dialog will always appear.
=> REL-2364 fix A/QR mixup; disable id lookup

bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/calendar/CalendarMonth.java, bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/calendar/JCalendar.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/ValidAtEditor.scala
There are a number of related bugs that appear when selecting calendar dates for non-sidereal coordinate lookups.  This code uses an ancient, complex calendar widget that should be retired.  The fundamental problem is that calling `setDate(d)` on a `JCalendar` instance immediately followed by `getDate` does not produce the value `d` unless it happens to be a date in the *same month* that is being displayed.
The "solution" was to examine the actions that take place in response to the user clicking to advance the month and doing corresponding actions in `setDate`.  Finally `getDate` was changed to simply return the date that was previously set.
=> REL-2260, REL-2360, REL-2361: old calendar widget bugs

bundle/edu.gemini.catalog/src/main/resources/resources/conf/AstroCat.xml
Split entry in AstroCat.xml to remove the old singular UCAC4 at Gemini entry and replace it with the two UCAC4 entries.
This causes the two entries to appear in the three places required by Bryan's comment on the JIRA task, namely:
1. TPE Catalog -> Catalogs menu
2. Guide Star Selection dialog (manual GS search)
3. Catalog Navigator -> My Catalogs menu
=> REL-2362: Make the two new UCAC4 at Gemini (North|South) catalog entries appear in old locations

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
Enable Texes on the list of supported instruments and do not delete texes proposals on upconversion
=> REL-2355: Change DSSI/TEXES instrument options in the 2016A PIT

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/VisitorSelector.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
This PR fixes a bug that would let users edit the list of classical visitors after a proposal has been submitted
=> REL-2375: Classical visitors list can be edited after submission

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala
This PR handles a small border case, if all the backends reject a proposal the user should be allowed to keep editing, before the model was marked as submitted
Partially submitted proposals remain as before, they get locked after submission
=> REL-2254: Editing is disabled if all submissions failed

app/all-bundles/build.sbt, bundle/edu.gemini.pit.launcher/build.sbt, bundle/edu.gemini.pit.launcher/src/main/scala/edu/gemini/pit/launcher/PITLauncher.scala, project/OcsApp.scala, project/OcsBundle.scala
PIT Launcher breaks the OSGi dependencies and the PIT distributions don't properly start. In this PR `PITLauncher` is move into its own package to solve this problem.
=> REL-2377: PIT build does not work

bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/sp/version/VersionMap.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/ProgramLocation.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/Vcs.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsFailure.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsServer.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/osgi/Activator.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/osgi/Commands.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/package.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/MergeCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/ObsNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/TemplateNumberCorrectionSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/TestEnv.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/VcsServerSpec.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/VcsSpec.scala
When I started looking into OT / VCS integration I realized I would need a few changes in the new vcs code.  The intention is for the OT to mostly work with the API provided by `edu.gemini.sp.vcs2.Vcs` which has methods for performing checkouts, adds, and syncs.  Unfortunately though,
1. It was missing a `version` method to simply fetch the current `VersionMap` from the remote peer.
2. It provided no way to cancel an ongoing sync or checkout operation.  Since a `VcsAction` is simply an `EitherT[Task, VcsFailure, A]`, I could just extract the `Task`, fork it into a new thread and call `runAsyncInterruptibly`.  I wanted more control over where the interrupt would happen though to make sure that I don't somehow half-commit any updates. I used the same API as `runAsyncInterruptibly` and just …
=> OCSADV-200-R: preparing for OT integration

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
When an instrument that features a parallactic angle option finds itself in a conflict folder, bad things happen.  The `ParallacticAngleControls` assume there will always be an observation to work with, but this isn't the case when in a conflict folder.  This PR takes the fact that there may not be a containing observation into account in order to avoid exceptions and strange behavior in the OT.  It isn't ideal because it will in some cases offer widgets that do nothing (and should therefore be disabled) but it avoids the worst problems and people aren't typically editing components in conflict folders anyway.
=> REL-2380: fix NPEs when instrument is in conflict folder

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala, bundle/edu.gemini.model.p1/src/main/xjb/MagnitudeBand.xjb, bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG, bundle/edu.gemini.model.p1/src/main/xsd/Target.xsd, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Ned.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Simbad.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/VOTableCatalog.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SynchronousLookup2.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetExporter.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/CatalogRobot.scala
This PR adds the SDSS bandpasses (u, g, r, i, z) to the PIT and it allows the user to enter them on the UI.
The Simbad queries were expanded to support those bands too. I couldn't find good documentation on Simbad's votable format so I followed the result of a sample
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=SDSS+J082354.96%2B280621.6
The Magnitude editor now looks like this:
=> REL-2352: Add SDSS filter to target bandpass list in PIT

bundle/edu.gemini.model.p1.visibility/src/main/scala/edu/gemini/model/p1/visibility/TargetVisibilityCalc.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
In this PR, RA errors for non-sidereal targets get reduced severity. The change is made at the calculation level so it is reflected on `ProblemRobot` and the `Visibility` indicator
=> REL-2284: Non-sidereal targets should not produce RA visibility errors

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala
Small update with a message for the user if the ToO target option is disabled
=> REL-259: ToO targets must not be allowed in non-ToO proposals (PIT)

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Phoenix.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/PhoenixBlueprint.scala, bundle/edu.gemini.model.p1/src/main/xsd/Phoenix.xsd, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_phoenix.xml, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/PhoenixSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/PhoenixBlueprintSpec.scala
On the first RC, Phoenix can only support a single filter, but it should have support for multiple ones. This PR changes the schema to support multiple filters
=> REL-2356: Add Phoenix to the 2016A PIT resource list

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Investigator.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Per user request the initial name of the PI is set to 'Principal Investigator'. This will generate an error asking the user to set the real name
=> REL-2287: Do not allow proposal submission without the full PI name

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala, bundle/edu.gemini.model.p1/src/main/xjb/Niri.xjb, bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG, bundle/edu.gemini.model.p1/src/main/xsd/Niri.xsd, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_niri_removed_filters.xml, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
This PR removes two NIRI filters fro the model and adds upconversion code for older proposals
A couple of bugs were fixed on the upconversion code and a few code inspections were fixed
=> REL-2390: Remove NIRI filters from 2016A PIT

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EdProgramHelper.scala
Corrects a bad assumption that programs will always have a program id, and that programs which have an ID also have a known peer with which to sync.  This was more or less harmless but could generate a confusing log message when viewing the root science program node in the OT.
=> OCSADV-200: small bugfix for sync history of new programs

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/checker/P2Checker.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/util/NodeValueCache.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/P2CheckerCowboy.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewer.java
This PR is aimed at speeding up the time it takes to recover from synchronization of large programs.  In particular it caches P2 check results for observations and avoids recalculating them unless something in the observation actually changes.   It makes the determination that something has changed by comparing a hash of the node version information used by the sync algorithm.
This change would introduce mutable state (the cache) in `P2Checker` so I changed it to have one instance per `SPViewer` instead of a singleton shared across all viewers.  Cache cleanup happens automatically when the viewer switches to view a new program and runs a P2 check for it.
A lot more could be done to speed up P2 checking in general but for the specific case of recovering from a sync, the cache is quite …
=> REL-1803: cache P2 check results

bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/Vcs.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsServer.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/VcsServerSpec.scala
This PR addresses a bug in which a PI with a valid user key cannot checkout his own program.  The `ImplicitPolicy` check for `PiPermission` for a user principal will open the program in the database and check whether it contains a matching email.  For a checkout, the permission check will work fine in the server because the program exists in the remote database.  The client can successfully retrieve the program from the remote database.  If we also check locally though at the point when we're trying to add the program to the local database, It will fail.
The solution is to simply stop checking for permission to add a program to a local database while retaining permission checks if you try to add a program to a remote database.  Adding a program to a remote database continues to require a …
=> REL-2400: user key program checkout failure

app/pit/build.sbt, build.sbt, bundle/edu.gemini.model.p1.submit/src/main/scala/edu/gemini/model/p1/submit/package.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/submit/SubmitView.scala, bundle/edu.gemini.shared.gui/build.sbt, bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/GlassLabel.java, project/OcsBundle.scala
Set the PIT to use non-test mode and use of the HBF based backend.
I also have in this PR moving `GlassLabel` from `edu.gemini.pit` to the bundle `edu.gemini.shared.gui`. Though this is not strictly related to REL-2372 I wanted to make sure I could build the PIT with this change
=> REL-2372: Prepare PIT 2016A

bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/sp/validator/ConflictConstraint.scala
This PR updates the `ConflictConstraint` to specify the set of valid types it may contain.  A conflict folder can contain anything other than another conflict folder.
This will avoid the exception reported in REL-2401, which was a result of the OT attempting to determine which UI features to enable when clicking on the conflict folder.
=> REL-2401-B: specify valid types for a conflict folder

bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/PreliminaryMerge.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/MergeTest.scala
This PR contains a small update to the preliminary merge logic.  The goal is to allow a locally deleted node to remain deleted even when the containing node has also been edited remotely.  The example from the issue should help to make this clear:
> Start with a folder with one observation 
> OT1: add second observation and sync 
> OT2: delete observation and sync 
> Surprise! both observations appear in OT2 
> This works as expected using the "Old Sync" button.
All the properties still pass except the one that explicitly stated that these nodes should be resurrected.  Since the point of this PR is to make that property no longer hold, I've removed it from the `MergeTest`.
=> REL-2402: local deletion of unedited remote nodes

bundle/edu.gemini.ags.servlet/src/main/java/edu/gemini/ags/servlet/ToContext.java, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsGuideSearchOptionsSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsVoTableCatalogSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/UCAC3Regression.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/mascot/MascotGuideStarSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/AgsTest.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/VignettingTest.scala, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/api/ObservationElements.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/context/ObsContext.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gmos/AgsStrategyTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbeTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiDetectorArrayTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgwGroupTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/guide/BoundaryValidatorTest.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingArbitraries.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/TpeContext.scala
In preparation for time-based coordinates this PR makes an `Option<SchedulingBlock>` available to some of the common "context" objects that we construct and pass around when working with observations. This value is currently unused.
- `ObsContext` (used in many places)
- `ObservationElements` (used in the P2 checker)
- `TpeContext` (used in the TPE)
=> OCSADV-399-B

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/CatalogRobot.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/target/TargetView.scala
Found a small bug on PIT's display of bands. It showed the SDSS bands with the class name rather than the visible name
=> REL-2352: Add SDSS filter to  target bandpass list in PIT

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/nifs/NifsRule.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/trecs/TrecsRule.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsSchedulingReport.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ITarget.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/Fixture.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/GuideEnvironmentTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/GuideGroupTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/GuideProbeTargetsTest.java, bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Obs.java, bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java, bundle/edu.gemini.qpt.shared/src/test/scala/edu/gemini/qpt/shared/util/ObsBuilder.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/data/ObservationProvider.scala, bundle/jsky.app.ot.shared/src/main/java/jsky/app/ot/shared/gemini/obscat/ObsQueryFunctor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java
Ok this is the next set of changes in preparation for time-varying coordinates.
- I added the following methods to `ITarget` which simply delegate to the old methods and always return `Some`. The idea is that you pass a time if you have one … in cases where it doesn't matter (like with extragalactic stuff) you don't need to.
- `Option<Double> getRaDegrees(Option<Long> when)`
- `Option<Double> getDecDegrees(Option<Long> when)`
- I began changing calls to use these new methods in cases where a `SchedulingBlock` is available (passing the `start` time) when it's clear what should happen if `None` is returned (which never happens at the moment).
The lack of `for` comprehensions or `|@|` in Java is really irritating.
=> OCSADV-399-C

bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
While doing OCSADV-402 a bug on the conditions adjustments was found that affects GEMS AGS. The bug was fixed in OCSADV-402 but tests were commented out. This PR reenables and fixes the tests
=> REL-2420: Wrong AGS GEMS conditions adjustments

bundle/jsky.elevation.plot/src/main/java/jsky/plot/ElevationPlotModel.java
Today I learned that `Foo(...)` isn't the same as `Foo<>(...)`. Java is awesome.
=> OCSADV-399-E-2

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/SPTargetSkyObjectTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
More time-based target updates. (3/6)
- Update `SPTarget.hasDefinedTarget` logic to match current logic in effect: `true` unless it's an `HmsDegTarget` with coordinates at `(0.0, 0.0)`.
- Update `SPTargetSkyObjectTest` trivially.
- Update `TelescopePosTableWidget` to support unknown coordinates (still more to do).
=> OCSADV-399-F

project/OcsCredentials.scala.template
Adding empty settings for OT credentials to credentials template file. This allows to compile the code with the template file without access to the actual credentials. (This is only relevant for people outside of the software group that need to work on some parts of the code base, like e.g. Sabrina working on ITC code.)
=> Added empty settings for OT

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/CandidateValidator.scala, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gems/GemsGuideStarRule.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/altair/AltairAowfsGuider.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2OiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/Canopus.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GnirsOiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgw.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/NiciOiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nifs/NifsOiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/NiriOiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideProbeUtil.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideStarValidation.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideStarValidator.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/PatrolField.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/PwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ITarget.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbeTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
This PR changes guidestar validation from a `Boolean` to a ternary `Valid/Invalid/Undefined` to reflect the case where base or guidestar coordinates are unknown for the context scheduling block.
=> OCSADV-399-I

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/Canopus.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gems/CanopusFeature.java
Updates Canopus to handle guidestars with unknown coordinates. Probe arm geometry computes `Option<Area>` now.
Note that if you add `?w=1` to the URL you'll see a whitespace-neutral diff that is less dramatic.
=> OCSADV-399-J

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiDetectorArray.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideProbeUtil.java
Two "final" changes, which were the last ones indicated by IntelliJ (but my hope was unjustified ... more PRs coming).
- `GsaoiDetectorArray.getId` returns `None` if base coordinates are unknown.
- `GuideProbeUtil.inRange` returns `false` if base coordinates are unknown.
=> OCSADV-399-K

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/MascotGuideStar.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/CandidateValidator.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeVignettingTest.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/context/ObsContext.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/flamingos2/F2OiwfsProbeArm.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/gmos/GmosOiwfsProbeArm.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/inst/ProbeArmGeometry.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingArbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingCalcSpec.scala
This updates the Scala uses of `ObsContext.getBaseCoordinates` to use the variant returning an `Option`, which will be renamed and become the only such method in a later PR.
=> OCSADV-399-L

README.md
Just some minor updates to the `README.md` file based on my recent exercise of setting things up on my laptop. I'm calling this project the **OCS** rather than **OCS 2.1**. Probably we should also remove references to the old ocs 1.5, but I'll leave that for later.
=> Readme Update based on recent setup

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/MascotGuideStar.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/CandidateValidator.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeVignettingTest.scala, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/altair/AltairAowfsGuider.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/Canopus.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosOiwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiDetectorArray.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/GuideProbeUtil.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/guide/PatrolField.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/context/ObsContext.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/PwfsGuideProbe.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/inst/ProbeArmGeometry.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingArbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingCalcSpec.scala
This does two unrelated things, sorry:
- renames `getBaseCoordinatesOpt` to `getBaseCoordinates`.
- fixes `GeneralRule` target equality to cope with missing coordinates.
=> OCSADV-399-M

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/Niri.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/niri/EdCompInstNIRI.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/niri/NiriForm.java
I took what I thought it was going to be a small task (<30m) to play around with GitHub and our development process. Unfortunately this took a bit longer than planned, as I was working on this thing I found a few *special* features that distracted me for a while. 
First, the filters were stored as a collection of `String` in the combo, instead of real `Filters` as God mandates. 
Second, they were separated by narrowband/broadband when they were displayed in the Combo (using of course a special String - `-----------`) which looked hideous, and had code to figure out how to map the Strings in the combo to the real Filters. I still believe the UI is confusing as there is no indication as to why the filters are separated, you must know that the ones at the top are broadband, the ones below …
=> REL-2399: Obsolete the NIRI filters Jcont(1.065) and Jcont(1.122) 

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Target.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
This removes `NamedTarget` from the new model. It is subsumed by `NonSiderealTarget`.
=> OCSADV-419-B remove named target from core model

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/AgsStrategyCombo.java, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
On this PR, the Catalog Navigator is enhanced to display information about the observation that triggered the manual guide star search. This includes instrument, guider and conditions. A screenshot is included below:
Note that this is a subtask of the overall *Manual Guide Search* task. In this subtask I want to display the observation context info and in later subtasks you could change the conditions to refine the queries.
Observation info is displayed in controls instead of labels, even though those controls don't do anything, as it is duplicated effort to do labels and then change them to combo boxes. In future PRs, these boxes will be used to update the queries
=> OCSADV-414: Display observation information on the Catalog Navigator

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/smartgcal/maps/BaseCalibrationMap.java, bundle/edu.gemini.spModel.smartgcal/src/main/java/edu/gemini/spModel/smartgcal/CalibrationMapFactory.java, bundle/edu.gemini.spModel.smartgcal/src/main/resources/resources/smartgcal/calibrations/NIRI_FLAT.csv, bundle/edu.gemini.spModel.smartgcal/src/test/java/edu/gemini/spModel/smartgcal/CalibrationMapTest.java
One test case wasn't passing in my previous PR as the look up tables for SmartGCAL we had were referring to these obsolete filters. I'm not sure how we handle this in operations. @fnussber could you review this PR and let me know what the procedure should be when we put this in operations?
I also added more detail info to the error message that is generated when this happens, as suggested by @tpolecat
=> REL-2399: Removing obsolete Niri filters from smartgcal lookup tables

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTable.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala, bundle/edu.gemini.catalog/src/test/resources/simbad-2MFGC6625.xml, bundle/edu.gemini.catalog/src/test/resources/simbad-J000008.13.xml, bundle/edu.gemini.catalog/src/test/resources/simbad-vega.xml, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQueryResultSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This is the first PR to support Simbad catalogs in the catalog code. This PR contains substantial changes to `VoTableParser` to support simbad VoTable format and initial support to make remote queries no simbad in `VoTableClient`
These changes are contained to the catalog bundle, while next PR will include updates to the target model to capture extra metadata about the targets (Radial Velocity, etc) and integration with the OT
As usual I include sample votable queries for tests
=> REL-2382-A: Update Simbad name resolvers

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This is the next step on the catalog navigator. With this PR the user can select a different guider and re-query with updated limits. By user request the initial load will read all the available rows without magnitude limits.
Note that the limits for different guide speeds for each guider are displayed too
=> OCSADV-403: Let the user choose the selected AGS strategy on manual search

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/ITarget.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/SpTargetPioSpec.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
This PR addresses the last few uses of non-time-based coordinate access on `ITarget`. This doesn't affect the behavior of the template parameter editor yet, but the UI will need to be revisited when the model is swapped out because "set RA" for example only makes sense for sidereal targets.
=> OCSADV-399-P

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Target.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
This adds a magnitude table to `NonSiderealTarget`.
=> OCSADV-419-E nonsidereal magnitudes

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/Strategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/api/AgsRegistrarSpec.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTable.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala, bundle/edu.gemini.catalog/src/test/resources/simbad-not-found.xml, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/QueryCacheSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala, bundle/edu.gemini.ui.miglayout/src/main/scala/edu/gemini/ui/miglayout/MigPanel.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This PR uses the support for Simbad queries added on PR #558 with the Catalog Navigator. It will do named queries and take the first result and replace the coordinates on the query form:
Unlike the target editor, errors are displayed without a popup, instead a message is displayed on the form and at the window's bottom:
Simbad returns non-valid votable documents if no targets are found, this PR handles that case too
=> OCSADV-420: Search by name to import targets

bundle/edu.gemini.ags/src/main/java/edu/gemini/ags/gems/GemsGuideStarSearchOptions.java, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/mascot/MascotGuideStarSpec.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/api/CatalogQuery.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/skycat/binding/skyobj/UCAC4.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/skycat/binding/skyobj/Votable2SkyCatalogServlet.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTable.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQueryResultSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQuerySpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/CandidateGuideStarsTableModel.java, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This is a small update to the Catalog Navigator adding  a combo box to choose among the available catalogs (Right now just UCAC4 and PPMXL hosted at Gemini)
see the screenshot below:
=> OCSADV-406: Support changing the gemini-hosted catalog (e.g. to PPMXL)

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/conf/ProbeLimitsTable.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/config/injector/ConfigInjector.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/InstGNIRS.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/michelle/InstMichelle.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/InstNICI.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nifs/InstNIFS.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/trecs/InstTReCS.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/GuideProbeTargets.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/offset/OffsetUtil.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/nici/test/InstNICITest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/offset/OffsetUtilTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/EdCompInstGMOS.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeBasePosFeature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/CatalogQueryDemo.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/PreferredSizeFrame.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/TableColumnsAdjuster.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingIcon.scala
On this PR a column is added to the Catalog navigator displaying ax guiding quality indicator as below (By default targets are sorted by quality):
This is a rather large code update, The Catalog Navigator was getting too big and had to be separated on a few files, additionally changes were made to support custom sorting and displaying of the drawn guiding quality icons.
Finally, for guiding quality calculations, we need to have a way to create an `ObsContext` from the information on the query form. I'm not completely happy with the way it is done in this PR but I have marked those to be reviewed later with @swalker2m 
For now I want to get these changes in to move forward with TPE integration
Several old java classes were updated with modern code while doing this PR
=> OCSADV-417: Display Guide Quality icon on the catalog navigator

bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
A quick correction of a read noise value for F2 on the HTML page.
Under cover of this change I also decided to introduce unicode characters where appropriate to display units.
=> OCSADV-1852B: Display correct read noise for F2; use unicode characters.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java, bundle/jsky.app.ot/src/main/java/jsky/catalog/gui/QueryResultDisplay.java, bundle/jsky.app.ot/src/main/java/jsky/navigator/NavigatorImageDisplay.java, bundle/jsky.app.ot/src/main/java/jsky/navigator/NavigatorImageDisplayToolBar.java, bundle/jsky.app.ot/src/main/java/jsky/navigator/NavigatorManager.java, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/TableColumnsAdjuster.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingControls.scala
Small PR that integrates the New Catalog Navigator instead of the old one. The old one is still accessible from the TPE
The PR also includes a couple of small bug fixes
With this PR in we should be able to make a release to let science staff check the new navigator
=> OCSADV-421: Convert non-gems ManualGS to use VoTable

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
Small bug fix that calculates the peak value for spectroscopy as the maximum value of the sum of the signal and background functions over wavelength.
**GNIRS**
**GNIRS Cross Dispersed**
*As a side note:*
If you wonder about the structuring of the data: ITC calculation results contain several series of resulting data, e.g. `SignalData` and `BackgroundData` (available types depend on instrument and calculation modes). For each of these types there can be several arrays, e.g. for GNIRS in cross dispersion mode there is one of each data arrays (signal, background) for each order (6).
The modeling of those result values is a bit cryptic, but I have to work with what the underlying ITC code provides. However by now I also have a better feeling for how this data looks like for different …
=> OCSADV-386: Spectroscopy ITC Peak counts = signal + background.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/DynamicSequenceCellRenderer.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/DynamicSequenceTableModel.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/SequenceTabUtil.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
Requirement: Allow multiple-word titles like "Exposure Time" and "Source Fraction" in ITC tables to be split into two rows, and those columns could be made narrower.
This is implemented by taking advantage of the little known fact that cell renderers in Swing tables support HTML. To simplify the definition of `Column`s in the code the HTML for the column header is created from a string that can contain newline characters `'\n'` to mark line breaks.
I also had to tweak the util method `SequenceTabUtil.resizeTableColumns`, which optimizes the column width of a table given the column headers and contents and needs to take multi line column headers into account properly.
[**Edit:** In an additional commit the multi line headers have been extended to the sequence table columns.]
=> OCSADV-379: Compress ITC output table.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
Previously, the `Yes` and `No` labels were accidentally reversed when I changed the code to use scalaz.
=> OCSADV-422: Fix to results output for BAGS logging.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
Since we have an icon indicating BAGS guide stars, having the type tag include `(BAGS)` is redundant, as pointed out by Andy. Thus, we are simply removing it.
=> OCSADV-431: Removed BAGS label from type tag.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
This was just a stupid lack of knowledge on my part: instead of iterating over ALL observations of a program, I was only iterating over the observations not contained in groups. By changing the method call from `getObservations` to `getAllObservations`, now observations in groups are handled.
Additionally, I added a case clause to handle changes to `ISPGroup`, since otherwise this would fall through to `ISPNode` and the `getContextObservation` method would not handle all observations in the group as should be done.
=> OCSADV-430: Fixed issue where observations in groups were being ignored.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/GuideStarWorker.scala
The position angle was not always being set properly, as I was only handling it in an `if` statement when auto guide stars changed. It is now examined and handled independently of whether or not auto guide stars change, and fixes the issue with the parallactic angle where the position angle was not being properly flipped by 180.
=> OCSADV-425: Fixed issue with PA.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
Two things in this PR:
1. BAGS threads are now prioritized to be below normal thread priority to make sure they run at a lower priority than other OT functionality.
2. A bug was fixed in the calculation of the number of threads to use (ooops).
=> OCSADV-433: BAGS thread reprioritizing and bugfix

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
Improvements to event handling to BAGS to cut down on having to handle specific types of nodes and to reduce the number of unnecessary lookups considerably.
Also fixed an issue where when a program was closed, failed lookups would continue to be performed. This is done by maintaining a set of active program node keys.
=> OCSADV-435: BAGS improved event handling

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
Previously, BAGS was selecting guide stars for observations marked as "executed".
We now leave these observations alone.
@swalker2m, as per your suggestion due to the computation-heavy nature of calls to `ObservationStatus.computeFor`, I tried to push this call as far as possible into the BAGS process, but I am not sure if this is the best place to put it (i.e. after AGS is called but before results are applied), and the calls to AGS are redundant in this case.
I would greatly appreciate any feedback or suggestions as to if you think there is a preferable place to put this, as the calls to AGS are unnecessary with the results thrown away as things currently stand.
=> OCSADV-426: Added checks for executed observations.

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
This PR adds a control to let the user select an instrument, thus updating the guiders and search criteria. It was agreed to make `Visitor` the default instrument and not to support the option of `No` instrument for the time being.
The control is indicated below:
=> OCSADV-436: Instrument selection

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/Parameters.scala, bundle/edu.gemini.itc.web/src/main/java/edu/gemini/itc/web/html/HtmlPrinter.java, bundle/edu.gemini.itc.web/src/main/scala/edu/gemini/itc/web/ITCRequest.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/EmissionLineSpectrum.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/PowerLawSpectrum.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/RedshiftVisitor.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/operation/BlackBodySpectrum.scala, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/util/Fixture.scala, bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/baseline/util/Hash.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Redshift.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/AlmostEqual.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcParametersProvider.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealDetailEditor.scala
Use `Redshift` value from core model instead of a double in ITC code.
@cquiroz Maybe we should rename the value from `redshift` to `value` or `z`? As it is now we end up with many places like `.. = redshift.redshift` in the code. Not really a big issue, just wondering if renaming would make the code more readable.
=> OCSADV-334: Use Redshift from core model in ITC code.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewer.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/GuideStarWorker.scala
This PR is to address several things, notably:
1. During refactoring, I found an issue in the way that I was using scala `Future`s inside of a `Thread`, which we have to do to work with the thread pool and GeMS as well as single probes due to the differences in the way these function. This has been fixed with `Await` to wait for the `Future` to complete, whereas previously the thread just merrily kept on letting the `Futures` run and completed, restarting to make more of them, which is exactly what we do not want.
2. Minor refactoring of methods and check for `TimeoutException` during lookups to handle it differently.
3. Synchronization. @tpolecat and @cquiroz both stated some concerns with the way I was using synchronization before, namely due to a nested synchronization. I have managed …
=> OCSADV-437: BAGS synchronization and threading

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamCodecs.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamSetCodecs.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/TargetParamCodecSpec.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/TargetParamSetCodecSpec.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Epoch.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/HorizonsDesignation.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Magnitude.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeBand.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeSystem.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProperMotion.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Target.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/AlmostEqual.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/CodecSyntax.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/ParamCodec.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/ParamSetCodec.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/PioError.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/package.scala
This PR does three things:
- It adds `PioParamCodec` and `PioParamSetCodec` typeclasses for PIO encoding. The main advantage of this approach is that encoding and decoding are defined together via lensing and cannot get out of sync.
- It adds instances for the atomic and composite types in `spModel.core` to allow serialization of the new target model. Tests are included.
- It straightens out the `Lens` situation for the new `Target` model.
:-1: need Jira issue, rebase
=> Typeclass-based PIO and impl for new target model

bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
This fixes three minor things:
1. Thread priority of BAGS threads. (May speed things up?)
2. Initial check for whether or not observations should be queued for BAGS lookup had accidentally been moved to always, causing obs changes to fail to queue obs for BAGS, so there is a fix for this with the addition of an `initialEnqueue` parameter to `BagsManager.enqueue` to only perform the check when programs are first watched. This will go away with the upcoming feedback changes, so this should be considered a temporary fix to a temporary problem.
3. Unrelated: timeout increased for `VoTableClientSpec` since the small value for timeout was causing this test case to frequently fail.
=> OCSADV-437: BAGS threading and lookups

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala
For GNIRS the central wavelength in a sequence can be a `String` or a `GNIRSParams.Wavelength` in case of a GNIRS sequence iterator. This has to be taken into account when extracting this value for ITC calculations.
=> OCSADV-440: Bug fix in extraction of central wavelength for GNIRS ITC.

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/flamingos2/F2ScienceAreaGeometry.scala
Tiny PR to fix an issue where a match error was encountered because of an incomplete match statement.
=> REL-2511: Fix error when selecting F2 pinhole masks

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/NamedTarget.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016A/To2016A.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016A/pluto.xml, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016A/PlutoDemotionTest.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/package.scala
This PR removes `NamedTarget.Pluto` and adds a `To2016A` conversion that swaps it for a `ConicTarget` with Pluto's orbital elements.
=> REL-2369 demote Pluto

bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/charts/VisibilityChart.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/filter/ui/FilterElement.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/selector/ConstraintsSelector.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/selector/ScheduleEditor.scala, bundle/edu.gemini.qv.plugin/src/main/scala/edu/gemini/qv/plugin/util/ScheduleCache.scala, bundle/edu.gemini.services.client/src/main/scala/edu/gemini/services/client/TelescopeSchedule.scala, bundle/edu.gemini.services.server/src/main/scala/edu/gemini/services/server/util/TelescopeScheduleServiceImpl.scala
The rules for scheduling Fast Turnaround programs have changed: Originally they were meant to be scheduled on specific FT nights only but recently it has been decided that they should be scheduled like additional queue programs on any nights that are available for queue observing.
This means that the special Fast Turnaround constraints in QVis have become obsolete and can be removed unceremoniously, which is what this PR is doing.
=> REL-2368: Update QVis to support FT observations on queue nights

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java
Tiny PR that updates a warning message and keeps it from showing if custom mask is selected.
=> REL-2199: Remove N&S slit PhaseII warning when Custom Mask selected

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/system/CoordinateTypes.java
Strange compilation error when referencing `CoordinateTypes.Epoch` from `ModelConverters`
It is fixed by adding an explicit import of the Units class, maybe it is a compiler bug?
=> Fix for weird compilation error

bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala, bundle/edu.gemini.catalog/src/test/resources/simbad-2MFGC6625.xml, bundle/edu.gemini.catalog/src/test/resources/simbad-J000008.13.xml, bundle/edu.gemini.catalog/src/test/resources/simbad-vega.xml, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
Simbad just updated their VoTable output at our request to include the magnitude system. This handles some special cases where the magnitude system does not match the default one
=> REL-2514: Update Simbad query to include flux system

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/AgsTest.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obsclass/ObsClass.java, bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/ShellAdvisor.java, bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/util/BooleanViewPreference.java, bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/view/candidate/ClientExclusion.java, bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/MiniModel.java, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/BandsList.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingFeedback.scala
Currently the QPT only allows to schedule night time calibrations. The aim of this PR is to allow QCs to schedule daytime calibrations as part of the nightly plans if needed.
This PR also deals with a serialization issue that stems from the use of `NonEmptyList` in `BandsList`. `NonEmptyList` is not serializable and breaks the communication between the ODB and the QPT. I am planning to add a serialization test case to cover this, but for now my main goal is to push the functionality into the test release. @cquiroz : you probably want to have a quick look at the changes I made to `BandsList`.
=> REL-2359: Add Daytime Calibration option to QPT

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgw.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/BagsResult.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/GuideProbeTargets.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/Fixture.java, bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/migration/to2009B/SPTargetPosListParser.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetGroupTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
Representation of Bags target in `GuideProbeTargets` changed from `Option<SPTarget>` to multi-valued `BagsResult` to allow for three states as required for BAGS feedback.
=> OCSADV-443: BagsResult implementation

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/BagsResult.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/GuideProbeTargets.java
I had a fundamental misunderstanding about how PIO worked and thus thought I had tested it when it turns out that I hadn't.
This repairs the PIO break that was introduced by the changes to the data model for `GuideProbeTargets`, making things more robust at the same time. I have tested this manually, but it still requires a formal test case, which I will add later.
(I didn't want to leave this broken in the build.)
=> OCSADV-443: Fixed broken GPT PIO.

bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016A/To2016A.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016A/pluto.xml
I was re-using the PIO `Params` defining Pluto's orbital elements, which you can't do ... adding the same `Param` to a second `ParamSet` removes it from wherever it was, so a program with more than one instance of Pluto ended up with the orbital elements only on the last instance.
Fixed, test updated to include two instances of Pluto. Fails without change, works with.
Note: this is a re-do of an earlier PR, with a more minimal test setup.
=> OCSADV-468 fix pluto conversion

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/CoordinateEditor.scala
This temporarily turns off BAGS by commenting out the `watch` and `unwatch` methods for programs so that they are never registered for automatic lookups.
Furthermore, the behavior of the RA and Dec text widgets in `CoordinateEditor` have been restored to previous behavior (with changes commented out - we can decide whether or not to remove these when we have a solution to the precision and updating issues).
=> OCSADV-475: BAGS disable and RA / Dec restore.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/CoordinateEditor.scala, bundle/jsky.util.gui/src/main/java/jsky/util/gui/TextBoxWidget.java
The primary purpose of this PR is to:
1. Re-enable BAGS. (I will do a second PR soon to disable BAGS for those who wish to do so.)
2. Fix the RA and Dec fields of the `CoordinateEditor` to work with BAGS.
There is also a couple items of general cleanup and a small bug fix in `TextBoxWidget`, although we might consider getting rid of the `TextBoxWidgetWatcher.textBoxDoneEditing` since this is no longer used. I will leave it for now.
=> OCSADV-443: RA / Dec field fix for BAGS

bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/OtItemEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
This PR accomplishes the following:
1. Changes to `EdCompTargetList` to make BAGS targets non-editable.
2. Fix of `OtItemEditor.updateEnabledState`, which I believe was incorrect before. (If any call was made to this method with `false` to disable a widget, I believe that the widget could then never be made enabled with another call with `true`. I have tested and it appears to work correctly now, but if I misunderstood the original intent of this very limited use method, please let me know.)
3. Cleaned up `OtItemEditor`, using Java 8 lambda expressions and `Optional`.
=> OCSADV-482: Make BAGS target non-editable

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java
The 2016A migration code will always run, even in the future, if we don't update the program container version.
````scala
object To2016A extends Migration {
val Version_2016A = Version.`match`("2016A-1")
def isPre2016A(c: Container): Boolean =
c.getVersion.compareTo(Version_2016A) < 0
// Entry point here
def updateProgram(d: Document): Unit =
d.containers.find(_.getKind == SpIOTags.PROGRAM).filter(isPre2016A).foreach { _ =>
conversions.foreach(_.apply(d))
}
````
=> REL-2517: update program container version

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSpec.scala, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/RuleSpec.scala
From 2016A onwards it is not allowed anymore to use GMOS-S with E2V detectors and PIs can not set the detector type to E2V. However it is possible to copy observations from previous semesters which have the detector set to E2V.
Adding some code to avoid this on copying seemed to be too complicated and too prone to introduce unwanted side-effects for something that is actually only a transitional problem. Therefore Andy and I decided to instead add a P2 error for GMOS-S observations in programs for semester 2016A or later that have the detector set to E2V.
I also added some test cases and hope that the new 'RuleSpec' abstract base class (modeled after `WfsRuleSpec`) and `GmosSpec` prove useful for other people implementing rule tests in the future. The current Java based tests in …
=> REL-2143: Copied GMOS-S E2V observations have wrong CCD manufacturer

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SourceDetailsEditor.scala
OCSADV-472 describes some issues with BAGS updates. One of them is that the SED aux file selector for user defined source distributions updates its list of available files on every single key stroke. Needless to say that this wasn't such a brilliant idea.
Currently there is no way to get notified when aux files are changed (added/removed) and therefore the best way to deal with updating the list of available SED aux files seems to be to update it every time the user opens the combobox popup menu.
Because this update is triggered when the user clicks on the combobox to display the available values we need to produce those immediately and therefore the load operation that gets the aux file list from the server is done synchronously and will be aborted after 3 seconds.
I was also thinking …
=> OCSADV-472: Keep SED aux file selection from updating on single key strokes

bundle/edu.gemini.itc/src/test/scala/edu/gemini/itc/base/DatFileTest.scala
Forgot to update a test whose result was impacted by a previous change to the data file it uses.
=> BUGFIX: Update to failing ITC test.

bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/CatalogQuerySpec.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala
In the old catalog severs the queries were widened to increase cache efficiency. This meant that when searching for nearby objects there was a good chance that the data would be already available locally
This PR brings this capability into the new catalogs. Queries are widened 150% with up to 10 arcmins to avoid covering too large of a sky swath
=> OCSADV-271: Support 'embiggen' feature

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/plannedtime/PlannedTimeSummaryService.java
This is a follow up on an earlier PR which added UI capabilities for filtering/selecting daytime calibrations in the QPT. So far daytime calibrations didn't really make it through the filtering mechanisms of the `ObsQueryFunctor` because their step count was set to 0 in the `PlannedTimeSummary`.
This PR has two commits, the first one contains some trivial code brush up, the relevant changes are in 
https://github.com/gemini-hlsw/ocs/commit/69f44692afb0140e861f3d3090c59f584f6ff43f :
I am not sure what the reason was (is) to treat Acq and Daytime Cals the way it was in `PlannedTimeSummary` but trying to analyze the code I think that removing this special treatment for `DAY_CAL` obs types should be ok, because:
1) The planned steps are only used in the `ObsQueryFunctor` to exclude …
=> REL-2359B: Add Daytime Calibration option to QPT

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/ArraySpectrum.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/DefaultArraySpectrum.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/DefaultSampledSpectrum.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/EmissionLineSpectrum.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/base/Spectrum.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/operation/BlackBodySpectrum.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/MagnitudeBand.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/MagnitudeBandSpec.scala
Some input values caused errors in ITC and debugging the issue showed that the root cause was an error in how the `start` and `end` values in `MagnitudeBand` were calculated. This was fixed and a simple sanity test introduced.
Then I was wondering why, after fixing this, all my regression tests were still working. Turns out that there was some special code in some classes that (accidentally) deals with this case. This code has been there forever and by chance masked out the problem with the `MagnitudeBand` start and end values, which only caused another error for some specific cases.
Since I can not see why this special code would be needed I just removed it and while doing that I also removed some unused methods from some interfaces together with their implementations.
All regression …
=> OCSADV-447: GNIRS ITC error -7847

app/spdb/build.sbt, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gpi/GpiTest.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016A/To2016A.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016A/gpi.xml, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016A/GpiUnblockedModesTest.scala
A simple PR to update GPI unblocked modes so they don't set the parameter `useCal` to `true`, and fix the setting of `APOD_K2` when using `K2_UNBLOCKED`. Once these changes are in the OCS, we need to update the GPI SW to be able to match these configurations.
=> REL-2472:Fix errors in GPI unblocked modes

README.md, build.sbt, bundle/edu.gemini.model.p1/build.sbt, bundle/edu.gemini.spModel.core/build.sbt, project/build.sbt
With this PR we are able to publish the bundles p1 and spModel to the internal artifactory repository directly from sbt. I couldn't enable it globally to publish all bundles but we need these 2 for ITAC
=> Support publishing p1 model to artifactory

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
Small PR that refreshes the coloring of the conditions text when the obs context is reloaded
=> REL-2535: Catalog Query conditions text color not reverting properly

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/EphemerisElementEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/ObservationEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/SubmissionRequestEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/tac/TacView.scala, bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/textComponent/NumberField.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleDialog.scala
Fix for a bug on Scala swing `FormattedTextField` that emits an extra `ValueChanged` event with empty text in certain occasions. This event is used on the PIT and the new Catalog Query Tool to do validation and due to this bug we have as a side effect, that the button used to control validation needs to be clicked twice
=> REL-2253: TimeRequest dialog box Ok button needs to be pressed twice

bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/GsaPostAction.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/core/DmanFailure.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaQaUpdateQuery.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaQueryError.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/JsonCodecs.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/core/Arbitraries.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/query/GsaQaUpdateQuerySpec.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/query/JsonCodecsSpec.scala
The goal of this Data Manager update is to improve error handling for problems that come up while working with the archive server.  Specifically there was a type of error response that could be generated by the server that would be handled as an "invalid response" instead of reporting the actual error message.
=> REL-2407-E: improve error messages

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/EdCompInstGMOS.java
There was an excess of initiative removing code that resulted in listeners associated to one of the radio buttons in the GMOS OT not being connected properly, and another field in the OT doing things it shouldn't. This PR fixes those. 
First commit 8d5ee2b is the actual fix. In 3a19e78 I removed a piece of code that didn't make any sense to me, so take a look at that as well.
=> REL-2537: GMOS doesn't update for Slow Read/Low gain

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgw.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/AgsStrategyCombo.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageDisplayMenuBar.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageDisplayToolBar.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/CoordinateEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/AgsClient.scala
The aim of this PR is to restore the pre-BAGS manually executed AGS functionality to the OT in a minimal way for the 2016A release, while maintaining the essential "guts" of BAGS for future work.
This involves, primarily:
1. Restoring the previous behaviour of the RA and Dec text fields in the CoordinateEditor.
2. Adding the Auto GS buttons back to the TPE and Guiding Controls in the target editor.
3. Restoring the AgsClient to indicate that an AGS lookup is being performed, and to prompt for a manual catalog search if no targets can be found.
4. Restoring the previous GeMS AGS behaviour, i.e. opening the TPE and displaying a dialog indicating the status of the GeMS lookup.
5. Storing AGS stars once again as primary guide stars in `GuideProbeTargets` instead of as BAGS targets.
6. …
=> REL-2542: Unbagging the OT

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/GuideProbeTargets.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
This short PR fixes two issues that Bryan identified in the rolling back of BAGS to the previous AGS logic:
1. The targets in the target editor are indexed by guide probe. Previously, they were indexed starting at 1, but in the BAGS unrolling, this was accidentally changed to have them indexing at 0. They are now once again indexed starting at 1 by the changes to `TelescopePosTableWidget`.
2. If AGS was run multiple times, an old target, if having the same name as the new target, was replaced by the new target and set as the primary. In the unrolling of BAGS, the new target was simply added, so the same target could appear multiple times. The old behaviour has been restored through restoring code to `AgsStrategy` and adding a method to `GuideProbeTargets` that corresponds to the old …
=> REL-2542: A couple issues with unbagging

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
When making the updates for BAGS, I used the incorrect boolean expression to set whether target details are editable.
This tiny PR fixes that oversight.
=> REL-2544: Fixed editability of target details

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/Site.java
When selecting the strategy for visitor instruments it could happen that the site isn't properly selected and AGS fails. This PR will default to the selected strategy site if none is available from the program
=> REL-2476: AGS for visitor instruments not working

bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/GRACES_BP.xml, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/graces/Graces.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/REL_2429_Test.scala
This updates the GRACES template and adds two notes to each template group. Ideally these should appear only once at the top level but the template expander doesn't allow for this yet. Opened [OCSADV-443](http://jira.gemini.edu:8080/browse/OCSINF-443) to address this in a future release.
=> REL-2429-B Modification of the GRACES template

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/template/InstantiationFunctor.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/template/InstantiationFunctorTest.scala
A small requested change to the template instantiation functor.  It now copies science observing conditions for all observation classes except `DAY_CAL`.
=> REL-2165: copy science observing conditions during template instantiation

bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/GsaPollActions.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsLogActions.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/core/GsaRecord.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/osgi/GsaCommands.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaRecordQuery.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/JsonCodecs.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/core/Arbitraries.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/query/GsaRecordCodecSpec.scala
A handful of updates to archive queries and parsing:
1. Adds "progid=" and "obsid=" filters so that arbitrary program names like `Andy` will work and not result in attempts to download the entire archive.
2. Adds the "RAW" filter on the query to avoid getting processed datasets in the results.
3. Treats the dataset label as optional in archive query results.  This is necessary because sometimes datasets are created from engineering screens without an associated science program.  The failure to parse one such dataset in a list shouldn't invalidate them all.
=> REL-2407-H: Data Manager Bug Fixes

bundle/jsky.app.ot/src/main/java/jsky/catalog/gui/BasicTablePlotter.java
Tiny PR, the bogus `==` check messes the state of plotted tables
=> OCSADV-466: Add an Unplot button to the Catalog Navigator

bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaRecordQuery.scala
Need to take out the `progid=` and `obsid=` filters until an issue with them can be clarified.  Removing for testing.
=> REL-2407: temporarily remove progid and obsid filters

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/itc/AnalysisMethodPanel.scala
This PR hides the "Sky Aperture" edit field from the analysis method panel for all IR instruments. A fixed value (1) is used for these instruments.
=> OCSADV-491: Remove ITC sky aperture from IR instruments

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gnirs/GnirsRule.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/config2/ItemKey.java
We want to generate a warning for GNIRS when the Decker is set to Acquisition Mirror and the acquisition mirror is Out.
Previously, I was looking at the instrument node for the settings for decker and acquisition mirror.
The decker, however, is never changed in the instrument node (why it is included here, I don't know, since this seems unused), and can only be set in GNIRS sequence items.
If not set in the sequence items, it is inferred to be "empty" by SeqExec and set to something other than Acquisition Mirror based on other parameters.
Thus, now the P2 check examines the sequence instead of the instrument configuration to properly generate the warning.
(Also fixed a spelling error in comments in `ItemKey`.)
=> REL-2167: GNIRS P2 check for Decker / Acquisition Mirror

bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/Dataman.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsRefreshRunnable.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/PollService.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ProgramSyncRunnable.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/core/DmanId.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/core/package.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/osgi/Activator.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/osgi/GsaCommands.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaQuery.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaRecordQuery.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/ObsRefreshRunnableSpec.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/PollServiceSpec.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/dataset/DatasetCodecs.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/dataset/DatasetMd5.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/package.scala
Three updates:
1. Split the thread pool that polls the summit and archive in two.  One half dedicated to the summit polling and one half to the public archive.  Since the network is so sketchy at GS, the public archive link is likely to be slow and unreliable and I don't think that should impact the relatively more important summit poll.
2. Resume filtering with the `progid=` and `obsid=` feature of the archive server.  This should allow us to put all non-standard program ids back in the test database.
3. Don't eat `java.lang.InterruptedException`. `\/.fromTryCatch` catches non-fatal exceptions, including `InterruptedException`.  Interrupts are sent to threads to stop them. Catching `InterruptedException` prevents the thread from stopping normally.  Switched `\/.fromTryCatch` for the same …
=> REL-2407-J: Minor Data Manager Updates

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/WatchablePos.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetObsComp.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/obsComp/TargetObsCompSpec.scala
`TargetObsComp` listens to change events on its contained `SPTargets` but these listeners were not removed when the target environment was updated. This led to out of control leakage during target editing. Fixed that and made `WatchablePos` slightly less idiotic.
=> REL-2515 leaky listeners

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/CatalogQueryDemo.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
Refreshing the table model during a conditions change may take some time and block the UI. This PR moves the table model update and replotting to be executed on the swing thread outside the event loop
=> REL-2552:UI pause when changing conditions in Catalog Query Tool

app/spdb/build.sbt
There is a new test FITS storage service for GN.  This update changes the configuration to use it.
=> REL-2407: update GN test archive

bundle/edu.gemini.phase2.skeleton.servlet/src/main/resources/edu/gemini/phase2/template/factory/xml/TEXES_BP.xml
In coordination with REL-2165, this update removes observing conditions from Telluric standard star observations.  Template instantiation will now use the science observing conditions when creating these observations.
=> REL-2555: change texes template program

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java
Change Error to RuntimeException to have it displayed on the web result page.
=> Bugfix: Change Error to RuntimeException

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/CCDGapCalc.java
Resetting the value to the one for E2V (which is the only CCD array we currently support for IFU-2).
=> Bugfix: Plate scale values for E2V and Hamamatsu were mixed up

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/SiderealNameEditor.scala
Tiny PR that clears the magnitudes if none is retrieved from Simbad
=> OCSADV-497: Old magnitudes remain after Simbad query without new magnitudes

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This PR fixes a bug on the way a combo box is rendered, the extra foreground call makes Swing to call the rendering method over and over leading to a CPU spike.
=> REL-2557: OT memory leak?

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gmos/GmosRule.java, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/GmosSpec.scala
Cut off date has been changed to 2014A, i.e. GMOS-S must use Hamamatsu for 2014B and later. Added test cases to make sure that error is also given for ENG and CAL programs.
=> REL-2143: Change cut-off semester for "no E2V rule for GS"

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This PR hides the obsolete Cloud Cover modes on the Catalog Query Tool
=> REL-2559: Don't show CC90 in Cloud Cover menu

bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcPanel.scala
This is a layout change that should make it easier for users to check the charts that are generated for ITC calculations with multiple IFU elements for GMOS and NIFS.
For each IFU element ITC creates a set of charts. These are currently all displayed horizontally in the OT which is cumbersome if there are many IFU elements. This PR changes this by allowing charts to be grouped (in this case per IFU element) and then display the charts for each group (IFU element) stacked vertically instead of horizontally.
Example: GMOS-N with multiple IFU elements, results per IFU element stacked vertically in the OT:
=> OCSADV-498: Display multiple IFU plots vertically in OT

bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/seq/Keys.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcUniqueConfig.scala
This PR adds some code that detects if GNIRS is in imaging mode (i.e. the acquisition mirror is in). ITC currently does not support imaging calculations for GNIRS, so what this PR is doing is that all imaging configs will be filtered/ignored on the "ITC Spectroscopy" tab. (If we ever added imaging for GNIRS to ITC the imaging configurations would show up on the "ITC Imaging" tab instead.)
=> OCSADV-495: GNIRS OT ITC recognition of imaging mode

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java
This PR fixes a NPE that happens because the custom slit width property isn't always set properly in the config sequence.
=> REL-2539: F2 NullPointerException

app/spdb/build.sbt
We ran into an issue this morning where two telnet connections were closed on the client end, but still maintained / blocked on the ODB server, and as the default settings of no timeout and only allowing two active telnet connections, we could not access the ODB through telnet.
This tiny PR increases the number of maximum allowed telnet connections and sets a timeout for blocking reads to prevent this problem in the future.
=> REL-2560: ODB telnet settings

bundle/edu.gemini.model.p1/src/main/xjb/Flamingos2.xjb, bundle/edu.gemini.model.p1/src/main/xsd/Flamingos2.xsd
This PR removes the changes made to the Phase 1 Model to update the label names for the F2 K-Long Filter. The reason to remove these is that this will make existing Phase 1 documents to generate errors when skeletons are generated in December. The changes to the OT display values are preserved. This was tested with a P1 document sent by Andy and works okay now 
These changes should be added at the same time we release a new version of the PIT in March, if we really want to keep the names of the filters updated in the PIT.
=> REL-2558: Fixes problem with F2 Skeleton

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/CatalogQueryDemo.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/package.scala
Small updates to the Catalog Query Tool improving performance by reusing calculated objects and swing components. The most important change is avoiding multiple redraws when updating the conditions boxes. The last change breaks REL-2535, but a different fix is included in this PR
=> REL-2562: Speed improvements to Catalog Query Tool for larger sets

bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/TextFieldPropertyCtrl.java
This PR addresses an issue in the F2 Custom MDB entry box - the textbox is always in 'overwrite mode' so that you can't insert characters in the middle of the string without overwriting other characters. 
There must be a way to set an appropriate `Format` in the `createStringInstance` method  that would do the same (I tried that, but I couldn't make it to persist the changes in properties), hence this other alternative that is not as good but I think it is safe in this context. I can't think of a case in the OT where we do want the overwrite mode to be set to `true` - if that happens in the future, we either need to put more effort in this, or just set the flag back in the specific instance of this class. 
The actual change is in 342ac6c. The other commit is just code cleanup.
=> REL-2563: Overwrite mode in F2 Custom MDF box

app/spdb/conf/logging.properties, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/Dataman.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsRefreshRunnable.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/PollService.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ProgramSyncRunnable.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/RetryFailedRunnable.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/osgi/Activator.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/osgi/DatamanCommands.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/package.scala, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/query/GsaQuery.scala
The Data Manager is currently generating copious logging output.  While it is probably a good idea to leave it that way initially, it makes it hard to spot non-data manager issues in the log.  This PR creates  shared data manager "detail" and "json" logging levels that are consulted when writing a variety of low-level log messages.  It also adds a shell command to allow changing the logging levels at runtime.
The overall logging level is configured to `INFO` in the spdb.  By default "detail" messages will be written at `INFO` and so will appear in the log.  The "json" level controls whether the JSON posted to and retrieved from the GSA is logged.  By default it will be written at `FINE` and will not appear.  To make general "detail" messages disappear and "json" appear, for example, the …
=> REL-2407-L: Logging Level Updates

project/src/main/scala/edu/gemini/osgi/tools/app/package.scala
This PR makes the distributed JRE (and every thing else that's executable) executable for group and world.  See REL-2048 for background.
=> REL-2048: make executables world executable

bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
Set default values for IFU sky fibres on web pages to 250 and add some explanatory text. Low impact late minute change.
=> REL-2567: Default sky fibers for IFU in ITC web form

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/operation/DetectorsTransmissionVisitor.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosSouthType.java
The IFU-2 slit separation was using a wrong input value and therefore produced wrong results. The value needed is the "lines per mm" value of the GMOS dispersers/gratings, which we currently don't have.
To solve this issue I added the missing value to the different GMOS dispersers and fed it into the calculation of the split separation which now delivers the expected results.
Fiddling around with the enums in the base model is of course a relatively risky operation at this point, however I can not immediately think of any problematic side-effect this particular change could have (?), so I assume this is overall still a relatively low risk change since the added values are new and are not used anywhere else.
=> REL-2573: Fix ITC GMOS IFU-2 slit separation

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/flamingos2/Flamingos2Recipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/GmosRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/GnirsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/NifsRecipe.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/NiriRecipe.java, bundle/edu.gemini.itc/src/main/scala/edu/gemini/itc/base/Recipe.scala
From the JIRA task: The 2015A infrared ITCs (F2, GNIRS, NIFS, NIRI) displayed the aperture size in the spectroscopy "Signal and sqrt(Background)" plot title. It would be useful to display this information in all of the 2016A ITC spectroscopy plot titles to remind users when multiple pixels are being summed. A suggested title is: "Signal & Sqrt(Background) summed in an aperture of N pix diameter"
I also streamlined the titles a little bit and added a line break for titles that are (too) long for a single line.
This is a low risk last minute change, low risk because it only impacts the chart titles, but no calculations etc.
=> OCSADV-500: Display the aperture size in ITC Signal plot title

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/template/ReapplicationFunctor.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/template/InstantiationFunctorTest.scala
This PR addresses an issue wherein the observing conditions would be reset upon template reapply. The previous PR (feature/REL-2165) updated template instantiation to copy the science observing conditions for nighttime calibrations as well as science and acquisitions.  It did not update template reapply though, so nighttime calibrations would lose observing conditions when updated.  In discussions with Bryan, it was decided that not only should conditions be kept on reapply, but also any changes to the target component or position angle.
=> REL-2165: reapply nighttime cal should not lose observing conditions

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This PR adds a button that will reload the currently selected target from the TPE back into the CQT, thus allowing the user, e.g. to drag the target and have that into the CQT.
I named the button "Sync from Obs." but I'm not that happy with the name. I'm open to suggestions. On the old Catalog Navigator this was called "From Image".
Here is a screenshot:
=> OCSADV-404: Import search target from the TPE

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/URLConstants.scala
Small PR adding a menu entry to open the ITC URL, see the screenshot:
=> REL-2584: Add ITC URL in PIT Help menu

bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtil.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/FLAMINGOS2.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TCS.scala
This cleans up the syntax for extracting a value from a config, so instead of
```scala
extract[FPUnit](config, a)
```
You say
```scala
config.extract(a).as[FPUnit]
```
Debatable whether this is an actual improvement but I think it reads better.
=> seqexec config syntax

bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ApplyOp.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/DefaultImList.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Function1.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Function2.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImCollections.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImList.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImOption.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/MapOp.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/None.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Option.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Pair.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/PredicateOp.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Some.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Trio.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Tuple2.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Tuple3.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/UpdateOp.java
I was feeling inspired by @cquiroz and his herculean efforts, so last night I tried to do some cleaning up of the edu.gemini.shared.util.immutable classes to get rid of template parameter warnings, exploit backing lists better for our `ImList`s, remove unnecessary comments, and add `@FunctionalInterface` annotations where it made sense to do so.
All test cases still pass and I don't think this will break anything (e.g. serializability), but please let me know if you see any issues.
=> Immutable library cleanup and functional interfaces

bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Executor.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerEpics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Epics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/GmosSouth.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala
This cleans up capitalization issues reported earlier and replaces singleton implementations with `object`s.
=> seqexec companion objects

bundle/edu.gemini.ags.client.impl/src/test/scala/edu/gemini/ags/client/impl/QueryArgsSpec.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Dssi.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Phoenix.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Texes.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/DssiBlueprint.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Instrument.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/PhoenixBlueprint.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/TexesBlueprint.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/VisitorBlueprint.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala, bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG, bundle/edu.gemini.model.p1/src/main/xsd/Dssi.xsd, bundle/edu.gemini.model.p1/src/main/xsd/Phoenix.xsd, bundle/edu.gemini.model.p1/src/main/xsd/Texes.xsd, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_dssi.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_phoenix.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_texes.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/proposal_with_texes_as_non_visitor.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_dssi_no_site.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_phoenix_no_site.xml, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_texes_no_site.xml, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/PhoenixSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/TexesSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/DssiBlueprintSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/PhoenixBlueprintSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/TexesBlueprintSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/VisitorBlueprintSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
This PR changes the phase 1 model of  Texes, Dssi and Phoenix to request the user to indicate which site the proposal belongs to. Included are model changes, UI updates on the decision tree, upconversion logic and multiple tests.
Most of the added lines are test files
=>  REL-2463: Add site options to all visitor instruments

bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml, bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/xsl-default.xml, bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_dssi.xml, bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_phoenix.xml, bundle/edu.gemini.model.p1.pdf/src/test/resources/edu/gemini/model/p1/pdf/proposal_with_texes.xml, bundle/edu.gemini.model.p1.pdf/src/test/scala/edu/gemini/model/p1/pdf/P1TemplatesSpec.scala
This PR adds the site option selected for Phoenix, Texes and DSSI to the PDF output. Tests are included
=> REL-2463B: Add site options to all visitor instruments

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/TelescopePosWatcher.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetSelection.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/SchedulingBlock.scala, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImOption.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/ags/AgsContextPublisher.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableDragDropObject.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableDragSource.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableDropTarget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java
This is a major cleanup with some changes to the target editor in preparation for BAGS.
The decision was made that the use of GuideGroups will now be mandatory and more explicit, so that BAGS acquired target(s) can all be placed in an explicit guide group.
In preparation for this, I overhauled the target editor to always display guide groups whenever any guide probe targets are listed, and prevented the collapsing of guide group nodes in the target editor tree.
In the past, when a single grouping of guide probe targets was provided, while in the data model, they belonged to a guide group, the guide group was not explicitly shown in the target editor:
Now, as you can see, the guide group is always shown:
Additionally, here is an image showing the old target editor with multiple guide …
=> OCSADV-515: Target Editor BAGS changes and cleanup

project/OcsBundleSettings.scala, project/src/main/scala/edu/gemini/osgi/tools/idea/IdeaModule.scala, project/src/main/scala/edu/gemini/osgi/tools/idea/IdeaProject.scala
A couple of minor updates to Idea project generation.
1) Update project and module XML files so that a conversion and backup is not performed on startup. (At least for Idea 14.  Further updates might be needed for Idea 15.)
2) Always replace module files when the project is generated regardless of whether they have been edited.  In practice not touching existing updated modules just meant having to delete all `.iml` files before regenerating the project file anyway.
=> Idea project generation update.

bundle/edu.gemini.horizons.server/build.sbt, bundle/edu.gemini.horizons.server/src/main/java/edu/gemini/horizons/server/backend/CgiReplyBuilder.java, bundle/edu.gemini.horizons.server/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/edu.gemini.horizons.server/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamSetCodecs.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/HorizonsDesignation.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala
This PR adds yet another version of the Horizons service, which provides support for automated ephemeris lookup.
- `search` fetches a list of `HorizonsDesignation` (with a text name for display, as needed) given a partial name. There are three cases for the user to consider (comet, asteroid, major body) and eight cases internally, for differing output formats.
- `lookupEphemeris` takes a `HorizonsDesignation` and a few other details and looks up an `Ephemeris`. This lookup should never fail or be ambiguous (it's an error condition if this happens).
The API will likely change, and will probably move from server to client. For now it's just basic library support proving that it works (or at least seems to).
=> Horizons Service for Ephemeris Lookup

build.sbt, project/build.properties
I found this little gem, With sbt 0.13.7 you can enable cached resolution, now when I change the project and reload instead of 30 mins it takes 30seconds
http://www.scala-sbt.org/0.13/docs/Cached-Resolution.html
I don't know about side effects of moving to 0.13.7 but I'm able to e.g. build the PIT without any problems with this patch
=> Enable sbt cached resolution

build.sbt, project/build.properties
This reverts commit b4bd9f51e0fe9ed74e9a4130a34c4ab4b553c6ca.
@cquiroz I was getting compiler crashes during a compile phase that sbt introduces, so I had to revert this commit locally to get my world to compile again. Can you see if a clean full sbt build works for you?
=> Revert "Enable sbt cached resolution"

bundle/edu.gemini.shared.util/src/main/scala/edu/gemini/shared/util/IntegerIsIntegral.scala, bundle/edu.gemini.shared.util/src/main/scala/edu/gemini/shared/util/VersionVector.scala
PR #788 introduced a bug with the exported packages as it contains a class on package `edu.gemini.shared` which likely shouldn't be exported
This PR moves the class on `package.scala` to its own file
=> Fix for package export bug

app/pit/build.sbt, bundle/edu.gemini.ui.workspace/src/main/java/edu/gemini/ui/workspace/osgi/Activator.java
The PIT breaks when doing GSA queries because monocle jars were not included after the scalaz migration.
I include a small bug fix removing an exception that appears when the PIT is closed from the felix console
=> REL-2412: PIT duplication check with the in-house archive

bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/MergePlan.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/MergeTest.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/VersionVectorPio.scala
Compilation breaks in a few places as `IntegerIsIntegral` was moved to another package. This was tested with a full project compilation
=> Compilation error fixes

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
This PR fixes a bug when clicking on the problems table with a conditions-related issue. The PIT would open the conditions editor but apply the updated conditions to the first condition on the plan. This is visible if you have many condition groups on your proposal
=> REL-1806: Implement PIT validation checks of conditions and configurations

project/src/main/resources/edu/gemini/osgi/tools/app/Info.plist, project/src/main/scala/edu/gemini/osgi/tools/app/MacDistHandler.scala
This PR updates the build to support signing Mac Applications thus becoming acceptable to GateKeeper. So far it has been tested only for the PIT
The code will check if the certificate exists on the system and only then do the signing, Several steps of signing must be done before the file is acceptable.
The signature can be verified running the command below on the app:
spctl -v -a <path.to>\Gemini...app
The certificate itself is not included as it cannot be made public but it must be installed in each system where the application is built. Note that in the code the SHA hash of the certificate and certificate id are included. That information is of no use to a potential attacker
=> REL-2202: Apple developer signature for PIT Mac app

project/src/main/scala/edu/gemini/osgi/tools/idea/IdeaProject.scala
Mini improvement to the IDEAproject generation logic. With this PR the generated IDEA project won't attempt to import the classes on the mutable p1 model by default. They are still available and the project compiles fine but avoids a common mistake I make when letting IDEA do the imports
=> Don't import p1 mutable classes

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Gpi.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala, bundle/edu.gemini.model.p1/src/test/resources/edu/gemini/model/p1/immutable/transform/proposal_with_gpi_hstar.xml, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/GpiSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala
This PR hides the GPI modes H_Star and H_Liwa on the UI and adds upconversion code to convert existing proposal with those modes and convert them to H Direct
=> REL-2617: Remove H_STAR and H_LIWA observing modes from PIT

build.sbt, bundle/edu.gemini.dataman.app/src/main/scala/edu/gemini/dataman/app/ObsLogActions.scala, bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/ObsLogActionsSpec.scala
This grim little PR fixes a fault report (FR-36116) that was triggered by the Data Manager update for 2016A.  Usually new datasets are recorded in the ODB via events from the seqexec.  Sometimes however the seqexec event is never generated and yet the dataset is created by the instrument and added to the archive.  When the Data Manager discovers a new dataset via archive poll results, it adds a new record to the corresponding Observing Log in the ODB.
The behavior change in 2016A was to no longer attempt to compute the sequence step configuration corresponding to the dataset.  Unfortunately though this information is needed by the Observing Log webapp, particularly for exporting the observing log to a text file.  When expected sequence step information is not available, it blows up.
This …
=> REL-2622: Data Manager Discovered Dataset Bug

bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
Note: the changes for GNIRS have been applied in REL-552
=> REL-2569: Removed 'Last update' line in ITC output for all instruments

app/itc/build.sbt
Dependencies that were introduced with `doobie` were missing in the ITC standalone server app.
(This is a stripped down server app that only runs the ITC and is currently used by science for development and is also what is running on itc.gemini.edu to provide the ITC calculation web pages to the outside world.)
=> FIX: Added missing dependencies to ITC standalone app.

bundle/jsky.util.gui/src/main/java/jsky/util/gui/TableUtil.java
The former `TableUtil` was not calculating column widths correctly as it was using the wrong renderers, so I made an attempt to fix this properly.
However, I made a small error in doing so, which used the wrong renderer to calculate header widths if a header renderer was not explicitly defined, and resulted in an exception in terms of the data contained in the data.
This can be seen by creating a new GSAOI observation and attempting to do a GeMS manual guide star search: a table will pop open and a complaint will be issued about String vs. Boolean types.
This PR simply changes the header renderer to be the correct one, i.e. a default, instead of using the cell renderer if the header renderer is not explicitly defined.
=> REL-2632: Small TableUtil bug

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
In previous versions of the OT, the target editor widget that allowed one to specify a name for a guide group was broken in that if edits were attempted to be made to the name, the caret would jump to the end of the text widget.
This can be seen if one goes to the target editor, adds a guide probe target, creates a guide group, and then enters a name for the group and tries to edit the name in the middle of group name field.
(I would include a screenshot, but there is nothing visible to be seen, really.)
This small fix simply checks to see if the guide group text widget requires updating, i.e. if the text in the widget differs from the name of the currently selected group, and only updates the guide group text widget contents require it.
=> REL-2621: Fix for erratic behaviour of Guide Group Name text widget

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
In an offset position list, you can configure custom guiding options for specific guide probes.  For example, you can specify that PWFS2 be parked at a particular offset position.  Over in the target component, you can specify multiple guide groups, some of which may have a PWFS2 guide star while others do not.  When you have custom guide configuration for a guide probe and then switch guide groups to one that doesn't include the probe for which there is custom configuration, the OT should display a confirmation dialog informing you of the consequences and allowing you to reconsider.
This is a small bug fix that takes longer to explain than fix.  The upshot is that we were calling `OffsetUtil.allOffsetPosLists` with a target component node instead of with its "context" observation.  That …
=> REL-2644: fix confirm group change bug

app/seqexec-server/build.sbt, bundle/edu.gemini.epics.acm/src/main/java/edu/gemini/epics/acm/CaService.java, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/EpicsUtil.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Executor.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ExecutorImpl.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2ControllerEpics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Flamingos2Epics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/SeqexecFailure.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/Tcs.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsControllerEpics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/TcsEpics.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/osgi/Activator.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/osgi/Commands.scala
The main goal of this task was to clean the sequence commands. In the initial prototype, commands could only be triggered from the console. The code that implemented the console commands had details that should have been in the sequence command themselves, so I fixed that. Also, I modified some commands to provide an immediate response in case of an error. For example, the method to run a sequence would have returned a Task, that has to be run to know if the sequence could actually be run. But if there was no problem, running that Task would actually run the sequence. So now the command is more like a "start sequence", that return a value that tells if the sequence started or there was a problem.
A secondary issue that I tried to fix is that a previous modification that changed some …
=> Cleaned sequence commands

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTableModel.scala
Similar to https://github.com/gemini-hlsw/ocs/pull/825, but this time we re-activate the peak pixel information columns in the OT.
=> REL-2576C: Peak pixel information for spectroscopy in OT.

app/pit/build.sbt, build.sbt, bundle/edu.gemini.p1monitor/build.sbt, bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016A.xml, bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.production-2016B.xml, bundle/edu.gemini.p1monitor/src/main/resources/edu/gemini/p1monitor/config/conf.test.xml, bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/DirScanner.scala, bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorDirMonitor.scala, bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/config/P1MonitorConfig.scala, bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/fetch/FetchRequest.scala
This PR contains updates to the phase1 monitor including:
- Remove the use of the legacy actors library
- Support that PDF templates can be assigned on a per monitor basis
- Setup final configuration of the PIT and P1-monitor for the final release
=> REL-2522: Implement backend monitors for hbfphase1-lv1

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Dssi.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Phoenix.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/PhoenixSpec.scala
Last minute request to change the PIT UI, displaying only the sites where a visitor instrument is really installed
=> Phoenix and DSSI should display a single site where it is installed

bundle/edu.gemini.p1monitor/src/main/scala/edu/gemini/p1monitor/P1MonitorMailer.scala
This is a tiny PR for a border case bug when the p1 monitor gets  a proposal with multiple visitors in each site
=> P1 monitor bug fix

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/SpectralDistribution.scala
Minor change made so the ITC works when KOIII star is selected.
=> REL-2656: ITC fails with K0III star SED

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsHash.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/api/AgsHashSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeVignettingTest.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingArbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/inst/VignettingCalcSpec.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Arbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/test/SpModelArbitraries.scala
This PR introduces a simple hash function for AGS.  In particular, given an `ObsContext` it will compute a hash value based on variables that play a role in AGS calculations.  The plan is to store this information in an LRU cache in the OT to avoid performing AGS lookups unless there is a chance that the algorithm will come up with a different result.
I think I did a somewhat reasonable job taking into account the various factors in play but nevertheless I expect I've overlooked some details.  This function will likely grow a bit as missing elements are discovered but should serve as a starting point.
=> OCSADV-519-C: Initial AgsHash function

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/init/ObservationNI.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/TargetEnvironment.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideEnv.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideEnvironment.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideGroup.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideGrp.scala, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/target/env/Pre2010BTargetEnvironmentIoTest.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Almosts.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Arbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/GuideGroupSpec.scala, bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/PioSyntax.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016A/To2016A.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016B/groupMigration.xml, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/GroupMigrationTest.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
This is an addendum to the model refactoring for the `GuideEnvironment` and friends.  In particular it introduces a third kind of `AutomaticGroup`, `Disabled`, joining `Initial` and `Active`.  `Disabled` is used when importing old programs from XML that do not have an automatic group.  This addresses a concern voiced by Andy when the automatic group concept was proposed in Hawaii in December.  Previously old observations would have been set to `Initial` and available for BAGS searches.  Now BAGS will be made to ignore `Disabled` automatic groups.
In the UI, these will show up with a distinctive name like "Auto (Disabled)".  It isn't done yet, but I propose that for unobserved observations you should be able to select the automatic group as primary and have it switch to `Initial`.  Beyond …
=> OCSADV-514-B: Add Auto Disabled

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTarget.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/SPTargetSerializationSpec.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/SpTargetPioSpec.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/CodecSyntax.scala
This makes the new `Target` carried by `SPTarget` persistent and hooks it up to PIO serialization. This is not yet visible in the UI. It will be renamed, etc., in a later PR.
=> persistent new target

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/conf/ProbeLimitsParser.scala, bundle/edu.gemini.gsa.query/src/test/scala/edu/gemini/gsa/query/JsonCodecsSpec.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.seqexec.server/src/main/scala/edu/gemini/seqexec/server/ConfigUtil.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/MergePlan.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/VcsServer.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/osgi/Commands.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/package.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016A/GsaMigration.scala, bundle/edu.gemini.util.security/src/main/scala/edu/gemini/util/security/auth/Signed.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details/package.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/obscat/ObsCatalogHelper.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/vcs/VcsPeerSelectionDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/action/VcsSyncAction.scala
Just a bit of cleanup and deprecation warning removal related to the scalaz update from a few weeks ago.  Most significantly, I switched `fromTryCatch` to `fromTryCatchNonFatal` which is what I believe we almost always want.
=> OCSADV-139-B: cleanup

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideGroup.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideGrp.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Almosts.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/Arbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/env/GuideGroupSpec.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/AgsClient.scala
This PR tweaks the `AutomaticGroup.Active` group to add a position angle.  Depending on the position angle constraint in the observation context, BAGS will sometimes find a guide star at a position angle other than the current one.  For example, if the constraint is `FIXED_180` BAGS is allowed to search at the current position angle and the current position angle plus 180º.  Previously we were not keeping track of the position angle required to reach the guide stars found by BAGS.  This means that when switching to a manual group and then later back to the automatic guide group, the position angle might no longer correspond.  With this update, we will be able to restore the position angle associated with the BAGS guide star.
=> OCSADV-514: add position angle to active guide group

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTarget.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/PioSyntax.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016B/schedulingBlock.xml, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016B/targetMigration.xml, bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2016B/targetMigrationToo.xml, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/MigrationTest.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/SchedulingBlockMigrationTest.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/TargetMigrationTest.scala
This adds code to the `To2016B` program converter to generate new-model targets from old ones and add a zero-length scheduling block to nonsidereal observations, corresponding with the single-element ephemeris generated from the existing fixed coordinates and `validAt` time. Right now the deserialized values contain *both* old and new targets; the old target will be removed once it is unused.
=> 16b Target Model Converters

build.sbt, bundle/edu.gemini.pot/build.sbt, project/build.properties
This PR makes some changes to the build to properly publish bundles to artifactory
sbt was updated too, fixing a bug on importing those modules on ocs itself, see this [sbt commit](https://github.com/eed3si9n/sbt/commit/2d2b585a609f2e1b892bd7bc3fa87e9391c055bf)
=> Improved publish

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/dataflow/GsaAspect.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/dataflow/ProprietaryTest.scala
A trivial update to the default proprietary period for C, DD, LP, and Q programs.
=> REL-2695: change default proprietary period

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPTarget.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/EphemerisEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealDetailEditor.scala
Some minor improvements in the display of ephemeris information in the target editor.
- shows ephemeris resolution in minutes
- shows time + position a bteginning of scheduling block (if any)
- shows current position, and updates in real time
There is still work to do but this is an improvement.
=> ephemeris display improvements

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPTarget.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Target.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/template/TemplateParametersEditor.scala
This PR corrects a bug in the OT template parameters editor.  It parses and shows RA values in degrees as a `Double` and yet was getting/setting in hours as a `Double`.  I updated the editor to work with `RightAscension` and `Declination` from `spModel.core` and avoid this type of issue.
=> REL-2598: Template Parameter Editor RA Bug

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/SPTargetPio.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala
Ok this works around the weirdness of the production ODB adding `o'clock` in the date formats for `validAt` ... I don't know why this is happening, but this works around it. To be continued...
=> REL-2702 Workaround for mystery o'clock

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/EphemerisEditor.scala
Resolution in hours was mislabeled as minutes. Added count.
=> fix ephemeris resolution display

bundle/edu.gemini.ags.servlet/src/main/java/edu/gemini/ags/servlet/ToContext.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsTargetCalculatorService.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/SchedulingBlock.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/SchedulingBlockMigrationTest.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleDialog.scala
This finishes a simplification started with #860. A scheduling block with duration zero had a special meaning ("remaining time"); we now use `None` for that, and any `Some(duration)` will always be positive.
=> Make SchedulingBlock.duration optional

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/SPTarget.scala
`SPTarget.getDecString` was returning the positive angle rather than ± declination.
=> REL-2707 fix dms format

bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/template/InstantiationFunctorTest.scala
This update was part of [PR 822](https://github.com/gemini-hlsw/ocs/pull/822), which was recently closed without merging.  I'm adding it here as a standalone PR since it took a while to diagnose and fix and is an improvement regardless of the fate of the other changes in #822.
This change fixes a bug in test case setup that caused some tests to be skipped and also avoids printing several long stack traces to the log while running the `InstantiationFunctorTest`.  There isn't a JIRA issue for this since it only impacts test case output and didn't seem worth raising to the attention of the science staff.
=> InstantiationFunctorTest bugfix

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Angle.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Declination.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/FormatTest.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016A/PlutoDemotionTest.scala
This PR addresses several issues related to formatting angles.
1. Fixes a bug wherein you could end up with 60 minutes or arcminutes in a formatted RA or Dec.  For example, if you parse "0:59:59.999999" and then format it with just three digits to the right of the decimal you would end up with "0:60:00.000" instead of "1:00:00.000".
2. Makes it possible to specify precision when rounding fractional seconds (was fixed to 3 digits to the right of the decimal).
3. Changes declination / DMS to just two digits of precision to match the standard convention.
4. Makes it possible to use a separator other than `:` for the fields of a formatted RA/Dec. This is required for formatting ephemeris elements in the format expected by the TCS, which expects a single space to separate the fields.
For the …
=> REL-2698: HMS/DMS/Dec formatting updates

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsClassService.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/TargetDetailPanel.scala
Precisely what the subject says 😄 .
We now check when determining if an observation is eligible for BAGS if it is a `DAY_CAL` observation, and if it is, we mark it as ineligible.
Also fixed a minor typo, and added a small safeguard to targets in `EdCompTargetList` for possible `null`s.
=> REL-2713: Daytime calibration observations should not be run by BAGS

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
Formerly, BAGS deemed GPI observations as unworthy of eligibility specifically as per an old JIRA task.
@cquiroz pointed out that this was not necessarily the best way to do things, and I agreed:
It is better if BAGS checks with `AgsRegistrar` if the current `ObsContext` allows any `AgsStrategies`, and if not, then do not register an observation with BAGS.
This allows us to add future instruments that have no strategies without having to explicitly remember to change `BagsManager`.
=> REL-2722: BAGS now ignores instruments with no AGS strategies

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/CoordinateEditor.scala
When the model is refreshed because of an edit, the RA/Dec editor text color should be reset to black.  See [REL-2725](http://jira.gemini.edu:8080/browse/REL-2725).
=> REL-2725: bugfix for color feedback in coordinates

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
This is a small bug where if the auto group was active, the position angle was not always being set correctly when it changed.
This would happen previously, say, if the PA was changed, and triggered a BAGS lookup that resulted in the same auto group. In that case `newEnv` and `oldEnv` were considered the same, so the subsequent PA changing code was not run.
Now, instead, if the primary guide group is the auto guide group, we simply set the associated PA.
=> REL-2712: BAGS PA not being set correctly

bundle/edu.gemini.dataman.app/src/test/scala/edu/gemini/dataman/app/TestSupport.scala, bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiHorizonsConstants.java, bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/api/package.scala, bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/pot/sp/ProgramGen.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/pot/sp/ProgramTestSupport.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/NonSiderealObservation.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/NonSiderealObservationFunctor.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisExport.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/spdb/cron/osgi/Activator.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/NonSiderealObservationTest.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/TcsEphemerisExportTest.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/TestSupport.scala, project/OcsBundle.scala
This PR represents work in progress on the TCS ephemeris refresh robot.  There is additional work to do but I wanted to break the project up into smaller parts to keep the PRs manageable.  This first installment  covers the basics:
1. An ODB "functor" that gathers up all active non-sidereal observation references.
2. A `TcsEphemerisExport` cron job that performs horizons lookups for each unique `HorizonsDesignation` and writes the results for each to a file in a format that can be read by the TCS.
It is anticipated that the cron job will be run repeatedly during the day.
Additional steps to follow in subsequent PRs include:
1. Figure out how to name the files appropriately for the TCS and to avoid collisions.
2. Transferring the files to the appropriate TCS directory.
3. Skipping …
=> OCSADV-383-A: Ephemeris Robot Work in Progress

bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCacqCam.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCflamingos2.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgnirs.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgsaoi.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCmichelle.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCnifs.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCniri.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCtrecs.html
Added "Y (1.02µm)" to the pull down menu at the top of all ITC webpage forms.
=> REL-1623: Add Y-band to ITC brightness normalization

.gitignore, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/checker/P2Checker.java, bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/NonSiderealTargetRulesSpec.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/package.scala
This adds four P2 checks:
- `NoSchedulingBlock` - no scheduling block for non-sidereal observation
- `SchedulingBlockOutsideSemester` - if scheduling block doesn't fall within program semester
- `NoEphemerisForSchedulingBlock` - if ephemeris is undefined at scheduling block start
- `NoHorizonsDesignation` - if a nonsidereal target has no HORIZONS designation (this means the high-res lookup will fail)
=> REL-2726 - P2 Checks for Nonsidereal 

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
If an observation is not eligible for execution by BAGS, BAGS should perform no lookup and simply instead clear out the auto group for the observation.
=> REL-2724: Observations not eligible for BAGS must have empty auto groups

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
In the current model, when a pre-2016 program is imported, the auto guide group is set to disabled.
It must be possible to enable these auto groups, and the mechanism that we have decided to allow this to be done is to have the disabled auto group selected as the primary or double clicked.
This change simply sets a disabled auto group to an enabled one, updates the table model, and then fires an event indicating that the table has been updated. BAGS handles the rest, and performs a lookup.
=> REL-2723: Allow enabling of disabled auto groups

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/env/GuideEnvironment.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeEditorTools.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
This is a weird bit of hackery that was requested by the astronomers.
In the target editor, previously, when an observation was created, the only things in the target table were the base and the auto guide group. If someone wanted a manual guide star, this required a two-step process, first adding the manual guide group and then adding the manual target to it.
The astronomers instead wanted manual targets to be able to be added in a one-step process, i.e. if there is no manual guide group, still allow users to add a manual target by automatically creating a manual guide group to hold the manual target.
This implements that bit of hackery.
=> REL-2715: Making addition of manual guide groups easier

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
This seems to fix the deadlock in the non-sidereal target editor when doing a Horizons lookup.
=> REL-2706 fix deadlock

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/HorizonsDesignation.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/HorizonsDesignationSpec.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisExport.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/TcsEphemerisExportTest.scala, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccNames.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TcsConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/InstrumentSupportTestBase.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TestBase.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/tcc/TcsConfigTest.scala
This PR changes the names given to ephemeris files written for the TCS.  Currently the TCC (or is it the TCS?) takes the target name and appends `.eph` and then looks for a matching filename. Since there is no guarantee that human readable names entered by the user map to unique non-sidereal targets, this is a recipe for fault reports.  Instead, we’ll use the unique `HorizonsDesignation` as the filename and tell the TCC (or TCS via the TCC) what filename to look for when it loads a configuration from the WDBA.  This requires a corresponding update in the TCC/TCS.
=> OCSADV-383-B: rename ephemeris files

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gems/GemsGuideStarRule.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/general/GeneralRule.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/michelle/MichelleRule.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/trecs/TrecsRule.java, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/WfsRuleSpec.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gems/Canopus.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgw.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/env/TargetEnvironment.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/GuideSequence.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/gsaoi/GsaoiOdgwGroupTest.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/nifs/SetupTimeTest.java, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/gemini/gsaoi/PlannedTimeTest.scala, bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/Obs.java, bundle/edu.gemini.qpt.shared/src/main/java/edu/gemini/qpt/shared/sp/ObsQueryFunctor.java, bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/Version.java, bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/migration/to2009B/To2009B.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GuideConfigSouth.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/ObservationEnvironment.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/UnusedGuideConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetGroupTest.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/offset/AbstractOffsetPosListEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/PrimaryTargetToggle.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gems/StrehlFeature.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
This is a tiny PR that allows simplification of setting the primary group in the target editor.
Previously, we required users to double click on the group entry in the table (or to select the group entry and click on the "Select Primary" button) to set a group as the primary guide group.
Now we allow a group to be designated as primary if any of its targets are double clicked, or selected with the "Select Primary" button clicked.
=> REL-2716: Primary group selection simplification

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/CoordinateEditor.scala
This simplifies the editor initialization, simply ignoring targets that don't have fixed coordinates rather than disabling the controls. They are never visible in this case so it doesn't matter ... we're doing this in a lot of places.
=> REL-2732 Fix Coordinate Enablement

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
This morning's PR for REL-2716 accidentally introduced a bug that ignored double clicks / primary setting on the already primary guide group.
This is problematic since if the auto guide group is the only guide group and disabled, we rely on the user double-clicking or clicking the set primary button to enable the auto group and thus make BAGS run.
This fixes that by removing the check that was done to see if the currently selected guide group is the primary, and not processing the guide group if that is the case.
=> REL-2733: Making auto disabled guide groups enableable

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
Fixed some warnings that I accidentally introduced in the previous REL-2733 PR.
Since this is pretty much nothing other than the removal of an import and removing the braces from a lambda expression, I am going to just merge immediately.
=> REL-2733: Removed warnings from TelescopePosTableWidget.

bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/edu.gemini.horizons.api/src/test/scala/edu/gemini/horizons/server/backend/HS2Spec.scala
Non-sidereal name lookup was failing for some unique results for moons due to trailing whitespace differences in HORIZONS results (╯°□°）╯︵ ┻━┻ and was also renaming moons in an irritating way. Both fixed.
=> REL-2708 fix failing major body lookup

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdCompInstBase.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Changing the position angle for an instrument can trigger a BAGS lookup, and if the position angle constraint is set to allow 180 degree flips, then when BAGS selects an auto group, if the auto group is at +180, the position angle text field in the instrument editors will be reflected to show this.
This is problematic when the user is editing the position angle text field, which triggers BAGS lookups, which can set the PA and thus contents of the field currently being edited.
This change simply ignores overwriting the contents of the PA text field if the field has the focus, i.e. is currently being edited. Thus, while BAGS may store PA in the model, the text field is not updated while edited.
Once the focus is gained / lost, if necessary, the text field is updated to reflect the model as …
=> REL-2720: Position angle text field updating

bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
This adds a handler for HORIZONS unique asteroid result headers of the form
JPL/HORIZONS                 (2016 GB222)                 2016-Apr-20 15:22:36
which had not been seen before.
=> REL-2735 add new header format

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/package.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
This finishes up REL-2709. The ephemeris track is now highlighted from the current time through the end of the scheduling block (or remaining obs time if scheduling block duration is unspecified).
=> REL-2709 ephemeris for remaining obs time

bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
This tiny PR fixes a bug in `HorizonsService2`.  When it formats the start/stop time arguments it was using the local time zone instead of UTC.  I fixed that and also switched to `DateTimeFormatter` since it is immutable and thread-safe and only one instance is needed.
=> OCSADV-383: bug in horizons start/stop time formatting

app/spdb/build.sbt
A small update to SPDB properties to explicitly set the TCS ephemeris file directory for test ODBs.  I've chosen `/home/software/ugemini/ephemeris`.  Science staff can login to the test ODBs as `dataproc` and review the contents of this directory after triggering the ephemeris file update task.
The production ephemeris file location is still TBD.
=> OCSADV-383: specify the ephemeris file directory in test ODBs

bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/EphemerisFiles.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/ExportError.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/FileStatus.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisCron.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisExport.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/EphemerisFilesTest.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/TcsEphemerisExportTest.scala
This PR changes the ephemeris robot logging output to
* separate successful updates from error cases
* group successful updates by what happened to the file (created, updated, deleted, or skipped)
* group error cases by common stack trace and message
In a subsequent PR, the idea is that error (and success?) reports will be emailed to interested parties so that they know when there is an issue with gathering ephemeris data for the night.
As an example of a successful update, all three ephemeris files were updated in this report (file paths are default values because I haven't specified a more appropriate directory):
````
* Updated
AsteroidOldStyle(4) => /Users/swalker/.ocs15/spdb_2016A-test.1.1.1_swalker/data/edu.gemini.spdb.reports.collection/cron/AsteroidOld_4.eph
Comet(1P)           => …
```
=> OCSADV-383-E: ephemeris robot improved logging output

bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdObservation2.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ObsForm.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
This PR hacks a copy of the parametric angle time doodad into the top-level observation editor. It's not great but it provides needed functionality for today's test release.
Also fixed a P2 warning about missing scheduling blocks that didn't actually check to see if there was a scheduling block or not.
=> REL-2745 add scheduling block editor at observation level

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ObsForm.java
I neglected to add space in the layout for the scheduling block, so part of the time correction UI was getting pushed off the bottom.
=> REL-2745-B fixed spacing problem

bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java
This forces the TPE to update in response to scheduling block changes, which live on the observation.
=> REL-2750 force refresh tpe on scheduling block update

bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala
As requested `ERR_NO_HORIZONS_DESIGNATION` is now an error.
=> REL-2726-B make missing horizons designation an error

bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/ReportMailer.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisCron.scala
This installment adds an error report mailer (which is a shameless copy of `KeyMailer`) and uses it to send an email if there is a problem with creating/refreshing/deleting ephemeris files.
=> OCSADV-383: add error report mailer

bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
This changes target editor ephemeris lookup in three ways:
- It always fetches the ephemeris for the semester in which the scheduling block falls.
- It fetches an extra month before and after the semester, as requested.
- It fetches 1200 points instead of 1000, to somewhat make up for the longer interval.
=> REL-2746 pad ephemeris by 1 month

bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/NonSiderealObservation.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/NonSiderealObservationFunctor.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisCron.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/TcsEphemerisExport.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/NonSiderealObservationTest.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/TestSupport.scala, bundle/edu.gemini.util.skycalc/src/main/java/edu/gemini/skycalc/TwilightBoundType.java
This PR addresses a few requests from science:
* [REL-2752](http://jira.gemini.edu:8080/browse/REL-2752) - include all non-sidereal observations except those with "observed" or "inactive" status.  Previously, only "ready" and "ongoing" were included.
* [REL-2753](http://jira.gemini.edu:8080/browse/REL-2753) - write ephemeris data with 24 hour coverage to facilitate testing.  Specifically a twilight bounds type parameter may be specified to control how a given night is defined ("official" twilight, civil twilight, nautical twilight, or astronomical twilight).  If not set, the robot will default to full day coverage where the day is defined to end on the nearest even minute after the next sunrise and start exactly 24 hours before.
* (no JIRA issue) - write ephemeris values that align with …
=> OCSADV-383-H: requested updates

bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala
This makes `ERR_NO_EPHEMERIS_FOR_BLOCK` an error rather than a warning.
=> REL-2726 make ERR_NO_EPHEMERIS_FOR_BLOCK an error

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/flamingos2/F2ScienceAreaGeometry.scala
Previously, the old F2 geometry feature was offsetting the geometry of long slits by `LongSlitFOVNorthPos` in a sort of hacky way that was missed when we extracted the geometry into its own class. This accounts for the offsetting properly so that the geometry of F2 long slits is now the same as it was in 2015B.
See the JIRA task for graphics showing how things looked in 2015B and how things incorrectly looked in 2016A:
http://jira.gemini.edu:8080/browse/REL-2599
=> REL-2599: Fixed F2 long slit geometry offsetting

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/SchedulingBlock.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleDialog.scala
This fixes several problems with the parallactic angle / scheduling controls and dialog:
- The relative time menu now correctly sets the start time, not the duration.
- When used in "scheduling" mode in the observation editor only the start date and time are shown; duration is not mentioned.
- It was formerly not possible to set the duration back to "remaining time", nor was it possible to set a duration of zero.
=> REL-2747 REL-2757 fix scheduling dialog

bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/HorizonsDesignation.scala
This PR fixes two issues with the current HORIZONS lookup:
- It allows you to search for comets by designation `67P` for example.
- It changes ephemeris lookup to search by designation, but *not* use the `DES` keyword, which doesn't always yield unique results. A non-wildcard search for `NAME=des;CAP` for comets and `ASTNAM=des` for asteroids seems to work.
=> REL-2700 improve horizons lookups

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/altair/AltairConstants.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/altair/AltairParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/altair/InstAltair.java, bundle/edu.gemini.pot/src/test/java/edu/gemini/spModel/gemini/altair/test/InstAltairCase.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/altair/AltairForm.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/altair/EdCompInstAltair.java
A new Altair dichroic (wavelength) has been added, and support is required for the OT / WDBA.
This PR adds this new wavelength, and additionally, changes the names of the enum members of the old `AltairParams.Wavelength` to more accurately represent the reality of the current situation, since `WAVELENGTH_A` and `WAVELENGTH_B` no longer have the same meaning.
Additionally, `To2016B` was updated to account for these enum name changes.
I have tested it with programs with Altair components exported from 2015B and 2016A, and the import appears to be working correctly.
=> REL-2662: Add support for new Altair dichroic to OT

bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2015B/To2015B.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/TargetMigrationTest.scala
This updates the `To2016B` migration logic to add notes for imported conic targets:
```
Starting with 2016B, the Observing Tool supports all nonsidereal targets with ephemerides
automatically downloaded from JPL HORIZONS.  This observation used the following orbital
elements which have been migrated to a single-point ephemeris.
Name: Pluto
Epoch: 2457217.5
IN: 17.36609399010031
OM: 110.2100007229519
W: 114.2248220688449
A: 39.74409337717218
EC: 0.2543036816945946
MA: 0.0
Re-resolve the target to set the unique target identifier and to update to the most recent
ephemeris.
```
I'm ignoring targets in template groups because they targets coming from the PIT won't have orbital elements. I'm not sure if this is the right approach.
=> REL-2731 add notes for conic target migration

app/itc/build.sbt, app/ot/build.sbt, app/p1-monitor/build.sbt, app/p1pdfmaker/build.sbt, app/pit/build.sbt, app/qpt/build.sbt, app/spdb/build.sbt
This PR adds explicit flags to all the applications setting the locale to `en_US`. I tested this by changing my locale to something else and after the launch spdb started with `en_US`
We could also set the locale using `Locale.setDefault` on the launcher but this option seems less intrusive
=> REL-2707: Set locale to en_US

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Angle.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Declination.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/FormatTest.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/EphemerisFileFormat.scala
This PR introduces a few minor RA/Dec formatting updates to help with TCS parsing.
* zero pads single digit hour/degree values
* adds a + sign to positive declinations
* removes a space from the whitespace separating the julian date from the RA
=> OCSADV-383-I: RA/Dec formatting updates

bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmos.html, bundle/edu.gemini.itc.web/src/main/resources/servlets/web/ITCgmosSouth.html
Added a short note under the "Analysis Method for Integral Field Unit (IFU) spectroscopy" section of the GMOS-N and GMOS-S ITC webpages.  The format of the note and the corresponding link was copied from other notes and links on the same page.
=> REL-2315: IFU Expanded Description

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/target/obsComp/TargetObsComp.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/action/EditItemTitleAction.java
One of the hugely irritating things about the POT model is that nodes have arbitrary settable names that in many cases should be computed, and the computed name ends up being set as a side-effect. So we end up in the position of looking at the name and trying to decide whether it had been computed and should thus be re-computed if properties change; or was set by hand and should thus be left alone.
So in 16B the target naming scheme has changed to reflect the new model, which makes all the old target names appear to have been set by hand via the "Edit Item Title…" menu item in the OT. This means if you change the target the label in the tree view in the OT doesn't change. Possible fixes are:
- Encode a representation of the old naming scheme forever in OCS so we can figure out whether the …
=> REL-2751 disable target node rename

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gpi/GpiRule.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java
This PR fixes some cases where GPI programs produce an NPE while doing p2 checks. This happens because for NONSTANDARD obs mode the bright limits were not set to any value. This is fixed on 	b9bea2e, the other commit are generic code cosmetic improvements
=> REL-2730: NullPointerException opening GPI programs

app/spdb/build.sbt, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TargetConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TcsConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/tcc/TcsConfigTest.scala
Previously, the WDBA XML generated a single ephemeris filename per observation if the science target was nonsidereal. This should have been done per target, with the filename associated with each nonsidereal target instead of with the observation root node.
This fixes this so that the ephemeris parameter is associated with each target if applicable.
I am not certain that we want to commit this until the change for nonsidereal targets is made throughout the OCS: as things currently stand, everything is simply done for the science target, such as the fetching of ephemeris files. I am still submitting this PR for consideration and for review by @swalker2m
=> REL-2765: Made changes for ephemeris output.

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdCompInstBase.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
As BAGS can use the "Flip 180" position angle feature in order to calculate a position angle +180 of the position angle currently being typed into the position angle field, we have special handling in place as per an earlier PR for this feature to prevent the contents of the PA field from being changed until the focus is gained / lost.
Andy reopened the JIRA task stating that this change should also occur when ENTER is pressed in the field, so this small PR adds that functionality.
=> REL-2720: More adjustments to position angle field

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
This does three unrelated things that happened to appear in the same issue:
- It adds the setup time to the path shown in the TPE.
- It adds a "Now +5 min" option to the sched block and PA controls.
- It removes the "Now + Setup" and "Now + Reacq" options from the sched block controls.
=> REL-2767 show setup time for nonsidereal targets in TPE

bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/altair/Altair.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gmos/Gmos.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/gnirs/Gnirs.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/nifs/Nifs.java, bundle/edu.gemini.itc/src/main/java/edu/gemini/itc/niri/Niri.java
Originally, Altair.java checked that the guide star separation was <= 25" for all instruments.
However, with NIRI, the guide star separation can be <=45" when guiding off-axis.  The check in Altair.java has been removed and is now implemented separately for each of the instruments:
-Gnirs.java and Nifs.java (limit is <= 25")
-Niri.java (limit is <= 45")
-Gmos.java (limit is <= 45", but has been commented out since GMOS cannot yet use Altair).
=> REL-1204: Modify NIRI + Altair max guide star distance

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Declination.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/EphemerisFileFormat.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/EphemerisFileFormatTest.scala
A small update to ephemeris formatting to meet TCS expectations.
* Adds a small header which is expected and parsed by the TCS to obtain the coordinate reference frame.
* Adds a space to positive RAs and replaces the declination `+` with a space so that they line up in the expected columns.
=> OCSADV-383-K

bundle/edu.gemini.horizons.api/build.sbt, bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/package.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/NumericKeyedMapOpsSpec.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/EphemerisEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala
This PR updates the ephemeris fetching logic to fetch fewer data points across the whole semester, and then add extra points for the observing night in which the schedule time falls, in order to allow accurate guidestar selection for rapidly moving/accelerating targets. A somewhat contrived example here, for Enceladus.
This also adds a P2 error if the base position is more than 10 arcminutes from the nearest ephemeris point, and removes the "resolution" value from the ephemeris editor since it's non-uniform now.
=> REL-2771 include higher-res data around scheduling block start

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/EphemerisEditor.scala
After literally hours of doing things at random it turns out that setting a minimum size for the labels was causing them to disappear when the window was sized down.
=> REL-2762 fix magical disappearing ephemeris

bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/Affiliate.java
Small fix, when importing UH proposals the partner affiliation was lost because there is no iso code for the University of Hawaii
I suppose the reason this is not present is because UH is not an iso code but I don't see downsides to this change
=> REL-2701: Fix UH affiliate support

bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala
This doesn't fix REL-2782 (it's not really a bug) but it does improve error reporting by spitting out the XML blob in cases where old model targets aren't readable. Example:
```
[error]    java.lang.RuntimeException: Can't recognize target:
[error]    
[error]    <paramset name="base" editable="true" access="public">
[error]      <param name="name" value="WISE J064205.58+410155.5"/>
[error]      <param name="system" value="J2000"/>
[error]      <param name="epoch" value="2000.0" units="years"/>
[error]      <param name="c1" value="06:42:05.592"/>
[error]      <param name="c2" value="41:01:60.00"/>
[error]      <param name="pm1" value="0.0" units="milli-arcsecs/year"/>
[error]      <param name="pm2" value="0.0" units="milli-arcsecs/year"/>
[error]      <param name="parallax" value="0.0" …
```
=> REL-2782 improve err reporting

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Before this change the target details were initialized as a side-effect of the initial selection in the target list, but this doesn't always happen for some reason. In particular if you change the scheduling block and click back to the target while the little time/date button still has focus then usually the target details would not be re-initialized. So this change adds an explicit update in the editor's `init` method to force the update.
=> REL-2748 attempted fix for target detail update issue

app/spdb/build.sbt
Sets the ephemeris file directory for testing and production.  Will these point to different places on g[ns]odb vs g[ns]odbtest2?
=> OCSADV-383: fix ephemeris file directory

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/EdCompObslog.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogGUI.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/ObslogTableModels.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/obslog/test/TestEventGenerator.java
This PR changes the old obslog comments table to dynamically adjust the width for the widest comment available. This is done at runtime as the user types the changes
There is quite some cleanup code, the commit f585d11 is the most relevante
Here's a screenshot
=> REL-2604: Expand comment field

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopeForm.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
This adds the scheduling block control to the target environment editor, as requested.
=> REL-2783 add scheduling controls to target editor

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
Once an obs is 'Observed' you cannot change it so everything is disabled. As a side effect you cannot select items on the targets' table
This PR disables the enabling of the table
=> REL-2781: Allow selecting any target in executed observations

bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/EphemerisFileFormat.scala
The ephemeris file header comment must align with the columns expected by the TCS.  The header I added in the previous PR was not properly aligned and so the TCS couldn't parse the reference frame.  This fixes that issue.
The only remaining inconsistency with horizons output is the RA/Dec tracking rate where the robot is using a fixed precision and horizons changes the precision in order to make the values always occupy the same number of characters in the text file.  According to @jluhrs, the TCS is able to handle this particular inconsistency so I'll leave it as is.
=> OCSADV-383: fix ephemeris file header for TCS parsing

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsAnalysis.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsGuideStars.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/ScienceTargetStrategy.scala, bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ConfigExtractor.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/ModelConverters.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/editor/OtItemEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcParametersProvider.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/editor/seq/ItcTable.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingFeedback.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/inst/OiwfsPlotFeature.scala
This PR addresses a bug with using non-sidereal targets as guide stars.  In particular the AGS analysis of a guide star works only with `SiderealTarget` so we convert arbitrary guide star targets to `SiderealTarget` if necessary before performing the analysis.  Unfortunately the conversion process would lose the coordinates of non-sidereal targets at the scheduling block start and always use (0,0) coordinates.  The analysis then reported that the guide star is out of reach.
To fix the conversion we need to know the coordinates at the scheduling block start time, which requires adding that time as a parameter.  This parameter then bubbles up a bit through a few APIs and in particular in the ITC, which accounts for most of the changes.
I also renamed the `SPTarget => SiderealTarget` …
=> REL-2768: Require a time when converting from arbitrary SPTarget to SiderealTarget

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsRegistrar.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/AgsStrategyCombo.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/GuidingControls.scala
The AGS registrar provides a method to obtain the valid strategies for a given observation, ranked in order of preference.  It also provides a method to obtain the "default" strategy for the observation.  Rather than simply picking the first (if any) ranked valid strategy, the code was performing a convoluted calculation involving the number of guide probes already selected in the observation.  Unfortunately I can't remember why this was done but it is, naturally, picking the wrong default strategy for simple cases. I believe that the separation of Auto/Manual groups makes the previous method obsolete.
In addition to simplifying the default strategy calculation, I updated a couple of labels as requested/approved by Bryan.
=> REL-2788: simplify default strategy calculation

bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gems/GemsGuideStarRule.java, bundle/edu.gemini.p2checker/src/main/java/edu/gemini/p2checker/rules/gsaoi/GsaoiRule.java, bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/ags/AgsAnalysisRule.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/ObsClassService.java
This PR checks the obs class to disable some of the phase2 checks for GSAOI
=> REL-2098: Update GeMS phase-2 checks to ignore daytime calibrations

bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/None.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Option.java, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/Some.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GMOSSupport.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GuideConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/GuideConfigSouth.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/ObservationEnvironment.java, bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/AoConfigTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/Flamingos2SupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GmosNorthSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GmosSouthSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GnirsSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GpiSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GsaoiSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GuideConfigTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/GuideGroupTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/InstrumentSupportTestBase.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/NiciSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/NifsSupportTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/RotatorConfigTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetGroupTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TargetMagnitudeTest.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/TestBase.java, bundle/edu.gemini.wdba.xmlrpc.server/src/test/java/edu/gemini/wdba/tcc/VisitorInstrumentSupportTest.java
This PR updates WDBA GMOS support to add new pointing origin and instrument types for GMOS-N + Altair.  The changes are relatively simple despite the size of the diff.  The meat of the change is in `GMOSSupport` in the `getTccConfigInstrument` and `getTccConfigInstrumentOrigin` methods.  For the most part the rest is code cleanup and updating test cases.  It also renames `GuideConfigSouth` to just `GuideConfig` since in reality it is used for both sites.
The WDBA is arguably the worst remaining code in the OCS, though the sequence model vies for that title.  This PR doesn't do much to improve the situation unfortunately. It does however introduce an important change to the way that we determine whether a given guide probe is "used" in a target environment.  Instead of just having …
=> REL-2518: new pointing origin and instrument types for GMOS-N + Altair

bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/SchedulingBlock.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EphemerisUpdater.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/NonSiderealNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
This PR updates the OT as follows:
- When the user moves the scheduling block into another observing night all ephemerides in the observation are updated.
- Refactored the existing ephemeris lookup a bit.
- Added logging for Horizons errors.
- Fixed a dumb bug in `SPTarget` that was returning the scheduling block duration rather than its start.
=> REL-2785 - WIP on auto ephemeris update

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
The target table wasn't being updated when the scheduling block changed. This PR fixes that.
=> REL-2748 reinit target table

bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewer.java
An exception can be produced when closing the OT and having multiple SPViewer instances. This PR replaces the list with `CopyOnWriteArrayList` which is safer for concurrent modification
=> REL-2658: Java exception closing OT with multiple windows open

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsHash.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/api/AgsHashSpec.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/test/SpModelArbitraries.scala
The AGS hash algorithm is missing a component for the Altair mode.  The mode impacts not only the default `AgsStrategy`, which already is taken into consideration, but also the magnitude limits for the catalog search.
The bug reported in this task happens because the initial Altair mode is NGS, which has different magnitude limits than when in LGS mode despite using the same AOWFS probe.   An initial search is performed with the NGS limits but later when the mode is switched to LGS the hash value computes the same because the AGS strategy is the same.
=> REL-2799: update hash value if altair mode differs

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsTargetCalculatorService.scala
The average PA calculation was blowing up for observations with no scheduling block duration or remaining plan time. This forces the duration to be 1ms for the purposes of computing the PA.
=> REL-2786 fix PA calculation for zero-duration obs

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
When BAGS finds a new guide star, the target editor will reinitialize to show it.  Great care is taken to minimize the amount of work done updating the target table and to maintain the selected target in this case.  Nevertheless the target editor always reinitializes the target details for whatever target is being edited.  When that target is the base position, say because the user is typing in the RA or dec, it resets the text editor with a formatted version of the coordinate and loses the cursor position.
This change simply skips the target detail update when responding to a BAGS update.  This is suboptimal in that when parked over a BAGS-managed star the user must select a different position in the table and come back to the BAGS star to see the updates.  It is however a cheap way to …
=> REL-2803: don't reinitialize target coordinates for BAGS updates

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
There was an issue as described in REL-2794 where attempting to morph one target into another type in the target editor was causing issues and not behaving properly: targets were being added to the Auto group, which is incorrect.
This fixes that by moving targets correctly now: auto targets are unmorphable, and guide probe targets remain in their manual group when morphed. User targets are removed and placed in the first manual group, or if there is no first manual group, then one is created.
=> REL-2794: Fix target morphing

bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewer.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
There were a few issues with the `BagsManager` that I found hard to solve by tweaking the existing version.  In particular:
1. When the `BagsManager` determines that an observation is not eligible for BAGS, it clears the `Auto` guide group.  It does not however remove the `AgsHash` value which is used to determine whether anything going into the AGS computation has changed.  If the observation should later become eligible again (say due to an observation class change) a new lookup is not performed. 
2. The above also applies when an AGS lookup fails, say due to a network issue.  The hash value is updated before we know whether the lookup will ultimately be successful.  By the time we try again we've stored the hash value and draw the conclusion that there is nothing to do.
3. The cache of …
=> REL-2724:  BagsManager Refactor

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/TelescopePosTableWidget.java
This PR fixes a bad UI interaction caused by ignoring the case when the index of the item selected on the target environment has no meaning for another observation. The fix will select the first item (Typically Base) instead of ignoring it
=> REL-2793: Select base target when first viewing Target node

bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiReplyBuilder.java, bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala
The issue in question is that we don't know how to interpret a horizons query response header in the case of Saturn's moon Albiorix.  The header in question is
````
*******************************************************************************
Revised: Aug 11, 2014               Albiorix / (Saturn)                    626
For MEAN orbital elements, see  http://ssd.jpl.nasa.gov/sat_elem.html
Recently discovered Saturnian irregular.
*******************************************************************************
````
which doesn't correspond to anything we are expecting.  This PR introduces an idea for how to handle these situations: skip the header processing when we only care about the ephemeris anyway.
I'm not sure if there are other ramifications of this change, but it does allow us to …
=> REL-2792: skip header parsing

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/EdObservation2.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/ObsForm.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
This PR makes two changes, as requested:
- It removes the scheduling block editor from `EdObservation2`.
- It updates the enablement logic for the scheduling block editor in `EdCompTargetList` such that it is enabled if and only if there is at least one nonsidereal target in the target environment.
Tested with switching program state and keys and the global magical enablement stuff seems to work correctly.
=> REL-2783 scheduling block editor enablement

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Same as 2805, but remade due to rebase issues. Argh.
There was a problem with the enabling of the tag menu when switching observations.
Doing so could allow a BAGS target to have the tag menu enabled for it.
It was possible to also have the tag menu enabled for the base, which should not be the case.
=> REL-2805B: Fixed enabling / disabling of target WFS tag drop down menu.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/MagnitudeEditor.scala
On the magnitude editor the ordering used removed `V` as it has the same wavelength as `AP`. the PR instead uses the default band ordering
=> REL-2806: Reinstate missing target V-band magnitude option

bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/template/factory/impl/flamingos2/Flamingos2Longslit.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/F2BlueprintTest.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala
This PR adds new notes to F2 Long-Slit templates. It includes a test too. The final template looks like this:
=> REL-2628: Update Flamingos-2 Templates for 2016B

bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala, bundle/jsky.coords/src/main/java/jsky/coords/platepos.java
A couple of tweaks to ephemeris plotting to remove erroneous points:
1) An update to ancient world coordinate to screen coordinate conversion code to remove points from the opposite side of the sky.
2) Filtering out points that don't fall on the viewport of the image widget.
=> REL-2791: ephemeris plot bugfixes

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
This updates the tooltip when the PA controls (which should really be renamed at this point) are used for editing the scheduling block start.
=> REL-2783 update tooltips

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EphemerisUpdater.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
This fixes an issue where all the event listeners and automatic doodads were clobbering bits and pieces of the scheduling block + ephemeris update. Turning events off seems to fix it.
=> REL-2785 fix ephemeris update chaos

bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/ISPObservation.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/ISPProgram.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemFactory.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemGroup.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemObservation.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemProgram.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemTemplateFolder.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/MemTemplateGroup.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/pot/sp/memImpl/ProgramData.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/pot/sp/SPAssert.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/pot/sp/DuplicateSpec.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/pot/sp/ObservationIteratorSpec.scala, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/MergePlan.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/DuplicateObsNumberTest.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/MergeTest.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/action/AddObservationAction.java
This PR addresses an issue in which it was possible to create two observations with the same observation number.  A little background is required to understand the issue.  Each program maintains a `ProgramData` object which tracks the maximum observation number ever created in the program.  When a new observation is created by the factory, this number is incremented and used for the observation.  Since programs can be edited independently, it is possible for observations with the same numbers to be created in distinct databases.  The sync process takes care of renumbering duplicate observation numbers though so that all observations in the merged update have a unique observation number once again.  It was not, however, updating the max observation number counter but instead leaving it set …
=> REL-2797: duplicate observation numbers

bundle/edu.gemini.ags.servlet/src/main/scala/edu/gemini/ags/servlet/ToContextHelper.scala, bundle/edu.gemini.horizons.api/src/main/scala/edu/gemini/horizons/server/backend/HS2.scala, bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala, bundle/edu.gemini.p2checker/src/test/scala/edu/gemini/p2checker/rules/NonSiderealTargetRulesSpec.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/Phase1FolderFactory.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/factory/SpTargetFactory.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/main/scala/edu/gemini/phase2/skeleton/servlet/SkeletonServlet.scala, bundle/edu.gemini.phase2.skeleton.servlet/src/test/scala/edu/gemini/phase2/skeleton/factory/TemplateSpec.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamCodecs.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamSetCodecs.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/TargetParamCodecSpec.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/TargetParamSetCodecSpec.scala, bundle/edu.gemini.sp.vcs.log/src/test/scala/edu/gemini/sp/vcs/log/impl/PersistentVcsLog2Spec.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Ephemeris.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Target.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/package.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/AlmostEqual.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/Arbitraries.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/TargetMigrationTest.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/TestSupport.scala, bundle/edu.gemini.wdba.xmlrpc.server/src/test/scala/edu/gemini/wdba/tcc/TcsConfigTest.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/EphemerisUpdater.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/EphemerisEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
Science wanted a P2 check for the case where you fetch an ephemeris for one site, then the instrument changes or the target is copy/pasted such that the ephemeris is no longer consistent with the site where the observation will take place. This ended up being quite a lot of work.
- `Ephemeris` is now a data type with a `site` field and a `data` field (which contains the time/coord map). For an empty ephemeris the site is irrelevant and is arbitrarily set to `GN`. This was a simpler change than introducing an `Option` or `Either` and is really ok.
- This changes both binary and PIO serialization.
- A P2 error is raised if the observation's site is know and inconsistent with the ephemeris.
👎  for now but you can go ahead and review; I need to add a unit test.
=> REL-2740 p2 check for obs site and ephemeris site consistency

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/init/ObservationNI.java, bundle/edu.gemini.sp.vcs/src/main/scala/edu/gemini/sp/vcs2/MergePlan.scala, bundle/edu.gemini.sp.vcs/src/test/scala/edu/gemini/sp/vcs2/DuplicateObsNumberTest.scala
This is an addendum to the REL-2797 observation renumbering PR.  There is a bug in that renumbered observations are not being fully initialized with the suite of non-"data object" client data.  Instead of using a `null` node initializer in the `MergePlan` I should have used an instance that does everything except add child nodes.
=> REL-2797: fully initialize renumbered observations

bundle/jsky.coords/src/main/java/jsky/coords/platepos.java
This PR fixes an embarrassing, gross oversight in my fix for REL-2791.  When computing angular separation, we need a value between 0 and PI.  D'oh!  In other words, if the RA is more than 18 hours away, it is actually closer than 6 hours if you go in the other direction of course.
=> REL-2812: minimum angular separation

bundle/edu.gemini.ags.client.api/src/main/scala/edu/gemini/ags/client/api/AgsClient.scala, bundle/edu.gemini.ags.servlet/src/main/scala/edu/gemini/ags/servlet/AgsServlet.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsUtil.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/ScienceTargetStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsVoTableCatalogSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeVignettingTest.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/GemsGuideStarWorker.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeImageWidget.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchController.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/gems/GemsGuideStarSearchDialog.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala
This PR adds an implicit `ExecutionContext` parameter to all the AGS methods (and also to the `VoTableClient` catalog search).  This makes it possible to run the BAGS searches in the BAGS execution context instead of the default global execution context where everything else runs.  The BAGS execution context runs with lower-priority threads so manual catalog searches and target name resolution can continue to be responsive while BAGS is running.  The execution context parameter bubbled up through the AGS APIs so a number of files had to be modified.
I also lowered the priority of BAGS searches a bit so as to not compete with the worker that updates serialized program files in the database.
=> REL-2814: add execution context parameter

bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/NonSiderealTargetRef.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/NonSiderealTargetRefFunctor.scala, bundle/edu.gemini.spdb.reports.collection/src/test/java/edu/gemini/dbTools/ephemeris/NonSiderealTargetRefTest.scala
This PR addresses a problem wherein an exception in computing the observation status of any observation in the ODB would stop the `NonSiderealTargetRefFunctor` (part of the "ephemeris robot") from finding other non-sidereal targets.  Specifically there are two changes:
- Handle exceptions in the observation status computation explicitly, since smart-gcal makes the computation error-prone.  Assume if we don't know the status because of an exception, the observation is still active.
- Handle other random exceptions that may happen while processing a particular program so that other programs without problems in the database can at least be included in the results.
(I struggled to come up with an automated test quickly so I just sanity checked it in my build.  I'll keep working on it but …
=> REL-2816: log NonSiderealTargetRefFunctor exceptions and continue

bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/TextExport/support/AbstractTextSegmentExporter.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/actions/BulkQAEditBase.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/actions/CommentTableDecorator.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/actions/ListPlanAction.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/config/model/OlBasicConfiguration.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/config/model/OlConfiguration.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/config/model/OlObsLogData.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/config/xml/OlXmlConfiguration.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/instruments/GsaoiLogSegment.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/obslog/OlDefaultObservingLog.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/obslog/functor/OlObsVisitFunctor.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/obslog/functor/OlObsVisitTimeFunctor.java, bundle/edu.gemini.obslog/src/main/java/edu/gemini/obslog/osgi/DatabaseTracker.java
This reverts commit 411661636a53c9f07103616a6a44e1f9a16b4c9a.
The issue with listing observing plans was traced to this commit, which did a bit of premature cleanup.  It removed "unused" code that turned out to have been accessed via reflection/JSPs.  Reverting the update fixes the issue.  There may be unrelated obslog cleanup that is being reverted as well, but it was easiest to just revert the commit altogether.
=> REL-2821 Revert "Remove warnings on obslog bundle"

bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/archive/Archiver.scala
The daily ODB backup fails when it tries to archive the fetch/store (i.e. "vcs") log. I traced this down to a call to `VcsLog.archive` which is unimplemented:
````scala
def archive(f: File): Unit = ???
````
I'm not sure how much work is involved in implementing the method but we can get around this for the next few days and allow the backup to complete by just skipping the fetch/store log archive for now, I think.
=> REL-2824: remove call to unimplemented method

bundle/edu.gemini.ags.client.api/src/main/scala/edu/gemini/ags/client/api/AgsClient.scala, bundle/edu.gemini.ags.servlet/src/main/scala/edu/gemini/ags/servlet/AgsServlet.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsUtil.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsVoTableCatalog.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/GemsStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/ScienceTargetStrategy.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsResultsAnalyzerSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/GemsVoTableCatalogSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/gems/mascot/MascotGuideStarSpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeStrategySpec.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/SingleProbeVignettingTest.scala, bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableClient.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/TestVoTableBackend.scala, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableClientSpec.scala, bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/ags/BagsManager.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/editor/targetComponent/details2/SiderealNameEditor.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/obscat/OTBrowserPresetsPersistence.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/obscat/ObsCatalogQueryTool.scala
Ok so this modifies @swalker2m's work on #998 by making all the `implicit ec: ExecutionContext` parameters **ex**plicit, and only using the passed `ec` at the very bottom, when doing the blocking call to look up targets. Everything else runs on the global executor, except the BAGS worker itself, which is on its own pool still but may not need to be. I didn't mess with it.
In any case the end result is that BAGS results trickle in rather than batching up, and don't interfere with high-priority manual searches (and sidereal name lookups).
Reviewers need to pull this branch and test locally; the code itself isn't going to tell you much.
=> use special executor for blocking catalog queries

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/editor/targetComponent/EdCompTargetList.java
Before the new target model was created, the only way to duplicate a target was via XML export followed by import.  Anything else required too much special case copying of individual fields and carried the risk of missing information as the target model evolved over time.  With the new target model all target classes are immutable except the `SPTarget` wrapper itself.  This makes duplication trivial and avoids any rounding errors introduced by passing the data through a `String` representation.
=> REL-2825: fix duplicate target feature

bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/ProgramId.scala
CAL and ENG program ids incorporate the date to which they correspond in format YYYYMMDD.  Unfortunately `ProgramId`, our program id parser/formatter, incorrectly formats CAL and ENG months and dates without a leading 0 in the case of single digit months and days.  Since the OT "Open" dialog works with `ProgramId` in order to accomplish its filtering, CAL and ENG programs are not handled correctly.  In particular, the "Remote" filter determines whether a program is local by asking a `ProgramId` for its corresponding `SPProgramID` and using that to lookup the program in the local ODB.  Since the `SPProgramID` is not correct, the filter fails.
=> REL-2262: fix CAL/ENG ProgramId formatting

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/rich/pot/sp/RichObservation.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/EphemerisPurge.scala, bundle/edu.gemini.shared.util/src/main/java/edu/gemini/shared/util/immutable/ImEither.java, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/EphemerisPurgeCron.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/dbTools/ephemeris/EphemerisPurgeFunctor.scala, bundle/edu.gemini.spdb.reports.collection/src/main/scala/edu/gemini/spdb/cron/osgi/Activator.scala, bundle/edu.gemini.spdb.shell/src/main/java/edu/gemini/spdb/shell/osgi/Activator.java, bundle/edu.gemini.spdb.shell/src/main/java/edu/gemini/spdb/shell/osgi/Commands.java, bundle/edu.gemini.spdb.shell/src/main/scala/edu/gemini/spdb/shell/misc/EphemerisPurgeCommand.scala, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewerActions.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewerMenuBar.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/action/EphemerisPurgeAction.scala
This PR introduces a new "Edit" menu item that, when selected, purges ephemeris data in all non-sidereal observations that the user has permission to edit.  In particular, it replaces the full ephemeris table with a single-element entry at the scheduling block start.  This can reduce the amount of memory occupied by the program in an observing database, including the OT's local database.  This is, hopefully, a stop-gap option for 16B.  The idea is that this action will only be needed in very special cases where the program has many non-sidereal target instances.
~~The usefulness of this item is somewhat questionable though because it can only update observations that the user can edit.  Otherwise, the updated observations will only be rejected by the merge algorithm upon sync. …
=> REL-2831: purge ephemeris action

bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala
Change warning to error when there is no scheduling block for nonsidereal targets
Additionally, the error is now reported next to scheduling form, on the `Major
Body` node, instead of the `Observation` parent node.
=> Fix for REL-2823 

bundle/edu.gemini.catalog/src/main/scala/edu/gemini/catalog/votable/VoTableParser.scala, bundle/edu.gemini.catalog/src/test/resources/simbad-ngc-2438.xml, bundle/edu.gemini.catalog/src/test/scala/edu/gemini/catalog/votable/VoTableParserSpec.scala
Sometimes Simbad votable contains several repetitions of the same magnitude and the current parser code wasn't able to cope with that case
This PR makes the parser more robust discarding the repeated values and includes a test case
=> REL-2853: Simbad target name resolution failing

bundle/jsky.app.ot/src/main/java/jsky/app/ot/viewer/SPViewer.java
This PR updates `SPViewer` to avoid flushing BAGS state unless actually closing a program.  Without this update, every time a user opens more than one program in a single viewer and cycles through programs with the Prev and Next navigation buttons, we redo all BAGS lookups in each program we pass through.
=> REL-2857: don't flush BAGS state until closing a program

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/api/AgsStrategy.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/Helpers.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/PosAngleUpdateTest.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/VignettingTest.scala
This PR fixes AGS selection application to properly record the position angle when updated, even if the selected guide star itself does not change.  In the version before this update, when AGS would run and find the same guide star that is already recorded, it would not update the target environment even if the position angle differs.
=> REL-2874: setting pos angle

bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TelescopePosEditor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeCreatableItem.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeEditorTools.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeMode.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/TpeToolBar.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/tpe/feat/TpeGuidePosFeature.java
This PR changes the TPE to let adding Guide Stars always regardless if there is an active manual group. Added guide stars will go to the active manual group or it will create a manual group instead
=> REL-2873: Keep TPE guide star add buttons active

bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/osgi/Activator.java, bundle/edu.gemini.qpt.client/src/main/java/edu/gemini/qpt/ui/action/PublishAction.java, bundle/edu.gemini.qpt.client/src/main/scala/edu/gemini/qpt/ui/action/PublishDialog.scala
The purpose of this PR is to add a password prompt when publishing a QPT plan.  The account under which plans are published will have a new password soon, requiring a new QPT release.  The IT department is not comfortable with keeping the password in a plain text file in svn, even if only available to staff members.  This PR updates the publish process to request the password from the user.  It will remember the password that the user provides for subsequent publishes until the application is restarted.
Beyond that simple goal, I rewrote the popup(s) associated with publishing.  Since the process already involved clicking through two separate popups, I felt it would be abusive to ask for the password in a new popup.  Instead I combined all the information in a single dialog as shown …
=> REL-2878: QPT password prompt

bundle/edu.gemini.p2checker/src/main/scala/edu/gemini/p2checker/target/NonSiderealTargetRules.scala
This has been backported from a previous PR to `develop`: https://github.com/gemini-hlsw/ocs/pull/1014
Please be extra careful with this PR since I had removed the branch for this bug and had to do some unconventional checkouts and cherry-picking to be able to reach this point.
=> REL-2823 Change warning to error when there is no scheduling block for nonsidereal targets

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPProgram.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/obs/SPObservation.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsParamSetCodecs.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsTargetCalculatorService.scala, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/SchedulingBlock.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obs/Arbitraries.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/obs/ObsParamSetCodecSpec.scala, bundle/edu.gemini.spModel.io/src/main/java/edu/gemini/spModel/io/impl/PioSpXmlParser.java, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/Migration.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/PioSyntax.scala, bundle/edu.gemini.spModel.io/src/main/scala/edu/gemini/spModel/io/impl/migration/to2016B/To2016B2.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016B/SchedulingBlockMigrationTest.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/ParamSetCodec.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/tpe/feat/TpeEphemerisFeature.scala
This PR improves the usability for mean parallactic angle computations as follows:
- The duration used for the computation is retained, even if it is a snapshot of the current remaining time. We do this by storing it as a negative value, in order to maintain binary compatibility with the existing `SchedulingBlock` class.
- When no duration is specified, remaining observe time is used instead and is *not* recorded in the scheduling block. This is a corner case that happens only once in practice, when you first select the mean parallactic angle option. Since this is never the final answer I don't think it matters … it would end up being a potentially risky change to update the scheduling block in this case.
This needs monkey testing.
=> REL-2852 improve mean parallactic angle calculation usability

bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/target/TargetParamSetCodecs.scala, bundle/edu.gemini.pot/src/test/scala/edu/gemini/spModel/target/TargetParamSetCodecSpec.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Deflated.scala, bundle/edu.gemini.spModel.core/src/main/scala/edu/gemini/spModel/core/Ephemeris.scala, bundle/edu.gemini.spModel.core/src/test/scala/edu/gemini/spModel/core/EphemerisSpec.scala, bundle/edu.gemini.spModel.io/src/test/scala/edu/gemini/spModel/io/impl/migration/to2016A/PlutoDemotionTest.scala, bundle/edu.gemini.spModel.pio/src/main/scala/edu/gemini/spModel/pio/codec/ParamCodec.scala
This is an experimental PR to see if we can make it less impossible to work with gigantic programs with many ephemerides. This stores data as a compressed blob, expanded lazily into a transient. The blob is written as Base64 in the XML.
If this seems ok we will need to write an updater to read earlier 16A files which have big ephemerides in their XML.
A test program with 1000 copies of IO's ephemeris results in ~24m of XML, which is much better than before. Currently this would be ~500m of XML.
=> REL-2831: compress ephemerides

bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/flamingos2/Flamingos2Editor.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gmos/EdCompInstGMOS.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gnirs/EdCompInstGNIRS.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
This PR addresses an issue with the position angle panel enabled state.  It adds an `updateEnabledState` method to `PositionAnglePanel` and calls it at appropriate points of the instruments that use it.
=> REL-2852-B: position angle panel enabled state fix

bundle/edu.gemini.pit/build.sbt, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/BrowseAction.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/BlueprintEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/VisitorSelector.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/ShellAction.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala, bundle/edu.gemini.shared.gui/build.sbt, bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/Platform.scala, bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/Browser.scala, bundle/edu.gemini.shared.gui/src/main/scala/edu/gemini/shared/gui/ErrorBoxWithHyperlink.scala, bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/VersionException.java, bundle/edu.gemini.util.security/src/main/scala/edu/gemini/util/security/auth/ui/AddKeyDialog.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/viewer/open/ProgTableModel.scala
This changes the error display shown when the OT/SPDB have incompatible versions to show on one hand the actual versions involved and an link to let the users download the current version of the OT
This PR requires quite a bit of swing dark magic. The second commit d393b59 is the relevant one
The new box looks like:
=> REL-2886: Include OT installation link in incompatibility warning

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/obs/ObsListView.scala
The subject line pretty much gives what this PR does.
I added vals for `GmosNDisperser` and `GmosSDisperser` to make it easy to check and compare the disperser values to look for `R600`.
I also added the `fixBlueprint` method to `ObsListView` to allow the `BlueprintEditor` to pop open when one double-clicks the warning and allow editing of the instrument configuration, but I'm not sure that this is what we want to do. @cquiroz ?
Finally, I added the `gmosR600Check` to the `ProblemRobot` to handle the identification of this case.
=> REL-1668: Warn when NOT classical observing at Gemini and GMOS configured to use disperser R600

bundle/edu.gemini.horizons.api/src/main/java/edu/gemini/horizons/server/backend/CgiQueryExecutor.java, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/package.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/catalog/Horizons.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Previously, the PIT would issue a warning for use of AO with IQ that was worse than 70.
New requirements allow GeMS based instruments to accept IQ up to 85.
This code checks for GeMS use (GSAOI) and implements the new rule.
Additionally:
1. Small cleanup of exception handling in `CgiQueryExecturor`; and
2. `Problem` messages were previous inconsistent with regards to punctuation. This has been fixed so that all problems now have a trailing period.
3. `Problem`s from catalog lookups that generate an `Error` did not do anything with the error message, but the format of the `Problem` message suggests that it should be included, so this has been added.
=> REL-2697: GeMS requires IQ 85

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/CoiEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/PiEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala
REL-2879 requests that a warning be generated when the PI phone number is missing, and that double-clicking on the warning launch the PI editor with the focus in the Phone field.
This PR takes care of that (and more) through the following:
1. A bug has been fixed in the phone list parsing, which resulted in a `List("")` being returned when no phone numbers were specified.
2. Warning added to `ProblemRobot` as required.
3. Cleaned up problems generated by `ProblemRobot` to ensure that we never display empty strings as investigator names.
4. Removed hard-coded strings from `ProblemRobot` for PIs.
5. Changed `CoiEditor` and `PIEditor` to allow for setup code so that the `Phone` text field can request the focus.
I'm not sure that (5) was done in the best way possible, so if anyone has …
=> REL-2879: Warning for missing PI phone number (and other investigator improvements)

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala
The PIT uses a servlet to communicate with a running instance of the ODB (gnodb) to obtain estimates for being able to use AGS to find guide stars, which is accomplished by trying a variety of position angles through a series of step sizes.
The default step size for most single probes is in 10 degree increments, as is the default in `SingleProbeStrategyParams`. Flamingoes 2 OIWFS overrode this to instead us 90 degree increments, which was found to be too large and give unsatisfactory estimates.
This reduces the step size to the default of 10 degree increments by removing the overriding step size of 90 degrees. Speed comparisons for 10 degree versus 90 degree increments on a test program provided by Andy were done from GS on an ODB instance installed on `gnodbtest2` and were found to be …
=> REL-1389: Change AGS step size for F2OI

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/EphemerisElement.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Semester.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/EphemerisElementEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/TargetEditor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
As per the REL task, the PIT was mis-reporting missing ephemeris data.
This PR fixes that, and a number of other bugs that were discovered in the process.
1. One of the main issues was misuse of `java.util.Calendar`, which was being used with the assumption that the `Calendar.DAY_OF_MONTH` field is indexed starting at 0, when it is actually indexed starting at 1. (Using a `DAY_OF_MONTH` of 0 will actually give the last day of the previous month, delightfully confusingly.) Thus, `Semester.firstDay` and `Semester.lastDay` both occurred one day too early.
2. Additionally, `Calendar.HOUR` was used instead of `Calendar.HOUR_OF_DAY`, which made the `Semester.firstDay` and `Semester.lastDay` flip from time `00:00:00` to `12:00:00` after noon.
3. There was a contradiction in the …
=> REL-1217: Fixed PIT ephemeris check issues and reporting.

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategyParams.scala
Reduced F2OI step size from 90 deg to default of 10 deg to improve AGS estimates.
=> REL-1389: Finer granularity for AGS estimates for F2OI.

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/model/AppMode.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/osgi/Activator.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/ShellAdvisor.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/RedoAction.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/action/UndoAction.scala
Originally, a test release of the PIT would be built if `app/pit/build.sbt` had the property `edu.gemini.pit.test` defined at all. This was confusing because in `app/pit/build.sbt`, it was set to `true` and commented out to create an official release: its actual contents were never looked at, so setting it to `false` would make it defined and thus also result in a test release being built.
This cleans that up by ONLY creating a test release / running in test mode if the property is set to `true`.
If it is set to `false`, it is not run in test mode.
If it is set to anything else or undefined, a warning is logged and it is also not run in test mode.
=> REL-2909: Changed PIT configuration handling of debug flags

bundle/jsky.app.ot/src/main/scala/edu/gemini/catalog/ui/QueryResultsFrame.scala
This PR adds a missing feature to the Catalog Query Tool. At the moment, when the user selects a different guider, the search form magnitudes is updated but not the radius range, thus making it necessary to set it manually
This PR acts when the guider's selection is updated and will set the radius range appropriately
=> REL-2910: Update radial range in Catalog Query Tool when WFS changes

bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml
This PR does two things:
1. Adds four new Australian institutions to the PIT; and
2. Removes some double spaces that were in institution names.
=> REL-2918: Added more AU institutions and fixed spacing issues

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala
This is a major cleanup of `UpConverter`, since some of the conversions in the past simply bumped version numbers, which should no longer be necessary for `2017A` as the later version was handled identically to the earlier version in terms of later upgrading.
Thus, this should simplify things substantially while still allowing full proposal upgrades.
=> REL-2888: Cleaned up UpConverter

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/Root.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Dssi.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/dtree/inst/Texes.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/RootSpec.scala, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/dtree/inst/TexesSpec.scala
This PR changes the instrument availability in the PIT for 2017A proposals as follows:
= Allow TEXES for GN only.
= Allow DSSI for both GN and GS (formerly was only allowed for GN).
=> REL-2914: Instrument changes for PIT 2017A.

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
When the parallactic angle mode is chosen, the parallactic angle is calculated based on the scheduling block and the angle entered for the PA.
In the past, if the user "overrode" this PA, a warning would be issued in the form of a small yield sign next to the parallactic angle calculation in the display (see first figure).
If the user restored the value to the parallactic angle calculation, the warning would disappear (see second figure).
This functionality was broken by code changes for the target model (I suspect) along the way, as the number formatter used for parallactic angle display was altered in the code (and used direct string formatting to one decimal place instead of two) and thus was no longer consistent with the internal check. I have restored the code to use the formatter: …
=> REL-2920: Fixing parallactic angle formatting and warning

bundle/edu.gemini.model.p1.pdf/src/main/resources/edu/gemini/model/p1/pdf/templates/snippets/format.xml, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Partners.scala, bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/Institutions.scala, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/timeacct/TimeAcctCategory.java, bundle/edu.gemini.spModel.core/src/main/java/edu/gemini/spModel/core/Affiliate.java
As per discussions, Korea was changed to Republic of Korea.
This will not affect earlier proposals, as there were previously no Korean institutions available for selection, and setting the affiliate manually to Korea simply wrote `kr` in the proposal XML, which should not be affected by this, especially in light of REL-2930.
=> REL-2691: Changed Korea to ROK.

bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/Meta.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/ProposalClass.scala, bundle/edu.gemini.model.p1/src/main/scala/edu/gemini/model/p1/immutable/transform/UpConverter.scala, bundle/edu.gemini.model.p1/src/main/xsd/CHANGELOG, bundle/edu.gemini.model.p1/src/main/xsd/Meta.xsd, bundle/edu.gemini.model.p1/src/test/scala/edu/gemini/model/p1/immutable/transform/UpConverterSpec.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/Institutions.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/partner/PartnerView.scala
In previous versions of the PIT, when an institution for the PI is selected, the address is used for FT programs to determine the affiliate.
This can be overridden, in which case, the affiliate should be set to the chosen affiliate in the combobox in `PartnerView`; however, this code was broken, and even if a new affiliate was chosen, when a proposal was saved to XML (which did contain the proper affiliate code in the XML) and then reloaded, the affiliate combo box defaulted to the affiliate of the PI's institution.
There was an attempt to work around this by using a `previousPartnerAffiliation` with the FT program class, but the code to use this was broken in `PartnerView`, and the value was not persistent, so the information was lost when the proposal was saved and then later re-opened. …
=> REL-2930: Fixed FT affiliate overriding

bundle/edu.gemini.pit/src/main/resources/edu/gemini/pit/ui/editor/institutions.xml, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/editor/Institutions.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/util/gface/SimpleListViewer.scala, bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/view/proposal/ProposalView.scala, bundle/edu.gemini.pit/src/test/scala/edu/gemini/pit/ui/editor/InstitutionsSpec.scala
In the past, the PIT used the country of location of an institution to do a lookup for the affiliate for FT programs.
This was problematic in several instances, because there are a small number of institutions where the country in which an institution is located should not dictate the affiliate. (Example: Gemini South is located in Chile, but the affiliate should be US.)
This PR introduces an optional `affiliate` XML tag for the `institutions.xml` file that allows an affiliate to be specified that, if given, is used instead of the `country` tag when doing affiliate lookups.
The appropriate institutions have been given `affiliate` tags in `institutions.xml`, along with a few typo fixes, as well as some cosmetic name changes as per the comments in the JIRA task. As well, `University of …
=> REL-2907: Affiliate for FT can now be specified independently from country

bundle/edu.gemini.pit/src/main/scala/edu/gemini/pit/ui/robot/ProblemRobot.scala
Bryan suggested modifying the warning displayed when an affiliate for an FT program differs from the affiliate associated with the PI's institution.
This makes more sense as not every affiliate is a country.
=> REL-2907: Modified warning message regarding affiliates

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/parallacticangle/ParallacticAngleSupportInst.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/inst/ParallacticAngleSupport.java, bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/obs/ObsTargetCalculatorService.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
When using the parallactic angle mode for observations, the resultant PA is calculated at an extremely high precision. This resulted in issues with the instrument configuration: for example, the parallactic angle would be calculated and set on the instrument to a high level of precision, and then BAGS would run, and then set the PA to the "almost equals" angle at a lower precision, which would cause issues with the parallactic angle once again to be calculated and determine itself to be different from the instrument PA. Lather, rinse, repeat.
This change comprises:
1. Using a more standard precision for setting the PA on the instrument for parallactic angle calculations;
2. Not recognizing a 180 flip from the calculated parallactic angle (which can be used by BAGS in GS selection and is …
=> REL-2922: Parallactic angle setting PA at too high a precision

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala
Simply moving the code from `develop` to `release/ocs-2016B` to do a test release, with the plan on making a new build.
=> REL-2920: REL-2920: Fixing parallactic angle formatting so warning when overridden works as expected.

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java, bundle/edu.gemini.shared.gui/src/main/java/edu/gemini/shared/gui/bean/ComboPropertyCtrl.java, bundle/jsky.app.ot/src/main/java/jsky/app/ot/gemini/gpi/GpiEditor.java
This PR updates GPI marking the `APOD_star` apodizer and `H_star` observing mode as obsolete and adds the `ND3` apodizer, which can be set on the engineering mode
Note that there are no existing programs using the obsolete options, so there is no need to convert existing data.
=> REL-2893: GPI TLC wrong name in TLC APODIZER entry

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
This task comprises two elements:
1. Making code for the `PositionAnglePanel` and `ParallacticAngleControls` run on the Swing EDT so that it plays nicely with BAGS, which runs on the Swing EDT. Formerly, there were issues where, IIRC, BAGS lookups were not triggered because of this discrepancy.
2. BAGS now triggers changes to instrument configuration, which causes the `PositionAnglePanel.init` method to be called to reinitialize the panel. This causes the `ParallacticAngleControls.init` to be called, which leads to a call to `ParallacticAngleControls.updateSchedulingBlock`. This causes the parallactic angle to be recalculated, which sends an event to the `PositionAnglePanel` to indicate that the parallactic angle has changed. The `PositionAnglePanel` previously naively assumed that this …
=> REL-2921: Making BAGS and parallactic angle play nicely.

bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/CalUnitParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/calunit/calibration/CalDictionary.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/flamingos2/Flamingos2.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosCommonType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosNorthType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/GmosSouthType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gnirs/GNIRSParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gpi/Gpi.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/michelle/MichelleParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/nici/NICIParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/niri/Niri.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/obscomp/SPSiteQuality.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/phoenix/PhoenixParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/seqcomp/SeqRepeatFlatObs.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/trecs/TReCSParams.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/type/ObsoletableSpType.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/type/PartiallyEngineeringSpType.java
As per my discussion with @cquiroz earlier on https://github.com/gemini-hlsw/ocs/pull/1077, I decided tonight to go ahead and eliminate the many redundant implementations of `ObsoletableSpType.isObsolete` by using Java implementation defaults, which allowed to to remove many unnecessary boolean variables from enums.
I also cleaned up a number of things along the way, trying to eliminate many warnings about `static` being used with `enum` and `private` being used with enum constructors. Furthermore, I eliminated a bunch of redundant simple maps, using lambda expressions instead, and in several places, moved to a stream based solution instead of using loops. 
I also cleaned up what seemed like some ridiculous uses of `Option`.
=> REL-2943: ObsoletableSpType cleanup and other warnings

build.sbt, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/gmos/InstGmosCommon.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/gemini/parallacticangle/ParallacticAngleSupportInst.java, bundle/edu.gemini.pot/src/main/java/edu/gemini/spModel/inst/ParallacticAngleSupport.java, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/ParallacticAngleControls.scala, bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
I had updated the `ParallacticAngleSupport` interface and `ParallacticAngleSupportInst` class to take advantage of Java interface `default`s and to use the new target model `Angle` class, but this, of course, broke serializability with the 2016B production ODB.
Thus, for the patch release for 2016B, we will revert back to the old `Angle` class and implementation of the aforementioned. This solves the problem and allows production ODB programs to be properly serialized / deserialized.
For 2017A, we can safely go ahead with the new and improved implementations, which I have left intact in the develop branch.
=> REL-2944: Undo changes to classes that break serializability with 2016B production ODBs

bundle/jsky.app.ot/src/main/scala/jsky/app/ot/gemini/parallacticangle/PositionAnglePanel.scala
Since the functionality to override the parallactic angle is currently broken and may be somewhat complicated to fix, for the patch release, we are going to leave this functionality out.
Bryan sensibly suggested that we thus make the PA text field uneditable in parallactic angle mode to indicate this. This PR simply does that.
=> REL-2924: Make PA text field uneditable in parallactic angle mode

bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/GemsResultsAnalyzer.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/Mascot.scala, bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/gems/mascot/MascotCat.scala, bundle/edu.gemini.ags/src/test/scala/edu/gemini/ags/impl/GemsStrategySpec.scala
This PR reduces the amount of logging produced by Gems AGS which pollutes the build output
I don't think this output is very useful to users  but perhaps @andrewwstephens can chime in about that
There is more output related to AGS that could be removed but I'm not sure, in particular in [SingleProbeStrategy](https://github.com/gemini-hlsw/ocs/blob/develop/bundle/edu.gemini.ags/src/main/scala/edu/gemini/ags/impl/SingleProbeStrategy.scala#L88)
=> Reduce the amount of logging on Gems AGS
